import { getDb } from './index';
import { questions } from './schema';

const newQuestions = [
  // ==========================================
  // 6-9 سنوات — كمي (10 أسئلة)
  // ==========================================
  {
    id: crypto.randomUUID(),
    ageGroup: '6-9', skillArea: 'quantitative', subSkill: 'basic_operations',
    difficulty: 'easy', questionType: 'text',
    questionTextAr: 'أحمد لديه 3 تفاحات واشترى 5 تفاحات أخرى. كم تفاحة لديه الآن؟',
    questionImageUrl: null,
    options: [{ text: '6' }, { text: '7' }, { text: '8' }, { text: '9' }],
    correctOptionIndex: 2,
    explanationAr: '3 + 5 = 8 تفاحات',
    tags: ['addition', 'word_problem'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '6-9', skillArea: 'quantitative', subSkill: 'number_sequences',
    difficulty: 'easy', questionType: 'text',
    questionTextAr: 'أكمل المتسلسلة: 5 ، 10 ، 15 ، __',
    questionImageUrl: null,
    options: [{ text: '16' }, { text: '17' }, { text: '18' }, { text: '20' }],
    correctOptionIndex: 3,
    explanationAr: 'كل رقم يزيد بمقدار 5، لذا 15 + 5 = 20',
    tags: ['sequences', 'counting_by_5'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '6-9', skillArea: 'quantitative', subSkill: 'basic_operations',
    difficulty: 'easy', questionType: 'text',
    questionTextAr: 'كانت لدى سارة 12 قلماً، فأعطت صديقتها 5 أقلام. كم قلماً تبقى معها؟',
    questionImageUrl: null,
    options: [{ text: '5' }, { text: '6' }, { text: '7' }, { text: '8' }],
    correctOptionIndex: 2,
    explanationAr: '12 - 5 = 7 أقلام',
    tags: ['subtraction', 'word_problem'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '6-9', skillArea: 'quantitative', subSkill: 'number_comparison',
    difficulty: 'easy', questionType: 'text',
    questionTextAr: 'أي رقم يقع بين 15 و 20؟',
    questionImageUrl: null,
    options: [{ text: '12' }, { text: '14' }, { text: '17' }, { text: '22' }],
    correctOptionIndex: 2,
    explanationAr: 'الرقم 17 يقع بين 15 و20',
    tags: ['number_line', 'comparison'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '6-9', skillArea: 'quantitative', subSkill: 'multiplication',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: '3 × 4 = ؟',
    questionImageUrl: null,
    options: [{ text: '7' }, { text: '10' }, { text: '12' }, { text: '14' }],
    correctOptionIndex: 2,
    explanationAr: '3 × 4 = 12',
    tags: ['multiplication', 'times_tables'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '6-9', skillArea: 'quantitative', subSkill: 'division',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'ما نصف العدد 18؟',
    questionImageUrl: null,
    options: [{ text: '6' }, { text: '8' }, { text: '9' }, { text: '10' }],
    correctOptionIndex: 2,
    explanationAr: '18 ÷ 2 = 9',
    tags: ['halving', 'division'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '6-9', skillArea: 'quantitative', subSkill: 'basic_operations',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: '100 - 37 = ؟',
    questionImageUrl: null,
    options: [{ text: '53' }, { text: '63' }, { text: '67' }, { text: '73' }],
    correctOptionIndex: 1,
    explanationAr: '100 - 37 = 63',
    tags: ['subtraction', 'two_digit'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '6-9', skillArea: 'quantitative', subSkill: 'multiplication',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'عند سارة 4 صناديق، في كل صندوق 6 أقلام. كم عدد الأقلام جميعاً؟',
    questionImageUrl: null,
    options: [{ text: '10' }, { text: '20' }, { text: '24' }, { text: '28' }],
    correctOptionIndex: 2,
    explanationAr: '4 × 6 = 24 قلماً',
    tags: ['multiplication', 'word_problem'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '6-9', skillArea: 'quantitative', subSkill: 'fractions',
    difficulty: 'hard', questionType: 'text',
    questionTextAr: 'أي الكسرين أكبر: 3/4 أم 2/3؟',
    questionImageUrl: null,
    options: [{ text: '3/4' }, { text: '2/3' }, { text: 'متساويان' }, { text: 'لا يمكن المقارنة' }],
    correctOptionIndex: 0,
    explanationAr: '3/4 = 0.75 وهو أكبر من 2/3 ≈ 0.67',
    tags: ['fractions', 'comparison'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '6-9', skillArea: 'quantitative', subSkill: 'word_problems',
    difficulty: 'hard', questionType: 'text',
    questionTextAr: 'حصل عمر على 15 نقطة، وسلمى أقل منه بـ 3 نقاط، وفهد أكثر من سلمى بـ 7 نقاط. كم نقطة لدى فهد؟',
    questionImageUrl: null,
    options: [{ text: '16' }, { text: '18' }, { text: '19' }, { text: '20' }],
    correctOptionIndex: 2,
    explanationAr: 'سلمى = 15 - 3 = 12، فهد = 12 + 7 = 19',
    tags: ['multi_step', 'word_problem'], isActive: true,
  },

  // ==========================================
  // 6-9 سنوات — لفظي (8 أسئلة)
  // ==========================================
  {
    id: crypto.randomUUID(),
    ageGroup: '6-9', skillArea: 'verbal', subSkill: 'antonyms',
    difficulty: 'easy', questionType: 'text',
    questionTextAr: 'ما مضاد كلمة "كبير"؟',
    questionImageUrl: null,
    options: [{ text: 'جديد' }, { text: 'صغير' }, { text: 'قديم' }, { text: 'ثقيل' }],
    correctOptionIndex: 1,
    explanationAr: 'مضاد كبير هو صغير',
    tags: ['antonyms', 'vocabulary'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '6-9', skillArea: 'verbal', subSkill: 'analogies',
    difficulty: 'easy', questionType: 'text',
    questionTextAr: 'الكتاب للقراءة، كالملعقة لـ ...',
    questionImageUrl: null,
    options: [{ text: 'اللعب' }, { text: 'الكتابة' }, { text: 'الأكل' }, { text: 'الشرب' }],
    correctOptionIndex: 2,
    explanationAr: 'نستخدم الكتاب للقراءة، ونستخدم الملعقة للأكل',
    tags: ['analogies', 'tools'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '6-9', skillArea: 'verbal', subSkill: 'odd_one_out',
    difficulty: 'easy', questionType: 'text',
    questionTextAr: 'أي من هذه الكلمات لا تنتمي للمجموعة؟',
    questionImageUrl: null,
    options: [{ text: 'قطة' }, { text: 'كلب' }, { text: 'شجرة' }, { text: 'أسد' }],
    correctOptionIndex: 2,
    explanationAr: 'القطة والكلب والأسد حيوانات، أما الشجرة فهي نبات',
    tags: ['classification', 'odd_one_out'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '6-9', skillArea: 'verbal', subSkill: 'general_knowledge',
    difficulty: 'easy', questionType: 'text',
    questionTextAr: 'أي الفصول يأتي بعد الصيف؟',
    questionImageUrl: null,
    options: [{ text: 'الربيع' }, { text: 'الشتاء' }, { text: 'الخريف' }, { text: 'الصيف من جديد' }],
    correctOptionIndex: 2,
    explanationAr: 'ترتيب الفصول: الربيع، الصيف، الخريف، الشتاء',
    tags: ['seasons', 'general_knowledge'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '6-9', skillArea: 'verbal', subSkill: 'grammar',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'اختر الفعل الصحيح: هو ___ إلى المدرسة أمس.',
    questionImageUrl: null,
    options: [{ text: 'ذهبت' }, { text: 'تذهب' }, { text: 'ذهب' }, { text: 'يذهب' }],
    correctOptionIndex: 2,
    explanationAr: 'الضمير "هو" مذكر غائب، ويناسبه الفعل الماضي "ذهب"',
    tags: ['grammar', 'verb_conjugation'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '6-9', skillArea: 'verbal', subSkill: 'plurals',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'ما جمع كلمة "كتاب"؟',
    questionImageUrl: null,
    options: [{ text: 'كتابات' }, { text: 'كتيبات' }, { text: 'كتب' }, { text: 'كتابان' }],
    correctOptionIndex: 2,
    explanationAr: 'جمع كتاب هو كُتُب',
    tags: ['plurals', 'grammar'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '6-9', skillArea: 'verbal', subSkill: 'synonyms',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'ما مرادف كلمة "سعيد"؟',
    questionImageUrl: null,
    options: [{ text: 'حزين' }, { text: 'مسرور' }, { text: 'خائف' }, { text: 'غاضب' }],
    correctOptionIndex: 1,
    explanationAr: 'مرادف سعيد هو مسرور، وكلاهما يعني الفرح',
    tags: ['synonyms', 'vocabulary'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '6-9', skillArea: 'verbal', subSkill: 'proverbs',
    difficulty: 'hard', questionType: 'text',
    questionTextAr: 'أكمل المثل: "العلم في الصغر..."',
    questionImageUrl: null,
    options: [{ text: 'كالنقش في الماء' }, { text: 'كالنقش في الحجر' }, { text: 'كالريح العابرة' }, { text: 'كالرمل في اليد' }],
    correctOptionIndex: 1,
    explanationAr: '"العلم في الصغر كالنقش في الحجر" — التعلم المبكر يثبت ويدوم',
    tags: ['proverbs', 'culture'], isActive: true,
  },

  // ==========================================
  // 6-9 سنوات — منطقي (7 أسئلة)
  // ==========================================
  {
    id: crypto.randomUUID(),
    ageGroup: '6-9', skillArea: 'logical_patterns', subSkill: 'pattern_completion',
    difficulty: 'easy', questionType: 'text',
    questionTextAr: 'ما الشكل الذي يكمل النمط: ■ ● ■ ● ■ __؟',
    questionImageUrl: null,
    options: [{ text: '■' }, { text: '●' }, { text: '○' }, { text: '□' }],
    correctOptionIndex: 1,
    explanationAr: 'النمط يتكرر: مربع ودائرة بالتناوب، لذا يأتي بعد المربع الأخير دائرة ●',
    tags: ['patterns', 'alternating'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '6-9', skillArea: 'logical_patterns', subSkill: 'number_sequences',
    difficulty: 'easy', questionType: 'text',
    questionTextAr: 'أكمل المتسلسلة: 2 ، 4 ، 8 ، 16 ، __',
    questionImageUrl: null,
    options: [{ text: '18' }, { text: '24' }, { text: '32' }, { text: '34' }],
    correctOptionIndex: 2,
    explanationAr: 'كل رقم يُضاعَف: 16 × 2 = 32',
    tags: ['doubling', 'sequences'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '6-9', skillArea: 'logical_patterns', subSkill: 'comparison',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'علي أطول من خالد، وخالد أطول من ناصر. من هو الأقصر؟',
    questionImageUrl: null,
    options: [{ text: 'علي' }, { text: 'خالد' }, { text: 'ناصر' }, { text: 'نفس الطول' }],
    correctOptionIndex: 2,
    explanationAr: 'الترتيب: علي > خالد > ناصر، إذن ناصر هو الأقصر',
    tags: ['ordering', 'comparison'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '6-9', skillArea: 'logical_patterns', subSkill: 'pattern_completion',
    difficulty: 'easy', questionType: 'text',
    questionTextAr: 'أكمل النمط: △ △ ○ △ △ ○ △ △ __',
    questionImageUrl: null,
    options: [{ text: '△' }, { text: '○' }, { text: '□' }, { text: '◇' }],
    correctOptionIndex: 1,
    explanationAr: 'النمط هو مثلثان ثم دائرة. بعد المثلثين الأخيرين تأتي الدائرة',
    tags: ['patterns', 'shapes'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '6-9', skillArea: 'logical_patterns', subSkill: 'rules',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'إذا كانت: 2 ← 6 و 3 ← 9 و 4 ← 12. فماذا يصبح 5 ← ؟',
    questionImageUrl: null,
    options: [{ text: '13' }, { text: '14' }, { text: '15' }, { text: '16' }],
    correctOptionIndex: 2,
    explanationAr: 'القاعدة هي الضرب في 3: 5 × 3 = 15',
    tags: ['rules', 'function'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '6-9', skillArea: 'logical_patterns', subSkill: 'deductive_reasoning',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'كل طلاب الفصل نجحوا في الامتحان، وعلي طالب في هذا الفصل. هل نجح علي؟',
    questionImageUrl: null,
    options: [{ text: 'نعم' }, { text: 'لا' }, { text: 'ربما' }, { text: 'لا يمكن المعرفة' }],
    correctOptionIndex: 0,
    explanationAr: 'بما أن كل طلاب الفصل نجحوا وعلي منهم، فهو نجح بالضرورة',
    tags: ['deduction', 'logic'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '6-9', skillArea: 'logical_patterns', subSkill: 'number_sequences',
    difficulty: 'hard', questionType: 'text',
    questionTextAr: 'أكمل المتسلسلة: 1 ، 1 ، 2 ، 3 ، 5 ، 8 ، __',
    questionImageUrl: null,
    options: [{ text: '11' }, { text: '12' }, { text: '13' }, { text: '15' }],
    correctOptionIndex: 2,
    explanationAr: 'كل رقم هو مجموع الرقمين السابقين: 5 + 8 = 13',
    tags: ['fibonacci', 'sequences'], isActive: true,
  },

  // ==========================================
  // 10-12 سنة — كمي (8 أسئلة)
  // ==========================================
  {
    id: crypto.randomUUID(),
    ageGroup: '10-12', skillArea: 'quantitative', subSkill: 'algebra',
    difficulty: 'easy', questionType: 'text',
    questionTextAr: 'إذا كان س + 7 = 15، فما قيمة س؟',
    questionImageUrl: null,
    options: [{ text: '6' }, { text: '7' }, { text: '8' }, { text: '9' }],
    correctOptionIndex: 2,
    explanationAr: 'س = 15 - 7 = 8',
    tags: ['algebra', 'equations'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '10-12', skillArea: 'quantitative', subSkill: 'geometry',
    difficulty: 'easy', questionType: 'text',
    questionTextAr: 'ما مساحة مستطيل طوله 8 م وعرضه 5 م؟',
    questionImageUrl: null,
    options: [{ text: '13 م²' }, { text: '26 م²' }, { text: '40 م²' }, { text: '45 م²' }],
    correctOptionIndex: 2,
    explanationAr: 'مساحة المستطيل = الطول × العرض = 8 × 5 = 40 م²',
    tags: ['geometry', 'area'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '10-12', skillArea: 'quantitative', subSkill: 'percentages',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'ما هو 25٪ من العدد 80؟',
    questionImageUrl: null,
    options: [{ text: '15' }, { text: '20' }, { text: '25' }, { text: '30' }],
    correctOptionIndex: 1,
    explanationAr: '25٪ من 80 = 80 × 25 ÷ 100 = 20',
    tags: ['percentages', 'operations'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '10-12', skillArea: 'quantitative', subSkill: 'ratios',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'إذا كانت النسبة 4 : 6 = 6 : ؟، فما القيمة المجهولة؟',
    questionImageUrl: null,
    options: [{ text: '7' }, { text: '8' }, { text: '9' }, { text: '10' }],
    correctOptionIndex: 2,
    explanationAr: '4 × ؟ = 6 × 6 → ؟ = 36 ÷ 4 = 9',
    tags: ['ratios', 'proportions'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '10-12', skillArea: 'quantitative', subSkill: 'statistics',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'ما متوسط الأعداد: 3 ، 7 ، 8 ، 10 ، 12؟',
    questionImageUrl: null,
    options: [{ text: '7' }, { text: '8' }, { text: '9' }, { text: '10' }],
    correctOptionIndex: 1,
    explanationAr: 'المجموع = 40، المتوسط = 40 ÷ 5 = 8',
    tags: ['average', 'statistics'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '10-12', skillArea: 'quantitative', subSkill: 'powers',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: '2³ × 2² = ؟',
    questionImageUrl: null,
    options: [{ text: '16' }, { text: '32' }, { text: '64' }, { text: '128' }],
    correctOptionIndex: 1,
    explanationAr: '2³ × 2² = 2^(3+2) = 2⁵ = 32',
    tags: ['powers', 'exponents'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '10-12', skillArea: 'quantitative', subSkill: 'word_problems',
    difficulty: 'hard', questionType: 'text',
    questionTextAr: 'تسير سيارة بسرعة 80 كم/ساعة لمدة 3 ساعات. كم تقطع من مسافة؟',
    questionImageUrl: null,
    options: [{ text: '200 كم' }, { text: '220 كم' }, { text: '240 كم' }, { text: '260 كم' }],
    correctOptionIndex: 2,
    explanationAr: 'المسافة = السرعة × الزمن = 80 × 3 = 240 كيلومتراً',
    tags: ['speed', 'word_problem'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '10-12', skillArea: 'quantitative', subSkill: 'algebra',
    difficulty: 'hard', questionType: 'text',
    questionTextAr: 'إذا كان 3س - 5 = 16، فما قيمة س؟',
    questionImageUrl: null,
    options: [{ text: '5' }, { text: '6' }, { text: '7' }, { text: '8' }],
    correctOptionIndex: 2,
    explanationAr: '3س = 16 + 5 = 21، إذن س = 21 ÷ 3 = 7',
    tags: ['algebra', 'linear_equations'], isActive: true,
  },

  // ==========================================
  // 10-12 سنة — لفظي (7 أسئلة)
  // ==========================================
  {
    id: crypto.randomUUID(),
    ageGroup: '10-12', skillArea: 'verbal', subSkill: 'antonyms',
    difficulty: 'easy', questionType: 'text',
    questionTextAr: 'ما مضاد كلمة "متفائل"؟',
    questionImageUrl: null,
    options: [{ text: 'محايد' }, { text: 'متشائم' }, { text: 'مبتهج' }, { text: 'حذر' }],
    correctOptionIndex: 1,
    explanationAr: 'مضاد متفائل هو متشائم',
    tags: ['antonyms', 'vocabulary'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '10-12', skillArea: 'verbal', subSkill: 'plurals',
    difficulty: 'easy', questionType: 'text',
    questionTextAr: 'ما جمع كلمة "مسألة"؟',
    questionImageUrl: null,
    options: [{ text: 'مسائل' }, { text: 'مساءل' }, { text: 'مسألات' }, { text: 'مسائلة' }],
    correctOptionIndex: 0,
    explanationAr: 'جمع مسألة هو مسائل',
    tags: ['plurals', 'grammar'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '10-12', skillArea: 'verbal', subSkill: 'analogies',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'القلم للكتابة كالسكين لـ ...',
    questionImageUrl: null,
    options: [{ text: 'اللعب' }, { text: 'القطع' }, { text: 'الطبخ' }, { text: 'الطعام' }],
    correctOptionIndex: 1,
    explanationAr: 'القلم أداة للكتابة، والسكين أداة للقطع',
    tags: ['analogies', 'tools'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '10-12', skillArea: 'verbal', subSkill: 'proverbs',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'أكمل المثل: "من جدَّ..."',
    questionImageUrl: null,
    options: [{ text: 'تعب' }, { text: 'وجد' }, { text: 'رجع' }, { text: 'أخطأ' }],
    correctOptionIndex: 1,
    explanationAr: '"من جدَّ وجد" — من اجتهد وسعى وجد ما يريد',
    tags: ['proverbs', 'culture'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '10-12', skillArea: 'verbal', subSkill: 'word_roots',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'ما جذر كلمة "اسْتِخْراج"؟',
    questionImageUrl: null,
    options: [{ text: 'خرج' }, { text: 'رجع' }, { text: 'جاء' }, { text: 'أخرج' }],
    correctOptionIndex: 0,
    explanationAr: 'اشتُقت "استخراج" من الجذر الثلاثي "خ ر ج"',
    tags: ['word_roots', 'morphology'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '10-12', skillArea: 'verbal', subSkill: 'synonyms',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'ما مرادف كلمة "الشُّح"؟',
    questionImageUrl: null,
    options: [{ text: 'الكرم' }, { text: 'البخل' }, { text: 'العطاء' }, { text: 'الجود' }],
    correctOptionIndex: 1,
    explanationAr: 'الشُّح يعني البخل وضيق النفس، وهو عكس الكرم',
    tags: ['synonyms', 'vocabulary'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '10-12', skillArea: 'verbal', subSkill: 'grammar',
    difficulty: 'hard', questionType: 'text',
    questionTextAr: 'في جملة "نجح المجتهدُ"، ما إعراب كلمة "المجتهد"؟',
    questionImageUrl: null,
    options: [{ text: 'مفعول به' }, { text: 'فاعل' }, { text: 'مبتدأ' }, { text: 'خبر' }],
    correctOptionIndex: 1,
    explanationAr: '"المجتهد" فاعل مرفوع، وعلامة رفعه الضمة الظاهرة على آخره',
    tags: ['grammar', 'syntax'], isActive: true,
  },

  // ==========================================
  // 10-12 سنة — منطقي (5 أسئلة)
  // ==========================================
  {
    id: crypto.randomUUID(),
    ageGroup: '10-12', skillArea: 'logical_patterns', subSkill: 'deductive_reasoning',
    difficulty: 'easy', questionType: 'text',
    questionTextAr: 'كل المديرين ذوو خبرة. فهد مدير. هل فهد ذو خبرة؟',
    questionImageUrl: null,
    options: [{ text: 'نعم' }, { text: 'لا' }, { text: 'ربما' }, { text: 'لا يمكن التحديد' }],
    correctOptionIndex: 0,
    explanationAr: 'قياس منطقي: كل المديرين ذوو خبرة + فهد مدير = فهد ذو خبرة',
    tags: ['deduction', 'syllogism'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '10-12', skillArea: 'logical_patterns', subSkill: 'number_sequences',
    difficulty: 'easy', questionType: 'text',
    questionTextAr: 'أكمل المتسلسلة: 3 ، 6 ، 12 ، 24 ، __',
    questionImageUrl: null,
    options: [{ text: '36' }, { text: '42' }, { text: '48' }, { text: '50' }],
    correctOptionIndex: 2,
    explanationAr: 'كل رقم يُضاعَف: 24 × 2 = 48',
    tags: ['geometric_sequence', 'doubling'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '10-12', skillArea: 'logical_patterns', subSkill: 'coding',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'إذا كانت A=1 وB=2 وC=3، فما قيمة الكلمة "CAB"؟',
    questionImageUrl: null,
    options: [{ text: '312' }, { text: '321' }, { text: '123' }, { text: '213' }],
    correctOptionIndex: 0,
    explanationAr: 'C=3، A=1، B=2 → CAB = 312',
    tags: ['coding', 'cipher'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '10-12', skillArea: 'logical_patterns', subSkill: 'word_problems',
    difficulty: 'hard', questionType: 'text',
    questionTextAr: 'لارا أكبر من منى بـ 3 سنوات. منى ضعف عمر هناء. هناء عمرها 5 سنوات. كم عمر لارا؟',
    questionImageUrl: null,
    options: [{ text: '10' }, { text: '12' }, { text: '13' }, { text: '15' }],
    correctOptionIndex: 2,
    explanationAr: 'هناء=5، منى=5×2=10، لارا=10+3=13',
    tags: ['age_problems', 'multi_step'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '10-12', skillArea: 'logical_patterns', subSkill: 'spatial',
    difficulty: 'hard', questionType: 'text',
    questionTextAr: 'ورقة مربعة طُويت من المنتصف مرتين، ثم قُصَّت دائرة في منتصفها. كم عدد الثقوب عند فتح الورقة؟',
    questionImageUrl: null,
    options: [{ text: '1' }, { text: '2' }, { text: '4' }, { text: '8' }],
    correctOptionIndex: 2,
    explanationAr: 'كل طية تضاعف عدد الثقوب. بعد طيتين تكون 4 طبقات، فالقص ينتج 4 ثقوب',
    tags: ['spatial', 'folding'], isActive: true,
  },

  // ==========================================
  // 4-5 سنوات — صوتي (5 أسئلة)
  // ==========================================
  {
    id: crypto.randomUUID(),
    ageGroup: '4-5', skillArea: 'quantitative', subSkill: 'counting',
    difficulty: 'easy', questionType: 'audio',
    questionTextAr: 'كم تفاحة لدى سارة: تفاحة وتفاحة وتفاحتان؟',
    questionImageUrl: null,
    options: [{ text: '2' }, { text: '3' }, { text: '4' }, { text: '5' }],
    correctOptionIndex: 2,
    explanationAr: '1 + 1 + 2 = 4 تفاحات',
    tags: ['counting', 'audio'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '4-5', skillArea: 'quantitative', subSkill: 'comparison',
    difficulty: 'easy', questionType: 'audio',
    questionTextAr: 'الفيل حيوان كبير جداً والنملة حيوان صغير جداً. أيهما أكبر؟',
    questionImageUrl: null,
    options: [{ text: '🐘' }, { text: '🐜' }, { text: '🐱' }, { text: '🐟' }],
    correctOptionIndex: 0,
    explanationAr: 'الفيل هو أكبر الأربعة بكثير',
    tags: ['size', 'comparison', 'audio'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '4-5', skillArea: 'verbal', subSkill: 'colors',
    difficulty: 'easy', questionType: 'audio',
    questionTextAr: 'السماء لونها أزرق وأوراق الشجر لونها أخضر. ما لون السماء؟',
    questionImageUrl: null,
    options: [{ text: '🟡' }, { text: '🔵' }, { text: '🔴' }, { text: '🟢' }],
    correctOptionIndex: 1,
    explanationAr: 'السماء لونها أزرق',
    tags: ['colors', 'audio'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '4-5', skillArea: 'logical_patterns', subSkill: 'shapes',
    difficulty: 'easy', questionType: 'audio',
    questionTextAr: 'أي شكل له أربعة أضلاع متساوية وأربعة أركان؟',
    questionImageUrl: null,
    options: [{ text: '⭕' }, { text: '🔺' }, { text: '⬛' }, { text: '🌟' }],
    correctOptionIndex: 2,
    explanationAr: 'المربع له أربعة أضلاع متساوية وأربعة أركان',
    tags: ['shapes', 'audio'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '4-5', skillArea: 'quantitative', subSkill: 'number_order',
    difficulty: 'easy', questionType: 'audio',
    questionTextAr: 'ما الرقم الذي يأتي بعد الرقم أربعة؟',
    questionImageUrl: null,
    options: [{ text: '3' }, { text: '4' }, { text: '5' }, { text: '6' }],
    correctOptionIndex: 2,
    explanationAr: 'بعد الرقم 4 يأتي الرقم 5',
    tags: ['number_order', 'audio'], isActive: true,
  },
];

async function main() {
  const db = getDb();
  console.log(`⏳ إضافة ${newQuestions.length} سؤال جديد...`);
  let added = 0;
  for (const q of newQuestions) {
    await db.insert(questions).values(q);
    added++;
    process.stdout.write(`\r✅ ${added}/${newQuestions.length}`);
  }
  console.log(`\n🎉 تم بنجاح إضافة ${added} سؤال.`);
  process.exit(0);
}

main().catch(e => { console.error(e); process.exit(1); });
