import { createClient } from '@libsql/client';
import { drizzle } from 'drizzle-orm/libsql';
import { questions } from './schema';

const questionData = [
  // ═══════════════════════════════════════════════
  // عمر 4-5 — كمي — سهل
  // ═══════════════════════════════════════════════
  { ageGroup:'4-5', skillArea:'quantitative', subSkill:'العد', difficulty:'easy', questionType:'text', questionTextAr:'كم عدد الأصابع في يد واحدة؟', questionImageUrl:null, options:[{text:'3'},{text:'4'},{text:'5'},{text:'6'}], correctOptionIndex:2, explanationAr:'يد الإنسان فيها 5 أصابع: الإبهام، السبابة، الوسطى، البنصر، والخنصر.', tags:[] },
  { ageGroup:'4-5', skillArea:'quantitative', subSkill:'العد', difficulty:'easy', questionType:'text', questionTextAr:'عُدّ: 🐱🐱🐱 — كم قطة؟', questionImageUrl:null, options:[{text:'1'},{text:'2'},{text:'3'},{text:'4'}], correctOptionIndex:2, explanationAr:'نعد القطط: واحدة، اثنتان، ثلاثة. إذن عدد القطط هو 3.', tags:[] },
  { ageGroup:'4-5', skillArea:'quantitative', subSkill:'العد', difficulty:'easy', questionType:'text', questionTextAr:'عُدّ: ⭐⭐ — كم نجمة؟', questionImageUrl:null, options:[{text:'1'},{text:'2'},{text:'3'},{text:'4'}], correctOptionIndex:1, explanationAr:'نعد النجوم: واحدة، اثنتان. إذن عدد النجوم هو 2.', tags:[] },
  { ageGroup:'4-5', skillArea:'quantitative', subSkill:'المقارنة', difficulty:'easy', questionType:'text', questionTextAr:'أيهما أكبر: 1 أم 4؟', questionImageUrl:null, options:[{text:'1'},{text:'4'},{text:'متساويان'},{text:'لا أعرف'}], correctOptionIndex:1, explanationAr:'الرقم 4 أكبر من الرقم 1. كلما عددنا أكثر كلما كان العدد أكبر.', tags:[] },
  { ageGroup:'4-5', skillArea:'quantitative', subSkill:'الأشكال', difficulty:'easy', questionType:'text', questionTextAr:'أي شكل له 3 أضلاع؟', questionImageUrl:null, options:[{text:'مربع'},{text:'دائرة'},{text:'مثلث'},{text:'مستطيل'}], correctOptionIndex:2, explanationAr:'المثلث له 3 أضلاع وثلاثة زوايا. المربع له 4 أضلاع، والدائرة ليس لها أضلاع.', tags:[] },
  { ageGroup:'4-5', skillArea:'quantitative', subSkill:'الأشكال', difficulty:'easy', questionType:'text', questionTextAr:'أي شكل مستدير؟', questionImageUrl:null, options:[{text:'مثلث'},{text:'مربع'},{text:'دائرة'},{text:'مستطيل'}], correctOptionIndex:2, explanationAr:'الدائرة هي الشكل المستدير الذي ليس له زوايا ولا أضلاع مستقيمة.', tags:[] },
  { ageGroup:'4-5', skillArea:'quantitative', subSkill:'العد', difficulty:'easy', questionType:'text', questionTextAr:'ما الرقم الذي يأتي بعد 2؟', questionImageUrl:null, options:[{text:'1'},{text:'3'},{text:'4'},{text:'5'}], correctOptionIndex:1, explanationAr:'عند العد بالترتيب: 1، 2، 3... الرقم الذي يأتي بعد 2 هو 3.', tags:[] },
  { ageGroup:'4-5', skillArea:'quantitative', subSkill:'المقارنة', difficulty:'easy', questionType:'text', questionTextAr:'عُدّ: 🍎🍎🍎🍎 — كم تفاحة؟', questionImageUrl:null, options:[{text:'2'},{text:'3'},{text:'4'},{text:'5'}], correctOptionIndex:2, explanationAr:'نعد التفاحات: واحدة، اثنتان، ثلاثة، أربعة. عدد التفاحات هو 4.', tags:[] },
  { ageGroup:'4-5', skillArea:'quantitative', subSkill:'العد', difficulty:'easy', questionType:'text', questionTextAr:'ما الرقم الذي يأتي قبل 5؟', questionImageUrl:null, options:[{text:'3'},{text:'4'},{text:'6'},{text:'2'}], correctOptionIndex:1, explanationAr:'عند العد: ...3، 4، 5. الرقم الذي يأتي قبل 5 هو 4.', tags:[] },
  { ageGroup:'4-5', skillArea:'quantitative', subSkill:'المقارنة', difficulty:'easy', questionType:'text', questionTextAr:'أيهما أقل: 5 أم 2؟', questionImageUrl:null, options:[{text:'5'},{text:'2'},{text:'متساويان'},{text:'لا أعرف'}], correctOptionIndex:1, explanationAr:'الرقم 2 أقل من الرقم 5. الأرقام الصغيرة تأتي في بداية التسلسل.', tags:[] },

  // عمر 4-5 — كمي — متوسط
  { ageGroup:'4-5', skillArea:'quantitative', subSkill:'العد', difficulty:'medium', questionType:'text', questionTextAr:'عُدّ: 🌟🌟🌟🌟🌟🌟🌟 — كم نجمة؟', questionImageUrl:null, options:[{text:'5'},{text:'6'},{text:'7'},{text:'8'}], correctOptionIndex:2, explanationAr:'نعد النجوم واحدة واحدة حتى نصل إلى 7 نجوم.', tags:[] },
  { ageGroup:'4-5', skillArea:'quantitative', subSkill:'الترتيب', difficulty:'medium', questionType:'text', questionTextAr:'رتّب من الأصغر للأكبر: 3، 1، 2', questionImageUrl:null, options:[{text:'1 ، 2 ، 3'},{text:'3 ، 2 ، 1'},{text:'2 ، 1 ، 3'},{text:'1 ، 3 ، 2'}], correctOptionIndex:0, explanationAr:'الترتيب من الأصغر للأكبر يعني أن نبدأ بأصغر رقم: 1 ثم 2 ثم 3.', tags:[] },
  { ageGroup:'4-5', skillArea:'quantitative', subSkill:'المقارنة', difficulty:'medium', questionType:'text', questionTextAr:'أي مجموعة فيها أكثر: 🐶🐶🐶 أم 🐶🐶🐶🐶🐶؟', questionImageUrl:null, options:[{text:'الأولى'},{text:'الثانية'},{text:'متساويتان'},{text:'لا أعرف'}], correctOptionIndex:1, explanationAr:'المجموعة الأولى فيها 3 كلاب والثانية 5 كلاب، لذا المجموعة الثانية أكثر.', tags:[] },
  { ageGroup:'4-5', skillArea:'quantitative', subSkill:'العد', difficulty:'medium', questionType:'text', questionTextAr:'ما الرقم الذي يأتي بعد 7؟', questionImageUrl:null, options:[{text:'6'},{text:'8'},{text:'9'},{text:'10'}], correctOptionIndex:1, explanationAr:'عند العد: 6، 7، 8... الرقم بعد 7 هو 8.', tags:[] },
  { ageGroup:'4-5', skillArea:'quantitative', subSkill:'الأشكال', difficulty:'medium', questionType:'text', questionTextAr:'أي شكل له 4 أضلاع متساوية؟', questionImageUrl:null, options:[{text:'مثلث'},{text:'مربع'},{text:'دائرة'},{text:'مستطيل'}], correctOptionIndex:1, explanationAr:'المربع له 4 أضلاع كلها متساوية في الطول. المستطيل له 4 أضلاع لكن ضلعان أطول من الآخرين.', tags:[] },
  { ageGroup:'4-5', skillArea:'quantitative', subSkill:'الترتيب', difficulty:'medium', questionType:'text', questionTextAr:'من هو الأول في الصف: 🔴🔵🟢؟', questionImageUrl:null, options:[{text:'الأحمر'},{text:'الأزرق'},{text:'الأخضر'},{text:'لا أعرف'}], correctOptionIndex:0, explanationAr:'الأول في الصف هو الشكل الذي يأتي في المقدمة، وهو الدائرة الحمراء 🔴.', tags:[] },
  { ageGroup:'4-5', skillArea:'quantitative', subSkill:'العد', difficulty:'medium', questionType:'text', questionTextAr:'ما مجموع ⭐ + ⭐⭐ = ؟', questionImageUrl:null, options:[{text:'2'},{text:'3'},{text:'4'},{text:'5'}], correctOptionIndex:1, explanationAr:'نجمة واحدة زائد نجمتان = 3 نجوم. هذا هو الجمع البسيط.', tags:[] },
  { ageGroup:'4-5', skillArea:'quantitative', subSkill:'المقارنة', difficulty:'medium', questionType:'text', questionTextAr:'أيهما أكبر: 9 أم 6؟', questionImageUrl:null, options:[{text:'6'},{text:'9'},{text:'متساويان'},{text:'لا أعرف'}], correctOptionIndex:1, explanationAr:'الرقم 9 أكبر من 6 لأنه يأتي بعده في سلسلة الأعداد.', tags:[] },
  { ageGroup:'4-5', skillArea:'quantitative', subSkill:'العد', difficulty:'medium', questionType:'text', questionTextAr:'كم رجلاً للكرسي؟', questionImageUrl:null, options:[{text:'2'},{text:'3'},{text:'4'},{text:'5'}], correctOptionIndex:2, explanationAr:'معظم الكراسي لها 4 أرجل للاتزان والاستقرار.', tags:[] },
  { ageGroup:'4-5', skillArea:'quantitative', subSkill:'الأنماط', difficulty:'medium', questionType:'text', questionTextAr:'ما التالي: 🔴🔵🔴🔵...؟', questionImageUrl:null, options:[{text:'🔴'},{text:'🔵'},{text:'🟢'},{text:'🟡'}], correctOptionIndex:0, explanationAr:'النمط يتكرر: أحمر ثم أزرق. بعد الأزرق يأتي الأحمر.', tags:[] },

  // عمر 4-5 — كمي — صعب
  { ageGroup:'4-5', skillArea:'quantitative', subSkill:'الجمع البسيط', difficulty:'hard', questionType:'text', questionTextAr:'2 + 2 = ؟', questionImageUrl:null, options:[{text:'3'},{text:'4'},{text:'5'},{text:'6'}], correctOptionIndex:1, explanationAr:'اثنان زائد اثنان = أربعة. يمكنك العد على أصابعك: 1، 2 ثم 3، 4.', tags:[] },
  { ageGroup:'4-5', skillArea:'quantitative', subSkill:'الجمع البسيط', difficulty:'hard', questionType:'text', questionTextAr:'عندي 3 حلوى وأعطاني أخي 1 — كم أصبح عندي؟', questionImageUrl:null, options:[{text:'3'},{text:'4'},{text:'5'},{text:'2'}], correctOptionIndex:1, explanationAr:'3 حلوى + 1 حلوى = 4 حلوى. جمعنا العددين.', tags:[] },
  { ageGroup:'4-5', skillArea:'quantitative', subSkill:'الطرح البسيط', difficulty:'hard', questionType:'text', questionTextAr:'عندي 5 بالونات، طارت واحدة — كم بقي؟', questionImageUrl:null, options:[{text:'3'},{text:'4'},{text:'5'},{text:'6'}], correctOptionIndex:1, explanationAr:'5 - 1 = 4. عندما يطير بالون واحد يبقى 4 بالونات.', tags:[] },
  { ageGroup:'4-5', skillArea:'quantitative', subSkill:'الأنماط', difficulty:'hard', questionType:'text', questionTextAr:'ما التالي: 1، 2، 3، ...؟', questionImageUrl:null, options:[{text:'3'},{text:'4'},{text:'5'},{text:'6'}], correctOptionIndex:1, explanationAr:'النمط هو العد بالترتيب. بعد 1، 2، 3 يأتي 4.', tags:[] },
  { ageGroup:'4-5', skillArea:'quantitative', subSkill:'الطرح البسيط', difficulty:'hard', questionType:'text', questionTextAr:'4 - 2 = ؟', questionImageUrl:null, options:[{text:'1'},{text:'2'},{text:'3'},{text:'4'}], correctOptionIndex:1, explanationAr:'أربعة ناقص اثنين = اثنان. إذا أخذنا 2 من 4 يبقى 2.', tags:[] },
  { ageGroup:'4-5', skillArea:'quantitative', subSkill:'الأنماط', difficulty:'hard', questionType:'text', questionTextAr:'ما التالي: 🔴🔴🔵🔴🔴...؟', questionImageUrl:null, options:[{text:'🔴'},{text:'🔵'},{text:'🟢'},{text:'🟡'}], correctOptionIndex:1, explanationAr:'النمط هو: أحمر أحمر أزرق. بعد أحمر أحمر يأتي الأزرق.', tags:[] },
  { ageGroup:'4-5', skillArea:'quantitative', subSkill:'الجمع البسيط', difficulty:'hard', questionType:'text', questionTextAr:'1 + 1 + 1 = ؟', questionImageUrl:null, options:[{text:'1'},{text:'2'},{text:'3'},{text:'4'}], correctOptionIndex:2, explanationAr:'واحد زائد واحد زائد واحد = ثلاثة. نجمع الأعداد معاً.', tags:[] },
  { ageGroup:'4-5', skillArea:'quantitative', subSkill:'المقارنة', difficulty:'hard', questionType:'text', questionTextAr:'رتّب من الأكبر للأصغر: 5، 2، 8', questionImageUrl:null, options:[{text:'8 ، 5 ، 2'},{text:'2 ، 5 ، 8'},{text:'5 ، 2 ، 8'},{text:'8 ، 2 ، 5'}], correctOptionIndex:0, explanationAr:'الترتيب من الأكبر للأصغر: 8 أكبر رقم، ثم 5، ثم 2 أصغر رقم.', tags:[] },
  { ageGroup:'4-5', skillArea:'quantitative', subSkill:'الطرح البسيط', difficulty:'hard', questionType:'text', questionTextAr:'عندي 3 تفاحات وأكلت تفاحة — كم بقي؟', questionImageUrl:null, options:[{text:'1'},{text:'2'},{text:'3'},{text:'4'}], correctOptionIndex:1, explanationAr:'3 - 1 = 2. عندما نأكل تفاحة من ثلاث يبقى تفاحتان.', tags:[] },
  { ageGroup:'4-5', skillArea:'quantitative', subSkill:'الأشكال', difficulty:'hard', questionType:'text', questionTextAr:'كم ضلعاً للمستطيل؟', questionImageUrl:null, options:[{text:'2'},{text:'3'},{text:'4'},{text:'5'}], correctOptionIndex:2, explanationAr:'المستطيل له 4 أضلاع: ضلعان طويلان وضلعان قصيران. مثله مثل المربع لكن بأطوال مختلفة.', tags:[] },

  // ═══════════════════════════════════════════════
  // عمر 4-5 — لفظي — سهل
  // ═══════════════════════════════════════════════
  { ageGroup:'4-5', skillArea:'verbal', subSkill:'الألوان', difficulty:'easy', questionType:'text', questionTextAr:'ما لون السماء في النهار؟', questionImageUrl:null, options:[{text:'أحمر'},{text:'أزرق'},{text:'أخضر'},{text:'أصفر'}], correctOptionIndex:1, explanationAr:'السماء في النهار تكون زرقاء. هذا اللون الجميل يسمى الأزرق السماوي.', tags:[] },
  { ageGroup:'4-5', skillArea:'verbal', subSkill:'الألوان', difficulty:'easy', questionType:'text', questionTextAr:'ما لون العشب؟', questionImageUrl:null, options:[{text:'أصفر'},{text:'أزرق'},{text:'أخضر'},{text:'أحمر'}], correctOptionIndex:2, explanationAr:'العشب والنباتات لونها أخضر لأنها تحتوي على مادة الكلوروفيل.', tags:[] },
  { ageGroup:'4-5', skillArea:'verbal', subSkill:'الحيوانات', difficulty:'easy', questionType:'text', questionTextAr:'أي حيوان يقول "مياو"؟', questionImageUrl:null, options:[{text:'كلب'},{text:'قطة'},{text:'بقرة'},{text:'حصان'}], correctOptionIndex:1, explanationAr:'القطة هي التي تقول "مياو" أو "مو". الكلب يقول "هاو هاو" والبقرة تقول "خوار".', tags:[] },
  { ageGroup:'4-5', skillArea:'verbal', subSkill:'الحيوانات', difficulty:'easy', questionType:'text', questionTextAr:'أي حيوان يعيش في البحر؟', questionImageUrl:null, options:[{text:'أسد'},{text:'سمكة'},{text:'فيل'},{text:'أرنب'}], correctOptionIndex:1, explanationAr:'السمكة تعيش في الماء — في البحر أو النهر. باقي الحيوانات المذكورة تعيش على اليابسة.', tags:[] },
  { ageGroup:'4-5', skillArea:'verbal', subSkill:'الألوان', difficulty:'easy', questionType:'text', questionTextAr:'ما لون الشمس؟', questionImageUrl:null, options:[{text:'أزرق'},{text:'أخضر'},{text:'أصفر'},{text:'بنفسجي'}], correctOptionIndex:2, explanationAr:'الشمس تبدو صفراء أو برتقالية. الضوء الأصفر الدافئ للشمس يضيء يومنا.', tags:[] },
  { ageGroup:'4-5', skillArea:'verbal', subSkill:'الحيوانات', difficulty:'easy', questionType:'text', questionTextAr:'أي حيوان له خرطوم طويل؟', questionImageUrl:null, options:[{text:'أسد'},{text:'زرافة'},{text:'فيل'},{text:'نمر'}], correctOptionIndex:2, explanationAr:'الفيل له خرطوم طويل يستخدمه للشرب والإمساك بالأشياء وتناول الطعام.', tags:[] },
  { ageGroup:'4-5', skillArea:'verbal', subSkill:'الأشياء اليومية', difficulty:'easy', questionType:'text', questionTextAr:'ماذا نستخدم لأكل الطعام؟', questionImageUrl:null, options:[{text:'قلم'},{text:'ملعقة'},{text:'مقص'},{text:'مسطرة'}], correctOptionIndex:1, explanationAr:'نستخدم الملعقة لأكل الطعام السائل كالشوربة. كما نستخدم الشوكة والسكين.', tags:[] },
  { ageGroup:'4-5', skillArea:'verbal', subSkill:'الأشياء اليومية', difficulty:'easy', questionType:'text', questionTextAr:'ماذا نلبس في قدمينا؟', questionImageUrl:null, options:[{text:'قبعة'},{text:'قفاز'},{text:'حذاء'},{text:'نظارة'}], correctOptionIndex:2, explanationAr:'نلبس الحذاء في قدمينا لحمايتهما. الحذاء له أنواع كثيرة: رياضي، رسمي، صندل.', tags:[] },
  { ageGroup:'4-5', skillArea:'verbal', subSkill:'الألوان', difficulty:'easy', questionType:'text', questionTextAr:'ما لون الموزة؟', questionImageUrl:null, options:[{text:'أحمر'},{text:'أصفر'},{text:'أزرق'},{text:'أخضر'}], correctOptionIndex:1, explanationAr:'الموزة الناضجة لونها أصفر. عندما تكون غير ناضجة تكون خضراء.', tags:[] },
  { ageGroup:'4-5', skillArea:'verbal', subSkill:'الحيوانات', difficulty:'easy', questionType:'text', questionTextAr:'أي حيوان له رقبة طويلة جداً؟', questionImageUrl:null, options:[{text:'فيل'},{text:'أسد'},{text:'زرافة'},{text:'دب'}], correctOptionIndex:2, explanationAr:'الزرافة لها رقبة طويلة جداً تساعدها على الوصول لأوراق الأشجار العالية.', tags:[] },

  // عمر 4-5 — لفظي — متوسط
  { ageGroup:'4-5', skillArea:'verbal', subSkill:'المتضادات', difficulty:'medium', questionType:'text', questionTextAr:'ما عكس كلمة "كبير"؟', questionImageUrl:null, options:[{text:'طويل'},{text:'صغير'},{text:'ثقيل'},{text:'سريع'}], correctOptionIndex:1, explanationAr:'عكس "كبير" هو "صغير". الكلمات المتعاكسة تحمل معنى معاكساً تماماً.', tags:[] },
  { ageGroup:'4-5', skillArea:'verbal', subSkill:'المتضادات', difficulty:'medium', questionType:'text', questionTextAr:'ما عكس كلمة "بارد"؟', questionImageUrl:null, options:[{text:'جاف'},{text:'ندي'},{text:'ساخن'},{text:'رطب'}], correctOptionIndex:2, explanationAr:'عكس "بارد" هو "ساخن". الماء البارد يكون برودته واضحة، والساخن يمكن لمسه بحذر.', tags:[] },
  { ageGroup:'4-5', skillArea:'verbal', subSkill:'التصنيف', difficulty:'medium', questionType:'text', questionTextAr:'أيهما لا ينتمي للمجموعة: تفاحة، موزة، سيارة، برتقالة؟', questionImageUrl:null, options:[{text:'تفاحة'},{text:'موزة'},{text:'سيارة'},{text:'برتقالة'}], correctOptionIndex:2, explanationAr:'السيارة لا تنتمي للمجموعة لأن التفاحة والموزة والبرتقالة كلها فواكه، أما السيارة فهي وسيلة نقل.', tags:[] },
  { ageGroup:'4-5', skillArea:'verbal', subSkill:'التصنيف', difficulty:'medium', questionType:'text', questionTextAr:'أيهما لا ينتمي: كلب، قطة، أسد، سيارة؟', questionImageUrl:null, options:[{text:'كلب'},{text:'قطة'},{text:'أسد'},{text:'سيارة'}], correctOptionIndex:3, explanationAr:'الكلب والقطة والأسد كلها حيوانات، أما السيارة فهي آلة من صنع الإنسان.', tags:[] },
  { ageGroup:'4-5', skillArea:'verbal', subSkill:'المتضادات', difficulty:'medium', questionType:'text', questionTextAr:'ما عكس كلمة "طويل"؟', questionImageUrl:null, options:[{text:'ضخم'},{text:'نحيف'},{text:'قصير'},{text:'سميك'}], correctOptionIndex:2, explanationAr:'عكس "طويل" هو "قصير". الجبل طويل، والسلم قد يكون قصيراً.', tags:[] },
  { ageGroup:'4-5', skillArea:'verbal', subSkill:'التصنيف', difficulty:'medium', questionType:'text', questionTextAr:'أيهما طعام: خبز، قلم، لبن، جبن؟', questionImageUrl:null, options:[{text:'خبز فقط'},{text:'قلم فقط'},{text:'خبز ولبن وجبن'},{text:'كلها'}], correctOptionIndex:2, explanationAr:'الخبز واللبن والجبن كلها أطعمة نأكلها. القلم أداة للكتابة وليس طعاماً.', tags:[] },
  { ageGroup:'4-5', skillArea:'verbal', subSkill:'المتضادات', difficulty:'medium', questionType:'text', questionTextAr:'ما عكس كلمة "ليل"؟', questionImageUrl:null, options:[{text:'مساء'},{text:'نهار'},{text:'غروب'},{text:'شروق'}], correctOptionIndex:1, explanationAr:'عكس "ليل" هو "نهار". في الليل تظهر النجوم والقمر، وفي النهار تشرق الشمس.', tags:[] },
  { ageGroup:'4-5', skillArea:'verbal', subSkill:'التصنيف', difficulty:'medium', questionType:'text', questionTextAr:'ماذا نستخدم في المدرسة: كتاب، دفتر، قلم، أم سيف؟', questionImageUrl:null, options:[{text:'كتاب فقط'},{text:'كتاب ودفتر وقلم'},{text:'سيف فقط'},{text:'كلها'}], correctOptionIndex:1, explanationAr:'الكتاب والدفتر والقلم أدوات مدرسية نستخدمها للتعلم. السيف ليس أداة مدرسية.', tags:[] },
  { ageGroup:'4-5', skillArea:'verbal', subSkill:'المتضادات', difficulty:'medium', questionType:'text', questionTextAr:'ما عكس كلمة "فوق"؟', questionImageUrl:null, options:[{text:'جانب'},{text:'أمام'},{text:'تحت'},{text:'خلف'}], correctOptionIndex:2, explanationAr:'عكس "فوق" هو "تحت". الطائر يطير فوق، والسمكة تسبح تحت الماء.', tags:[] },
  { ageGroup:'4-5', skillArea:'verbal', subSkill:'المتضادات', difficulty:'medium', questionType:'text', questionTextAr:'ما عكس كلمة "سريع"؟', questionImageUrl:null, options:[{text:'قوي'},{text:'بطيء'},{text:'ذكي'},{text:'كبير'}], correctOptionIndex:1, explanationAr:'عكس "سريع" هو "بطيء". الأرنب سريع، والسلحفاة بطيئة.', tags:[] },

  // عمر 4-5 — لفظي — صعب
  { ageGroup:'4-5', skillArea:'verbal', subSkill:'إكمال الجملة', difficulty:'hard', questionType:'text', questionTextAr:'أكمل: "نشرب الماء لأننا ..."', questionImageUrl:null, options:[{text:'نريد النوم'},{text:'عطشانون'},{text:'نريد اللعب'},{text:'نريد الأكل'}], correctOptionIndex:1, explanationAr:'نشرب الماء لأننا عطشانون. الماء ضروري لحياة الإنسان ويجب أن نشربه كل يوم.', tags:[] },
  { ageGroup:'4-5', skillArea:'verbal', subSkill:'إكمال الجملة', difficulty:'hard', questionType:'text', questionTextAr:'أكمل: "نلبس المعطف عندما يكون الجو ..."', questionImageUrl:null, options:[{text:'حاراً'},{еtext:'جميلاً'},{text:'بارداً'},{text:'ممطراً'}], correctOptionIndex:2, explanationAr:'نلبس المعطف عندما يكون الجو بارداً لنحمي أجسامنا من البرد.', tags:[] },
  { ageGroup:'4-5', skillArea:'verbal', subSkill:'الفهم', difficulty:'hard', questionType:'text', questionTextAr:'ما الذي يطير في السماء: طائر، سمكة، كلب، قطة؟', questionImageUrl:null, options:[{text:'سمكة'},{text:'طائر'},{text:'كلب'},{text:'قطة'}], correctOptionIndex:1, explanationAr:'الطائر هو الذي يطير في السماء بأجنحته. باقي الحيوانات المذكورة لا تطير.', tags:[] },
  { ageGroup:'4-5', skillArea:'verbal', subSkill:'التصنيف المتقدم', difficulty:'hard', questionType:'text', questionTextAr:'أيهما يسبح في الماء: حوت، فيل، أسد، نسر؟', questionImageUrl:null, options:[{text:'فيل'},{text:'أسد'},{text:'حوت'},{text:'نسر'}], correctOptionIndex:2, explanationAr:'الحوت هو الكائن الذي يعيش ويسبح في الماء. الفيل والأسد حيوانات برية والنسر يطير.', tags:[] },
  { ageGroup:'4-5', skillArea:'verbal', subSkill:'إكمال الجملة', difficulty:'hard', questionType:'text', questionTextAr:'أكمل: "نذهب إلى المستشفى عندما نكون ..."', questionImageUrl:null, options:[{text:'جائعين'},{text:'مرضى'},{text:'نائمين'},{text:'فرحين'}], correctOptionIndex:1, explanationAr:'نذهب إلى المستشفى عندما نكون مرضى لنرى الطبيب الذي يساعدنا على الشفاء.', tags:[] },
  { ageGroup:'4-5', skillArea:'verbal', subSkill:'الفهم', difficulty:'hard', questionType:'text', questionTextAr:'ما الذي يعطينا الضوء في الليل في المنزل؟', questionImageUrl:null, options:[{text:'الشمس'},{text:'القمر'},{text:'المصباح'},{text:'النجوم'}], correctOptionIndex:2, explanationAr:'المصباح الكهربائي هو ما يعطينا الضوء في المنزل ليلاً. الشمس تضيء النهار خارج البيت.', tags:[] },
  { ageGroup:'4-5', skillArea:'verbal', subSkill:'التصنيف المتقدم', difficulty:'hard', questionType:'text', questionTextAr:'أي الأماكن التالية نذهب إليه للدراسة؟', questionImageUrl:null, options:[{text:'المستشفى'},{text:'السوق'},{text:'المدرسة'},{text:'الحديقة'}], correctOptionIndex:2, explanationAr:'نذهب إلى المدرسة للدراسة وتعلم القراءة والكتابة والحساب.', tags:[] },
  { ageGroup:'4-5', skillArea:'verbal', subSkill:'إكمال الجملة', difficulty:'hard', questionType:'text', questionTextAr:'أكمل: "الأسد يعيش في ..."', questionImageUrl:null, options:[{text:'البحر'},{text:'الغابة'},{text:'المنزل'},{text:'المدرسة'}], correctOptionIndex:1, explanationAr:'الأسد يعيش في الغابة أو السافانا. يصطاد ويعيش مع أسرته في بيئته الطبيعية.', tags:[] },
  { ageGroup:'4-5', skillArea:'verbal', subSkill:'الفهم', difficulty:'hard', questionType:'text', questionTextAr:'ماذا تفعل النحلة؟', questionImageUrl:null, options:[{text:'تسبح في الماء'},{text:'تجمع العسل'},{text:'تحفر في الأرض'},{text:'تقطع الأشجار'}], correctOptionIndex:1, explanationAr:'النحلة تجمع رحيق الزهور وتصنع منه العسل اللذيذ. العسل مفيد جداً لصحتنا.', tags:[] },
  { ageGroup:'4-5', skillArea:'verbal', subSkill:'الفهم', difficulty:'hard', questionType:'text', questionTextAr:'ما الذي نستخدمه لكتابة الحروف؟', questionImageUrl:null, options:[{text:'ملعقة'},{text:'قلم'},{text:'كأس'},{text:'مفتاح'}], correctOptionIndex:1, explanationAr:'نستخدم القلم لكتابة الحروف والأرقام. القلم يمكن أن يكون رصاصاً أو حبراً.', tags:[] },

  // ═══════════════════════════════════════════════
  // عمر 4-5 — منطقي — سهل
  // ═══════════════════════════════════════════════
  { ageGroup:'4-5', skillArea:'logical_patterns', subSkill:'ما يختلف', difficulty:'easy', questionType:'text', questionTextAr:'أيهما مختلف: 🔴🔴🔴🔵؟', questionImageUrl:null, options:[{text:'الأولى'},{text:'الثانية'},{text:'الثالثة'},{text:'الرابعة'}], correctOptionIndex:3, explanationAr:'الأولى والثانية والثالثة حمراء، لكن الرابعة زرقاء — إذن هي المختلفة.', tags:[] },
  { ageGroup:'4-5', skillArea:'logical_patterns', subSkill:'الأنماط', difficulty:'easy', questionType:'text', questionTextAr:'ما التالي: ⭐🌙⭐🌙...؟', questionImageUrl:null, options:[{text:'⭐'},{text:'🌙'},{text:'☀️'},{text:'🌟'}], correctOptionIndex:0, explanationAr:'النمط يتكرر: نجمة ثم قمر. بعد القمر يأتي نجمة.', tags:[] },
  { ageGroup:'4-5', skillArea:'logical_patterns', subSkill:'التصنيف', difficulty:'easy', questionType:'text', questionTextAr:'أيهما ينتمي للفواكه: موزة، قلم، كتاب، حذاء؟', questionImageUrl:null, options:[{text:'قلم'},{text:'موزة'},{text:'كتاب'},{text:'حذاء'}], correctOptionIndex:1, explanationAr:'الموزة فاكهة نأكلها. القلم والكتاب أدوات مدرسية والحذاء ملبس.', tags:[] },
  { ageGroup:'4-5', skillArea:'logical_patterns', subSkill:'ما يختلف', difficulty:'easy', questionType:'text', questionTextAr:'أيهما مختلف: كلب، قطة، سمكة، طائر؟', questionImageUrl:null, options:[{text:'كلب'},{text:'قطة'},{text:'سمكة'},{text:'طائر'}], correctOptionIndex:2, explanationAr:'الكلب والقطة والطائر يعيشون على اليابسة، أما السمكة فتعيش في الماء — هي المختلفة.', tags:[] },
  { ageGroup:'4-5', skillArea:'logical_patterns', subSkill:'الأنماط', difficulty:'easy', questionType:'text', questionTextAr:'ما التالي: 🔴🔴🔴...؟', questionImageUrl:null, options:[{text:'🔴'},{text:'🔵'},{text:'🟢'},{text:'🟡'}], correctOptionIndex:0, explanationAr:'النمط هو تكرار الدائرة الحمراء باستمرار.', tags:[] },
  { ageGroup:'4-5', skillArea:'logical_patterns', subSkill:'التصنيف', difficulty:'easy', questionType:'text', questionTextAr:'أيهما وسيلة نقل: سيارة، كتاب، قلم، كرسي؟', questionImageUrl:null, options:[{text:'كتاب'},{text:'سيارة'},{text:'قلم'},{text:'كرسي'}], correctOptionIndex:1, explanationAr:'السيارة وسيلة نقل تحملنا من مكان لآخر. الكتاب والقلم أدوات تعلم والكرسي أثاث.', tags:[] },
  { ageGroup:'4-5', skillArea:'logical_patterns', subSkill:'ما يختلف', difficulty:'easy', questionType:'text', questionTextAr:'أيهما مختلف: مثلث، دائرة، مربع، قطة؟', questionImageUrl:null, options:[{text:'مثلث'},{text:'دائرة'},{text:'مربع'},{text:'قطة'}], correctOptionIndex:3, explanationAr:'المثلث والدائرة والمربع كلها أشكال هندسية، أما القطة فهي حيوان — هي المختلفة.', tags:[] },
  { ageGroup:'4-5', skillArea:'logical_patterns', subSkill:'الأنماط', difficulty:'easy', questionType:'text', questionTextAr:'ما التالي: 1، 2، 1، 2، ...؟', questionImageUrl:null, options:[{text:'3'},{text:'1'},{text:'4'},{text:'2'}], correctOptionIndex:1, explanationAr:'النمط هو: 1 ثم 2 ثم 1 ثم 2... بعد الـ2 يأتي الـ1.', tags:[] },
  { ageGroup:'4-5', skillArea:'logical_patterns', subSkill:'التصنيف', difficulty:'easy', questionType:'text', questionTextAr:'أيهما ينتمي للحيوانات البحرية: حوت، أسد، فيل، نمر؟', questionImageUrl:null, options:[{text:'أسد'},{text:'حوت'},{text:'فيل'},{text:'نمر'}], correctOptionIndex:1, explanationAr:'الحوت يعيش في البحر وهو من الحيوانات البحرية. الأسد والفيل والنمر حيوانات برية.', tags:[] },
  { ageGroup:'4-5', skillArea:'logical_patterns', subSkill:'ما يختلف', difficulty:'easy', questionType:'text', questionTextAr:'أيهما مختلف: تفاحة، برتقالة، كمبيوتر، موزة؟', questionImageUrl:null, options:[{text:'تفاحة'},{text:'برتقالة'},{text:'كمبيوتر'},{text:'موزة'}], correctOptionIndex:2, explanationAr:'التفاحة والبرتقالة والموزة فواكه، أما الكمبيوتر فجهاز إلكتروني — هو المختلف.', tags:[] },

  // عمر 4-5 — منطقي — متوسط
  { ageGroup:'4-5', skillArea:'logical_patterns', subSkill:'الأنماط', difficulty:'medium', questionType:'text', questionTextAr:'ما التالي: 🔴🔵🟢🔴🔵...؟', questionImageUrl:null, options:[{text:'🔴'},{text:'🔵'},{text:'🟢'},{text:'🟡'}], correctOptionIndex:2, explanationAr:'النمط هو: أحمر ثم أزرق ثم أخضر. بعد الأزرق يأتي الأخضر.', tags:[] },
  { ageGroup:'4-5', skillArea:'logical_patterns', subSkill:'الاستنتاج', difficulty:'medium', questionType:'text', questionTextAr:'كل طيور تطير. الببغاء طائر. هل يطير الببغاء؟', questionImageUrl:null, options:[{text:'نعم'},{text:'لا'},{text:'أحياناً'},{text:'لا أعرف'}], correctOptionIndex:0, explanationAr:'نعم! كل الطيور تطير، والببغاء طائر، إذن الببغاء يطير. هذا ما يسمى الاستنتاج المنطقي.', tags:[] },
  { ageGroup:'4-5', skillArea:'logical_patterns', subSkill:'التصنيف', difficulty:'medium', questionType:'text', questionTextAr:'رتّب من الأصغر للأكبر: قطة، أسد، فأر', questionImageUrl:null, options:[{text:'أسد، قطة، فأر'},{text:'فأر، قطة، أسد'},{text:'قطة، فأر، أسد'},{text:'فأر، أسد، قطة'}], correctOptionIndex:1, explanationAr:'الفأر أصغر حيوان، ثم القطة متوسطة الحجم، ثم الأسد أكبرها. الترتيب: فأر، قطة، أسد.', tags:[] },
  { ageGroup:'4-5', skillArea:'logical_patterns', subSkill:'الأنماط', difficulty:'medium', questionType:'text', questionTextAr:'ما التالي: 1، 2، 3، 4، ...؟', questionImageUrl:null, options:[{text:'4'},{text:'5'},{text:'6'},{text:'7'}], correctOptionIndex:1, explanationAr:'النمط هو العد بالترتيب +1 في كل مرة. بعد 4 يأتي 5.', tags:[] },
  { ageGroup:'4-5', skillArea:'logical_patterns', subSkill:'ما يختلف', difficulty:'medium', questionType:'text', questionTextAr:'أيهما لا يسبح: سمكة، دلفين، حصان، حوت؟', questionImageUrl:null, options:[{text:'سمكة'},{text:'دلفين'},{text:'حصان'},{text:'حوت'}], correctOptionIndex:2, explanationAr:'الحصان حيوان بري يجري على الأرض. السمكة والدلفين والحوت تعيش في الماء وتسبح.', tags:[] },
  { ageGroup:'4-5', skillArea:'logical_patterns', subSkill:'الاستنتاج', difficulty:'medium', questionType:'text', questionTextAr:'سارة أكبر من علي، وعلي أكبر من محمد. من الأصغر؟', questionImageUrl:null, options:[{text:'سارة'},{text:'علي'},{text:'محمد'},{text:'كلهم متساوون'}], correctOptionIndex:2, explanationAr:'سارة > علي > محمد. إذن محمد هو الأصغر بينهم.', tags:[] },
  { ageGroup:'4-5', skillArea:'logical_patterns', subSkill:'الأنماط', difficulty:'medium', questionType:'text', questionTextAr:'ما التالي: 2، 2، 2، ...؟', questionImageUrl:null, options:[{text:'1'},{text:'2'},{text:'3'},{text:'4'}], correctOptionIndex:1, explanationAr:'النمط هو تكرار الرقم 2 باستمرار. إذن التالي هو 2.', tags:[] },
  { ageGroup:'4-5', skillArea:'logical_patterns', subSkill:'الاستنتاج', difficulty:'medium', questionType:'text', questionTextAr:'إذا كانت التفاحة حمراء والموزة صفراء، ما لون التفاحة؟', questionImageUrl:null, options:[{text:'أصفر'},{text:'أخضر'},{text:'أحمر'},{text:'أزرق'}], correctOptionIndex:2, explanationAr:'السؤال يخبرنا مباشرة أن التفاحة حمراء. هذا سؤال اختبار الفهم والانتباه.', tags:[] },
  { ageGroup:'4-5', skillArea:'logical_patterns', subSkill:'التصنيف', difficulty:'medium', questionType:'text', questionTextAr:'أيهما في مجموعة الحلويات: تفاحة، كيكة، جزر، خيار؟', questionImageUrl:null, options:[{text:'تفاحة'},{text:'جزر'},{text:'كيكة'},{text:'خيار'}], correctOptionIndex:2, explanationAr:'الكيكة حلوى. التفاحة والجزر والخيار خضروات وفواكه صحية.', tags:[] },
  { ageGroup:'4-5', skillArea:'logical_patterns', subSkill:'الأنماط', difficulty:'medium', questionType:'text', questionTextAr:'ما التالي: 🌞🌧️🌞🌧️...؟', questionImageUrl:null, options:[{text:'🌧️'},{text:'🌞'},{text:'⭐'},{text:'🌙'}], correctOptionIndex:1, explanationAr:'النمط يتكرر: شمس ثم مطر. بعد المطر تأتي الشمس.', tags:[] },

  // عمر 4-5 — منطقي — صعب
  { ageGroup:'4-5', skillArea:'logical_patterns', subSkill:'الاستنتاج', difficulty:'hard', questionType:'text', questionTextAr:'كل القطط تموء. ميمي قطة. ماذا تفعل ميمي؟', questionImageUrl:null, options:[{text:'تنبح'},{text:'تموء'},{text:'تصفر'},{text:'تزقزق'}], correctOptionIndex:1, explanationAr:'لأن كل القطط تموء وميمي قطة، إذن ميمي تموء. هذا استنتاج منطقي مبني على قاعدة عامة.', tags:[] },
  { ageGroup:'4-5', skillArea:'logical_patterns', subSkill:'الأنماط المتقدمة', difficulty:'hard', questionType:'text', questionTextAr:'ما التالي: 1، 3، 5، ...؟', questionImageUrl:null, options:[{text:'6'},{text:'7'},{text:'8'},{text:'9'}], correctOptionIndex:1, explanationAr:'النمط هو الأعداد الفردية: 1، 3، 5، 7... نضيف 2 في كل مرة.', tags:[] },
  { ageGroup:'4-5', skillArea:'logical_patterns', subSkill:'الاستنتاج', difficulty:'hard', questionType:'text', questionTextAr:'أحمد أطول من خالد، وخالد أطول من عمر. من الأقصر؟', questionImageUrl:null, options:[{text:'أحمد'},{text:'خالد'},{text:'عمر'},{text:'كلهم متساوون'}], correctOptionIndex:2, explanationAr:'أحمد > خالد > عمر. إذن عمر هو الأقصر بينهم.', tags:[] },
  { ageGroup:'4-5', skillArea:'logical_patterns', subSkill:'الأنماط المتقدمة', difficulty:'hard', questionType:'text', questionTextAr:'ما التالي: 2، 4، 6، ...؟', questionImageUrl:null, options:[{text:'7'},{text:'8'},{text:'9'},{text:'10'}], correctOptionIndex:1, explanationAr:'النمط هو الأعداد الزوجية: 2، 4، 6، 8... نضيف 2 في كل مرة.', tags:[] },
  { ageGroup:'4-5', skillArea:'logical_patterns', subSkill:'الاستنتاج', difficulty:'hard', questionType:'text', questionTextAr:'إذا كان اليوم الثلاثاء، ما اليوم الذي قبله؟', questionImageUrl:null, options:[{text:'الأربعاء'},{text:'الاثنين'},{text:'الأحد'},{text:'الأحد'}], correctOptionIndex:1, explanationAr:'ترتيب الأسبوع: الأحد، الاثنين، الثلاثاء... اليوم الذي قبل الثلاثاء هو الاثنين.', tags:[] },
  { ageGroup:'4-5', skillArea:'logical_patterns', subSkill:'الأنماط المتقدمة', difficulty:'hard', questionType:'text', questionTextAr:'ما التالي: 🔴🔴🔵🔴🔴🔵...؟', questionImageUrl:null, options:[{text:'🔵'},{text:'🔴'},{text:'🟢'},{text:'🟡'}], correctOptionIndex:1, explanationAr:'النمط هو: أحمر، أحمر، أزرق. بعد الأزرق يأتي أحمر أحمر مرة أخرى.', tags:[] },
  { ageGroup:'4-5', skillArea:'logical_patterns', subSkill:'التفكير الإبداعي', difficulty:'hard', questionType:'text', questionTextAr:'لدي 3 أقلام وأخي لديه 5. من لديه أكثر بقلمين؟', questionImageUrl:null, options:[{text:'أنا'},{text:'أخي'},{text:'متساوون'},{text:'لا أعرف'}], correctOptionIndex:1, explanationAr:'أنا لدي 3 وأخي 5. الفرق = 5 - 3 = 2. أخي لديه أكثر بقلمين.', tags:[] },
  { ageGroup:'4-5', skillArea:'logical_patterns', subSkill:'الاستنتاج', difficulty:'hard', questionType:'text', questionTextAr:'الثلج أبيض. أسقط الثلج. ما لون الأرض الآن؟', questionImageUrl:null, options:[{text:'أسود'},{text:'أبيض'},{text:'أخضر'},{text:'بني'}], correctOptionIndex:1, explanationAr:'الثلج أبيض. عندما يسقط الثلج ويغطي الأرض، تصبح الأرض بيضاء اللون.', tags:[] },
  { ageGroup:'4-5', skillArea:'logical_patterns', subSkill:'الأنماط المتقدمة', difficulty:'hard', questionType:'text', questionTextAr:'ما الرقم المفقود: 1، __, 3، 4؟', questionImageUrl:null, options:[{text:'1'},{text:'2'},{text:'5'},{text:'6'}], correctOptionIndex:1, explanationAr:'السلسلة هي: 1، 2، 3، 4. الرقم المفقود هو 2.', tags:[] },
  { ageGroup:'4-5', skillArea:'logical_patterns', subSkill:'الاستنتاج', difficulty:'hard', questionType:'text', questionTextAr:'إذا نام الطفل مبكراً، سيستيقظ مبكراً. نام مبكراً. هل سيستيقظ مبكراً؟', questionImageUrl:null, options:[{text:'نعم'},{text:'لا'},{text:'ربما'},{text:'لا أعرف'}], correctOptionIndex:0, explanationAr:'نعم. لأن القاعدة تقول: النوم مبكراً يؤدي للاستيقاظ مبكراً، وقد نام مبكراً فعلاً.', tags:[] },

  // ═══════════════════════════════════════════════
  // عمر 6-9 — كمي — سهل
  // ═══════════════════════════════════════════════
  { ageGroup:'6-9', skillArea:'quantitative', subSkill:'الجمع', difficulty:'easy', questionType:'text', questionTextAr:'12 + 7 = ؟', questionImageUrl:null, options:[{text:'17'},{text:'18'},{text:'19'},{text:'20'}], correctOptionIndex:2, explanationAr:'12 + 7 = 19. نجمع العدد 7 مع العدد 12: 12، 13، 14، 15، 16، 17، 18، 19.', tags:[] },
  { ageGroup:'6-9', skillArea:'quantitative', subSkill:'الطرح', difficulty:'easy', questionType:'text', questionTextAr:'20 - 8 = ؟', questionImageUrl:null, options:[{text:'10'},{text:'11'},{text:'12'},{text:'13'}], correctOptionIndex:2, explanationAr:'20 - 8 = 12. نطرح 8 من 20: 20 - 10 = 10، 10 + 2 = 12.', tags:[] },
  { ageGroup:'6-9', skillArea:'quantitative', subSkill:'الجمع', difficulty:'easy', questionType:'text', questionTextAr:'25 + 10 = ؟', questionImageUrl:null, options:[{text:'33'},{text:'34'},{text:'35'},{text:'36'}], correctOptionIndex:2, explanationAr:'25 + 10 = 35. عند جمع 10 نزيد العشرات بمقدار واحد.', tags:[] },
  { ageGroup:'6-9', skillArea:'quantitative', subSkill:'الطرح', difficulty:'easy', questionType:'text', questionTextAr:'15 - 5 = ؟', questionImageUrl:null, options:[{text:'8'},{text:'9'},{text:'10'},{text:'11'}], correctOptionIndex:2, explanationAr:'15 - 5 = 10. نطرح الآحاد من الآحاد: 5 - 5 = 0، تبقى العشرة.', tags:[] },
  { ageGroup:'6-9', skillArea:'quantitative', subSkill:'الضرب', difficulty:'easy', questionType:'text', questionTextAr:'2 × 5 = ؟', questionImageUrl:null, options:[{text:'8'},{text:'9'},{text:'10'},{text:'11'}], correctOptionIndex:2, explanationAr:'2 × 5 = 10. الضرب هو جمع متكرر: 2 + 2 + 2 + 2 + 2 = 10.', tags:[] },
  { ageGroup:'6-9', skillArea:'quantitative', subSkill:'القسمة', difficulty:'easy', questionType:'text', questionTextAr:'10 ÷ 2 = ؟', questionImageUrl:null, options:[{text:'3'},{text:'4'},{text:'5'},{text:'6'}], correctOptionIndex:2, explanationAr:'10 ÷ 2 = 5. القسمة تعني التوزيع المتساوي: 10 مقسمة على 2 = 5 لكل واحد.', tags:[] },
  { ageGroup:'6-9', skillArea:'quantitative', subSkill:'المسائل', difficulty:'easy', questionType:'text', questionTextAr:'اشترت أمل 6 تفاحات وأكلت 2. كم تبقى معها؟', questionImageUrl:null, options:[{text:'2'},{text:'3'},{text:'4'},{text:'5'}], correctOptionIndex:2, explanationAr:'6 - 2 = 4. أمل لديها 4 تفاحات متبقية.', tags:[] },
  { ageGroup:'6-9', skillArea:'quantitative', subSkill:'الجمع', difficulty:'easy', questionType:'text', questionTextAr:'30 + 20 = ؟', questionImageUrl:null, options:[{text:'40'},{text:'50'},{text:'60'},{text:'70'}], correctOptionIndex:1, explanationAr:'30 + 20 = 50. نجمع العشرات: 3 + 2 = 5، والنتيجة 50.', tags:[] },
  { ageGroup:'6-9', skillArea:'quantitative', subSkill:'الضرب', difficulty:'easy', questionType:'text', questionTextAr:'3 × 3 = ؟', questionImageUrl:null, options:[{text:'6'},{text:'7'},{text:'8'},{text:'9'}], correctOptionIndex:3, explanationAr:'3 × 3 = 9. ثلاثة مجموعات من ثلاثة: 3 + 3 + 3 = 9.', tags:[] },
  { ageGroup:'6-9', skillArea:'quantitative', subSkill:'المسائل', difficulty:'easy', questionType:'text', questionTextAr:'لدى سامي 10 ريالات، اشترى كتاباً بـ6 ريالات. كم تبقى؟', questionImageUrl:null, options:[{text:'2'},{text:'3'},{text:'4'},{text:'5'}], correctOptionIndex:2, explanationAr:'10 - 6 = 4 ريالات. هذا سؤال طرح بسيط مع قصة.', tags:[] },

  // عمر 6-9 — كمي — متوسط
  { ageGroup:'6-9', skillArea:'quantitative', subSkill:'الضرب', difficulty:'medium', questionType:'text', questionTextAr:'6 × 7 = ؟', questionImageUrl:null, options:[{text:'38'},{text:'40'},{text:'42'},{text:'44'}], correctOptionIndex:2, explanationAr:'6 × 7 = 42. من جدول ضرب الستة: 6، 12، 18، 24، 30، 36، 42.', tags:[] },
  { ageGroup:'6-9', skillArea:'quantitative', subSkill:'الكسور', difficulty:'medium', questionType:'text', questionTextAr:'ما نصف الرقم 18؟', questionImageUrl:null, options:[{text:'7'},{text:'8'},{text:'9'},{text:'10'}], correctOptionIndex:2, explanationAr:'نصف 18 = 18 ÷ 2 = 9. النصف يعني القسمة على اثنين.', tags:[] },
  { ageGroup:'6-9', skillArea:'quantitative', subSkill:'المسائل', difficulty:'medium', questionType:'text', questionTextAr:'اشترى فارس 3 أقلام بسعر 5 ريالات لكل قلم. كم دفع؟', questionImageUrl:null, options:[{text:'12'},{text:'15'},{text:'18'},{text:'20'}], correctOptionIndex:1, explanationAr:'3 × 5 = 15 ريال. نضرب عدد الأقلام في سعر القلم الواحد.', tags:[] },
  { ageGroup:'6-9', skillArea:'quantitative', subSkill:'الكسور', difficulty:'medium', questionType:'text', questionTextAr:'ما ربع الرقم 20؟', questionImageUrl:null, options:[{text:'3'},{text:'4'},{text:'5'},{text:'6'}], correctOptionIndex:2, explanationAr:'ربع 20 = 20 ÷ 4 = 5. الربع يعني القسمة على أربعة.', tags:[] },
  { ageGroup:'6-9', skillArea:'quantitative', subSkill:'الضرب', difficulty:'medium', questionType:'text', questionTextAr:'8 × 9 = ؟', questionImageUrl:null, options:[{text:'62'},{text:'70'},{text:'72'},{text:'74'}], correctOptionIndex:2, explanationAr:'8 × 9 = 72. من جدول ضرب الثمانية: ...64، 72...', tags:[] },
  { ageGroup:'6-9', skillArea:'quantitative', subSkill:'المسائل', difficulty:'medium', questionType:'text', questionTextAr:'كيس فيه 24 تمرة، تقاسمها 4 أطفال بالتساوي. كم لكل طفل؟', questionImageUrl:null, options:[{text:'4'},{text:'5'},{text:'6'},{text:'7'}], correctOptionIndex:2, explanationAr:'24 ÷ 4 = 6. نقسم عدد التمرات على عدد الأطفال.', tags:[] },
  { ageGroup:'6-9', skillArea:'quantitative', subSkill:'القسمة', difficulty:'medium', questionType:'text', questionTextAr:'36 ÷ 6 = ؟', questionImageUrl:null, options:[{text:'4'},{text:'5'},{text:'6'},{text:'7'}], correctOptionIndex:2, explanationAr:'36 ÷ 6 = 6. لأن 6 × 6 = 36.', tags:[] },
  { ageGroup:'6-9', skillArea:'quantitative', subSkill:'الكسور', difficulty:'medium', questionType:'text', questionTextAr:'ما ثلثا الرقم 12؟', questionImageUrl:null, options:[{text:'6'},{text:'7'},{text:'8'},{text:'9'}], correctOptionIndex:2, explanationAr:'ثلث 12 = 4، وثلثان = 8. نقسم على 3 ونضرب في 2.', tags:[] },
  { ageGroup:'6-9', skillArea:'quantitative', subSkill:'المسائل', difficulty:'medium', questionType:'text', questionTextAr:'في فصل 30 طالباً، نصفهم بنات. كم عدد البنات؟', questionImageUrl:null, options:[{text:'10'},{text:'15'},{text:'20'},{text:'25'}], correctOptionIndex:1, explanationAr:'نصف 30 = 30 ÷ 2 = 15. نصف الطلاب يعني قسمة العدد الكلي على 2.', tags:[] },
  { ageGroup:'6-9', skillArea:'quantitative', subSkill:'الضرب', difficulty:'medium', questionType:'text', questionTextAr:'4 × 8 = ؟', questionImageUrl:null, options:[{text:'29'},{text:'30'},{text:'31'},{text:'32'}], correctOptionIndex:3, explanationAr:'4 × 8 = 32. من جدول ضرب الأربعة: 4، 8، 12، 16، 20، 24، 28، 32.', tags:[] },

  // عمر 6-9 — كمي — صعب
  { ageGroup:'6-9', skillArea:'quantitative', subSkill:'المسائل المركبة', difficulty:'hard', questionType:'text', questionTextAr:'اشترى أحمد 5 كتب بـ8 ريالات كل كتاب، ودفع 50 ريالاً. كم باقيه؟', questionImageUrl:null, options:[{text:'5'},{text:'10'},{text:'15'},{text:'20'}], correctOptionIndex:1, explanationAr:'سعر الكتب = 5 × 8 = 40 ريال. الباقي = 50 - 40 = 10 ريال.', tags:[] },
  { ageGroup:'6-9', skillArea:'quantitative', subSkill:'الأنماط الرقمية', difficulty:'hard', questionType:'text', questionTextAr:'ما الرقم المفقود: 2، 4، 8، 16، __؟', questionImageUrl:null, options:[{text:'24'},{text:'28'},{text:'32'},{text:'36'}], correctOptionIndex:2, explanationAr:'كل رقم يُضرب في 2: 2×2=4، 4×2=8، 8×2=16، 16×2=32.', tags:[] },
  { ageGroup:'6-9', skillArea:'quantitative', subSkill:'الكسور', difficulty:'hard', questionType:'text', questionTextAr:'أي كسر أكبر: 1/2 أم 1/3؟', questionImageUrl:null, options:[{text:'1/3'},{text:'1/2'},{text:'متساويان'},{text:'لا يمكن المقارنة'}], correctOptionIndex:1, explanationAr:'1/2 أكبر من 1/3. عندما يكون البسط 1، كلما صغر المقام كلما كان الكسر أكبر. نصف الشيء أكثر من ثلثه.', tags:[] },
  { ageGroup:'6-9', skillArea:'quantitative', subSkill:'المسائل المركبة', difficulty:'hard', questionType:'text', questionTextAr:'صف من 24 طالباً، ثلثهم ذهبوا في رحلة. كم بقي في الفصل؟', questionImageUrl:null, options:[{text:'8'},{text:'12'},{text:'16'},{text:'18'}], correctOptionIndex:2, explanationAr:'ثلث 24 = 24÷3 = 8. ذهب 8 طلاب. بقي: 24 - 8 = 16 طالباً.', tags:[] },
  { ageGroup:'6-9', skillArea:'quantitative', subSkill:'الأنماط الرقمية', difficulty:'hard', questionType:'text', questionTextAr:'ما الرقم المفقود: 1، 1، 2، 3، 5، 8، __؟', questionImageUrl:null, options:[{text:'11'},{text:'12'},{text:'13'},{text:'14'}], correctOptionIndex:2, explanationAr:'متتالية فيبوناتشي: كل عدد = جمع العددين اللذين قبله. 5+8=13.', tags:[] },
  { ageGroup:'6-9', skillArea:'quantitative', subSkill:'الهندسة', difficulty:'hard', questionType:'text', questionTextAr:'مستطيل طوله 8 سم وعرضه 5 سم. ما مساحته؟', questionImageUrl:null, options:[{text:'30 سم²'},{text:'35 سم²'},{text:'40 سم²'},{text:'45 سم²'}], correctOptionIndex:2, explanationAr:'مساحة المستطيل = الطول × العرض = 8 × 5 = 40 سم².', tags:[] },
  { ageGroup:'6-9', skillArea:'quantitative', subSkill:'المسائل المركبة', difficulty:'hard', questionType:'text', questionTextAr:'إذا كان سعر التفاحة 2 ريال وسعر البرتقالة 3 ريال، فكم يكلف 3 تفاحات و2 برتقالات؟', questionImageUrl:null, options:[{text:'10'},{text:'12'},{text:'14'},{text:'16'}], correctOptionIndex:1, explanationAr:'3 تفاحات = 3×2 = 6 ريال. 2 برتقالات = 2×3 = 6 ريال. المجموع = 6 + 6 = 12 ريال.', tags:[] },
  { ageGroup:'6-9', skillArea:'quantitative', subSkill:'الكسور', difficulty:'hard', questionType:'text', questionTextAr:'عندي 1/4 كعكة وأضفت 1/4 أخرى. كم عندي الآن؟', questionImageUrl:null, options:[{text:'1/2'},{text:'1/3'},{text:'2/4 فقط'},{text:'1/8'}], correctOptionIndex:0, explanationAr:'1/4 + 1/4 = 2/4 = 1/2. عندما يتساوى المقام نجمع البسط فقط، ثم نبسّط الكسر.', tags:[] },
  { ageGroup:'6-9', skillArea:'quantitative', subSkill:'الأنماط الرقمية', difficulty:'hard', questionType:'text', questionTextAr:'ما الرقم المفقود: 100، 90، 80، 70، __؟', questionImageUrl:null, options:[{text:'50'},{text:'55'},{text:'60'},{text:'65'}], correctOptionIndex:2, explanationAr:'النمط هو طرح 10 في كل مرة: 100-10=90، 90-10=80... 70-10=60.', tags:[] },
  { ageGroup:'6-9', skillArea:'quantitative', subSkill:'المسائل المركبة', difficulty:'hard', questionType:'text', questionTextAr:'كان لدى يوسف 50 ريالاً. أنفق ربعها على كتب ونصفها على طعام. كم تبقى؟', questionImageUrl:null, options:[{text:'10'},{text:'12'},{text:'15'},{text:'25'}], correctOptionIndex:1, explanationAr:'ربع 50 = 12.5 ريال على كتب. نصف 50 = 25 على طعام. المجموع = 37.5. الباقي = 50 - 37.5 = 12.5 ≈ 12.', tags:[] },
];

// Export for use in other files
export { questionData };

async function seed() {
  const client = createClient({ url: process.env.TURSO_DATABASE_URL || 'file:./local.db', ...(process.env.TURSO_AUTH_TOKEN ? { authToken: process.env.TURSO_AUTH_TOKEN } : {}) });
  const db = drizzle(client);
  console.log('Seeding questions (batch 1)...');
  let count = 0;
  for (const q of questionData) {
    await db.insert(questions).values({
      id: crypto.randomUUID(),
      skillArea: q.skillArea,
      subSkill: q.subSkill,
      ageGroup: q.ageGroup,
      difficulty: q.difficulty,
      questionType: q.questionType as 'text' | 'image',
      questionTextAr: q.questionTextAr,
      questionImageUrl: q.questionImageUrl,
      options: q.options as Array<{text: string}>,
      correctOptionIndex: q.correctOptionIndex,
      explanationAr: q.explanationAr,
      tags: q.tags,
      isActive: true,
    }).onConflictDoNothing();
    count++;
  }
  console.log(`Seeded ${count} questions so far.`);
  return count;
}

if (require.main === module) {
  seed().then(n => { console.log(`Done: ${n}`); process.exit(0); }).catch(e => { console.error(e); process.exit(1); });
}
