import { createClient } from '@libsql/client';
import { drizzle } from 'drizzle-orm/libsql';
import { questions } from './schema';

const questionData2 = [
  // ═══════════════════════════════════════════════
  // عمر 6-9 — لفظي — سهل
  // ═══════════════════════════════════════════════
  { ageGroup:'6-9', skillArea:'verbal', subSkill:'المتضادات', difficulty:'easy', questionType:'text', questionTextAr:'ما عكس كلمة "سعيد"؟', questionImageUrl:null, options:[{text:'مريض'},{text:'حزين'},{text:'خائف'},{text:'غاضب'}], correctOptionIndex:1, explanationAr:'عكس "سعيد" هو "حزين". المتضادات هي كلمات تحمل معنى معاكساً.', tags:[] },
  { ageGroup:'6-9', skillArea:'verbal', subSkill:'المفردات', difficulty:'easy', questionType:'text', questionTextAr:'ما معنى كلمة "شجاع"؟', questionImageUrl:null, options:[{text:'يخاف من كل شيء'},{text:'لا يخاف ويواجه التحديات'},{text:'يحب النوم كثيراً'},{text:'يأكل كثيراً'}], correctOptionIndex:1, explanationAr:'الشجاع هو الشخص الذي لا يخاف ويواجه التحديات والمواقف الصعبة بثبات.', tags:[] },
  { ageGroup:'6-9', skillArea:'verbal', subSkill:'المتضادات', difficulty:'easy', questionType:'text', questionTextAr:'ما عكس كلمة "نظيف"؟', questionImageUrl:null, options:[{text:'جميل'},{text:'قبيح'},{text:'وسخ'},{text:'قديم'}], correctOptionIndex:2, explanationAr:'عكس "نظيف" هو "وسخ" أو "قذر". النظافة من الإيمان كما يقال.', tags:[] },
  { ageGroup:'6-9', skillArea:'verbal', subSkill:'المفردات', difficulty:'easy', questionType:'text', questionTextAr:'ما معنى "يتأمل"؟', questionImageUrl:null, options:[{text:'يجري بسرعة'},{text:'ينظر بتمعن ويفكر'},{text:'يأكل بهدوء'},{text:'ينام بعمق'}], correctOptionIndex:1, explanationAr:'التأمل هو النظر بتمعن والتفكير العميق في شيء ما.', tags:[] },
  { ageGroup:'6-9', skillArea:'verbal', subSkill:'المتضادات', difficulty:'easy', questionType:'text', questionTextAr:'ما عكس كلمة "قديم"؟', questionImageUrl:null, options:[{text:'كبير'},{text:'جديد'},{text:'ثقيل'},{text:'بعيد'}], correctOptionIndex:1, explanationAr:'عكس "قديم" هو "جديد". الكتاب القديم يختلف عن الجديد في حالته.', tags:[] },
  { ageGroup:'6-9', skillArea:'verbal', subSkill:'المفردات', difficulty:'easy', questionType:'text', questionTextAr:'ما معنى "الفجر"؟', questionImageUrl:null, options:[{text:'وسط الليل'},{text:'أول النهار عند شروق الشمس'},{text:'منتصف النهار'},{text:'غروب الشمس'}], correctOptionIndex:1, explanationAr:'الفجر هو أول وقت النهار عند بداية ظهور ضوء الشمس قبل شروقها.', tags:[] },
  { ageGroup:'6-9', skillArea:'verbal', subSkill:'المتضادات', difficulty:'easy', questionType:'text', questionTextAr:'ما عكس كلمة "يتقدم"؟', questionImageUrl:null, options:[{text:'يتوقف'},{text:'يتأخر'},{text:'يتراجع'},{text:'ينام'}], correctOptionIndex:2, explanationAr:'عكس "يتقدم" هو "يتراجع". التقدم يعني الذهاب للأمام، والتراجع يعني الرجوع للخلف.', tags:[] },
  { ageGroup:'6-9', skillArea:'verbal', subSkill:'المفردات', difficulty:'easy', questionType:'text', questionTextAr:'ما معنى "يتسامح"؟', questionImageUrl:null, options:[{text:'يتجاهل الآخرين'},{text:'يغضب بسرعة'},{text:'يعفو ويصفح'},{text:'يتسابق'}], correctOptionIndex:2, explanationAr:'التسامح هو العفو والصفح عن الآخرين وعدم الاحتقان من أخطائهم.', tags:[] },
  { ageGroup:'6-9', skillArea:'verbal', subSkill:'المتضادات', difficulty:'easy', questionType:'text', questionTextAr:'ما عكس "الكرم"؟', questionImageUrl:null, options:[{text:'الطيبة'},{text:'البخل'},{text:'الشجاعة'},{text:'الصدق'}], correctOptionIndex:1, explanationAr:'عكس "الكرم" هو "البخل". الكريم يعطي بسخاء والبخيل لا يحب العطاء.', tags:[] },
  { ageGroup:'6-9', skillArea:'verbal', subSkill:'المفردات', difficulty:'easy', questionType:'text', questionTextAr:'ما معنى "الغسق"؟', questionImageUrl:null, options:[{text:'وقت الظهر'},{text:'وقت الصباح'},{text:'وقت المساء عند غروب الشمس'},{text:'وقت منتصف الليل'}], correctOptionIndex:2, explanationAr:'الغسق هو وقت المساء عند غروب الشمس وبداية الظلام.', tags:[] },

  // عمر 6-9 — لفظي — متوسط
  { ageGroup:'6-9', skillArea:'verbal', subSkill:'المترادفات', difficulty:'medium', questionType:'text', questionTextAr:'ما مرادف كلمة "سريع"؟', questionImageUrl:null, options:[{text:'بطيء'},{text:'كسول'},{text:'خفيف'},{text:'رزين'}], correctOptionIndex:2, explanationAr:'مرادف "سريع" هو "خفيف" أو "عجول". المترادفات كلمات تحمل نفس المعنى أو معنى متقارباً.', tags:[] },
  { ageGroup:'6-9', skillArea:'verbal', subSkill:'إكمال الجملة', difficulty:'medium', questionType:'text', questionTextAr:'الكتاب للقراءة كما أن القلم لـ...', questionImageUrl:null, options:[{text:'الحفر'},{text:'الكتابة'},{text:'القطع'},{text:'الطبخ'}], correctOptionIndex:1, explanationAr:'الكتاب أداة للقراءة، والقلم أداة للكتابة. هذا تناظر وظيفي.', tags:[] },
  { ageGroup:'6-9', skillArea:'verbal', subSkill:'المترادفات', difficulty:'medium', questionType:'text', questionTextAr:'ما مرادف كلمة "حزن"؟', questionImageUrl:null, options:[{text:'فرح'},{text:'غم'},{text:'سرور'},{text:'بهجة'}], correctOptionIndex:1, explanationAr:'مرادف "حزن" هو "غم" أو "كآبة". كلها تعبر عن الشعور بالألم النفسي.', tags:[] },
  { ageGroup:'6-9', skillArea:'verbal', subSkill:'التناظر', difficulty:'medium', questionType:'text', questionTextAr:'الطيور : الأجنحة = الأسماك : ؟', questionImageUrl:null, options:[{text:'أرجل'},{text:'زعانف'},{text:'ذيل'},{text:'فراء'}], correctOptionIndex:1, explanationAr:'الطيور تتحرك بأجنحتها في الهواء، والأسماك تتحرك بزعانفها في الماء. هذا تناظر وظيفي.', tags:[] },
  { ageGroup:'6-9', skillArea:'verbal', subSkill:'إكمال الجملة', difficulty:'medium', questionType:'text', questionTextAr:'الطبيب يعالج المرضى كما أن المعلم يـ...', questionImageUrl:null, options:[{text:'يطبخ الطعام'},{text:'يعلم الطلاب'},{text:'يبني المنازل'},{text:'يزرع الحقول'}], correctOptionIndex:1, explanationAr:'الطبيب يعالج المرضى وهذه وظيفته، والمعلم يعلم الطلاب وهذه وظيفته.', tags:[] },
  { ageGroup:'6-9', skillArea:'verbal', subSkill:'المترادفات', difficulty:'medium', questionType:'text', questionTextAr:'ما مرادف "ذكي"؟', questionImageUrl:null, options:[{text:'غبي'},{text:'كسول'},{text:'فطين'},{text:'ضعيف'}], correctOptionIndex:2, explanationAr:'مرادف "ذكي" هو "فطين" أو "نبيه" أو "لبيب". كلها تعني سرعة الفهم والإدراك.', tags:[] },
  { ageGroup:'6-9', skillArea:'verbal', subSkill:'التناظر', difficulty:'medium', questionType:'text', questionTextAr:'النهار : الشمس = الليل : ؟', questionImageUrl:null, options:[{text:'الفجر'},{text:'النجوم'},{text:'القمر'},{text:'الغسق'}], correctOptionIndex:2, explanationAr:'الشمس تضيء النهار والقمر يضيء الليل. هذا تناظر بين النقيضين.', tags:[] },
  { ageGroup:'6-9', skillArea:'verbal', subSkill:'إكمال الجملة', difficulty:'medium', questionType:'text', questionTextAr:'العين للرؤية كما أن الأذن لـ...', questionImageUrl:null, options:[{text:'الشم'},{text:'التذوق'},{text:'السمع'},{text:'اللمس'}], correctOptionIndex:2, explanationAr:'العين تستخدم للرؤية والأذن تستخدم للسمع. حواسنا الخمس لكل منها وظيفة.', tags:[] },
  { ageGroup:'6-9', skillArea:'verbal', subSkill:'المترادفات', difficulty:'medium', questionType:'text', questionTextAr:'ما مرادف "جميل"؟', questionImageUrl:null, options:[{text:'قبيح'},{text:'حسن'},{text:'مزعج'},{text:'ثقيل'}], correctOptionIndex:1, explanationAr:'مرادف "جميل" هو "حسن" أو "بهي" أو "رائع". كلها تعبر عن الجمال.', tags:[] },
  { ageGroup:'6-9', skillArea:'verbal', subSkill:'التناظر', difficulty:'medium', questionType:'text', questionTextAr:'الملك : القصر = الأسد : ؟', questionImageUrl:null, options:[{text:'الغابة'},{text:'البحر'},{text:'الصحراء'},{text:'الجبل'}], correctOptionIndex:0, explanationAr:'الملك يسكن القصر والأسد يسكن الغابة. هذا تناظر بين الكائن ومسكنه.', tags:[] },

  // عمر 6-9 — لفظي — صعب
  { ageGroup:'6-9', skillArea:'verbal', subSkill:'التناظر اللغوي', difficulty:'hard', questionType:'text', questionTextAr:'القلم : الكاتب = المشرط : ؟', questionImageUrl:null, options:[{text:'المزارع'},{text:'الجراح'},{text:'البنّاء'},{text:'الطاهي'}], correctOptionIndex:1, explanationAr:'القلم أداة الكاتب، والمشرط أداة الجراح. كل مهنة لها أدواتها المختصة.', tags:[] },
  { ageGroup:'6-9', skillArea:'verbal', subSkill:'الفهم القرائي', difficulty:'hard', questionType:'text', questionTextAr:'قرأت: "الطالبة المجتهدة تذاكر دروسها يومياً وتحصل على درجات عالية." ما سبب حصولها على درجات عالية؟', questionImageUrl:null, options:[{text:'لأنها تنام كثيراً'},{text:'لأنها تذاكر يومياً'},{text:'لأنها تلعب'},{text:'لأن المعلمة تحبها'}], correctOptionIndex:1, explanationAr:'النص يخبرنا مباشرة أن المذاكرة اليومية هي سبب الدرجات العالية. السبب والنتيجة في النص.', tags:[] },
  { ageGroup:'6-9', skillArea:'verbal', subSkill:'التناظر اللغوي', difficulty:'hard', questionType:'text', questionTextAr:'الخريف : الأوراق = الربيع : ؟', questionImageUrl:null, options:[{text:'المطر'},{text:'الأزهار'},{text:'الثلج'},{text:'الحر'}], correctOptionIndex:1, explanationAr:'الخريف يرتبط بسقوط الأوراق والربيع يرتبط بتفتح الأزهار. هذا تناظر موسمي.', tags:[] },
  { ageGroup:'6-9', skillArea:'verbal', subSkill:'الخطأ السياقي', difficulty:'hard', questionType:'text', questionTextAr:'أي كلمة خطأ في الجملة: "ذهبت إلى المدرسة وطبخت الدرس"؟', questionImageUrl:null, options:[{text:'ذهبت'},{text:'المدرسة'},{text:'طبخت'},{text:'الدرس'}], correctOptionIndex:2, explanationAr:'"طبخت" خطأ سياقي. الصحيح "درست" أو "شرحت". الطبخ يكون في المطبخ لا للدروس.', tags:[] },
  { ageGroup:'6-9', skillArea:'verbal', subSkill:'الفهم القرائي', difficulty:'hard', questionType:'text', questionTextAr:'قرأت: "الماء يتحول إلى بخار عند تسخينه ويتحول إلى جليد عند تبريده." ما حالة الماء عند التسخين؟', questionImageUrl:null, options:[{text:'جليد'},{text:'بخار'},{text:'يبقى سائلاً'},{text:'يختفي'}], correctOptionIndex:1, explanationAr:'النص يقول صراحة أن الماء يتحول إلى بخار عند التسخين. هذه الحالة الغازية للماء.', tags:[] },
  { ageGroup:'6-9', skillArea:'verbal', subSkill:'التناظر اللغوي', difficulty:'hard', questionType:'text', questionTextAr:'الكلمات : القاموس = الكتب : ؟', questionImageUrl:null, options:[{text:'الورق'},{text:'المكتبة'},{text:'القلم'},{text:'الحبر'}], correctOptionIndex:1, explanationAr:'الكلمات تُجمع في القاموس، والكتب تُجمع في المكتبة. مكان التجميع والحفظ.', tags:[] },
  { ageGroup:'6-9', skillArea:'verbal', subSkill:'الخطأ السياقي', difficulty:'hard', questionType:'text', questionTextAr:'أي كلمة خطأ: "شرب الطالب الكتاب ببطء"؟', questionImageUrl:null, options:[{text:'شرب'},{text:'الطالب'},{text:'الكتاب'},{text:'ببطء'}], correctOptionIndex:0, explanationAr:'"شرب" خطأ سياقي. لا يُشرب الكتاب. الصحيح "قرأ" الطالب الكتاب ببطء.', tags:[] },
  { ageGroup:'6-9', skillArea:'verbal', subSkill:'الفهم القرائي', difficulty:'hard', questionType:'text', questionTextAr:'قرأت: "بنى عمر بيتاً من طوب ليصمد أمام العواصف". لماذا اختار الطوب؟', questionImageUrl:null, options:[{text:'لأنه أرخص'},{text:'لأنه يصمد أمام العواصف'},{text:'لأنه أجمل'},{text:'لأنه أسرع بناءً'}], correctOptionIndex:1, explanationAr:'النص يخبرنا صراحة أن السبب هو الصمود أمام العواصف. يجب قراءة النص بتمعن.', tags:[] },
  { ageGroup:'6-9', skillArea:'verbal', subSkill:'التناظر اللغوي', difficulty:'hard', questionType:'text', questionTextAr:'المعلم : التلميذ = الطبيب : ؟', questionImageUrl:null, options:[{text:'المستشفى'},{text:'الدواء'},{text:'المريض'},{text:'العملية'}], correctOptionIndex:2, explanationAr:'المعلم يتعامل مع التلميذ في التعليم، والطبيب يتعامل مع المريض في العلاج.', tags:[] },
  { ageGroup:'6-9', skillArea:'verbal', subSkill:'الخطأ السياقي', difficulty:'hard', questionType:'text', questionTextAr:'أي جملة صحيحة سياقياً؟', questionImageUrl:null, options:[{text:'طارت السمكة في السماء'},{text:'ركض الطفل في الحديقة'},{text:'شرب الكتاب القهوة'},{text:'نامت السيارة في الفراش'}], correctOptionIndex:1, explanationAr:'"ركض الطفل في الحديقة" صحيحة لأن الطفل يركض والحديقة مكان مناسب. باقي الجمل غير منطقية.', tags:[] },

  // ═══════════════════════════════════════════════
  // عمر 6-9 — منطقي — سهل
  // ═══════════════════════════════════════════════
  { ageGroup:'6-9', skillArea:'logical_patterns', subSkill:'السلاسل الرقمية', difficulty:'easy', questionType:'text', questionTextAr:'ما التالي: 2، 4، 6، 8، __؟', questionImageUrl:null, options:[{text:'9'},{text:'10'},{text:'11'},{text:'12'}], correctOptionIndex:1, explanationAr:'النمط هو إضافة 2 في كل مرة (الأعداد الزوجية): 2، 4، 6، 8، 10.', tags:[] },
  { ageGroup:'6-9', skillArea:'logical_patterns', subSkill:'السلاسل الرقمية', difficulty:'easy', questionType:'text', questionTextAr:'ما التالي: 5، 10، 15، 20، __؟', questionImageUrl:null, options:[{text:'22'},{text:'23'},{text:'25'},{text:'28'}], correctOptionIndex:2, explanationAr:'النمط هو مضاعفات 5: 5، 10، 15، 20، 25.', tags:[] },
  { ageGroup:'6-9', skillArea:'logical_patterns', subSkill:'الاستنتاج', difficulty:'easy', questionType:'text', questionTextAr:'كل الطلاب في الفصل يلبسون زياً مدرسياً. خالد طالب في الفصل. هل يلبس زياً؟', questionImageUrl:null, options:[{text:'نعم'},{text:'لا'},{text:'ربما'},{text:'لا يمكن التحديد'}], correctOptionIndex:0, explanationAr:'نعم! القاعدة تقول كل طلاب الفصل يلبسون الزي، وخالد من الفصل، إذن يلبس الزي.', tags:[] },
  { ageGroup:'6-9', skillArea:'logical_patterns', subSkill:'السلاسل الرقمية', difficulty:'easy', questionType:'text', questionTextAr:'ما التالي: 1، 3، 5، 7، __؟', questionImageUrl:null, options:[{text:'8'},{text:'9'},{text:'10'},{text:'11'}], correctOptionIndex:1, explanationAr:'النمط هو الأعداد الفردية: 1، 3، 5، 7، 9.', tags:[] },
  { ageGroup:'6-9', skillArea:'logical_patterns', subSkill:'الأنماط', difficulty:'easy', questionType:'text', questionTextAr:'ما الرقم المفقود: 2، 4، __, 8، 10؟', questionImageUrl:null, options:[{text:'5'},{text:'6'},{text:'7'},{text:'3'}], correctOptionIndex:1, explanationAr:'النمط هو إضافة 2: 2، 4، 6، 8، 10. الرقم المفقود هو 6.', tags:[] },
  { ageGroup:'6-9', skillArea:'logical_patterns', subSkill:'الاستنتاج', difficulty:'easy', questionType:'text', questionTextAr:'إذا كان اليوم السبت، ما اليوم غداً؟', questionImageUrl:null, options:[{text:'الجمعة'},{text:'الأحد'},{text:'الاثنين'},{text:'الثلاثاء'}], correctOptionIndex:1, explanationAr:'ترتيب الأسبوع: ...الجمعة، السبت، الأحد، الاثنين... غداً الأحد.', tags:[] },
  { ageGroup:'6-9', skillArea:'logical_patterns', subSkill:'السلاسل الرقمية', difficulty:'easy', questionType:'text', questionTextAr:'ما التالي: 10، 20، 30، __؟', questionImageUrl:null, options:[{text:'35'},{text:'38'},{text:'40'},{text:'45'}], correctOptionIndex:2, explanationAr:'النمط هو إضافة 10: 10، 20، 30، 40.', tags:[] },
  { ageGroup:'6-9', skillArea:'logical_patterns', subSkill:'الاستنتاج', difficulty:'easy', questionType:'text', questionTextAr:'سارة أعلى نتيجة من نورة، ونورة أعلى من ريم. من الأول؟', questionImageUrl:null, options:[{text:'ريم'},{text:'نورة'},{text:'سارة'},{text:'كلهن متساويات'}], correctOptionIndex:2, explanationAr:'سارة > نورة > ريم. إذن سارة هي الأولى بأعلى نتيجة.', tags:[] },
  { ageGroup:'6-9', skillArea:'logical_patterns', subSkill:'الأنماط', difficulty:'easy', questionType:'text', questionTextAr:'ما الرقم المفقود: 100، 90، __, 70، 60؟', questionImageUrl:null, options:[{text:'75'},{text:'80'},{text:'85'},{text:'95'}], correctOptionIndex:1, explanationAr:'النمط هو طرح 10: 100، 90، 80، 70، 60. الرقم المفقود هو 80.', tags:[] },
  { ageGroup:'6-9', skillArea:'logical_patterns', subSkill:'الاستنتاج', difficulty:'easy', questionType:'text', questionTextAr:'كل المربعات لها 4 زوايا. هذا الشكل مربع. كم زاوية له؟', questionImageUrl:null, options:[{text:'2'},{text:'3'},{text:'4'},{text:'5'}], correctOptionIndex:2, explanationAr:'لأن كل المربعات لها 4 زوايا وهذا مربع، إذن له 4 زوايا.', tags:[] },

  // عمر 6-9 — منطقي — متوسط
  { ageGroup:'6-9', skillArea:'logical_patterns', subSkill:'السلاسل المتقدمة', difficulty:'medium', questionType:'text', questionTextAr:'ما التالي: 3، 6، 12، 24، __؟', questionImageUrl:null, options:[{text:'36'},{text:'48'},{text:'42'},{text:'30'}], correctOptionIndex:1, explanationAr:'كل رقم يُضرب في 2: 3×2=6، 6×2=12، 12×2=24، 24×2=48.', tags:[] },
  { ageGroup:'6-9', skillArea:'logical_patterns', subSkill:'الاستدلال', difficulty:'medium', questionType:'text', questionTextAr:'إذا كان A أكبر من B وB أكبر من C وC أكبر من D، من الأصغر؟', questionImageUrl:null, options:[{text:'A'},{text:'B'},{text:'C'},{text:'D'}], correctOptionIndex:3, explanationAr:'A>B>C>D. إذن D هو الأصغر في هذه السلسلة.', tags:[] },
  { ageGroup:'6-9', skillArea:'logical_patterns', subSkill:'الأنماط المتقدمة', difficulty:'medium', questionType:'text', questionTextAr:'ما الرقم المفقود: 1، 4، 9، 16، __؟', questionImageUrl:null, options:[{text:'20'},{text:'23'},{text:'25'},{text:'28'}], correctOptionIndex:2, explanationAr:'هذه مربعات الأعداد: 1²=1، 2²=4، 3²=9، 4²=16، 5²=25.', tags:[] },
  { ageGroup:'6-9', skillArea:'logical_patterns', subSkill:'الاستدلال', difficulty:'medium', questionType:'text', questionTextAr:'كل الحلويات تحتوي على سكر. الكيك حلوى. هل الكيك يحتوي على سكر؟', questionImageUrl:null, options:[{text:'نعم'},{text:'لا'},{text:'أحياناً'},{text:'لا يمكن التحديد'}], correctOptionIndex:0, explanationAr:'نعم، بالاستنتاج: كل الحلويات = سكر، الكيك = حلوى، إذن الكيك = سكر.', tags:[] },
  { ageGroup:'6-9', skillArea:'logical_patterns', subSkill:'السلاسل المتقدمة', difficulty:'medium', questionType:'text', questionTextAr:'ما التالي: 1، 2، 4، 7، 11، __؟', questionImageUrl:null, options:[{text:'14'},{text:'15'},{text:'16'},{text:'17'}], correctOptionIndex:2, explanationAr:'الفرق بين الأعداد يزداد: +1، +2، +3، +4، +5. بعد 11 يأتي 11+5=16.', tags:[] },
  { ageGroup:'6-9', skillArea:'logical_patterns', subSkill:'الاستدلال', difficulty:'medium', questionType:'text', questionTextAr:'في مسابقة، أحمد يسبق محمداً وعلي يسبق أحمد. من الأول؟', questionImageUrl:null, options:[{text:'أحمد'},{text:'محمد'},{text:'علي'},{text:'لا يمكن التحديد'}], correctOptionIndex:2, explanationAr:'علي يسبق أحمد، وأحمد يسبق محمد. إذن الترتيب: علي، أحمد، محمد. علي الأول.', tags:[] },
  { ageGroup:'6-9', skillArea:'logical_patterns', subSkill:'الأنماط المتقدمة', difficulty:'medium', questionType:'text', questionTextAr:'ما الرقم المفقود: 2، __, 8، 11، 14؟', questionImageUrl:null, options:[{text:'4'},{text:'5'},{text:'6'},{text:'7'}], correctOptionIndex:1, explanationAr:'النمط هو إضافة 3: 2+3=5، 5+3=8، 8+3=11. الرقم المفقود هو 5.', tags:[] },
  { ageGroup:'6-9', skillArea:'logical_patterns', subSkill:'الاستدلال', difficulty:'medium', questionType:'text', questionTextAr:'لا يوجد طائر بدون جناح. البطريق طائر. هل للبطريق جناح؟', questionImageUrl:null, options:[{text:'نعم'},{text:'لا'},{text:'أحياناً'},{text:'لا أعرف'}], correctOptionIndex:0, explanationAr:'نعم، البطريق له جناح حتى لو لم يستطع الطيران. القاعدة تقول لا طائر بلا جناح.', tags:[] },
  { ageGroup:'6-9', skillArea:'logical_patterns', subSkill:'السلاسل المتقدمة', difficulty:'medium', questionType:'text', questionTextAr:'ما التالي: 64، 32، 16، 8، __؟', questionImageUrl:null, options:[{text:'2'},{text:'4'},{text:'6'},{text:'8'}], correctOptionIndex:1, explanationAr:'كل رقم يُقسم على 2: 64÷2=32، 32÷2=16، 16÷2=8، 8÷2=4.', tags:[] },
  { ageGroup:'6-9', skillArea:'logical_patterns', subSkill:'الأنماط المتقدمة', difficulty:'medium', questionType:'text', questionTextAr:'ما الرقم المفقود: 3، 6، 9، __, 15؟', questionImageUrl:null, options:[{text:'10'},{text:'11'},{text:'12'},{text:'13'}], correctOptionIndex:2, explanationAr:'مضاعفات 3: 3، 6، 9، 12، 15. الرقم المفقود هو 12.', tags:[] },

  // عمر 6-9 — منطقي — صعب
  { ageGroup:'6-9', skillArea:'logical_patterns', subSkill:'الاستدلال المعقد', difficulty:'hard', questionType:'text', questionTextAr:'ما التالي: 1، 1، 2، 3، 5، 8، 13، __؟', questionImageUrl:null, options:[{text:'18'},{text:'20'},{text:'21'},{text:'23'}], correctOptionIndex:2, explanationAr:'هذه متتالية فيبوناتشي الشهيرة: كل عدد = مجموع العددين قبله. 8+13=21.', tags:[] },
  { ageGroup:'6-9', skillArea:'logical_patterns', subSkill:'القياس المنطقي', difficulty:'hard', questionType:'text', questionTextAr:'بعض الفواكه حلوة. التفاح فاكهة. هل التفاح حلو بالضرورة؟', questionImageUrl:null, options:[{text:'نعم دائماً'},{text:'لا أبداً'},{text:'ليس بالضرورة'},{text:'لا يمكن التحديد'}], correctOptionIndex:2, explanationAr:'القاعدة تقول "بعض" الفواكه حلوة، لا "كل" الفواكه. إذن التفاح قد يكون حلواً أو غير حلو.', tags:[] },
  { ageGroup:'6-9', skillArea:'logical_patterns', subSkill:'السلاسل المعقدة', difficulty:'hard', questionType:'text', questionTextAr:'ما التالي: 2، 6، 12، 20، 30، __؟', questionImageUrl:null, options:[{text:'36'},{text:'40'},{text:'42'},{text:'46'}], correctOptionIndex:2, explanationAr:'الفروق: +4، +6، +8، +10، +12. بعد 30 نضيف 12: 30+12=42.', tags:[] },
  { ageGroup:'6-9', skillArea:'logical_patterns', subSkill:'الاستدلال المعقد', difficulty:'hard', questionType:'text', questionTextAr:'إذا كان كل A هو B، وبعض B هو C، هل كل A هو C بالضرورة؟', questionImageUrl:null, options:[{text:'نعم'},{text:'لا'},{text:'أحياناً'},{text:'ليس بالضرورة'}], correctOptionIndex:3, explanationAr:'ليس بالضرورة. كل A هو B، لكن B ليست كلها C (بعضها فقط). إذن بعض A قد يكون C وبعضها لا.', tags:[] },
  { ageGroup:'6-9', skillArea:'logical_patterns', subSkill:'السلاسل المعقدة', difficulty:'hard', questionType:'text', questionTextAr:'ما الرقم المفقود: 1، 2، 6، 24، __؟', questionImageUrl:null, options:[{text:'48'},{text:'96'},{text:'120'},{text:'144'}], correctOptionIndex:2, explanationAr:'كل رقم مضروب في: ×2، ×3، ×4، ×5. بعد 24: 24×5=120. (المضروب هو المضاعفات).', tags:[] },
  { ageGroup:'6-9', skillArea:'logical_patterns', subSkill:'الاستدلال المعقد', difficulty:'hard', questionType:'text', questionTextAr:'في مباراة، الأحمر يكسب الأزرق، والأزرق يكسب الأخضر، والأخضر يكسب الأصفر. من الأخسر؟', questionImageUrl:null, options:[{text:'الأحمر'},{text:'الأزرق'},{text:'الأخضر'},{text:'الأصفر'}], correctOptionIndex:3, explanationAr:'السلسلة: أحمر > أزرق > أخضر > أصفر. الأصفر يخسر من الأخضر وهو في النهاية.', tags:[] },
  { ageGroup:'6-9', skillArea:'logical_patterns', subSkill:'السلاسل المعقدة', difficulty:'hard', questionType:'text', questionTextAr:'ما التالي: 1، 4، 9، 16، 25، __؟', questionImageUrl:null, options:[{text:'34'},{text:'36'},{text:'38'},{text:'40'}], correctOptionIndex:1, explanationAr:'هذه مربعات الأعداد: 1²=1، 2²=4، 3²=9، 4²=16، 5²=25، 6²=36.', tags:[] },
  { ageGroup:'6-9', skillArea:'logical_patterns', subSkill:'الاستدلال المعقد', difficulty:'hard', questionType:'text', questionTextAr:'لا طالب يغش. هشام لا يغش. هل هشام طالب؟', questionImageUrl:null, options:[{text:'نعم'},{text:'لا'},{text:'ربما'},{text:'ليس بالضرورة'}], correctOptionIndex:3, explanationAr:'ليس بالضرورة. عدم الغش لا يعني أنه طالب — قد يكون أي شخص لا يغش.', tags:[] },
  { ageGroup:'6-9', skillArea:'logical_patterns', subSkill:'السلاسل المعقدة', difficulty:'hard', questionType:'text', questionTextAr:'ما الرقم المفقود: 2، 3، 5، 7، 11، __؟', questionImageUrl:null, options:[{text:'12'},{text:'13'},{text:'14'},{text:'15'}], correctOptionIndex:1, explanationAr:'هذه الأعداد الأولية: 2، 3، 5، 7، 11، 13. الأعداد التي لا تقبل القسمة إلا على 1 وعلى نفسها.', tags:[] },
  { ageGroup:'6-9', skillArea:'logical_patterns', subSkill:'الاستدلال المعقد', difficulty:'hard', questionType:'text', questionTextAr:'إذا صح أن "كل ما يلمع ذهب"، ماذا نستنتج عن هذا الحجر اللامع؟', questionImageUrl:null, options:[{text:'إنه ذهب'},{text:'ليس ذهباً'},{text:'ربما ذهب'},{text:'لا يمكن التحديد'}], correctOptionIndex:0, explanationAr:'إذا افترضنا صحة القاعدة "كل ما يلمع = ذهب"، وهذا الحجر يلمع، إذن هو ذهب وفق هذه الافتراض.', tags:[] },

  // ═══════════════════════════════════════════════
  // عمر 10-12 — كمي — سهل
  // ═══════════════════════════════════════════════
  { ageGroup:'10-12', skillArea:'quantitative', subSkill:'النسبة والتناسب', difficulty:'easy', questionType:'text', questionTextAr:'إذا كانت نسبة الطلاب إلى المعلمين 10:1، وعدد المعلمين 5، فكم عدد الطلاب؟', questionImageUrl:null, options:[{text:'40'},{text:'45'},{text:'50'},{text:'55'}], correctOptionIndex:2, explanationAr:'النسبة 10:1 تعني لكل معلم 10 طلاب. 5 معلمين × 10 = 50 طالباً.', tags:[] },
  { ageGroup:'10-12', skillArea:'quantitative', subSkill:'النسبة والتناسب', difficulty:'easy', questionType:'text', questionTextAr:'ما هو 20٪ من 80؟', questionImageUrl:null, options:[{text:'12'},{text:'14'},{text:'16'},{text:'18'}], correctOptionIndex:2, explanationAr:'20٪ من 80 = (20 ÷ 100) × 80 = 0.2 × 80 = 16.', tags:[] },
  { ageGroup:'10-12', skillArea:'quantitative', subSkill:'الجبر', difficulty:'easy', questionType:'text', questionTextAr:'إذا كانت س + 5 = 12، فما قيمة س؟', questionImageUrl:null, options:[{text:'5'},{text:'6'},{text:'7'},{text:'8'}], correctOptionIndex:2, explanationAr:'س + 5 = 12 → س = 12 - 5 = 7. نطرح 5 من الطرفين.', tags:[] },
  { ageGroup:'10-12', skillArea:'quantitative', subSkill:'الكسور', difficulty:'easy', questionType:'text', questionTextAr:'ما نتيجة 3/4 + 1/4؟', questionImageUrl:null, options:[{text:'4/8'},{text:'1'},{text:'2/4'},{text:'4/4'}], correctOptionIndex:1, explanationAr:'3/4 + 1/4 = 4/4 = 1. عند جمع كسور متشابهة المقام نجمع البسط.', tags:[] },
  { ageGroup:'10-12', skillArea:'quantitative', subSkill:'النسبة والتناسب', difficulty:'easy', questionType:'text', questionTextAr:'إذا كان سعر 3 كيلو برتقال 15 ريال، فكم يكلف 5 كيلو؟', questionImageUrl:null, options:[{text:'20'},{text:'25'},{text:'30'},{text:'35'}], correctOptionIndex:1, explanationAr:'سعر الكيلو = 15 ÷ 3 = 5 ريال. 5 كيلو = 5 × 5 = 25 ريال.', tags:[] },
  { ageGroup:'10-12', skillArea:'quantitative', subSkill:'الجبر', difficulty:'easy', questionType:'text', questionTextAr:'إذا كانت 2ص = 16، فما قيمة ص؟', questionImageUrl:null, options:[{text:'6'},{text:'7'},{text:'8'},{text:'9'}], correctOptionIndex:2, explanationAr:'2ص = 16 → ص = 16 ÷ 2 = 8. نقسم الطرفين على 2.', tags:[] },
  { ageGroup:'10-12', skillArea:'quantitative', subSkill:'النسبة والتناسب', difficulty:'easy', questionType:'text', questionTextAr:'ما هو 50٪ من 140؟', questionImageUrl:null, options:[{text:'60'},{text:'65'},{text:'70'},{text:'75'}], correctOptionIndex:2, explanationAr:'50٪ = النصف. نصف 140 = 70.', tags:[] },
  { ageGroup:'10-12', skillArea:'quantitative', subSkill:'الكسور', difficulty:'easy', questionType:'text', questionTextAr:'ما نتيجة 1/2 × 4؟', questionImageUrl:null, options:[{text:'1'},{text:'2'},{text:'3'},{text:'4'}], correctOptionIndex:1, explanationAr:'1/2 × 4 = 4/2 = 2. نضرب البسط في العدد ونقسم على المقام.', tags:[] },
  { ageGroup:'10-12', skillArea:'quantitative', subSkill:'الجبر', difficulty:'easy', questionType:'text', questionTextAr:'إذا كانت س - 9 = 15، فما قيمة س؟', questionImageUrl:null, options:[{text:'21'},{text:'23'},{text:'24'},{text:'26'}], correctOptionIndex:2, explanationAr:'س - 9 = 15 → س = 15 + 9 = 24.', tags:[] },
  { ageGroup:'10-12', skillArea:'quantitative', subSkill:'النسبة والتناسب', difficulty:'easy', questionType:'text', questionTextAr:'إذا كانت نسبة الرجال إلى النساء 2:3 في مجموعة من 25 شخصاً، كم عدد الرجال؟', questionImageUrl:null, options:[{text:'8'},{text:'10'},{text:'12'},{text:'15'}], correctOptionIndex:1, explanationAr:'المجموع = 2+3 = 5 أجزاء. الرجال = (2/5) × 25 = 10.', tags:[] },

  // عمر 10-12 — كمي — متوسط
  { ageGroup:'10-12', skillArea:'quantitative', subSkill:'الجبر', difficulty:'medium', questionType:'text', questionTextAr:'حل المعادلة: 2س + 3 = 11', questionImageUrl:null, options:[{text:'س = 3'},{text:'س = 4'},{text:'س = 5'},{text:'س = 6'}], correctOptionIndex:1, explanationAr:'2س + 3 = 11 → 2س = 8 → س = 4. نطرح 3 ثم نقسم على 2.', tags:[] },
  { ageGroup:'10-12', skillArea:'quantitative', subSkill:'الهندسة', difficulty:'medium', questionType:'text', questionTextAr:'مثلث قائم الزاوية أطوال ضلعيه القائمين 3 و4. ما طول الوتر؟', questionImageUrl:null, options:[{text:'4'},{text:'5'},{text:'6'},{text:'7'}], correctOptionIndex:1, explanationAr:'بمبرهنة فيثاغورس: الوتر² = 3² + 4² = 9 + 16 = 25. الوتر = √25 = 5.', tags:[] },
  { ageGroup:'10-12', skillArea:'quantitative', subSkill:'النسبة والتناسب', difficulty:'medium', questionType:'text', questionTextAr:'ارتفع سعر سلعة من 80 إلى 100 ريال. ما نسبة الارتفاع؟', questionImageUrl:null, options:[{text:'15٪'},{text:'20٪'},{text:'25٪'},{text:'30٪'}], correctOptionIndex:2, explanationAr:'نسبة الزيادة = (الزيادة ÷ السعر الأصلي) × 100 = (20 ÷ 80) × 100 = 25٪.', tags:[] },
  { ageGroup:'10-12', skillArea:'quantitative', subSkill:'الجبر', difficulty:'medium', questionType:'text', questionTextAr:'إذا كان 3(س + 2) = 18، فما قيمة س؟', questionImageUrl:null, options:[{text:'2'},{text:'4'},{text:'6'},{text:'8'}], correctOptionIndex:1, explanationAr:'3(س+2)=18 → س+2=6 → س=4.', tags:[] },
  { ageGroup:'10-12', skillArea:'quantitative', subSkill:'الهندسة', difficulty:'medium', questionType:'text', questionTextAr:'مربع محيطه 32 سم. ما مساحته؟', questionImageUrl:null, options:[{text:'48 سم²'},{text:'60 سم²'},{text:'64 سم²'},{text:'80 سم²'}], correctOptionIndex:2, explanationAr:'المحيط = 4×الضلع → الضلع = 32÷4 = 8. المساحة = 8² = 64 سم².', tags:[] },
  { ageGroup:'10-12', skillArea:'quantitative', subSkill:'النسبة والتناسب', difficulty:'medium', questionType:'text', questionTextAr:'أنجز عامل 40٪ من المشروع في 4 أيام. كم يوماً لإنجاز الباقي؟', questionImageUrl:null, options:[{text:'4'},{text:'5'},{text:'6'},{text:'7'}], correctOptionIndex:2, explanationAr:'4 أيام = 40٪. الباقي = 60٪. بالتناسب: 60٪ تحتاج 6 أيام.', tags:[] },
  { ageGroup:'10-12', skillArea:'quantitative', subSkill:'الجبر', difficulty:'medium', questionType:'text', questionTextAr:'ما قيمة س إذا كان س² = 49؟', questionImageUrl:null, options:[{text:'6'},{text:'7'},{text:'8'},{text:'9'}], correctOptionIndex:1, explanationAr:'س² = 49 → س = √49 = 7. (لأن 7×7=49)', tags:[] },
  { ageGroup:'10-12', skillArea:'quantitative', subSkill:'الهندسة', difficulty:'medium', questionType:'text', questionTextAr:'دائرة نصف قطرها 7 سم. ما محيطها؟ (استخدم π ≈ 22/7)', questionImageUrl:null, options:[{text:'38 سم'},{text:'42 سم'},{text:'44 سم'},{text:'48 سم'}], correctOptionIndex:2, explanationAr:'المحيط = 2πر = 2 × (22/7) × 7 = 2 × 22 = 44 سم.', tags:[] },
  { ageGroup:'10-12', skillArea:'quantitative', subSkill:'النسبة والتناسب', difficulty:'medium', questionType:'text', questionTextAr:'إذا كانت خصومة على سلعة 30٪ وسعرها الأصلي 200 ريال، فكم سعرها بعد الخصم؟', questionImageUrl:null, options:[{text:'120'},{text:'130'},{text:'140'},{text:'150'}], correctOptionIndex:2, explanationAr:'الخصم = 30٪ × 200 = 60. السعر بعد الخصم = 200 - 60 = 140 ريال.', tags:[] },
  { ageGroup:'10-12', skillArea:'quantitative', subSkill:'الجبر', difficulty:'medium', questionType:'text', questionTextAr:'إذا كان الطول × (الطول - 2) = 24 وأحد الأبعاد 6، ما البعد الآخر؟', questionImageUrl:null, options:[{text:'3'},{text:'4'},{text:'5'},{text:'6'}], correctOptionIndex:1, explanationAr:'6 × (6-2) = 6 × 4 = 24. البعد الآخر = 6-2 = 4.', tags:[] },

  // عمر 10-12 — كمي — صعب
  { ageGroup:'10-12', skillArea:'quantitative', subSkill:'الاحتمالات', difficulty:'hard', questionType:'text', questionTextAr:'كيس فيه 3 كرات حمراء و2 زرقاء. ما احتمال سحب كرة حمراء؟', questionImageUrl:null, options:[{text:'2/5'},{text:'3/5'},{text:'1/2'},{text:'3/2'}], correctOptionIndex:1, explanationAr:'إجمالي الكرات = 5. الكرات الحمراء = 3. الاحتمال = 3/5.', tags:[] },
  { ageGroup:'10-12', skillArea:'quantitative', subSkill:'الجبر المتقدم', difficulty:'hard', questionType:'text', questionTextAr:'حل: 2س + 3ص = 12 عندما ص = 2', questionImageUrl:null, options:[{text:'س = 2'},{text:'س = 3'},{text:'س = 4'},{text:'س = 5'}], correctOptionIndex:1, explanationAr:'نعوض ص=2: 2س+6=12 → 2س=6 → س=3.', tags:[] },
  { ageGroup:'10-12', skillArea:'quantitative', subSkill:'الهندسة المتقدمة', difficulty:'hard', questionType:'text', questionTextAr:'مكعب طول ضلعه 4 سم. ما حجمه؟', questionImageUrl:null, options:[{text:'48 سم³'},{text:'60 سم³'},{text:'64 سم³'},{text:'80 سم³'}], correctOptionIndex:2, explanationAr:'حجم المكعب = الضلع³ = 4×4×4 = 64 سم³.', tags:[] },
  { ageGroup:'10-12', skillArea:'quantitative', subSkill:'الاحتمالات', difficulty:'hard', questionType:'text', questionTextAr:'رُمي حجر نرد مرة واحدة. ما احتمال ظهور عدد زوجي؟', questionImageUrl:null, options:[{text:'1/6'},{text:'1/3'},{text:'1/2'},{text:'2/3'}], correctOptionIndex:2, explanationAr:'الأعداد الزوجية على النرد: 2، 4، 6 أي 3 من 6. الاحتمال = 3/6 = 1/2.', tags:[] },
  { ageGroup:'10-12', skillArea:'quantitative', subSkill:'الأنماط المتقدمة', difficulty:'hard', questionType:'text', questionTextAr:'ما مجموع الأعداد من 1 إلى 100؟', questionImageUrl:null, options:[{text:'4500'},{text:'5000'},{text:'5050'},{text:'5500'}], correctOptionIndex:2, explanationAr:'المجموع = (50 × 101) = 5050. أو بالقاعدة: ن(ن+1)/2 = 100×101/2 = 5050.', tags:[] },
  { ageGroup:'10-12', skillArea:'quantitative', subSkill:'الاحتمالات', difficulty:'hard', questionType:'text', questionTextAr:'رُميت عملة نقود مرتين. ما احتمال ظهور صورة مرتين؟', questionImageUrl:null, options:[{text:'1/4'},{text:'1/2'},{text:'3/4'},{text:'1'}], correctOptionIndex:0, explanationAr:'احتمال صورة في الأولى = 1/2، وفي الثانية = 1/2. الاحتمالان مستقلان: 1/2 × 1/2 = 1/4.', tags:[] },
  { ageGroup:'10-12', skillArea:'quantitative', subSkill:'الجبر المتقدم', difficulty:'hard', questionType:'text', questionTextAr:'إذا كان س² - 5س + 6 = 0، ما قيمتا س؟', questionImageUrl:null, options:[{text:'1 و6'},{text:'2 و3'},{text:'3 و4'},{text:'-2 و-3'}], correctOptionIndex:1, explanationAr:'نحلل: (س-2)(س-3)=0 → س=2 أو س=3.', tags:[] },
  { ageGroup:'10-12', skillArea:'quantitative', subSkill:'الهندسة المتقدمة', difficulty:'hard', questionType:'text', questionTextAr:'مثلث قاعدته 10 سم وارتفاعه 6 سم. ما مساحته؟', questionImageUrl:null, options:[{text:'25 سم²'},{text:'30 سم²'},{text:'40 سم²'},{text:'60 سم²'}], correctOptionIndex:1, explanationAr:'مساحة المثلث = (القاعدة × الارتفاع) / 2 = (10 × 6) / 2 = 30 سم².', tags:[] },
  { ageGroup:'10-12', skillArea:'quantitative', subSkill:'التحليل', difficulty:'hard', questionType:'text', questionTextAr:'إذا كانت ن = ن-1 + ن-2 للسلسلة 1، 1، 2، 3، 5، ما الحد العاشر؟', questionImageUrl:null, options:[{text:'34'},{text:'55'},{text:'89'},{text:'144'}], correctOptionIndex:1, explanationAr:'متتالية فيبوناتشي: 1،1،2،3،5،8،13،21،34،55. الحد العاشر هو 55.', tags:[] },
  { ageGroup:'10-12', skillArea:'quantitative', subSkill:'المسائل المتقدمة', difficulty:'hard', questionType:'text', questionTextAr:'قطار يسير بسرعة 90 كم/ساعة. كم يقطع في 40 دقيقة؟', questionImageUrl:null, options:[{text:'50 كم'},{text:'55 كم'},{text:'60 كم'},{text:'65 كم'}], correctOptionIndex:2, explanationAr:'40 دقيقة = 2/3 ساعة. المسافة = السرعة × الزمن = 90 × 2/3 = 60 كم.', tags:[] },

  // ═══════════════════════════════════════════════
  // عمر 10-12 — لفظي — سهل
  // ═══════════════════════════════════════════════
  { ageGroup:'10-12', skillArea:'verbal', subSkill:'المفردات المتقدمة', difficulty:'easy', questionType:'text', questionTextAr:'ما معنى كلمة "مُبهم"؟', questionImageUrl:null, options:[{text:'واضح وصريح'},{text:'غير واضح وملتبس'},{text:'مفرح وسار'},{text:'صعب ومعقد'}], correctOptionIndex:1, explanationAr:'"مبهم" تعني غير واضح أو ملتبس. نقول "كلام مبهم" أي كلام غير مفهوم بوضوح.', tags:[] },
  { ageGroup:'10-12', skillArea:'verbal', subSkill:'المفردات المتقدمة', difficulty:'easy', questionType:'text', questionTextAr:'ما مرادف "النزاهة"؟', questionImageUrl:null, options:[{text:'الكذب'},{text:'الأمانة والصدق'},{text:'الغرور'},{text:'البخل'}], correctOptionIndex:1, explanationAr:'"النزاهة" تعني الأمانة والصدق والبُعد عن الفساد. شخص نزيه لا يقبل الرشوة.', tags:[] },
  { ageGroup:'10-12', skillArea:'verbal', subSkill:'المفردات المتقدمة', difficulty:'easy', questionType:'text', questionTextAr:'ما معنى "يتهاون"؟', questionImageUrl:null, options:[{text:'يجتهد بجدية'},{text:'يتساهل ولا يُعطي الأهمية'},{text:'يعمل بنشاط'},{text:'يتفوق دائماً'}], correctOptionIndex:1, explanationAr:'"يتهاون" تعني يتساهل ولا يُعطي الأمر حقه من الاهتمام والجدية.', tags:[] },
  { ageGroup:'10-12', skillArea:'verbal', subSkill:'المتضادات المتقدمة', difficulty:'easy', questionType:'text', questionTextAr:'ما عكس كلمة "الإجمال"؟', questionImageUrl:null, options:[{text:'الإيجاز'},{text:'التفصيل'},{text:'الاختصار'},{text:'التقليل'}], correctOptionIndex:1, explanationAr:'عكس "الإجمال" (الإيجاز والاختصار) هو "التفصيل" (الشرح المطول).', tags:[] },
  { ageGroup:'10-12', skillArea:'verbal', subSkill:'المفردات المتقدمة', difficulty:'easy', questionType:'text', questionTextAr:'ما معنى "يستشف"؟', questionImageUrl:null, options:[{text:'يشفى من مرض'},{text:'يستنتج ويستخلص'},{text:'يضع في مستشفى'},{text:'يصنع دواء'}], correctOptionIndex:1, explanationAr:'"يستشف" تعني يستنتج ويستخلص معنى خفياً من كلام أو موقف.', tags:[] },
  { ageGroup:'10-12', skillArea:'verbal', subSkill:'المتضادات المتقدمة', difficulty:'easy', questionType:'text', questionTextAr:'ما عكس "الطاعة"؟', questionImageUrl:null, options:[{text:'الحكمة'},{text:'الشجاعة'},{text:'العصيان'},{text:'الكرم'}], correctOptionIndex:2, explanationAr:'عكس "الطاعة" هو "العصيان" أو "المعصية". الطاعة الالتزام بالأوامر والعصيان مخالفتها.', tags:[] },
  { ageGroup:'10-12', skillArea:'verbal', subSkill:'المفردات المتقدمة', difficulty:'easy', questionType:'text', questionTextAr:'ما معنى "التراكم"؟', questionImageUrl:null, options:[{text:'التناقص التدريجي'},{text:'التجمع والتكدس'},{text:'الانتشار السريع'},{text:'الاختفاء التام'}], correctOptionIndex:1, explanationAr:'"التراكم" يعني تجمع الأشياء فوق بعضها تدريجياً. مثل تراكم الغبار أو الديون.', tags:[] },
  { ageGroup:'10-12', skillArea:'verbal', subSkill:'المتضادات المتقدمة', difficulty:'easy', questionType:'text', questionTextAr:'ما عكس "الإسراف"؟', questionImageUrl:null, options:[{text:'الكرم'},{text:'الجود'},{text:'القصد والاعتدال'},{text:'البخل'}], correctOptionIndex:2, explanationAr:'عكس "الإسراف" (المبالغة في الإنفاق) هو "القصد" أو "الاعتدال". البخل طرف آخر.', tags:[] },
  { ageGroup:'10-12', skillArea:'verbal', subSkill:'المفردات المتقدمة', difficulty:'easy', questionType:'text', questionTextAr:'ما معنى "المثابرة"؟', questionImageUrl:null, options:[{text:'الاستسلام السريع'},{text:'الكسل والتقاعس'},{text:'الاستمرار والمواظبة'},{text:'العجلة والتسرع'}], correctOptionIndex:2, explanationAr:'"المثابرة" هي الاستمرار في العمل والمواظبة دون تراجع. صفة ضرورية للنجاح.', tags:[] },
  { ageGroup:'10-12', skillArea:'verbal', subSkill:'المتضادات المتقدمة', difficulty:'easy', questionType:'text', questionTextAr:'ما عكس "الغموض"؟', questionImageUrl:null, options:[{text:'التعقيد'},{text:'الوضوح'},{text:'التشابك'},{text:'الإبهام'}], correctOptionIndex:1, explanationAr:'عكس "الغموض" هو "الوضوح". الغامض غير مفهوم، والواضح مفهوم بسهولة.', tags:[] },

  // عمر 10-12 — لفظي — متوسط
  { ageGroup:'10-12', skillArea:'verbal', subSkill:'التناظر اللغوي', difficulty:'medium', questionType:'text', questionTextAr:'الرسام : الفرشاة = النجار : ؟', questionImageUrl:null, options:[{text:'الخشب'},{text:'المنشار'},{text:'المسمار'},{text:'الطلاء'}], correctOptionIndex:1, explanationAr:'الرسام يستخدم الفرشاة كأداة رئيسية، والنجار يستخدم المنشار كأداته الرئيسية.', tags:[] },
  { ageGroup:'10-12', skillArea:'verbal', subSkill:'الفهم القرائي', difficulty:'medium', questionType:'text', questionTextAr:'قرأت: "المثابرة مفتاح النجاح، فمن يصبر ويداوم على العمل يصل إلى هدفه مهما كانت العقبات." ما الفكرة الرئيسية؟', questionImageUrl:null, options:[{text:'النجاح سهل دائماً'},{text:'المثابرة تقود للنجاح رغم العقبات'},{text:'يجب تجنب العقبات'},{text:'الصبر وحده يكفي'}], correctOptionIndex:1, explanationAr:'النص يؤكد أن المثابرة مع الصبر يقودان للنجاح حتى في وجود العقبات.', tags:[] },
  { ageGroup:'10-12', skillArea:'verbal', subSkill:'التناظر اللغوي', difficulty:'medium', questionType:'text', questionTextAr:'الطيار : الطائرة = البحار : ؟', questionImageUrl:null, options:[{text:'البحر'},{text:'السفينة'},{text:'المرساة'},{text:'الميناء'}], correctOptionIndex:1, explanationAr:'الطيار يقود الطائرة، والبحار يقود السفينة. هذا تناظر بين الشخص وما يقوده.', tags:[] },
  { ageGroup:'10-12', skillArea:'verbal', subSkill:'الخطأ السياقي', difficulty:'medium', questionType:'text', questionTextAr:'أي جملة فيها خطأ سياقي: "الشمس تشرق في الشرق"، "الجليد يذوب في الحر"، "النار تُجمّد الماء"؟', questionImageUrl:null, options:[{text:'الأولى'},{text:'الثانية'},{text:'الثالثة'},{text:'لا يوجد خطأ'}], correctOptionIndex:2, explanationAr:'"النار تجمد الماء" خطأ سياقي. النار تسخن وتذيب وليس تجمد. الجملتان الأوليان صحيحتان.', tags:[] },
  { ageGroup:'10-12', skillArea:'verbal', subSkill:'التناظر اللغوي', difficulty:'medium', questionType:'text', questionTextAr:'الربيع : الازدهار = الشتاء : ؟', questionImageUrl:null, options:[{text:'المطر'},{text:'البرودة'},{text:'الخمول'},{text:'الثلج'}], correctOptionIndex:1, explanationAr:'الربيع يرمز للازدهار والنمو، والشتاء يرمز للبرودة والركود.', tags:[] },
  { ageGroup:'10-12', skillArea:'verbal', subSkill:'الفهم القرائي', difficulty:'medium', questionType:'text', questionTextAr:'قرأت: "إن العلم نور يضيء العقول ويرفع الأمم، وبه تتحقق التنمية والتقدم." ما الذي يرفع الأمم وفق النص؟', questionImageUrl:null, options:[{text:'المال'},{text:'القوة العسكرية'},{text:'العلم'},{text:'الموارد الطبيعية'}], correctOptionIndex:2, explanationAr:'النص يقول صراحة أن العلم هو ما يرفع الأمم ويحقق التنمية والتقدم.', tags:[] },
  { ageGroup:'10-12', skillArea:'verbal', subSkill:'التناظر اللغوي', difficulty:'medium', questionType:'text', questionTextAr:'القضاء : العدالة = التعليم : ؟', questionImageUrl:null, options:[{text:'الكتب'},{text:'المعرفة'},{text:'المدارس'},{text:'المعلمون'}], correctOptionIndex:1, explanationAr:'القضاء غايته تحقيق العدالة، والتعليم غايته نشر المعرفة.', tags:[] },
  { ageGroup:'10-12', skillArea:'verbal', subSkill:'الخطأ السياقي', difficulty:'medium', questionType:'text', questionTextAr:'أي كلمة خطأ سياقي: "الشاعر كتب قصيدة رائعة وقرأها بصوت عالٍ على المُستمعين"؟', questionImageUrl:null, options:[{text:'الشاعر'},{text:'قصيدة'},{text:'لا يوجد خطأ'},{text:'المستمعين'}], correctOptionIndex:2, explanationAr:'الجملة صحيحة تماماً سياقياً. الشاعر يكتب القصائد ويقرأها على المستمعين.', tags:[] },
  { ageGroup:'10-12', skillArea:'verbal', subSkill:'التناظر اللغوي', difficulty:'medium', questionType:'text', questionTextAr:'الكلمة : الجملة = الجملة : ؟', questionImageUrl:null, options:[{text:'الحرف'},{text:'المقطع'},{text:'الفقرة'},{text:'الكلمة'}], correctOptionIndex:2, explanationAr:'الكلمات تتكون منها الجملة، والجمل تتكون منها الفقرة. تناظر تركيبي متسلسل.', tags:[] },
  { ageGroup:'10-12', skillArea:'verbal', subSkill:'الفهم القرائي', difficulty:'medium', questionType:'text', questionTextAr:'قرأت: "الوقت كالسيف إن لم تقطعه قطعك." ماذا يقصد الكاتب؟', questionImageUrl:null, options:[{text:'الوقت أداة حادة'},{text:'من لا يستثمر وقته يخسره'},{text:'السيف أهم من الوقت'},{text:'الوقت خطر جداً'}], correctOptionIndex:1, explanationAr:'المقصود: من لا يستثمر وقته ويستغله بالعمل المفيد، ضاع عمره وخسر. هو كناية عن أهمية الوقت.', tags:[] },

  // عمر 10-12 — لفظي — صعب
  { ageGroup:'10-12', skillArea:'verbal', subSkill:'الاستنتاج من النص', difficulty:'hard', questionType:'text', questionTextAr:'قرأت: "لم تكن الرحلة سهلة، لكن الفريق لم يتراجع. واجهوا العواصف والإرهاق، وفي النهاية وصلوا." ما الصفة الغالبة على الفريق؟', questionImageUrl:null, options:[{text:'الخوف'},{text:'الكسل'},{text:'الإصرار'},{text:'التهور'}], correctOptionIndex:2, explanationAr:'النص يصف مواجهتهم للصعاب دون تراجع — هذا يدل على الإصرار والعزيمة.', tags:[] },
  { ageGroup:'10-12', skillArea:'verbal', subSkill:'التناظر المعقد', difficulty:'hard', questionType:'text', questionTextAr:'الإهمال : الفشل = الاجتهاد : ؟', questionImageUrl:null, options:[{text:'الكسل'},{text:'التعب'},{text:'النجاح'},{text:'المحاولة'}], correctOptionIndex:2, explanationAr:'الإهمال سبب الفشل، والاجتهاد سبب النجاح. تناظر سبب ونتيجة.', tags:[] },
  { ageGroup:'10-12', skillArea:'verbal', subSkill:'الخطأ السياقي المتقدم', difficulty:'hard', questionType:'text', questionTextAr:'أي جملة صحيحة منطقياً وسياقياً؟', questionImageUrl:null, options:[{text:'ابتلع الجبل البحيرة كاملة'},{text:'قرأ العالم الكتاب بعناية ليفهم النظرية'},{text:'شرب القلم الحبر وكتب بالماء'},{text:'نامت الأفكار في الدرج الأيمن'}], correctOptionIndex:1, explanationAr:'"قرأ العالم الكتاب بعناية" منطقية وصحيحة. باقي الجمل تنسب أفعالاً لغير مالكيها.', tags:[] },
  { ageGroup:'10-12', skillArea:'verbal', subSkill:'الاستنتاج من النص', difficulty:'hard', questionType:'text', questionTextAr:'قرأت: "ازداد تلوث الهواء في المدن مع نمو الصناعة." ما الاستنتاج المنطقي؟', questionImageUrl:null, options:[{text:'الصناعة مفيدة فقط'},{text:'التلوث لا علاقة له بالصناعة'},{text:'الصناعة تساهم في تلوث الهواء'},{text:'المدن أنظف من الريف'}], correctOptionIndex:2, explanationAr:'النص يقول "ازداد التلوث مع نمو الصناعة" — هذا دليل على علاقة سببية بين الصناعة والتلوث.', tags:[] },
  { ageGroup:'10-12', skillArea:'verbal', subSkill:'التناظر المعقد', difficulty:'hard', questionType:'text', questionTextAr:'الديمقراطية : الانتخاب = الملكية : ؟', questionImageUrl:null, options:[{text:'البرلمان'},{text:'الوراثة'},{text:'الانقلاب'},{text:'التصويت'}], correctOptionIndex:1, explanationAr:'في الديمقراطية يُختار الحاكم بالانتخاب، وفي الملكية ينتقل الحكم بالوراثة.', tags:[] },
  { ageGroup:'10-12', skillArea:'verbal', subSkill:'الاستنتاج من النص', difficulty:'hard', questionType:'text', questionTextAr:'قرأت: "لكل إنسان طاقة محدودة. النجاح الحقيقي في توزيع هذه الطاقة بذكاء." ما النتيجة؟', questionImageUrl:null, options:[{text:'يجب العمل بلا توقف'},{text:'إدارة الطاقة أهم من كميتها'},{text:'الكسل مقبول أحياناً'},{text:'الطاقة لا تنفد'}], correctOptionIndex:1, explanationAr:'النص يقول إن التوزيع الذكي للطاقة هو مفتاح النجاح — أي الإدارة أهم من الكمية.', tags:[] },
  { ageGroup:'10-12', skillArea:'verbal', subSkill:'التناظر المعقد', difficulty:'hard', questionType:'text', questionTextAr:'البذرة : الشجرة = الفكرة : ؟', questionImageUrl:null, options:[{text:'الكتاب'},{text:'العقل'},{text:'المشروع'},{text:'العلم'}], correctOptionIndex:2, explanationAr:'البذرة تنمو لتصبح شجرة، والفكرة تتطور لتصبح مشروعاً. تناظر نمو وتطور.', tags:[] },
  { ageGroup:'10-12', skillArea:'verbal', subSkill:'الخطأ السياقي المتقدم', difficulty:'hard', questionType:'text', questionTextAr:'أي جملة فيها خطأ دلالي: "شعر الطالب بالفرح عند سماع النتيجة الجيدة"، "تألم المريض من الألم"، "تألم المريض من الدواء"؟', questionImageUrl:null, options:[{text:'الأولى'},{text:'الثانية'},{text:'الثالثة'},{text:'لا يوجد خطأ'}], correctOptionIndex:1, explanationAr:'"تألم المريض من الألم" تحصيل حاصل — ليست جملة ذات معنى إضافي. هي خطأ دلالي بالتكرار.', tags:[] },
  { ageGroup:'10-12', skillArea:'verbal', subSkill:'الاستنتاج من النص', difficulty:'hard', questionType:'text', questionTextAr:'قرأت: "من لا يُجرّب لا يكتسب خبرة، ومن لا تكون له خبرة لا يُحكم في الأمور." ما الخلاصة؟', questionImageUrl:null, options:[{text:'التجربة تضيع الوقت'},{text:'الخبرة تأتي من التجربة وتُنتج حكمة'},{text:'يجب تجنب التجارب الصعبة'},{text:'الحكمة فطرية لا مكتسبة'}], correctOptionIndex:1, explanationAr:'السلسلة: تجربة → خبرة → حكم سليم. التجربة هي أصل الخبرة التي تُنتج الحكمة.', tags:[] },
  { ageGroup:'10-12', skillArea:'verbal', subSkill:'التناظر المعقد', difficulty:'hard', questionType:'text', questionTextAr:'الفوضى : النظام = الجهل : ؟', questionImageUrl:null, options:[{text:'التعلم'},{text:'الكتاب'},{text:'العلم'},{text:'المدرسة'}], correctOptionIndex:2, explanationAr:'الفوضى عكس النظام، والجهل عكس العلم. تناظر بين المتضادات.', tags:[] },

  // ═══════════════════════════════════════════════
  // عمر 10-12 — منطقي — سهل
  // ═══════════════════════════════════════════════
  { ageGroup:'10-12', skillArea:'logical_patterns', subSkill:'السلاسل الرقمية', difficulty:'easy', questionType:'text', questionTextAr:'ما التالي: 3، 6، 12، 24، __؟', questionImageUrl:null, options:[{text:'36'},{text:'42'},{text:'48'},{text:'50'}], correctOptionIndex:2, explanationAr:'كل رقم يُضرب في 2: 3×2=6، 6×2=12، 12×2=24، 24×2=48.', tags:[] },
  { ageGroup:'10-12', skillArea:'logical_patterns', subSkill:'الاستنتاج', difficulty:'easy', questionType:'text', questionTextAr:'كل الثدييات تتنفس هواء. الحوت ثديي. هل الحوت يتنفس هواء؟', questionImageUrl:null, options:[{text:'لا لأنه يعيش في الماء'},{text:'نعم'},{text:'أحياناً'},{text:'لا أعرف'}], correctOptionIndex:1, explanationAr:'نعم. بالرغم من عيشه في الماء، الحوت ثديي يتنفس هواء من خلال خياشيمه على سطح الماء.', tags:[] },
  { ageGroup:'10-12', skillArea:'logical_patterns', subSkill:'السلاسل الرقمية', difficulty:'easy', questionType:'text', questionTextAr:'ما الرقم المفقود: 2، 5، 8، 11، __؟', questionImageUrl:null, options:[{text:'12'},{text:'13'},{text:'14'},{text:'15'}], correctOptionIndex:2, explanationAr:'النمط هو إضافة 3: 2+3=5، 5+3=8، 8+3=11، 11+3=14.', tags:[] },
  { ageGroup:'10-12', skillArea:'logical_patterns', subSkill:'القياس', difficulty:'easy', questionType:'text', questionTextAr:'إذا كان كل المدراء موظفون، وسالم مدير، فهل سالم موظف؟', questionImageUrl:null, options:[{text:'لا'},{text:'نعم'},{text:'ربما'},{text:'لا يمكن التحديد'}], correctOptionIndex:1, explanationAr:'نعم. كل مدير = موظف، وسالم مدير، إذن سالم موظف. هذا قياس منطقي صحيح.', tags:[] },
  { ageGroup:'10-12', skillArea:'logical_patterns', subSkill:'السلاسل الرقمية', difficulty:'easy', questionType:'text', questionTextAr:'ما التالي: 1، 8، 27، 64، __؟', questionImageUrl:null, options:[{text:'100'},{text:'119'},{text:'125'},{text:'136'}], correctOptionIndex:2, explanationAr:'هذه مكعبات الأعداد: 1³=1، 2³=8، 3³=27، 4³=64، 5³=125.', tags:[] },
  { ageGroup:'10-12', skillArea:'logical_patterns', subSkill:'الاستنتاج', difficulty:'easy', questionType:'text', questionTextAr:'إذا كان 3س = 15، هل س أكبر من 4؟', questionImageUrl:null, options:[{text:'نعم'},{text:'لا'},{text:'لا يمكن التحديد'},{text:'متساوٍ مع 4'}], correctOptionIndex:0, explanationAr:'س = 15÷3 = 5. وبما أن 5 > 4، فنعم س أكبر من 4.', tags:[] },
  { ageGroup:'10-12', skillArea:'logical_patterns', subSkill:'السلاسل الرقمية', difficulty:'easy', questionType:'text', questionTextAr:'ما الرقم المفقود: 7، 14، 21، 28، __؟', questionImageUrl:null, options:[{text:'33'},{text:'34'},{text:'35'},{text:'36'}], correctOptionIndex:2, explanationAr:'مضاعفات 7: 7، 14، 21، 28، 35.', tags:[] },
  { ageGroup:'10-12', skillArea:'logical_patterns', subSkill:'القياس', difficulty:'easy', questionType:'text', questionTextAr:'لا يوجد مربع له 3 زوايا. هذا الشكل له 3 زوايا. هل هو مربع؟', questionImageUrl:null, options:[{text:'نعم'},{text:'لا'},{text:'ربما'},{text:'يحتاج معلومات أكثر'}], correctOptionIndex:1, explanationAr:'لا. المربع له 4 زوايا. الشكل ذو 3 زوايا هو مثلث وليس مربعاً.', tags:[] },
  { ageGroup:'10-12', skillArea:'logical_patterns', subSkill:'السلاسل الرقمية', difficulty:'easy', questionType:'text', questionTextAr:'ما التالي: 50، 45، 40، 35، __؟', questionImageUrl:null, options:[{text:'28'},{text:'30'},{text:'32'},{text:'34'}], correctOptionIndex:1, explanationAr:'النمط هو طرح 5: 50-5=45، 45-5=40، 40-5=35، 35-5=30.', tags:[] },
  { ageGroup:'10-12', skillArea:'logical_patterns', subSkill:'الاستنتاج', difficulty:'easy', questionType:'text', questionTextAr:'إذا كانت 3 كتب تكلف 36 ريال، كم تكلف 7 كتب؟', questionImageUrl:null, options:[{text:'70'},{text:'74'},{text:'82'},{text:'84'}], correctOptionIndex:3, explanationAr:'سعر الكتاب الواحد = 36÷3 = 12. 7 كتب = 7×12 = 84 ريال.', tags:[] },

  // عمر 10-12 — منطقي — متوسط
  { ageGroup:'10-12', skillArea:'logical_patterns', subSkill:'الاستدلال المنطقي', difficulty:'medium', questionType:'text', questionTextAr:'إذا كانت كل X تكون Y وبعض Y تكون Z، فما الذي يمكن استنتاجه؟', questionImageUrl:null, options:[{text:'كل X تكون Z'},{text:'بعض X قد تكون Z'},{text:'لا علاقة بين X وZ'},{text:'X = Z دائماً'}], correctOptionIndex:1, explanationAr:'كل X هي Y، وبعض Y هي Z. يمكن أن بعض X تقع ضمن الـ Y التي هي Z. إذن بعض X قد تكون Z.', tags:[] },
  { ageGroup:'10-12', skillArea:'logical_patterns', subSkill:'السلاسل المتقدمة', difficulty:'medium', questionType:'text', questionTextAr:'ما التالي: 2، 3، 5، 7، 11، 13، __؟', questionImageUrl:null, options:[{text:'15'},{text:'16'},{text:'17'},{text:'19'}], correctOptionIndex:2, explanationAr:'هذه الأعداد الأولية بالترتيب: 2، 3، 5، 7، 11، 13، 17.', tags:[] },
  { ageGroup:'10-12', skillArea:'logical_patterns', subSkill:'الاستدلال المنطقي', difficulty:'medium', questionType:'text', questionTextAr:'كل الشعراء حساسون. بعض الفنانين شعراء. ما الذي يلزم؟', questionImageUrl:null, options:[{text:'كل الفنانين حساسون'},{text:'لا أحد من الفنانين حساس'},{text:'بعض الفنانين حساسون'},{text:'الفنانون ليسوا حساسين'}], correctOptionIndex:2, explanationAr:'بعض الفنانين = شعراء. وكل الشعراء = حساسون. إذن بعض الفنانين (الذين هم شعراء) حساسون.', tags:[] },
  { ageGroup:'10-12', skillArea:'logical_patterns', subSkill:'الأنماط المتقدمة', difficulty:'medium', questionType:'text', questionTextAr:'ما الرقم المفقود: 2، 6، 12، 20، 30، __؟', questionImageUrl:null, options:[{text:'38'},{text:'40'},{text:'42'},{text:'44'}], correctOptionIndex:2, explanationAr:'الفروق: +4، +6، +8، +10، +12. بعد 30: 30+12=42.', tags:[] },
  { ageGroup:'10-12', skillArea:'logical_patterns', subSkill:'الاستدلال المنطقي', difficulty:'medium', questionType:'text', questionTextAr:'إذا "ليس كل الطلاب مجتهدون" فأي جملة صحيحة بالضرورة؟', questionImageUrl:null, options:[{text:'لا أحد مجتهد'},{text:'كلهم كسالى'},{text:'بعض الطلاب ليسوا مجتهدين'},{text:'كلهم مجتهدون'}], correctOptionIndex:2, explanationAr:'"ليس كل" = بعضهم ليسوا. إذن بعض الطلاب ليسوا مجتهدين.', tags:[] },
  { ageGroup:'10-12', skillArea:'logical_patterns', subSkill:'السلاسل المتقدمة', difficulty:'medium', questionType:'text', questionTextAr:'ما التالي: 1، 4، 10، 20، 35، __؟', questionImageUrl:null, options:[{text:'50'},{text:'53'},{text:'56'},{text:'58'}], correctOptionIndex:1, explanationAr:'الفروق: +3، +6، +10، +15، +21. (الفروق نفسها هي أعداد مثلثية). بعد 35: 35+21=56. تصحيح: +3،+6،+10،+15 → الفرق +5،+4،+5 → 35+21=56.', tags:[] },
  { ageGroup:'10-12', skillArea:'logical_patterns', subSkill:'الاستدلال المنطقي', difficulty:'medium', questionType:'text', questionTextAr:'خالد أذكى من سامي وسامي أذكى من فهد. من الأقل ذكاءً من سامي؟', questionImageUrl:null, options:[{text:'خالد'},{text:'سامي'},{text:'فهد'},{text:'لا يمكن التحديد'}], correctOptionIndex:2, explanationAr:'خالد > سامي > فهد. فهد هو أقل الثلاثة ذكاءً.', tags:[] },
  { ageGroup:'10-12', skillArea:'logical_patterns', subSkill:'الأنماط المتقدمة', difficulty:'medium', questionType:'text', questionTextAr:'ما التالي: أ، ج، هـ، ز، __؟', questionImageUrl:null, options:[{text:'ح'},{text:'ط'},{text:'ي'},{text:'ك'}], correctOptionIndex:1, explanationAr:'حروف الهجاء: أ(1)، ب(2)، ج(3)، د(4)، هـ(5)، و(6)، ز(7)، ح(8)، ط(9)... النمط الأحرف الفردية: 1،3،5،7،9. بعد ز(7) يأتي ط(9).', tags:[] },
  { ageGroup:'10-12', skillArea:'logical_patterns', subSkill:'الاستدلال المنطقي', difficulty:'medium', questionType:'text', questionTextAr:'جميع أ هي ب. لا شيء من ب هو ج. ما العلاقة بين أ وج؟', questionImageUrl:null, options:[{text:'أ = ج'},{text:'أ وج مختلفتان تماماً'},{text:'أحياناً أ = ج'},{text:'لا يمكن التحديد'}], correctOptionIndex:1, explanationAr:'كل أ = ب، ولا شيء من ب = ج. إذن لا شيء من أ = ج. أ وج مختلفتان تماماً.', tags:[] },
  { ageGroup:'10-12', skillArea:'logical_patterns', subSkill:'السلاسل المتقدمة', difficulty:'medium', questionType:'text', questionTextAr:'ما الرقم المفقود: 1، 3، 6، 10، 15، __؟', questionImageUrl:null, options:[{text:'20'},{text:'21'},{text:'22'},{text:'25'}], correctOptionIndex:1, explanationAr:'هذه الأعداد المثلثية: الفروق +2،+3،+4،+5،+6. بعد 15: 15+6=21.', tags:[] },

  // عمر 10-12 — منطقي — صعب
  { ageGroup:'10-12', skillArea:'logical_patterns', subSkill:'القياس المنطقي المعقد', difficulty:'hard', questionType:'text', questionTextAr:'كل أ هي ب. كل ب هي ج. بعض ج هي د. ما الذي يلزم؟', questionImageUrl:null, options:[{text:'كل أ هي د'},{text:'بعض أ قد تكون د'},{text:'لا علاقة بين أ ود'},{text:'أ لا تكون د أبداً'}], correctOptionIndex:1, explanationAr:'كل أ هي ب، وكل ب هي ج، وبعض ج هي د. أ ⊂ ب ⊂ ج وبعض ج ⊂ د. إذن بعض أ قد تكون د.', tags:[] },
  { ageGroup:'10-12', skillArea:'logical_patterns', subSkill:'السلاسل المعقدة', difficulty:'hard', questionType:'text', questionTextAr:'ما التالي: 1، 2، 4، 8، 16، 32، __؟', questionImageUrl:null, options:[{text:'48'},{text:'60'},{text:'64'},{text:'72'}], correctOptionIndex:2, explanationAr:'كل رقم يُضرب في 2: 32×2=64. هذه قوى العدد 2.', tags:[] },
  { ageGroup:'10-12', skillArea:'logical_patterns', subSkill:'القياس المنطقي المعقد', difficulty:'hard', questionType:'text', questionTextAr:'إذا كان "إذا مطر ← فرطوبة" و"رطوبة الآن موجودة". هل مطرت بالضرورة؟', questionImageUrl:null, options:[{text:'نعم'},{text:'لا'},{text:'ليس بالضرورة'},{text:'مستحيل'}], correctOptionIndex:2, explanationAr:'ليس بالضرورة. الرطوبة قد تأتي من مصدر آخر غير المطر. هذا خطأ منطقي يسمى "تأكيد التالي".', tags:[] },
  { ageGroup:'10-12', skillArea:'logical_patterns', subSkill:'السلاسل المعقدة', difficulty:'hard', questionType:'text', questionTextAr:'ما التالي: 2، 6، 18، 54، __؟', questionImageUrl:null, options:[{text:'108'},{text:'162'},{text:'126'},{text:'144'}], correctOptionIndex:1, explanationAr:'كل رقم يُضرب في 3: 2×3=6، 6×3=18، 18×3=54، 54×3=162.', tags:[] },
  { ageGroup:'10-12', skillArea:'logical_patterns', subSkill:'القياس المنطقي المعقد', difficulty:'hard', questionType:'text', questionTextAr:'إذا كان "إذا اجتهدت ← نجحت" ولم تنجح. ماذا نستنتج؟', questionImageUrl:null, options:[{text:'اجتهدت'},{text:'لم تجتهد'},{text:'ربما اجتهدت'},{text:'لا يمكن الاستنتاج'}], correctOptionIndex:1, explanationAr:'بالنفي المنطقي: "إذا أ ← ب" فنفي ب يعني نفي أ. لم ينجح → لم يجتهد. (مبدأ نقيض الشرطية)', tags:[] },
  { ageGroup:'10-12', skillArea:'logical_patterns', subSkill:'الاستدلال الرياضي', difficulty:'hard', questionType:'text', questionTextAr:'إذا كان مجموع 3 أعداد متتالية 51، ما الأعداد؟', questionImageUrl:null, options:[{text:'15، 16، 17'},{text:'16، 17، 18'},{text:'17، 18، 19'},{text:'18، 19، 20'}], correctOptionIndex:1, explanationAr:'الأعداد: ن، ن+1، ن+2. مجموعها = 3ن+3 = 51 → 3ن = 48 → ن = 16. الأعداد: 16، 17، 18.', tags:[] },
  { ageGroup:'10-12', skillArea:'logical_patterns', subSkill:'السلاسل المعقدة', difficulty:'hard', questionType:'text', questionTextAr:'ما الرقم المفقود: 1، 3، 7، 13، 21، __؟', questionImageUrl:null, options:[{text:'29'},{text:'31'},{text:'33'},{text:'35'}], correctOptionIndex:1, explanationAr:'الفروق: +2، +4، +6، +8، +10. بعد 21: 21+10=31.', tags:[] },
  { ageGroup:'10-12', skillArea:'logical_patterns', subSkill:'القياس المنطقي المعقد', difficulty:'hard', questionType:'text', questionTextAr:'إذا كان "الحرارة تمدد المعادن"، ماذا يحدث للجسر المعدني في الصيف الحار؟', questionImageUrl:null, options:[{text:'يتقلص'},{text:'يبقى كما هو'},{text:'يتمدد'},{text:'يذوب'}], correctOptionIndex:2, explanationAr:'الحرارة تمدد المعادن، والصيف حار، إذن الجسر المعدني يتمدد. لهذا تُترك فجوات في الجسور.', tags:[] },
  { ageGroup:'10-12', skillArea:'logical_patterns', subSkill:'الاستدلال الرياضي', difficulty:'hard', questionType:'text', questionTextAr:'في مجموعة من 30 شخصاً، 20 يحبون القهوة و15 يحبون الشاي و10 يحبون كليهما. كم لا يحب شيئاً؟', questionImageUrl:null, options:[{text:'3'},{text:'5'},{text:'7'},{text:'8'}], correctOptionIndex:1, explanationAr:'بمبدأ الإدراج والإقصاء: يحبون الأقل واحد = 20+15-10 = 25. لا يحب شيئاً = 30-25 = 5.', tags:[] },
  { ageGroup:'10-12', skillArea:'logical_patterns', subSkill:'السلاسل المعقدة', difficulty:'hard', questionType:'text', questionTextAr:'ما التالي: 1، 2، 6، 24، 120، __؟', questionImageUrl:null, options:[{text:'360'},{text:'600'},{text:'720'},{text:'840'}], correctOptionIndex:2, explanationAr:'هذه المضروبات (Factorials): 1!=1، 2!=2، 3!=6، 4!=24، 5!=120، 6!=720.', tags:[] },
];

async function seed2() {
  const client = createClient({ url: process.env.TURSO_DATABASE_URL || 'file:./local.db' });
  const db = drizzle(client);
  console.log('Seeding part 2...');
  let count = 0;
  for (const q of questionData2) {
    await db.insert(questions).values({
      id: crypto.randomUUID(),
      skillArea: q.skillArea,
      subSkill: q.subSkill,
      ageGroup: q.ageGroup,
      difficulty: q.difficulty,
      questionType: q.questionType as 'text' | 'image',
      questionTextAr: q.questionTextAr,
      questionImageUrl: q.questionImageUrl,
      options: q.options as Array<{text: string}>,
      correctOptionIndex: q.correctOptionIndex,
      explanationAr: q.explanationAr,
      tags: q.tags,
      isActive: true,
    }).onConflictDoNothing();
    count++;
  }
  console.log(`Seeded ${count} additional questions`);
  return count;
}

if (require.main === module) {
  seed2().then(n => { console.log(`Done: ${n}`); process.exit(0); }).catch(e => { console.error(e); process.exit(1); });
}
