import { getDb } from './index';
import { questions } from './schema';

const newQuestions = [
  // ==========================================
  // 6-9 سنوات — كمي (10 أسئلة)
  // ==========================================
  {
    id: crypto.randomUUID(),
    ageGroup: '6-9', skillArea: 'quantitative', subSkill: 'basic_operations',
    difficulty: 'easy', questionType: 'text',
    questionTextAr: 'أحمد لديه ٣ تفاحات واشترى ٥ تفاحات أخرى. كم تفاحة لديه الآن؟',
    questionImageUrl: null,
    options: [{ text: '٦' }, { text: '٧' }, { text: '٨' }, { text: '٩' }],
    correctOptionIndex: 2,
    explanationAr: '٣ + ٥ = ٨ تفاحات',
    tags: ['addition', 'word_problem'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '6-9', skillArea: 'quantitative', subSkill: 'number_sequences',
    difficulty: 'easy', questionType: 'text',
    questionTextAr: 'أكمل المتسلسلة: ٥ ، ١٠ ، ١٥ ، __',
    questionImageUrl: null,
    options: [{ text: '١٦' }, { text: '١٧' }, { text: '١٨' }, { text: '٢٠' }],
    correctOptionIndex: 3,
    explanationAr: 'كل رقم يزيد بمقدار ٥، لذا ١٥ + ٥ = ٢٠',
    tags: ['sequences', 'counting_by_5'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '6-9', skillArea: 'quantitative', subSkill: 'basic_operations',
    difficulty: 'easy', questionType: 'text',
    questionTextAr: 'كانت لدى سارة ١٢ قلماً، فأعطت صديقتها ٥ أقلام. كم قلماً تبقى معها؟',
    questionImageUrl: null,
    options: [{ text: '٥' }, { text: '٦' }, { text: '٧' }, { text: '٨' }],
    correctOptionIndex: 2,
    explanationAr: '١٢ - ٥ = ٧ أقلام',
    tags: ['subtraction', 'word_problem'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '6-9', skillArea: 'quantitative', subSkill: 'number_comparison',
    difficulty: 'easy', questionType: 'text',
    questionTextAr: 'أي رقم يقع بين ١٥ و ٢٠؟',
    questionImageUrl: null,
    options: [{ text: '١٢' }, { text: '١٤' }, { text: '١٧' }, { text: '٢٢' }],
    correctOptionIndex: 2,
    explanationAr: 'الرقم ١٧ يقع بين ١٥ و٢٠',
    tags: ['number_line', 'comparison'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '6-9', skillArea: 'quantitative', subSkill: 'multiplication',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: '٣ × ٤ = ؟',
    questionImageUrl: null,
    options: [{ text: '٧' }, { text: '١٠' }, { text: '١٢' }, { text: '١٤' }],
    correctOptionIndex: 2,
    explanationAr: '٣ × ٤ = ١٢',
    tags: ['multiplication', 'times_tables'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '6-9', skillArea: 'quantitative', subSkill: 'division',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'ما نصف العدد ١٨؟',
    questionImageUrl: null,
    options: [{ text: '٦' }, { text: '٨' }, { text: '٩' }, { text: '١٠' }],
    correctOptionIndex: 2,
    explanationAr: '١٨ ÷ ٢ = ٩',
    tags: ['halving', 'division'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '6-9', skillArea: 'quantitative', subSkill: 'basic_operations',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: '١٠٠ - ٣٧ = ؟',
    questionImageUrl: null,
    options: [{ text: '٥٣' }, { text: '٦٣' }, { text: '٦٧' }, { text: '٧٣' }],
    correctOptionIndex: 1,
    explanationAr: '١٠٠ - ٣٧ = ٦٣',
    tags: ['subtraction', 'two_digit'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '6-9', skillArea: 'quantitative', subSkill: 'multiplication',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'عند سارة ٤ صناديق، في كل صندوق ٦ أقلام. كم عدد الأقلام جميعاً؟',
    questionImageUrl: null,
    options: [{ text: '١٠' }, { text: '٢٠' }, { text: '٢٤' }, { text: '٢٨' }],
    correctOptionIndex: 2,
    explanationAr: '٤ × ٦ = ٢٤ قلماً',
    tags: ['multiplication', 'word_problem'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '6-9', skillArea: 'quantitative', subSkill: 'fractions',
    difficulty: 'hard', questionType: 'text',
    questionTextAr: 'أي الكسرين أكبر: ٣/٤ أم ٢/٣؟',
    questionImageUrl: null,
    options: [{ text: '٣/٤' }, { text: '٢/٣' }, { text: 'متساويان' }, { text: 'لا يمكن المقارنة' }],
    correctOptionIndex: 0,
    explanationAr: '٣/٤ = ٠.٧٥ وهو أكبر من ٢/٣ ≈ ٠.٦٧',
    tags: ['fractions', 'comparison'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '6-9', skillArea: 'quantitative', subSkill: 'word_problems',
    difficulty: 'hard', questionType: 'text',
    questionTextAr: 'حصل عمر على ١٥ نقطة، وسلمى أقل منه بـ ٣ نقاط، وفهد أكثر من سلمى بـ ٧ نقاط. كم نقطة لدى فهد؟',
    questionImageUrl: null,
    options: [{ text: '١٦' }, { text: '١٨' }, { text: '١٩' }, { text: '٢٠' }],
    correctOptionIndex: 2,
    explanationAr: 'سلمى = ١٥ - ٣ = ١٢، فهد = ١٢ + ٧ = ١٩',
    tags: ['multi_step', 'word_problem'], isActive: true,
  },

  // ==========================================
  // 6-9 سنوات — لفظي (8 أسئلة)
  // ==========================================
  {
    id: crypto.randomUUID(),
    ageGroup: '6-9', skillArea: 'verbal', subSkill: 'antonyms',
    difficulty: 'easy', questionType: 'text',
    questionTextAr: 'ما مضاد كلمة "كبير"؟',
    questionImageUrl: null,
    options: [{ text: 'جديد' }, { text: 'صغير' }, { text: 'قديم' }, { text: 'ثقيل' }],
    correctOptionIndex: 1,
    explanationAr: 'مضاد كبير هو صغير',
    tags: ['antonyms', 'vocabulary'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '6-9', skillArea: 'verbal', subSkill: 'analogies',
    difficulty: 'easy', questionType: 'text',
    questionTextAr: 'الكتاب للقراءة، كالملعقة لـ ...',
    questionImageUrl: null,
    options: [{ text: 'اللعب' }, { text: 'الكتابة' }, { text: 'الأكل' }, { text: 'الشرب' }],
    correctOptionIndex: 2,
    explanationAr: 'نستخدم الكتاب للقراءة، ونستخدم الملعقة للأكل',
    tags: ['analogies', 'tools'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '6-9', skillArea: 'verbal', subSkill: 'odd_one_out',
    difficulty: 'easy', questionType: 'text',
    questionTextAr: 'أي من هذه الكلمات لا تنتمي للمجموعة؟',
    questionImageUrl: null,
    options: [{ text: 'قطة' }, { text: 'كلب' }, { text: 'شجرة' }, { text: 'أسد' }],
    correctOptionIndex: 2,
    explanationAr: 'القطة والكلب والأسد حيوانات، أما الشجرة فهي نبات',
    tags: ['classification', 'odd_one_out'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '6-9', skillArea: 'verbal', subSkill: 'general_knowledge',
    difficulty: 'easy', questionType: 'text',
    questionTextAr: 'أي الفصول يأتي بعد الصيف؟',
    questionImageUrl: null,
    options: [{ text: 'الربيع' }, { text: 'الشتاء' }, { text: 'الخريف' }, { text: 'الصيف من جديد' }],
    correctOptionIndex: 2,
    explanationAr: 'ترتيب الفصول: الربيع، الصيف، الخريف، الشتاء',
    tags: ['seasons', 'general_knowledge'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '6-9', skillArea: 'verbal', subSkill: 'grammar',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'اختر الفعل الصحيح: هو ___ إلى المدرسة أمس.',
    questionImageUrl: null,
    options: [{ text: 'ذهبت' }, { text: 'تذهب' }, { text: 'ذهب' }, { text: 'يذهب' }],
    correctOptionIndex: 2,
    explanationAr: 'الضمير "هو" مذكر غائب، ويناسبه الفعل الماضي "ذهب"',
    tags: ['grammar', 'verb_conjugation'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '6-9', skillArea: 'verbal', subSkill: 'plurals',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'ما جمع كلمة "كتاب"؟',
    questionImageUrl: null,
    options: [{ text: 'كتابات' }, { text: 'كتيبات' }, { text: 'كتب' }, { text: 'كتابان' }],
    correctOptionIndex: 2,
    explanationAr: 'جمع كتاب هو كُتُب',
    tags: ['plurals', 'grammar'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '6-9', skillArea: 'verbal', subSkill: 'synonyms',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'ما مرادف كلمة "سعيد"؟',
    questionImageUrl: null,
    options: [{ text: 'حزين' }, { text: 'مسرور' }, { text: 'خائف' }, { text: 'غاضب' }],
    correctOptionIndex: 1,
    explanationAr: 'مرادف سعيد هو مسرور، وكلاهما يعني الفرح',
    tags: ['synonyms', 'vocabulary'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '6-9', skillArea: 'verbal', subSkill: 'proverbs',
    difficulty: 'hard', questionType: 'text',
    questionTextAr: 'أكمل المثل: "العلم في الصغر..."',
    questionImageUrl: null,
    options: [{ text: 'كالنقش في الماء' }, { text: 'كالنقش في الحجر' }, { text: 'كالريح العابرة' }, { text: 'كالرمل في اليد' }],
    correctOptionIndex: 1,
    explanationAr: '"العلم في الصغر كالنقش في الحجر" — التعلم المبكر يثبت ويدوم',
    tags: ['proverbs', 'culture'], isActive: true,
  },

  // ==========================================
  // 6-9 سنوات — منطقي (7 أسئلة)
  // ==========================================
  {
    id: crypto.randomUUID(),
    ageGroup: '6-9', skillArea: 'logical_patterns', subSkill: 'pattern_completion',
    difficulty: 'easy', questionType: 'text',
    questionTextAr: 'ما الشكل الذي يكمل النمط: ■ ● ■ ● ■ __؟',
    questionImageUrl: null,
    options: [{ text: '■' }, { text: '●' }, { text: '○' }, { text: '□' }],
    correctOptionIndex: 1,
    explanationAr: 'النمط يتكرر: مربع ودائرة بالتناوب، لذا يأتي بعد المربع الأخير دائرة ●',
    tags: ['patterns', 'alternating'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '6-9', skillArea: 'logical_patterns', subSkill: 'number_sequences',
    difficulty: 'easy', questionType: 'text',
    questionTextAr: 'أكمل المتسلسلة: ٢ ، ٤ ، ٨ ، ١٦ ، __',
    questionImageUrl: null,
    options: [{ text: '١٨' }, { text: '٢٤' }, { text: '٣٢' }, { text: '٣٤' }],
    correctOptionIndex: 2,
    explanationAr: 'كل رقم يُضاعَف: ١٦ × ٢ = ٣٢',
    tags: ['doubling', 'sequences'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '6-9', skillArea: 'logical_patterns', subSkill: 'comparison',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'علي أطول من خالد، وخالد أطول من ناصر. من هو الأقصر؟',
    questionImageUrl: null,
    options: [{ text: 'علي' }, { text: 'خالد' }, { text: 'ناصر' }, { text: 'نفس الطول' }],
    correctOptionIndex: 2,
    explanationAr: 'الترتيب: علي > خالد > ناصر، إذن ناصر هو الأقصر',
    tags: ['ordering', 'comparison'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '6-9', skillArea: 'logical_patterns', subSkill: 'pattern_completion',
    difficulty: 'easy', questionType: 'text',
    questionTextAr: 'أكمل النمط: △ △ ○ △ △ ○ △ △ __',
    questionImageUrl: null,
    options: [{ text: '△' }, { text: '○' }, { text: '□' }, { text: '◇' }],
    correctOptionIndex: 1,
    explanationAr: 'النمط هو مثلثان ثم دائرة. بعد المثلثين الأخيرين تأتي الدائرة',
    tags: ['patterns', 'shapes'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '6-9', skillArea: 'logical_patterns', subSkill: 'rules',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'إذا كانت: ٢ ← ٦ و ٣ ← ٩ و ٤ ← ١٢. فماذا يصبح ٥ ← ؟',
    questionImageUrl: null,
    options: [{ text: '١٣' }, { text: '١٤' }, { text: '١٥' }, { text: '١٦' }],
    correctOptionIndex: 2,
    explanationAr: 'القاعدة هي الضرب في ٣: ٥ × ٣ = ١٥',
    tags: ['rules', 'function'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '6-9', skillArea: 'logical_patterns', subSkill: 'deductive_reasoning',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'كل طلاب الفصل نجحوا في الامتحان، وعلي طالب في هذا الفصل. هل نجح علي؟',
    questionImageUrl: null,
    options: [{ text: 'نعم' }, { text: 'لا' }, { text: 'ربما' }, { text: 'لا يمكن المعرفة' }],
    correctOptionIndex: 0,
    explanationAr: 'بما أن كل طلاب الفصل نجحوا وعلي منهم، فهو نجح بالضرورة',
    tags: ['deduction', 'logic'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '6-9', skillArea: 'logical_patterns', subSkill: 'number_sequences',
    difficulty: 'hard', questionType: 'text',
    questionTextAr: 'أكمل المتسلسلة: ١ ، ١ ، ٢ ، ٣ ، ٥ ، ٨ ، __',
    questionImageUrl: null,
    options: [{ text: '١١' }, { text: '١٢' }, { text: '١٣' }, { text: '١٥' }],
    correctOptionIndex: 2,
    explanationAr: 'كل رقم هو مجموع الرقمين السابقين: ٥ + ٨ = ١٣',
    tags: ['fibonacci', 'sequences'], isActive: true,
  },

  // ==========================================
  // 10-12 سنة — كمي (8 أسئلة)
  // ==========================================
  {
    id: crypto.randomUUID(),
    ageGroup: '10-12', skillArea: 'quantitative', subSkill: 'algebra',
    difficulty: 'easy', questionType: 'text',
    questionTextAr: 'إذا كان س + ٧ = ١٥، فما قيمة س؟',
    questionImageUrl: null,
    options: [{ text: '٦' }, { text: '٧' }, { text: '٨' }, { text: '٩' }],
    correctOptionIndex: 2,
    explanationAr: 'س = ١٥ - ٧ = ٨',
    tags: ['algebra', 'equations'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '10-12', skillArea: 'quantitative', subSkill: 'geometry',
    difficulty: 'easy', questionType: 'text',
    questionTextAr: 'ما مساحة مستطيل طوله ٨ م وعرضه ٥ م؟',
    questionImageUrl: null,
    options: [{ text: '١٣ م²' }, { text: '٢٦ م²' }, { text: '٤٠ م²' }, { text: '٤٥ م²' }],
    correctOptionIndex: 2,
    explanationAr: 'مساحة المستطيل = الطول × العرض = ٨ × ٥ = ٤٠ م²',
    tags: ['geometry', 'area'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '10-12', skillArea: 'quantitative', subSkill: 'percentages',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'ما هو ٢٥٪ من العدد ٨٠؟',
    questionImageUrl: null,
    options: [{ text: '١٥' }, { text: '٢٠' }, { text: '٢٥' }, { text: '٣٠' }],
    correctOptionIndex: 1,
    explanationAr: '٢٥٪ من ٨٠ = ٨٠ × ٢٥ ÷ ١٠٠ = ٢٠',
    tags: ['percentages', 'operations'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '10-12', skillArea: 'quantitative', subSkill: 'ratios',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'إذا كانت النسبة ٤ : ٦ = ٦ : ؟، فما القيمة المجهولة؟',
    questionImageUrl: null,
    options: [{ text: '٧' }, { text: '٨' }, { text: '٩' }, { text: '١٠' }],
    correctOptionIndex: 2,
    explanationAr: '٤ × ؟ = ٦ × ٦ → ؟ = ٣٦ ÷ ٤ = ٩',
    tags: ['ratios', 'proportions'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '10-12', skillArea: 'quantitative', subSkill: 'statistics',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'ما متوسط الأعداد: ٣ ، ٧ ، ٨ ، ١٠ ، ١٢؟',
    questionImageUrl: null,
    options: [{ text: '٧' }, { text: '٨' }, { text: '٩' }, { text: '١٠' }],
    correctOptionIndex: 1,
    explanationAr: 'المجموع = ٤٠، المتوسط = ٤٠ ÷ ٥ = ٨',
    tags: ['average', 'statistics'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '10-12', skillArea: 'quantitative', subSkill: 'powers',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: '٢³ × ٢² = ؟',
    questionImageUrl: null,
    options: [{ text: '١٦' }, { text: '٣٢' }, { text: '٦٤' }, { text: '١٢٨' }],
    correctOptionIndex: 1,
    explanationAr: '٢³ × ٢² = ٢^(٣+٢) = ٢⁵ = ٣٢',
    tags: ['powers', 'exponents'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '10-12', skillArea: 'quantitative', subSkill: 'word_problems',
    difficulty: 'hard', questionType: 'text',
    questionTextAr: 'تسير سيارة بسرعة ٨٠ كم/ساعة لمدة ٣ ساعات. كم تقطع من مسافة؟',
    questionImageUrl: null,
    options: [{ text: '٢٠٠ كم' }, { text: '٢٢٠ كم' }, { text: '٢٤٠ كم' }, { text: '٢٦٠ كم' }],
    correctOptionIndex: 2,
    explanationAr: 'المسافة = السرعة × الزمن = ٨٠ × ٣ = ٢٤٠ كيلومتراً',
    tags: ['speed', 'word_problem'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '10-12', skillArea: 'quantitative', subSkill: 'algebra',
    difficulty: 'hard', questionType: 'text',
    questionTextAr: 'إذا كان ٣س - ٥ = ١٦، فما قيمة س؟',
    questionImageUrl: null,
    options: [{ text: '٥' }, { text: '٦' }, { text: '٧' }, { text: '٨' }],
    correctOptionIndex: 2,
    explanationAr: '٣س = ١٦ + ٥ = ٢١، إذن س = ٢١ ÷ ٣ = ٧',
    tags: ['algebra', 'linear_equations'], isActive: true,
  },

  // ==========================================
  // 10-12 سنة — لفظي (7 أسئلة)
  // ==========================================
  {
    id: crypto.randomUUID(),
    ageGroup: '10-12', skillArea: 'verbal', subSkill: 'antonyms',
    difficulty: 'easy', questionType: 'text',
    questionTextAr: 'ما مضاد كلمة "متفائل"؟',
    questionImageUrl: null,
    options: [{ text: 'محايد' }, { text: 'متشائم' }, { text: 'مبتهج' }, { text: 'حذر' }],
    correctOptionIndex: 1,
    explanationAr: 'مضاد متفائل هو متشائم',
    tags: ['antonyms', 'vocabulary'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '10-12', skillArea: 'verbal', subSkill: 'plurals',
    difficulty: 'easy', questionType: 'text',
    questionTextAr: 'ما جمع كلمة "مسألة"؟',
    questionImageUrl: null,
    options: [{ text: 'مسائل' }, { text: 'مساءل' }, { text: 'مسألات' }, { text: 'مسائلة' }],
    correctOptionIndex: 0,
    explanationAr: 'جمع مسألة هو مسائل',
    tags: ['plurals', 'grammar'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '10-12', skillArea: 'verbal', subSkill: 'analogies',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'القلم للكتابة كالسكين لـ ...',
    questionImageUrl: null,
    options: [{ text: 'اللعب' }, { text: 'القطع' }, { text: 'الطبخ' }, { text: 'الطعام' }],
    correctOptionIndex: 1,
    explanationAr: 'القلم أداة للكتابة، والسكين أداة للقطع',
    tags: ['analogies', 'tools'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '10-12', skillArea: 'verbal', subSkill: 'proverbs',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'أكمل المثل: "من جدَّ..."',
    questionImageUrl: null,
    options: [{ text: 'تعب' }, { text: 'وجد' }, { text: 'رجع' }, { text: 'أخطأ' }],
    correctOptionIndex: 1,
    explanationAr: '"من جدَّ وجد" — من اجتهد وسعى وجد ما يريد',
    tags: ['proverbs', 'culture'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '10-12', skillArea: 'verbal', subSkill: 'word_roots',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'ما جذر كلمة "اسْتِخْراج"؟',
    questionImageUrl: null,
    options: [{ text: 'خرج' }, { text: 'رجع' }, { text: 'جاء' }, { text: 'أخرج' }],
    correctOptionIndex: 0,
    explanationAr: 'اشتُقت "استخراج" من الجذر الثلاثي "خ ر ج"',
    tags: ['word_roots', 'morphology'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '10-12', skillArea: 'verbal', subSkill: 'synonyms',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'ما مرادف كلمة "الشُّح"؟',
    questionImageUrl: null,
    options: [{ text: 'الكرم' }, { text: 'البخل' }, { text: 'العطاء' }, { text: 'الجود' }],
    correctOptionIndex: 1,
    explanationAr: 'الشُّح يعني البخل وضيق النفس، وهو عكس الكرم',
    tags: ['synonyms', 'vocabulary'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '10-12', skillArea: 'verbal', subSkill: 'grammar',
    difficulty: 'hard', questionType: 'text',
    questionTextAr: 'في جملة "نجح المجتهدُ"، ما إعراب كلمة "المجتهد"؟',
    questionImageUrl: null,
    options: [{ text: 'مفعول به' }, { text: 'فاعل' }, { text: 'مبتدأ' }, { text: 'خبر' }],
    correctOptionIndex: 1,
    explanationAr: '"المجتهد" فاعل مرفوع، وعلامة رفعه الضمة الظاهرة على آخره',
    tags: ['grammar', 'syntax'], isActive: true,
  },

  // ==========================================
  // 10-12 سنة — منطقي (5 أسئلة)
  // ==========================================
  {
    id: crypto.randomUUID(),
    ageGroup: '10-12', skillArea: 'logical_patterns', subSkill: 'deductive_reasoning',
    difficulty: 'easy', questionType: 'text',
    questionTextAr: 'كل المديرين ذوو خبرة. فهد مدير. هل فهد ذو خبرة؟',
    questionImageUrl: null,
    options: [{ text: 'نعم' }, { text: 'لا' }, { text: 'ربما' }, { text: 'لا يمكن التحديد' }],
    correctOptionIndex: 0,
    explanationAr: 'قياس منطقي: كل المديرين ذوو خبرة + فهد مدير = فهد ذو خبرة',
    tags: ['deduction', 'syllogism'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '10-12', skillArea: 'logical_patterns', subSkill: 'number_sequences',
    difficulty: 'easy', questionType: 'text',
    questionTextAr: 'أكمل المتسلسلة: ٣ ، ٦ ، ١٢ ، ٢٤ ، __',
    questionImageUrl: null,
    options: [{ text: '٣٦' }, { text: '٤٢' }, { text: '٤٨' }, { text: '٥٠' }],
    correctOptionIndex: 2,
    explanationAr: 'كل رقم يُضاعَف: ٢٤ × ٢ = ٤٨',
    tags: ['geometric_sequence', 'doubling'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '10-12', skillArea: 'logical_patterns', subSkill: 'coding',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'إذا كانت A=١ وB=٢ وC=٣، فما قيمة الكلمة "CAB"؟',
    questionImageUrl: null,
    options: [{ text: '٣١٢' }, { text: '٣٢١' }, { text: '١٢٣' }, { text: '٢١٣' }],
    correctOptionIndex: 0,
    explanationAr: 'C=٣، A=١، B=٢ → CAB = ٣١٢',
    tags: ['coding', 'cipher'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '10-12', skillArea: 'logical_patterns', subSkill: 'word_problems',
    difficulty: 'hard', questionType: 'text',
    questionTextAr: 'لارا أكبر من منى بـ ٣ سنوات. منى ضعف عمر هناء. هناء عمرها ٥ سنوات. كم عمر لارا؟',
    questionImageUrl: null,
    options: [{ text: '١٠' }, { text: '١٢' }, { text: '١٣' }, { text: '١٥' }],
    correctOptionIndex: 2,
    explanationAr: 'هناء=٥، منى=٥×٢=١٠، لارا=١٠+٣=١٣',
    tags: ['age_problems', 'multi_step'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '10-12', skillArea: 'logical_patterns', subSkill: 'spatial',
    difficulty: 'hard', questionType: 'text',
    questionTextAr: 'ورقة مربعة طُويت من المنتصف مرتين، ثم قُصَّت دائرة في منتصفها. كم عدد الثقوب عند فتح الورقة؟',
    questionImageUrl: null,
    options: [{ text: '١' }, { text: '٢' }, { text: '٤' }, { text: '٨' }],
    correctOptionIndex: 2,
    explanationAr: 'كل طية تضاعف عدد الثقوب. بعد طيتين تكون ٤ طبقات، فالقص ينتج ٤ ثقوب',
    tags: ['spatial', 'folding'], isActive: true,
  },

  // ==========================================
  // 4-5 سنوات — صوتي (5 أسئلة)
  // ==========================================
  {
    id: crypto.randomUUID(),
    ageGroup: '4-5', skillArea: 'quantitative', subSkill: 'counting',
    difficulty: 'easy', questionType: 'audio',
    questionTextAr: 'كم تفاحة لدى سارة: تفاحة وتفاحة وتفاحتان؟',
    questionImageUrl: null,
    options: [{ text: '٢' }, { text: '٣' }, { text: '٤' }, { text: '٥' }],
    correctOptionIndex: 2,
    explanationAr: '١ + ١ + ٢ = ٤ تفاحات',
    tags: ['counting', 'audio'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '4-5', skillArea: 'quantitative', subSkill: 'comparison',
    difficulty: 'easy', questionType: 'audio',
    questionTextAr: 'الفيل حيوان كبير جداً والنملة حيوان صغير جداً. أيهما أكبر؟',
    questionImageUrl: null,
    options: [{ text: '🐘' }, { text: '🐜' }, { text: '🐱' }, { text: '🐟' }],
    correctOptionIndex: 0,
    explanationAr: 'الفيل هو أكبر الأربعة بكثير',
    tags: ['size', 'comparison', 'audio'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '4-5', skillArea: 'verbal', subSkill: 'colors',
    difficulty: 'easy', questionType: 'audio',
    questionTextAr: 'السماء لونها أزرق وأوراق الشجر لونها أخضر. ما لون السماء؟',
    questionImageUrl: null,
    options: [{ text: '🟡' }, { text: '🔵' }, { text: '🔴' }, { text: '🟢' }],
    correctOptionIndex: 1,
    explanationAr: 'السماء لونها أزرق',
    tags: ['colors', 'audio'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '4-5', skillArea: 'logical_patterns', subSkill: 'shapes',
    difficulty: 'easy', questionType: 'audio',
    questionTextAr: 'أي شكل له أربعة أضلاع متساوية وأربعة أركان؟',
    questionImageUrl: null,
    options: [{ text: '⭕' }, { text: '🔺' }, { text: '⬛' }, { text: '🌟' }],
    correctOptionIndex: 2,
    explanationAr: 'المربع له أربعة أضلاع متساوية وأربعة أركان',
    tags: ['shapes', 'audio'], isActive: true,
  },
  {
    id: crypto.randomUUID(),
    ageGroup: '4-5', skillArea: 'quantitative', subSkill: 'number_order',
    difficulty: 'easy', questionType: 'audio',
    questionTextAr: 'ما الرقم الذي يأتي بعد الرقم أربعة؟',
    questionImageUrl: null,
    options: [{ text: '٣' }, { text: '٤' }, { text: '٥' }, { text: '٦' }],
    correctOptionIndex: 2,
    explanationAr: 'بعد الرقم ٤ يأتي الرقم ٥',
    tags: ['number_order', 'audio'], isActive: true,
  },
];

async function main() {
  const db = getDb();
  console.log(`⏳ إضافة ${newQuestions.length} سؤال جديد...`);
  let added = 0;
  for (const q of newQuestions) {
    await db.insert(questions).values(q);
    added++;
    process.stdout.write(`\r✅ ${added}/${newQuestions.length}`);
  }
  console.log(`\n🎉 تم بنجاح إضافة ${added} سؤال.`);
  process.exit(0);
}

main().catch(e => { console.error(e); process.exit(1); });
