import { createClient } from '@libsql/client';
import { drizzle } from 'drizzle-orm/libsql';
import { questions } from './schema';

const questionData = [
  // ═══════════════════════════════════════════════
  // عمر 4-5 — كمي — سهل
  // ═══════════════════════════════════════════════
  { ageGroup:'4-5', skillArea:'quantitative', subSkill:'العد', difficulty:'easy', questionType:'text', questionTextAr:'كم عدد الأصابع في يد واحدة؟', questionImageUrl:null, options:[{text:'٣'},{text:'٤'},{text:'٥'},{text:'٦'}], correctOptionIndex:2, explanationAr:'يد الإنسان فيها ٥ أصابع: الإبهام، السبابة، الوسطى، البنصر، والخنصر.', tags:[] },
  { ageGroup:'4-5', skillArea:'quantitative', subSkill:'العد', difficulty:'easy', questionType:'text', questionTextAr:'عُدّ: 🐱🐱🐱 — كم قطة؟', questionImageUrl:null, options:[{text:'١'},{text:'٢'},{text:'٣'},{text:'٤'}], correctOptionIndex:2, explanationAr:'نعد القطط: واحدة، اثنتان، ثلاثة. إذن عدد القطط هو ٣.', tags:[] },
  { ageGroup:'4-5', skillArea:'quantitative', subSkill:'العد', difficulty:'easy', questionType:'text', questionTextAr:'عُدّ: ⭐⭐ — كم نجمة؟', questionImageUrl:null, options:[{text:'١'},{text:'٢'},{text:'٣'},{text:'٤'}], correctOptionIndex:1, explanationAr:'نعد النجوم: واحدة، اثنتان. إذن عدد النجوم هو ٢.', tags:[] },
  { ageGroup:'4-5', skillArea:'quantitative', subSkill:'المقارنة', difficulty:'easy', questionType:'text', questionTextAr:'أيهما أكبر: ١ أم ٤؟', questionImageUrl:null, options:[{text:'١'},{text:'٤'},{text:'متساويان'},{text:'لا أعرف'}], correctOptionIndex:1, explanationAr:'الرقم ٤ أكبر من الرقم ١. كلما عددنا أكثر كلما كان العدد أكبر.', tags:[] },
  { ageGroup:'4-5', skillArea:'quantitative', subSkill:'الأشكال', difficulty:'easy', questionType:'text', questionTextAr:'أي شكل له ٣ أضلاع؟', questionImageUrl:null, options:[{text:'مربع'},{text:'دائرة'},{text:'مثلث'},{text:'مستطيل'}], correctOptionIndex:2, explanationAr:'المثلث له ٣ أضلاع وثلاثة زوايا. المربع له ٤ أضلاع، والدائرة ليس لها أضلاع.', tags:[] },
  { ageGroup:'4-5', skillArea:'quantitative', subSkill:'الأشكال', difficulty:'easy', questionType:'text', questionTextAr:'أي شكل مستدير؟', questionImageUrl:null, options:[{text:'مثلث'},{text:'مربع'},{text:'دائرة'},{text:'مستطيل'}], correctOptionIndex:2, explanationAr:'الدائرة هي الشكل المستدير الذي ليس له زوايا ولا أضلاع مستقيمة.', tags:[] },
  { ageGroup:'4-5', skillArea:'quantitative', subSkill:'العد', difficulty:'easy', questionType:'text', questionTextAr:'ما الرقم الذي يأتي بعد ٢؟', questionImageUrl:null, options:[{text:'١'},{text:'٣'},{text:'٤'},{text:'٥'}], correctOptionIndex:1, explanationAr:'عند العد بالترتيب: ١، ٢، ٣... الرقم الذي يأتي بعد ٢ هو ٣.', tags:[] },
  { ageGroup:'4-5', skillArea:'quantitative', subSkill:'المقارنة', difficulty:'easy', questionType:'text', questionTextAr:'عُدّ: 🍎🍎🍎🍎 — كم تفاحة؟', questionImageUrl:null, options:[{text:'٢'},{text:'٣'},{text:'٤'},{text:'٥'}], correctOptionIndex:2, explanationAr:'نعد التفاحات: واحدة، اثنتان، ثلاثة، أربعة. عدد التفاحات هو ٤.', tags:[] },
  { ageGroup:'4-5', skillArea:'quantitative', subSkill:'العد', difficulty:'easy', questionType:'text', questionTextAr:'ما الرقم الذي يأتي قبل ٥؟', questionImageUrl:null, options:[{text:'٣'},{text:'٤'},{text:'٦'},{text:'٢'}], correctOptionIndex:1, explanationAr:'عند العد: ...٣، ٤، ٥. الرقم الذي يأتي قبل ٥ هو ٤.', tags:[] },
  { ageGroup:'4-5', skillArea:'quantitative', subSkill:'المقارنة', difficulty:'easy', questionType:'text', questionTextAr:'أيهما أقل: ٥ أم ٢؟', questionImageUrl:null, options:[{text:'٥'},{text:'٢'},{text:'متساويان'},{text:'لا أعرف'}], correctOptionIndex:1, explanationAr:'الرقم ٢ أقل من الرقم ٥. الأرقام الصغيرة تأتي في بداية التسلسل.', tags:[] },

  // عمر 4-5 — كمي — متوسط
  { ageGroup:'4-5', skillArea:'quantitative', subSkill:'العد', difficulty:'medium', questionType:'text', questionTextAr:'عُدّ: 🌟🌟🌟🌟🌟🌟🌟 — كم نجمة؟', questionImageUrl:null, options:[{text:'٥'},{text:'٦'},{text:'٧'},{text:'٨'}], correctOptionIndex:2, explanationAr:'نعد النجوم واحدة واحدة حتى نصل إلى ٧ نجوم.', tags:[] },
  { ageGroup:'4-5', skillArea:'quantitative', subSkill:'الترتيب', difficulty:'medium', questionType:'text', questionTextAr:'رتّب من الأصغر للأكبر: ٣، ١، ٢', questionImageUrl:null, options:[{text:'١ ، ٢ ، ٣'},{text:'٣ ، ٢ ، ١'},{text:'٢ ، ١ ، ٣'},{text:'١ ، ٣ ، ٢'}], correctOptionIndex:0, explanationAr:'الترتيب من الأصغر للأكبر يعني أن نبدأ بأصغر رقم: ١ ثم ٢ ثم ٣.', tags:[] },
  { ageGroup:'4-5', skillArea:'quantitative', subSkill:'المقارنة', difficulty:'medium', questionType:'text', questionTextAr:'أي مجموعة فيها أكثر: 🐶🐶🐶 أم 🐶🐶🐶🐶🐶؟', questionImageUrl:null, options:[{text:'الأولى'},{text:'الثانية'},{text:'متساويتان'},{text:'لا أعرف'}], correctOptionIndex:1, explanationAr:'المجموعة الأولى فيها ٣ كلاب والثانية ٥ كلاب، لذا المجموعة الثانية أكثر.', tags:[] },
  { ageGroup:'4-5', skillArea:'quantitative', subSkill:'العد', difficulty:'medium', questionType:'text', questionTextAr:'ما الرقم الذي يأتي بعد ٧؟', questionImageUrl:null, options:[{text:'٦'},{text:'٨'},{text:'٩'},{text:'١٠'}], correctOptionIndex:1, explanationAr:'عند العد: ٦، ٧، ٨... الرقم بعد ٧ هو ٨.', tags:[] },
  { ageGroup:'4-5', skillArea:'quantitative', subSkill:'الأشكال', difficulty:'medium', questionType:'text', questionTextAr:'أي شكل له ٤ أضلاع متساوية؟', questionImageUrl:null, options:[{text:'مثلث'},{text:'مربع'},{text:'دائرة'},{text:'مستطيل'}], correctOptionIndex:1, explanationAr:'المربع له ٤ أضلاع كلها متساوية في الطول. المستطيل له ٤ أضلاع لكن ضلعان أطول من الآخرين.', tags:[] },
  { ageGroup:'4-5', skillArea:'quantitative', subSkill:'الترتيب', difficulty:'medium', questionType:'text', questionTextAr:'من هو الأول في الصف: 🔴🔵🟢؟', questionImageUrl:null, options:[{text:'الأحمر'},{text:'الأزرق'},{text:'الأخضر'},{text:'لا أعرف'}], correctOptionIndex:0, explanationAr:'الأول في الصف هو الشكل الذي يأتي في المقدمة، وهو الدائرة الحمراء 🔴.', tags:[] },
  { ageGroup:'4-5', skillArea:'quantitative', subSkill:'العد', difficulty:'medium', questionType:'text', questionTextAr:'ما مجموع ⭐ + ⭐⭐ = ؟', questionImageUrl:null, options:[{text:'٢'},{text:'٣'},{text:'٤'},{text:'٥'}], correctOptionIndex:1, explanationAr:'نجمة واحدة زائد نجمتان = ٣ نجوم. هذا هو الجمع البسيط.', tags:[] },
  { ageGroup:'4-5', skillArea:'quantitative', subSkill:'المقارنة', difficulty:'medium', questionType:'text', questionTextAr:'أيهما أكبر: ٩ أم ٦؟', questionImageUrl:null, options:[{text:'٦'},{text:'٩'},{text:'متساويان'},{text:'لا أعرف'}], correctOptionIndex:1, explanationAr:'الرقم ٩ أكبر من ٦ لأنه يأتي بعده في سلسلة الأعداد.', tags:[] },
  { ageGroup:'4-5', skillArea:'quantitative', subSkill:'العد', difficulty:'medium', questionType:'text', questionTextAr:'كم رجلاً للكرسي؟', questionImageUrl:null, options:[{text:'٢'},{text:'٣'},{text:'٤'},{text:'٥'}], correctOptionIndex:2, explanationAr:'معظم الكراسي لها ٤ أرجل للاتزان والاستقرار.', tags:[] },
  { ageGroup:'4-5', skillArea:'quantitative', subSkill:'الأنماط', difficulty:'medium', questionType:'text', questionTextAr:'ما التالي: 🔴🔵🔴🔵...؟', questionImageUrl:null, options:[{text:'🔴'},{text:'🔵'},{text:'🟢'},{text:'🟡'}], correctOptionIndex:0, explanationAr:'النمط يتكرر: أحمر ثم أزرق. بعد الأزرق يأتي الأحمر.', tags:[] },

  // عمر 4-5 — كمي — صعب
  { ageGroup:'4-5', skillArea:'quantitative', subSkill:'الجمع البسيط', difficulty:'hard', questionType:'text', questionTextAr:'٢ + ٢ = ؟', questionImageUrl:null, options:[{text:'٣'},{text:'٤'},{text:'٥'},{text:'٦'}], correctOptionIndex:1, explanationAr:'اثنان زائد اثنان = أربعة. يمكنك العد على أصابعك: ١، ٢ ثم ٣، ٤.', tags:[] },
  { ageGroup:'4-5', skillArea:'quantitative', subSkill:'الجمع البسيط', difficulty:'hard', questionType:'text', questionTextAr:'عندي ٣ حلوى وأعطاني أخي ١ — كم أصبح عندي؟', questionImageUrl:null, options:[{text:'٣'},{text:'٤'},{text:'٥'},{text:'٢'}], correctOptionIndex:1, explanationAr:'٣ حلوى + ١ حلوى = ٤ حلوى. جمعنا العددين.', tags:[] },
  { ageGroup:'4-5', skillArea:'quantitative', subSkill:'الطرح البسيط', difficulty:'hard', questionType:'text', questionTextAr:'عندي ٥ بالونات، طارت واحدة — كم بقي؟', questionImageUrl:null, options:[{text:'٣'},{text:'٤'},{text:'٥'},{text:'٦'}], correctOptionIndex:1, explanationAr:'٥ - ١ = ٤. عندما يطير بالون واحد يبقى ٤ بالونات.', tags:[] },
  { ageGroup:'4-5', skillArea:'quantitative', subSkill:'الأنماط', difficulty:'hard', questionType:'text', questionTextAr:'ما التالي: ١، ٢، ٣، ...؟', questionImageUrl:null, options:[{text:'٣'},{text:'٤'},{text:'٥'},{text:'٦'}], correctOptionIndex:1, explanationAr:'النمط هو العد بالترتيب. بعد ١، ٢، ٣ يأتي ٤.', tags:[] },
  { ageGroup:'4-5', skillArea:'quantitative', subSkill:'الطرح البسيط', difficulty:'hard', questionType:'text', questionTextAr:'٤ - ٢ = ؟', questionImageUrl:null, options:[{text:'١'},{text:'٢'},{text:'٣'},{text:'٤'}], correctOptionIndex:1, explanationAr:'أربعة ناقص اثنين = اثنان. إذا أخذنا ٢ من ٤ يبقى ٢.', tags:[] },
  { ageGroup:'4-5', skillArea:'quantitative', subSkill:'الأنماط', difficulty:'hard', questionType:'text', questionTextAr:'ما التالي: 🔴🔴🔵🔴🔴...؟', questionImageUrl:null, options:[{text:'🔴'},{text:'🔵'},{text:'🟢'},{text:'🟡'}], correctOptionIndex:1, explanationAr:'النمط هو: أحمر أحمر أزرق. بعد أحمر أحمر يأتي الأزرق.', tags:[] },
  { ageGroup:'4-5', skillArea:'quantitative', subSkill:'الجمع البسيط', difficulty:'hard', questionType:'text', questionTextAr:'١ + ١ + ١ = ؟', questionImageUrl:null, options:[{text:'١'},{text:'٢'},{text:'٣'},{text:'٤'}], correctOptionIndex:2, explanationAr:'واحد زائد واحد زائد واحد = ثلاثة. نجمع الأعداد معاً.', tags:[] },
  { ageGroup:'4-5', skillArea:'quantitative', subSkill:'المقارنة', difficulty:'hard', questionType:'text', questionTextAr:'رتّب من الأكبر للأصغر: ٥، ٢، ٨', questionImageUrl:null, options:[{text:'٨ ، ٥ ، ٢'},{text:'٢ ، ٥ ، ٨'},{text:'٥ ، ٢ ، ٨'},{text:'٨ ، ٢ ، ٥'}], correctOptionIndex:0, explanationAr:'الترتيب من الأكبر للأصغر: ٨ أكبر رقم، ثم ٥، ثم ٢ أصغر رقم.', tags:[] },
  { ageGroup:'4-5', skillArea:'quantitative', subSkill:'الطرح البسيط', difficulty:'hard', questionType:'text', questionTextAr:'عندي ٣ تفاحات وأكلت تفاحة — كم بقي؟', questionImageUrl:null, options:[{text:'١'},{text:'٢'},{text:'٣'},{text:'٤'}], correctOptionIndex:1, explanationAr:'٣ - ١ = ٢. عندما نأكل تفاحة من ثلاث يبقى تفاحتان.', tags:[] },
  { ageGroup:'4-5', skillArea:'quantitative', subSkill:'الأشكال', difficulty:'hard', questionType:'text', questionTextAr:'كم ضلعاً للمستطيل؟', questionImageUrl:null, options:[{text:'٢'},{text:'٣'},{text:'٤'},{text:'٥'}], correctOptionIndex:2, explanationAr:'المستطيل له ٤ أضلاع: ضلعان طويلان وضلعان قصيران. مثله مثل المربع لكن بأطوال مختلفة.', tags:[] },

  // ═══════════════════════════════════════════════
  // عمر 4-5 — لفظي — سهل
  // ═══════════════════════════════════════════════
  { ageGroup:'4-5', skillArea:'verbal', subSkill:'الألوان', difficulty:'easy', questionType:'text', questionTextAr:'ما لون السماء في النهار؟', questionImageUrl:null, options:[{text:'أحمر'},{text:'أزرق'},{text:'أخضر'},{text:'أصفر'}], correctOptionIndex:1, explanationAr:'السماء في النهار تكون زرقاء. هذا اللون الجميل يسمى الأزرق السماوي.', tags:[] },
  { ageGroup:'4-5', skillArea:'verbal', subSkill:'الألوان', difficulty:'easy', questionType:'text', questionTextAr:'ما لون العشب؟', questionImageUrl:null, options:[{text:'أصفر'},{text:'أزرق'},{text:'أخضر'},{text:'أحمر'}], correctOptionIndex:2, explanationAr:'العشب والنباتات لونها أخضر لأنها تحتوي على مادة الكلوروفيل.', tags:[] },
  { ageGroup:'4-5', skillArea:'verbal', subSkill:'الحيوانات', difficulty:'easy', questionType:'text', questionTextAr:'أي حيوان يقول "مياو"؟', questionImageUrl:null, options:[{text:'كلب'},{text:'قطة'},{text:'بقرة'},{text:'حصان'}], correctOptionIndex:1, explanationAr:'القطة هي التي تقول "مياو" أو "مو". الكلب يقول "هاو هاو" والبقرة تقول "خوار".', tags:[] },
  { ageGroup:'4-5', skillArea:'verbal', subSkill:'الحيوانات', difficulty:'easy', questionType:'text', questionTextAr:'أي حيوان يعيش في البحر؟', questionImageUrl:null, options:[{text:'أسد'},{text:'سمكة'},{text:'فيل'},{text:'أرنب'}], correctOptionIndex:1, explanationAr:'السمكة تعيش في الماء — في البحر أو النهر. باقي الحيوانات المذكورة تعيش على اليابسة.', tags:[] },
  { ageGroup:'4-5', skillArea:'verbal', subSkill:'الألوان', difficulty:'easy', questionType:'text', questionTextAr:'ما لون الشمس؟', questionImageUrl:null, options:[{text:'أزرق'},{text:'أخضر'},{text:'أصفر'},{text:'بنفسجي'}], correctOptionIndex:2, explanationAr:'الشمس تبدو صفراء أو برتقالية. الضوء الأصفر الدافئ للشمس يضيء يومنا.', tags:[] },
  { ageGroup:'4-5', skillArea:'verbal', subSkill:'الحيوانات', difficulty:'easy', questionType:'text', questionTextAr:'أي حيوان له خرطوم طويل؟', questionImageUrl:null, options:[{text:'أسد'},{text:'زرافة'},{text:'فيل'},{text:'نمر'}], correctOptionIndex:2, explanationAr:'الفيل له خرطوم طويل يستخدمه للشرب والإمساك بالأشياء وتناول الطعام.', tags:[] },
  { ageGroup:'4-5', skillArea:'verbal', subSkill:'الأشياء اليومية', difficulty:'easy', questionType:'text', questionTextAr:'ماذا نستخدم لأكل الطعام؟', questionImageUrl:null, options:[{text:'قلم'},{text:'ملعقة'},{text:'مقص'},{text:'مسطرة'}], correctOptionIndex:1, explanationAr:'نستخدم الملعقة لأكل الطعام السائل كالشوربة. كما نستخدم الشوكة والسكين.', tags:[] },
  { ageGroup:'4-5', skillArea:'verbal', subSkill:'الأشياء اليومية', difficulty:'easy', questionType:'text', questionTextAr:'ماذا نلبس في قدمينا؟', questionImageUrl:null, options:[{text:'قبعة'},{text:'قفاز'},{text:'حذاء'},{text:'نظارة'}], correctOptionIndex:2, explanationAr:'نلبس الحذاء في قدمينا لحمايتهما. الحذاء له أنواع كثيرة: رياضي، رسمي، صندل.', tags:[] },
  { ageGroup:'4-5', skillArea:'verbal', subSkill:'الألوان', difficulty:'easy', questionType:'text', questionTextAr:'ما لون الموزة؟', questionImageUrl:null, options:[{text:'أحمر'},{text:'أصفر'},{text:'أزرق'},{text:'أخضر'}], correctOptionIndex:1, explanationAr:'الموزة الناضجة لونها أصفر. عندما تكون غير ناضجة تكون خضراء.', tags:[] },
  { ageGroup:'4-5', skillArea:'verbal', subSkill:'الحيوانات', difficulty:'easy', questionType:'text', questionTextAr:'أي حيوان له رقبة طويلة جداً؟', questionImageUrl:null, options:[{text:'فيل'},{text:'أسد'},{text:'زرافة'},{text:'دب'}], correctOptionIndex:2, explanationAr:'الزرافة لها رقبة طويلة جداً تساعدها على الوصول لأوراق الأشجار العالية.', tags:[] },

  // عمر 4-5 — لفظي — متوسط
  { ageGroup:'4-5', skillArea:'verbal', subSkill:'المتضادات', difficulty:'medium', questionType:'text', questionTextAr:'ما عكس كلمة "كبير"؟', questionImageUrl:null, options:[{text:'طويل'},{text:'صغير'},{text:'ثقيل'},{text:'سريع'}], correctOptionIndex:1, explanationAr:'عكس "كبير" هو "صغير". الكلمات المتعاكسة تحمل معنى معاكساً تماماً.', tags:[] },
  { ageGroup:'4-5', skillArea:'verbal', subSkill:'المتضادات', difficulty:'medium', questionType:'text', questionTextAr:'ما عكس كلمة "بارد"؟', questionImageUrl:null, options:[{text:'جاف'},{text:'ندي'},{text:'ساخن'},{text:'رطب'}], correctOptionIndex:2, explanationAr:'عكس "بارد" هو "ساخن". الماء البارد يكون برودته واضحة، والساخن يمكن لمسه بحذر.', tags:[] },
  { ageGroup:'4-5', skillArea:'verbal', subSkill:'التصنيف', difficulty:'medium', questionType:'text', questionTextAr:'أيهما لا ينتمي للمجموعة: تفاحة، موزة، سيارة، برتقالة؟', questionImageUrl:null, options:[{text:'تفاحة'},{text:'موزة'},{text:'سيارة'},{text:'برتقالة'}], correctOptionIndex:2, explanationAr:'السيارة لا تنتمي للمجموعة لأن التفاحة والموزة والبرتقالة كلها فواكه، أما السيارة فهي وسيلة نقل.', tags:[] },
  { ageGroup:'4-5', skillArea:'verbal', subSkill:'التصنيف', difficulty:'medium', questionType:'text', questionTextAr:'أيهما لا ينتمي: كلب، قطة، أسد، سيارة؟', questionImageUrl:null, options:[{text:'كلب'},{text:'قطة'},{text:'أسد'},{text:'سيارة'}], correctOptionIndex:3, explanationAr:'الكلب والقطة والأسد كلها حيوانات، أما السيارة فهي آلة من صنع الإنسان.', tags:[] },
  { ageGroup:'4-5', skillArea:'verbal', subSkill:'المتضادات', difficulty:'medium', questionType:'text', questionTextAr:'ما عكس كلمة "طويل"؟', questionImageUrl:null, options:[{text:'ضخم'},{text:'نحيف'},{text:'قصير'},{text:'سميك'}], correctOptionIndex:2, explanationAr:'عكس "طويل" هو "قصير". الجبل طويل، والسلم قد يكون قصيراً.', tags:[] },
  { ageGroup:'4-5', skillArea:'verbal', subSkill:'التصنيف', difficulty:'medium', questionType:'text', questionTextAr:'أيهما طعام: خبز، قلم، لبن، جبن؟', questionImageUrl:null, options:[{text:'خبز فقط'},{text:'قلم فقط'},{text:'خبز ولبن وجبن'},{text:'كلها'}], correctOptionIndex:2, explanationAr:'الخبز واللبن والجبن كلها أطعمة نأكلها. القلم أداة للكتابة وليس طعاماً.', tags:[] },
  { ageGroup:'4-5', skillArea:'verbal', subSkill:'المتضادات', difficulty:'medium', questionType:'text', questionTextAr:'ما عكس كلمة "ليل"؟', questionImageUrl:null, options:[{text:'مساء'},{text:'نهار'},{text:'غروب'},{text:'شروق'}], correctOptionIndex:1, explanationAr:'عكس "ليل" هو "نهار". في الليل تظهر النجوم والقمر، وفي النهار تشرق الشمس.', tags:[] },
  { ageGroup:'4-5', skillArea:'verbal', subSkill:'التصنيف', difficulty:'medium', questionType:'text', questionTextAr:'ماذا نستخدم في المدرسة: كتاب، دفتر، قلم، أم سيف؟', questionImageUrl:null, options:[{text:'كتاب فقط'},{text:'كتاب ودفتر وقلم'},{text:'سيف فقط'},{text:'كلها'}], correctOptionIndex:1, explanationAr:'الكتاب والدفتر والقلم أدوات مدرسية نستخدمها للتعلم. السيف ليس أداة مدرسية.', tags:[] },
  { ageGroup:'4-5', skillArea:'verbal', subSkill:'المتضادات', difficulty:'medium', questionType:'text', questionTextAr:'ما عكس كلمة "فوق"؟', questionImageUrl:null, options:[{text:'جانب'},{text:'أمام'},{text:'تحت'},{text:'خلف'}], correctOptionIndex:2, explanationAr:'عكس "فوق" هو "تحت". الطائر يطير فوق، والسمكة تسبح تحت الماء.', tags:[] },
  { ageGroup:'4-5', skillArea:'verbal', subSkill:'المتضادات', difficulty:'medium', questionType:'text', questionTextAr:'ما عكس كلمة "سريع"؟', questionImageUrl:null, options:[{text:'قوي'},{text:'بطيء'},{text:'ذكي'},{text:'كبير'}], correctOptionIndex:1, explanationAr:'عكس "سريع" هو "بطيء". الأرنب سريع، والسلحفاة بطيئة.', tags:[] },

  // عمر 4-5 — لفظي — صعب
  { ageGroup:'4-5', skillArea:'verbal', subSkill:'إكمال الجملة', difficulty:'hard', questionType:'text', questionTextAr:'أكمل: "نشرب الماء لأننا ..."', questionImageUrl:null, options:[{text:'نريد النوم'},{text:'عطشانون'},{text:'نريد اللعب'},{text:'نريد الأكل'}], correctOptionIndex:1, explanationAr:'نشرب الماء لأننا عطشانون. الماء ضروري لحياة الإنسان ويجب أن نشربه كل يوم.', tags:[] },
  { ageGroup:'4-5', skillArea:'verbal', subSkill:'إكمال الجملة', difficulty:'hard', questionType:'text', questionTextAr:'أكمل: "نلبس المعطف عندما يكون الجو ..."', questionImageUrl:null, options:[{text:'حاراً'},{еtext:'جميلاً'},{text:'بارداً'},{text:'ممطراً'}], correctOptionIndex:2, explanationAr:'نلبس المعطف عندما يكون الجو بارداً لنحمي أجسامنا من البرد.', tags:[] },
  { ageGroup:'4-5', skillArea:'verbal', subSkill:'الفهم', difficulty:'hard', questionType:'text', questionTextAr:'ما الذي يطير في السماء: طائر، سمكة، كلب، قطة؟', questionImageUrl:null, options:[{text:'سمكة'},{text:'طائر'},{text:'كلب'},{text:'قطة'}], correctOptionIndex:1, explanationAr:'الطائر هو الذي يطير في السماء بأجنحته. باقي الحيوانات المذكورة لا تطير.', tags:[] },
  { ageGroup:'4-5', skillArea:'verbal', subSkill:'التصنيف المتقدم', difficulty:'hard', questionType:'text', questionTextAr:'أيهما يسبح في الماء: حوت، فيل، أسد، نسر؟', questionImageUrl:null, options:[{text:'فيل'},{text:'أسد'},{text:'حوت'},{text:'نسر'}], correctOptionIndex:2, explanationAr:'الحوت هو الكائن الذي يعيش ويسبح في الماء. الفيل والأسد حيوانات برية والنسر يطير.', tags:[] },
  { ageGroup:'4-5', skillArea:'verbal', subSkill:'إكمال الجملة', difficulty:'hard', questionType:'text', questionTextAr:'أكمل: "نذهب إلى المستشفى عندما نكون ..."', questionImageUrl:null, options:[{text:'جائعين'},{text:'مرضى'},{text:'نائمين'},{text:'فرحين'}], correctOptionIndex:1, explanationAr:'نذهب إلى المستشفى عندما نكون مرضى لنرى الطبيب الذي يساعدنا على الشفاء.', tags:[] },
  { ageGroup:'4-5', skillArea:'verbal', subSkill:'الفهم', difficulty:'hard', questionType:'text', questionTextAr:'ما الذي يعطينا الضوء في الليل في المنزل؟', questionImageUrl:null, options:[{text:'الشمس'},{text:'القمر'},{text:'المصباح'},{text:'النجوم'}], correctOptionIndex:2, explanationAr:'المصباح الكهربائي هو ما يعطينا الضوء في المنزل ليلاً. الشمس تضيء النهار خارج البيت.', tags:[] },
  { ageGroup:'4-5', skillArea:'verbal', subSkill:'التصنيف المتقدم', difficulty:'hard', questionType:'text', questionTextAr:'أي الأماكن التالية نذهب إليه للدراسة؟', questionImageUrl:null, options:[{text:'المستشفى'},{text:'السوق'},{text:'المدرسة'},{text:'الحديقة'}], correctOptionIndex:2, explanationAr:'نذهب إلى المدرسة للدراسة وتعلم القراءة والكتابة والحساب.', tags:[] },
  { ageGroup:'4-5', skillArea:'verbal', subSkill:'إكمال الجملة', difficulty:'hard', questionType:'text', questionTextAr:'أكمل: "الأسد يعيش في ..."', questionImageUrl:null, options:[{text:'البحر'},{text:'الغابة'},{text:'المنزل'},{text:'المدرسة'}], correctOptionIndex:1, explanationAr:'الأسد يعيش في الغابة أو السافانا. يصطاد ويعيش مع أسرته في بيئته الطبيعية.', tags:[] },
  { ageGroup:'4-5', skillArea:'verbal', subSkill:'الفهم', difficulty:'hard', questionType:'text', questionTextAr:'ماذا تفعل النحلة؟', questionImageUrl:null, options:[{text:'تسبح في الماء'},{text:'تجمع العسل'},{text:'تحفر في الأرض'},{text:'تقطع الأشجار'}], correctOptionIndex:1, explanationAr:'النحلة تجمع رحيق الزهور وتصنع منه العسل اللذيذ. العسل مفيد جداً لصحتنا.', tags:[] },
  { ageGroup:'4-5', skillArea:'verbal', subSkill:'الفهم', difficulty:'hard', questionType:'text', questionTextAr:'ما الذي نستخدمه لكتابة الحروف؟', questionImageUrl:null, options:[{text:'ملعقة'},{text:'قلم'},{text:'كأس'},{text:'مفتاح'}], correctOptionIndex:1, explanationAr:'نستخدم القلم لكتابة الحروف والأرقام. القلم يمكن أن يكون رصاصاً أو حبراً.', tags:[] },

  // ═══════════════════════════════════════════════
  // عمر 4-5 — منطقي — سهل
  // ═══════════════════════════════════════════════
  { ageGroup:'4-5', skillArea:'logical_patterns', subSkill:'ما يختلف', difficulty:'easy', questionType:'text', questionTextAr:'أيهما مختلف: 🔴🔴🔴🔵؟', questionImageUrl:null, options:[{text:'الأولى'},{text:'الثانية'},{text:'الثالثة'},{text:'الرابعة'}], correctOptionIndex:3, explanationAr:'الأولى والثانية والثالثة حمراء، لكن الرابعة زرقاء — إذن هي المختلفة.', tags:[] },
  { ageGroup:'4-5', skillArea:'logical_patterns', subSkill:'الأنماط', difficulty:'easy', questionType:'text', questionTextAr:'ما التالي: ⭐🌙⭐🌙...؟', questionImageUrl:null, options:[{text:'⭐'},{text:'🌙'},{text:'☀️'},{text:'🌟'}], correctOptionIndex:0, explanationAr:'النمط يتكرر: نجمة ثم قمر. بعد القمر يأتي نجمة.', tags:[] },
  { ageGroup:'4-5', skillArea:'logical_patterns', subSkill:'التصنيف', difficulty:'easy', questionType:'text', questionTextAr:'أيهما ينتمي للفواكه: موزة، قلم، كتاب، حذاء؟', questionImageUrl:null, options:[{text:'قلم'},{text:'موزة'},{text:'كتاب'},{text:'حذاء'}], correctOptionIndex:1, explanationAr:'الموزة فاكهة نأكلها. القلم والكتاب أدوات مدرسية والحذاء ملبس.', tags:[] },
  { ageGroup:'4-5', skillArea:'logical_patterns', subSkill:'ما يختلف', difficulty:'easy', questionType:'text', questionTextAr:'أيهما مختلف: كلب، قطة، سمكة، طائر؟', questionImageUrl:null, options:[{text:'كلب'},{text:'قطة'},{text:'سمكة'},{text:'طائر'}], correctOptionIndex:2, explanationAr:'الكلب والقطة والطائر يعيشون على اليابسة، أما السمكة فتعيش في الماء — هي المختلفة.', tags:[] },
  { ageGroup:'4-5', skillArea:'logical_patterns', subSkill:'الأنماط', difficulty:'easy', questionType:'text', questionTextAr:'ما التالي: 🔴🔴🔴...؟', questionImageUrl:null, options:[{text:'🔴'},{text:'🔵'},{text:'🟢'},{text:'🟡'}], correctOptionIndex:0, explanationAr:'النمط هو تكرار الدائرة الحمراء باستمرار.', tags:[] },
  { ageGroup:'4-5', skillArea:'logical_patterns', subSkill:'التصنيف', difficulty:'easy', questionType:'text', questionTextAr:'أيهما وسيلة نقل: سيارة، كتاب، قلم، كرسي؟', questionImageUrl:null, options:[{text:'كتاب'},{text:'سيارة'},{text:'قلم'},{text:'كرسي'}], correctOptionIndex:1, explanationAr:'السيارة وسيلة نقل تحملنا من مكان لآخر. الكتاب والقلم أدوات تعلم والكرسي أثاث.', tags:[] },
  { ageGroup:'4-5', skillArea:'logical_patterns', subSkill:'ما يختلف', difficulty:'easy', questionType:'text', questionTextAr:'أيهما مختلف: مثلث، دائرة، مربع، قطة؟', questionImageUrl:null, options:[{text:'مثلث'},{text:'دائرة'},{text:'مربع'},{text:'قطة'}], correctOptionIndex:3, explanationAr:'المثلث والدائرة والمربع كلها أشكال هندسية، أما القطة فهي حيوان — هي المختلفة.', tags:[] },
  { ageGroup:'4-5', skillArea:'logical_patterns', subSkill:'الأنماط', difficulty:'easy', questionType:'text', questionTextAr:'ما التالي: ١، ٢، ١، ٢، ...؟', questionImageUrl:null, options:[{text:'٣'},{text:'١'},{text:'٤'},{text:'٢'}], correctOptionIndex:1, explanationAr:'النمط هو: ١ ثم ٢ ثم ١ ثم ٢... بعد الـ٢ يأتي الـ١.', tags:[] },
  { ageGroup:'4-5', skillArea:'logical_patterns', subSkill:'التصنيف', difficulty:'easy', questionType:'text', questionTextAr:'أيهما ينتمي للحيوانات البحرية: حوت، أسد، فيل، نمر؟', questionImageUrl:null, options:[{text:'أسد'},{text:'حوت'},{text:'فيل'},{text:'نمر'}], correctOptionIndex:1, explanationAr:'الحوت يعيش في البحر وهو من الحيوانات البحرية. الأسد والفيل والنمر حيوانات برية.', tags:[] },
  { ageGroup:'4-5', skillArea:'logical_patterns', subSkill:'ما يختلف', difficulty:'easy', questionType:'text', questionTextAr:'أيهما مختلف: تفاحة، برتقالة، كمبيوتر، موزة؟', questionImageUrl:null, options:[{text:'تفاحة'},{text:'برتقالة'},{text:'كمبيوتر'},{text:'موزة'}], correctOptionIndex:2, explanationAr:'التفاحة والبرتقالة والموزة فواكه، أما الكمبيوتر فجهاز إلكتروني — هو المختلف.', tags:[] },

  // عمر 4-5 — منطقي — متوسط
  { ageGroup:'4-5', skillArea:'logical_patterns', subSkill:'الأنماط', difficulty:'medium', questionType:'text', questionTextAr:'ما التالي: 🔴🔵🟢🔴🔵...؟', questionImageUrl:null, options:[{text:'🔴'},{text:'🔵'},{text:'🟢'},{text:'🟡'}], correctOptionIndex:2, explanationAr:'النمط هو: أحمر ثم أزرق ثم أخضر. بعد الأزرق يأتي الأخضر.', tags:[] },
  { ageGroup:'4-5', skillArea:'logical_patterns', subSkill:'الاستنتاج', difficulty:'medium', questionType:'text', questionTextAr:'كل طيور تطير. الببغاء طائر. هل يطير الببغاء؟', questionImageUrl:null, options:[{text:'نعم'},{text:'لا'},{text:'أحياناً'},{text:'لا أعرف'}], correctOptionIndex:0, explanationAr:'نعم! كل الطيور تطير، والببغاء طائر، إذن الببغاء يطير. هذا ما يسمى الاستنتاج المنطقي.', tags:[] },
  { ageGroup:'4-5', skillArea:'logical_patterns', subSkill:'التصنيف', difficulty:'medium', questionType:'text', questionTextAr:'رتّب من الأصغر للأكبر: قطة، أسد، فأر', questionImageUrl:null, options:[{text:'أسد، قطة، فأر'},{text:'فأر، قطة، أسد'},{text:'قطة، فأر، أسد'},{text:'فأر، أسد، قطة'}], correctOptionIndex:1, explanationAr:'الفأر أصغر حيوان، ثم القطة متوسطة الحجم، ثم الأسد أكبرها. الترتيب: فأر، قطة، أسد.', tags:[] },
  { ageGroup:'4-5', skillArea:'logical_patterns', subSkill:'الأنماط', difficulty:'medium', questionType:'text', questionTextAr:'ما التالي: ١، ٢، ٣، ٤، ...؟', questionImageUrl:null, options:[{text:'٤'},{text:'٥'},{text:'٦'},{text:'٧'}], correctOptionIndex:1, explanationAr:'النمط هو العد بالترتيب +١ في كل مرة. بعد ٤ يأتي ٥.', tags:[] },
  { ageGroup:'4-5', skillArea:'logical_patterns', subSkill:'ما يختلف', difficulty:'medium', questionType:'text', questionTextAr:'أيهما لا يسبح: سمكة، دلفين، حصان، حوت؟', questionImageUrl:null, options:[{text:'سمكة'},{text:'دلفين'},{text:'حصان'},{text:'حوت'}], correctOptionIndex:2, explanationAr:'الحصان حيوان بري يجري على الأرض. السمكة والدلفين والحوت تعيش في الماء وتسبح.', tags:[] },
  { ageGroup:'4-5', skillArea:'logical_patterns', subSkill:'الاستنتاج', difficulty:'medium', questionType:'text', questionTextAr:'سارة أكبر من علي، وعلي أكبر من محمد. من الأصغر؟', questionImageUrl:null, options:[{text:'سارة'},{text:'علي'},{text:'محمد'},{text:'كلهم متساوون'}], correctOptionIndex:2, explanationAr:'سارة > علي > محمد. إذن محمد هو الأصغر بينهم.', tags:[] },
  { ageGroup:'4-5', skillArea:'logical_patterns', subSkill:'الأنماط', difficulty:'medium', questionType:'text', questionTextAr:'ما التالي: ٢، ٢، ٢، ...؟', questionImageUrl:null, options:[{text:'١'},{text:'٢'},{text:'٣'},{text:'٤'}], correctOptionIndex:1, explanationAr:'النمط هو تكرار الرقم ٢ باستمرار. إذن التالي هو ٢.', tags:[] },
  { ageGroup:'4-5', skillArea:'logical_patterns', subSkill:'الاستنتاج', difficulty:'medium', questionType:'text', questionTextAr:'إذا كانت التفاحة حمراء والموزة صفراء، ما لون التفاحة؟', questionImageUrl:null, options:[{text:'أصفر'},{text:'أخضر'},{text:'أحمر'},{text:'أزرق'}], correctOptionIndex:2, explanationAr:'السؤال يخبرنا مباشرة أن التفاحة حمراء. هذا سؤال اختبار الفهم والانتباه.', tags:[] },
  { ageGroup:'4-5', skillArea:'logical_patterns', subSkill:'التصنيف', difficulty:'medium', questionType:'text', questionTextAr:'أيهما في مجموعة الحلويات: تفاحة، كيكة، جزر، خيار؟', questionImageUrl:null, options:[{text:'تفاحة'},{text:'جزر'},{text:'كيكة'},{text:'خيار'}], correctOptionIndex:2, explanationAr:'الكيكة حلوى. التفاحة والجزر والخيار خضروات وفواكه صحية.', tags:[] },
  { ageGroup:'4-5', skillArea:'logical_patterns', subSkill:'الأنماط', difficulty:'medium', questionType:'text', questionTextAr:'ما التالي: 🌞🌧️🌞🌧️...؟', questionImageUrl:null, options:[{text:'🌧️'},{text:'🌞'},{text:'⭐'},{text:'🌙'}], correctOptionIndex:1, explanationAr:'النمط يتكرر: شمس ثم مطر. بعد المطر تأتي الشمس.', tags:[] },

  // عمر 4-5 — منطقي — صعب
  { ageGroup:'4-5', skillArea:'logical_patterns', subSkill:'الاستنتاج', difficulty:'hard', questionType:'text', questionTextAr:'كل القطط تموء. ميمي قطة. ماذا تفعل ميمي؟', questionImageUrl:null, options:[{text:'تنبح'},{text:'تموء'},{text:'تصفر'},{text:'تزقزق'}], correctOptionIndex:1, explanationAr:'لأن كل القطط تموء وميمي قطة، إذن ميمي تموء. هذا استنتاج منطقي مبني على قاعدة عامة.', tags:[] },
  { ageGroup:'4-5', skillArea:'logical_patterns', subSkill:'الأنماط المتقدمة', difficulty:'hard', questionType:'text', questionTextAr:'ما التالي: ١، ٣، ٥، ...؟', questionImageUrl:null, options:[{text:'٦'},{text:'٧'},{text:'٨'},{text:'٩'}], correctOptionIndex:1, explanationAr:'النمط هو الأعداد الفردية: ١، ٣، ٥، ٧... نضيف ٢ في كل مرة.', tags:[] },
  { ageGroup:'4-5', skillArea:'logical_patterns', subSkill:'الاستنتاج', difficulty:'hard', questionType:'text', questionTextAr:'أحمد أطول من خالد، وخالد أطول من عمر. من الأقصر؟', questionImageUrl:null, options:[{text:'أحمد'},{text:'خالد'},{text:'عمر'},{text:'كلهم متساوون'}], correctOptionIndex:2, explanationAr:'أحمد > خالد > عمر. إذن عمر هو الأقصر بينهم.', tags:[] },
  { ageGroup:'4-5', skillArea:'logical_patterns', subSkill:'الأنماط المتقدمة', difficulty:'hard', questionType:'text', questionTextAr:'ما التالي: ٢، ٤، ٦، ...؟', questionImageUrl:null, options:[{text:'٧'},{text:'٨'},{text:'٩'},{text:'١٠'}], correctOptionIndex:1, explanationAr:'النمط هو الأعداد الزوجية: ٢، ٤، ٦، ٨... نضيف ٢ في كل مرة.', tags:[] },
  { ageGroup:'4-5', skillArea:'logical_patterns', subSkill:'الاستنتاج', difficulty:'hard', questionType:'text', questionTextAr:'إذا كان اليوم الثلاثاء، ما اليوم الذي قبله؟', questionImageUrl:null, options:[{text:'الأربعاء'},{text:'الاثنين'},{text:'الأحد'},{text:'الأحد'}], correctOptionIndex:1, explanationAr:'ترتيب الأسبوع: الأحد، الاثنين، الثلاثاء... اليوم الذي قبل الثلاثاء هو الاثنين.', tags:[] },
  { ageGroup:'4-5', skillArea:'logical_patterns', subSkill:'الأنماط المتقدمة', difficulty:'hard', questionType:'text', questionTextAr:'ما التالي: 🔴🔴🔵🔴🔴🔵...؟', questionImageUrl:null, options:[{text:'🔵'},{text:'🔴'},{text:'🟢'},{text:'🟡'}], correctOptionIndex:1, explanationAr:'النمط هو: أحمر، أحمر، أزرق. بعد الأزرق يأتي أحمر أحمر مرة أخرى.', tags:[] },
  { ageGroup:'4-5', skillArea:'logical_patterns', subSkill:'التفكير الإبداعي', difficulty:'hard', questionType:'text', questionTextAr:'لدي ٣ أقلام وأخي لديه ٥. من لديه أكثر بقلمين؟', questionImageUrl:null, options:[{text:'أنا'},{text:'أخي'},{text:'متساوون'},{text:'لا أعرف'}], correctOptionIndex:1, explanationAr:'أنا لدي ٣ وأخي ٥. الفرق = ٥ - ٣ = ٢. أخي لديه أكثر بقلمين.', tags:[] },
  { ageGroup:'4-5', skillArea:'logical_patterns', subSkill:'الاستنتاج', difficulty:'hard', questionType:'text', questionTextAr:'الثلج أبيض. أسقط الثلج. ما لون الأرض الآن؟', questionImageUrl:null, options:[{text:'أسود'},{text:'أبيض'},{text:'أخضر'},{text:'بني'}], correctOptionIndex:1, explanationAr:'الثلج أبيض. عندما يسقط الثلج ويغطي الأرض، تصبح الأرض بيضاء اللون.', tags:[] },
  { ageGroup:'4-5', skillArea:'logical_patterns', subSkill:'الأنماط المتقدمة', difficulty:'hard', questionType:'text', questionTextAr:'ما الرقم المفقود: ١، __, ٣، ٤؟', questionImageUrl:null, options:[{text:'١'},{text:'٢'},{text:'٥'},{text:'٦'}], correctOptionIndex:1, explanationAr:'السلسلة هي: ١، ٢، ٣، ٤. الرقم المفقود هو ٢.', tags:[] },
  { ageGroup:'4-5', skillArea:'logical_patterns', subSkill:'الاستنتاج', difficulty:'hard', questionType:'text', questionTextAr:'إذا نام الطفل مبكراً، سيستيقظ مبكراً. نام مبكراً. هل سيستيقظ مبكراً؟', questionImageUrl:null, options:[{text:'نعم'},{text:'لا'},{text:'ربما'},{text:'لا أعرف'}], correctOptionIndex:0, explanationAr:'نعم. لأن القاعدة تقول: النوم مبكراً يؤدي للاستيقاظ مبكراً، وقد نام مبكراً فعلاً.', tags:[] },

  // ═══════════════════════════════════════════════
  // عمر 6-9 — كمي — سهل
  // ═══════════════════════════════════════════════
  { ageGroup:'6-9', skillArea:'quantitative', subSkill:'الجمع', difficulty:'easy', questionType:'text', questionTextAr:'١٢ + ٧ = ؟', questionImageUrl:null, options:[{text:'١٧'},{text:'١٨'},{text:'١٩'},{text:'٢٠'}], correctOptionIndex:2, explanationAr:'١٢ + ٧ = ١٩. نجمع العدد ٧ مع العدد ١٢: ١٢، ١٣، ١٤، ١٥، ١٦، ١٧، ١٨، ١٩.', tags:[] },
  { ageGroup:'6-9', skillArea:'quantitative', subSkill:'الطرح', difficulty:'easy', questionType:'text', questionTextAr:'٢٠ - ٨ = ؟', questionImageUrl:null, options:[{text:'١٠'},{text:'١١'},{text:'١٢'},{text:'١٣'}], correctOptionIndex:2, explanationAr:'٢٠ - ٨ = ١٢. نطرح ٨ من ٢٠: ٢٠ - ١٠ = ١٠، ١٠ + ٢ = ١٢.', tags:[] },
  { ageGroup:'6-9', skillArea:'quantitative', subSkill:'الجمع', difficulty:'easy', questionType:'text', questionTextAr:'٢٥ + ١٠ = ؟', questionImageUrl:null, options:[{text:'٣٣'},{text:'٣٤'},{text:'٣٥'},{text:'٣٦'}], correctOptionIndex:2, explanationAr:'٢٥ + ١٠ = ٣٥. عند جمع ١٠ نزيد العشرات بمقدار واحد.', tags:[] },
  { ageGroup:'6-9', skillArea:'quantitative', subSkill:'الطرح', difficulty:'easy', questionType:'text', questionTextAr:'١٥ - ٥ = ؟', questionImageUrl:null, options:[{text:'٨'},{text:'٩'},{text:'١٠'},{text:'١١'}], correctOptionIndex:2, explanationAr:'١٥ - ٥ = ١٠. نطرح الآحاد من الآحاد: ٥ - ٥ = ٠، تبقى العشرة.', tags:[] },
  { ageGroup:'6-9', skillArea:'quantitative', subSkill:'الضرب', difficulty:'easy', questionType:'text', questionTextAr:'٢ × ٥ = ؟', questionImageUrl:null, options:[{text:'٨'},{text:'٩'},{text:'١٠'},{text:'١١'}], correctOptionIndex:2, explanationAr:'٢ × ٥ = ١٠. الضرب هو جمع متكرر: ٢ + ٢ + ٢ + ٢ + ٢ = ١٠.', tags:[] },
  { ageGroup:'6-9', skillArea:'quantitative', subSkill:'القسمة', difficulty:'easy', questionType:'text', questionTextAr:'١٠ ÷ ٢ = ؟', questionImageUrl:null, options:[{text:'٣'},{text:'٤'},{text:'٥'},{text:'٦'}], correctOptionIndex:2, explanationAr:'١٠ ÷ ٢ = ٥. القسمة تعني التوزيع المتساوي: ١٠ مقسمة على ٢ = ٥ لكل واحد.', tags:[] },
  { ageGroup:'6-9', skillArea:'quantitative', subSkill:'المسائل', difficulty:'easy', questionType:'text', questionTextAr:'اشترت أمل ٦ تفاحات وأكلت ٢. كم تبقى معها؟', questionImageUrl:null, options:[{text:'٢'},{text:'٣'},{text:'٤'},{text:'٥'}], correctOptionIndex:2, explanationAr:'٦ - ٢ = ٤. أمل لديها ٤ تفاحات متبقية.', tags:[] },
  { ageGroup:'6-9', skillArea:'quantitative', subSkill:'الجمع', difficulty:'easy', questionType:'text', questionTextAr:'٣٠ + ٢٠ = ؟', questionImageUrl:null, options:[{text:'٤٠'},{text:'٥٠'},{text:'٦٠'},{text:'٧٠'}], correctOptionIndex:1, explanationAr:'٣٠ + ٢٠ = ٥٠. نجمع العشرات: ٣ + ٢ = ٥، والنتيجة ٥٠.', tags:[] },
  { ageGroup:'6-9', skillArea:'quantitative', subSkill:'الضرب', difficulty:'easy', questionType:'text', questionTextAr:'٣ × ٣ = ؟', questionImageUrl:null, options:[{text:'٦'},{text:'٧'},{text:'٨'},{text:'٩'}], correctOptionIndex:3, explanationAr:'٣ × ٣ = ٩. ثلاثة مجموعات من ثلاثة: ٣ + ٣ + ٣ = ٩.', tags:[] },
  { ageGroup:'6-9', skillArea:'quantitative', subSkill:'المسائل', difficulty:'easy', questionType:'text', questionTextAr:'لدى سامي ١٠ ريالات، اشترى كتاباً بـ٦ ريالات. كم تبقى؟', questionImageUrl:null, options:[{text:'٢'},{text:'٣'},{text:'٤'},{text:'٥'}], correctOptionIndex:2, explanationAr:'١٠ - ٦ = ٤ ريالات. هذا سؤال طرح بسيط مع قصة.', tags:[] },

  // عمر 6-9 — كمي — متوسط
  { ageGroup:'6-9', skillArea:'quantitative', subSkill:'الضرب', difficulty:'medium', questionType:'text', questionTextAr:'٦ × ٧ = ؟', questionImageUrl:null, options:[{text:'٣٨'},{text:'٤٠'},{text:'٤٢'},{text:'٤٤'}], correctOptionIndex:2, explanationAr:'٦ × ٧ = ٤٢. من جدول ضرب الستة: ٦، ١٢، ١٨، ٢٤، ٣٠، ٣٦، ٤٢.', tags:[] },
  { ageGroup:'6-9', skillArea:'quantitative', subSkill:'الكسور', difficulty:'medium', questionType:'text', questionTextAr:'ما نصف الرقم ١٨؟', questionImageUrl:null, options:[{text:'٧'},{text:'٨'},{text:'٩'},{text:'١٠'}], correctOptionIndex:2, explanationAr:'نصف ١٨ = ١٨ ÷ ٢ = ٩. النصف يعني القسمة على اثنين.', tags:[] },
  { ageGroup:'6-9', skillArea:'quantitative', subSkill:'المسائل', difficulty:'medium', questionType:'text', questionTextAr:'اشترى فارس ٣ أقلام بسعر ٥ ريالات لكل قلم. كم دفع؟', questionImageUrl:null, options:[{text:'١٢'},{text:'١٥'},{text:'١٨'},{text:'٢٠'}], correctOptionIndex:1, explanationAr:'٣ × ٥ = ١٥ ريال. نضرب عدد الأقلام في سعر القلم الواحد.', tags:[] },
  { ageGroup:'6-9', skillArea:'quantitative', subSkill:'الكسور', difficulty:'medium', questionType:'text', questionTextAr:'ما ربع الرقم ٢٠؟', questionImageUrl:null, options:[{text:'٣'},{text:'٤'},{text:'٥'},{text:'٦'}], correctOptionIndex:2, explanationAr:'ربع ٢٠ = ٢٠ ÷ ٤ = ٥. الربع يعني القسمة على أربعة.', tags:[] },
  { ageGroup:'6-9', skillArea:'quantitative', subSkill:'الضرب', difficulty:'medium', questionType:'text', questionTextAr:'٨ × ٩ = ؟', questionImageUrl:null, options:[{text:'٦٢'},{text:'٧٠'},{text:'٧٢'},{text:'٧٤'}], correctOptionIndex:2, explanationAr:'٨ × ٩ = ٧٢. من جدول ضرب الثمانية: ...٦٤، ٧٢...', tags:[] },
  { ageGroup:'6-9', skillArea:'quantitative', subSkill:'المسائل', difficulty:'medium', questionType:'text', questionTextAr:'كيس فيه ٢٤ تمرة، تقاسمها ٤ أطفال بالتساوي. كم لكل طفل؟', questionImageUrl:null, options:[{text:'٤'},{text:'٥'},{text:'٦'},{text:'٧'}], correctOptionIndex:2, explanationAr:'٢٤ ÷ ٤ = ٦. نقسم عدد التمرات على عدد الأطفال.', tags:[] },
  { ageGroup:'6-9', skillArea:'quantitative', subSkill:'القسمة', difficulty:'medium', questionType:'text', questionTextAr:'٣٦ ÷ ٦ = ؟', questionImageUrl:null, options:[{text:'٤'},{text:'٥'},{text:'٦'},{text:'٧'}], correctOptionIndex:2, explanationAr:'٣٦ ÷ ٦ = ٦. لأن ٦ × ٦ = ٣٦.', tags:[] },
  { ageGroup:'6-9', skillArea:'quantitative', subSkill:'الكسور', difficulty:'medium', questionType:'text', questionTextAr:'ما ثلثا الرقم ١٢؟', questionImageUrl:null, options:[{text:'٦'},{text:'٧'},{text:'٨'},{text:'٩'}], correctOptionIndex:2, explanationAr:'ثلث ١٢ = ٤، وثلثان = ٨. نقسم على ٣ ونضرب في ٢.', tags:[] },
  { ageGroup:'6-9', skillArea:'quantitative', subSkill:'المسائل', difficulty:'medium', questionType:'text', questionTextAr:'في فصل ٣٠ طالباً، نصفهم بنات. كم عدد البنات؟', questionImageUrl:null, options:[{text:'١٠'},{text:'١٥'},{text:'٢٠'},{text:'٢٥'}], correctOptionIndex:1, explanationAr:'نصف ٣٠ = ٣٠ ÷ ٢ = ١٥. نصف الطلاب يعني قسمة العدد الكلي على ٢.', tags:[] },
  { ageGroup:'6-9', skillArea:'quantitative', subSkill:'الضرب', difficulty:'medium', questionType:'text', questionTextAr:'٤ × ٨ = ؟', questionImageUrl:null, options:[{text:'٢٩'},{text:'٣٠'},{text:'٣١'},{text:'٣٢'}], correctOptionIndex:3, explanationAr:'٤ × ٨ = ٣٢. من جدول ضرب الأربعة: ٤، ٨، ١٢، ١٦، ٢٠، ٢٤، ٢٨، ٣٢.', tags:[] },

  // عمر 6-9 — كمي — صعب
  { ageGroup:'6-9', skillArea:'quantitative', subSkill:'المسائل المركبة', difficulty:'hard', questionType:'text', questionTextAr:'اشترى أحمد ٥ كتب بـ٨ ريالات كل كتاب، ودفع ٥٠ ريالاً. كم باقيه؟', questionImageUrl:null, options:[{text:'٥'},{text:'١٠'},{text:'١٥'},{text:'٢٠'}], correctOptionIndex:1, explanationAr:'سعر الكتب = ٥ × ٨ = ٤٠ ريال. الباقي = ٥٠ - ٤٠ = ١٠ ريال.', tags:[] },
  { ageGroup:'6-9', skillArea:'quantitative', subSkill:'الأنماط الرقمية', difficulty:'hard', questionType:'text', questionTextAr:'ما الرقم المفقود: ٢، ٤، ٨، ١٦، __؟', questionImageUrl:null, options:[{text:'٢٤'},{text:'٢٨'},{text:'٣٢'},{text:'٣٦'}], correctOptionIndex:2, explanationAr:'كل رقم يُضرب في ٢: ٢×٢=٤، ٤×٢=٨، ٨×٢=١٦، ١٦×٢=٣٢.', tags:[] },
  { ageGroup:'6-9', skillArea:'quantitative', subSkill:'الكسور', difficulty:'hard', questionType:'text', questionTextAr:'أي كسر أكبر: ١/٢ أم ١/٣؟', questionImageUrl:null, options:[{text:'١/٣'},{text:'١/٢'},{text:'متساويان'},{text:'لا يمكن المقارنة'}], correctOptionIndex:1, explanationAr:'١/٢ أكبر من ١/٣. عندما يكون البسط ١، كلما صغر المقام كلما كان الكسر أكبر. نصف الشيء أكثر من ثلثه.', tags:[] },
  { ageGroup:'6-9', skillArea:'quantitative', subSkill:'المسائل المركبة', difficulty:'hard', questionType:'text', questionTextAr:'صف من ٢٤ طالباً، ثلثهم ذهبوا في رحلة. كم بقي في الفصل؟', questionImageUrl:null, options:[{text:'٨'},{text:'١٢'},{text:'١٦'},{text:'١٨'}], correctOptionIndex:2, explanationAr:'ثلث ٢٤ = ٢٤÷٣ = ٨. ذهب ٨ طلاب. بقي: ٢٤ - ٨ = ١٦ طالباً.', tags:[] },
  { ageGroup:'6-9', skillArea:'quantitative', subSkill:'الأنماط الرقمية', difficulty:'hard', questionType:'text', questionTextAr:'ما الرقم المفقود: ١، ١، ٢، ٣، ٥، ٨، __؟', questionImageUrl:null, options:[{text:'١١'},{text:'١٢'},{text:'١٣'},{text:'١٤'}], correctOptionIndex:2, explanationAr:'متتالية فيبوناتشي: كل عدد = جمع العددين اللذين قبله. ٥+٨=١٣.', tags:[] },
  { ageGroup:'6-9', skillArea:'quantitative', subSkill:'الهندسة', difficulty:'hard', questionType:'text', questionTextAr:'مستطيل طوله ٨ سم وعرضه ٥ سم. ما مساحته؟', questionImageUrl:null, options:[{text:'٣٠ سم²'},{text:'٣٥ سم²'},{text:'٤٠ سم²'},{text:'٤٥ سم²'}], correctOptionIndex:2, explanationAr:'مساحة المستطيل = الطول × العرض = ٨ × ٥ = ٤٠ سم².', tags:[] },
  { ageGroup:'6-9', skillArea:'quantitative', subSkill:'المسائل المركبة', difficulty:'hard', questionType:'text', questionTextAr:'إذا كان سعر التفاحة ٢ ريال وسعر البرتقالة ٣ ريال، فكم يكلف ٣ تفاحات و٢ برتقالات؟', questionImageUrl:null, options:[{text:'١٠'},{text:'١٢'},{text:'١٤'},{text:'١٦'}], correctOptionIndex:1, explanationAr:'٣ تفاحات = ٣×٢ = ٦ ريال. ٢ برتقالات = ٢×٣ = ٦ ريال. المجموع = ٦ + ٦ = ١٢ ريال.', tags:[] },
  { ageGroup:'6-9', skillArea:'quantitative', subSkill:'الكسور', difficulty:'hard', questionType:'text', questionTextAr:'عندي ١/٤ كعكة وأضفت ١/٤ أخرى. كم عندي الآن؟', questionImageUrl:null, options:[{text:'١/٢'},{text:'١/٣'},{text:'٢/٤ فقط'},{text:'١/٨'}], correctOptionIndex:0, explanationAr:'١/٤ + ١/٤ = ٢/٤ = ١/٢. عندما يتساوى المقام نجمع البسط فقط، ثم نبسّط الكسر.', tags:[] },
  { ageGroup:'6-9', skillArea:'quantitative', subSkill:'الأنماط الرقمية', difficulty:'hard', questionType:'text', questionTextAr:'ما الرقم المفقود: ١٠٠، ٩٠، ٨٠، ٧٠، __؟', questionImageUrl:null, options:[{text:'٥٠'},{text:'٥٥'},{text:'٦٠'},{text:'٦٥'}], correctOptionIndex:2, explanationAr:'النمط هو طرح ١٠ في كل مرة: ١٠٠-١٠=٩٠، ٩٠-١٠=٨٠... ٧٠-١٠=٦٠.', tags:[] },
  { ageGroup:'6-9', skillArea:'quantitative', subSkill:'المسائل المركبة', difficulty:'hard', questionType:'text', questionTextAr:'كان لدى يوسف ٥٠ ريالاً. أنفق ربعها على كتب ونصفها على طعام. كم تبقى؟', questionImageUrl:null, options:[{text:'١٠'},{text:'١٢'},{text:'١٥'},{text:'٢٥'}], correctOptionIndex:1, explanationAr:'ربع ٥٠ = ١٢.٥ ريال على كتب. نصف ٥٠ = ٢٥ على طعام. المجموع = ٣٧.٥. الباقي = ٥٠ - ٣٧.٥ = ١٢.٥ ≈ ١٢.', tags:[] },
];

// Export for use in other files
export { questionData };

async function seed() {
  const client = createClient({ url: process.env.TURSO_DATABASE_URL || 'file:./local.db' });
  const db = drizzle(client);
  console.log('Seeding questions (batch 1)...');
  let count = 0;
  for (const q of questionData) {
    await db.insert(questions).values({
      id: crypto.randomUUID(),
      skillArea: q.skillArea,
      subSkill: q.subSkill,
      ageGroup: q.ageGroup,
      difficulty: q.difficulty,
      questionType: q.questionType as 'text' | 'image',
      questionTextAr: q.questionTextAr,
      questionImageUrl: q.questionImageUrl,
      options: q.options as Array<{text: string}>,
      correctOptionIndex: q.correctOptionIndex,
      explanationAr: q.explanationAr,
      tags: q.tags,
      isActive: true,
    }).onConflictDoNothing();
    count++;
  }
  console.log(`Seeded ${count} questions so far.`);
  return count;
}

if (require.main === module) {
  seed().then(n => { console.log(`Done: ${n}`); process.exit(0); }).catch(e => { console.error(e); process.exit(1); });
}
