import { createClient } from '@libsql/client';
import { drizzle } from 'drizzle-orm/libsql';
import { questions } from './schema';

const questionData2 = [
  // ═══════════════════════════════════════════════
  // عمر 6-9 — لفظي — سهل
  // ═══════════════════════════════════════════════
  { ageGroup:'6-9', skillArea:'verbal', subSkill:'المتضادات', difficulty:'easy', questionType:'text', questionTextAr:'ما عكس كلمة "سعيد"؟', questionImageUrl:null, options:[{text:'مريض'},{text:'حزين'},{text:'خائف'},{text:'غاضب'}], correctOptionIndex:1, explanationAr:'عكس "سعيد" هو "حزين". المتضادات هي كلمات تحمل معنى معاكساً.', tags:[] },
  { ageGroup:'6-9', skillArea:'verbal', subSkill:'المفردات', difficulty:'easy', questionType:'text', questionTextAr:'ما معنى كلمة "شجاع"؟', questionImageUrl:null, options:[{text:'يخاف من كل شيء'},{text:'لا يخاف ويواجه التحديات'},{text:'يحب النوم كثيراً'},{text:'يأكل كثيراً'}], correctOptionIndex:1, explanationAr:'الشجاع هو الشخص الذي لا يخاف ويواجه التحديات والمواقف الصعبة بثبات.', tags:[] },
  { ageGroup:'6-9', skillArea:'verbal', subSkill:'المتضادات', difficulty:'easy', questionType:'text', questionTextAr:'ما عكس كلمة "نظيف"؟', questionImageUrl:null, options:[{text:'جميل'},{text:'قبيح'},{text:'وسخ'},{text:'قديم'}], correctOptionIndex:2, explanationAr:'عكس "نظيف" هو "وسخ" أو "قذر". النظافة من الإيمان كما يقال.', tags:[] },
  { ageGroup:'6-9', skillArea:'verbal', subSkill:'المفردات', difficulty:'easy', questionType:'text', questionTextAr:'ما معنى "يتأمل"؟', questionImageUrl:null, options:[{text:'يجري بسرعة'},{text:'ينظر بتمعن ويفكر'},{text:'يأكل بهدوء'},{text:'ينام بعمق'}], correctOptionIndex:1, explanationAr:'التأمل هو النظر بتمعن والتفكير العميق في شيء ما.', tags:[] },
  { ageGroup:'6-9', skillArea:'verbal', subSkill:'المتضادات', difficulty:'easy', questionType:'text', questionTextAr:'ما عكس كلمة "قديم"؟', questionImageUrl:null, options:[{text:'كبير'},{text:'جديد'},{text:'ثقيل'},{text:'بعيد'}], correctOptionIndex:1, explanationAr:'عكس "قديم" هو "جديد". الكتاب القديم يختلف عن الجديد في حالته.', tags:[] },
  { ageGroup:'6-9', skillArea:'verbal', subSkill:'المفردات', difficulty:'easy', questionType:'text', questionTextAr:'ما معنى "الفجر"؟', questionImageUrl:null, options:[{text:'وسط الليل'},{text:'أول النهار عند شروق الشمس'},{text:'منتصف النهار'},{text:'غروب الشمس'}], correctOptionIndex:1, explanationAr:'الفجر هو أول وقت النهار عند بداية ظهور ضوء الشمس قبل شروقها.', tags:[] },
  { ageGroup:'6-9', skillArea:'verbal', subSkill:'المتضادات', difficulty:'easy', questionType:'text', questionTextAr:'ما عكس كلمة "يتقدم"؟', questionImageUrl:null, options:[{text:'يتوقف'},{text:'يتأخر'},{text:'يتراجع'},{text:'ينام'}], correctOptionIndex:2, explanationAr:'عكس "يتقدم" هو "يتراجع". التقدم يعني الذهاب للأمام، والتراجع يعني الرجوع للخلف.', tags:[] },
  { ageGroup:'6-9', skillArea:'verbal', subSkill:'المفردات', difficulty:'easy', questionType:'text', questionTextAr:'ما معنى "يتسامح"؟', questionImageUrl:null, options:[{text:'يتجاهل الآخرين'},{text:'يغضب بسرعة'},{text:'يعفو ويصفح'},{text:'يتسابق'}], correctOptionIndex:2, explanationAr:'التسامح هو العفو والصفح عن الآخرين وعدم الاحتقان من أخطائهم.', tags:[] },
  { ageGroup:'6-9', skillArea:'verbal', subSkill:'المتضادات', difficulty:'easy', questionType:'text', questionTextAr:'ما عكس "الكرم"؟', questionImageUrl:null, options:[{text:'الطيبة'},{text:'البخل'},{text:'الشجاعة'},{text:'الصدق'}], correctOptionIndex:1, explanationAr:'عكس "الكرم" هو "البخل". الكريم يعطي بسخاء والبخيل لا يحب العطاء.', tags:[] },
  { ageGroup:'6-9', skillArea:'verbal', subSkill:'المفردات', difficulty:'easy', questionType:'text', questionTextAr:'ما معنى "الغسق"؟', questionImageUrl:null, options:[{text:'وقت الظهر'},{text:'وقت الصباح'},{text:'وقت المساء عند غروب الشمس'},{text:'وقت منتصف الليل'}], correctOptionIndex:2, explanationAr:'الغسق هو وقت المساء عند غروب الشمس وبداية الظلام.', tags:[] },

  // عمر 6-9 — لفظي — متوسط
  { ageGroup:'6-9', skillArea:'verbal', subSkill:'المترادفات', difficulty:'medium', questionType:'text', questionTextAr:'ما مرادف كلمة "سريع"؟', questionImageUrl:null, options:[{text:'بطيء'},{text:'كسول'},{text:'خفيف'},{text:'رزين'}], correctOptionIndex:2, explanationAr:'مرادف "سريع" هو "خفيف" أو "عجول". المترادفات كلمات تحمل نفس المعنى أو معنى متقارباً.', tags:[] },
  { ageGroup:'6-9', skillArea:'verbal', subSkill:'إكمال الجملة', difficulty:'medium', questionType:'text', questionTextAr:'الكتاب للقراءة كما أن القلم لـ...', questionImageUrl:null, options:[{text:'الحفر'},{text:'الكتابة'},{text:'القطع'},{text:'الطبخ'}], correctOptionIndex:1, explanationAr:'الكتاب أداة للقراءة، والقلم أداة للكتابة. هذا تناظر وظيفي.', tags:[] },
  { ageGroup:'6-9', skillArea:'verbal', subSkill:'المترادفات', difficulty:'medium', questionType:'text', questionTextAr:'ما مرادف كلمة "حزن"؟', questionImageUrl:null, options:[{text:'فرح'},{text:'غم'},{text:'سرور'},{text:'بهجة'}], correctOptionIndex:1, explanationAr:'مرادف "حزن" هو "غم" أو "كآبة". كلها تعبر عن الشعور بالألم النفسي.', tags:[] },
  { ageGroup:'6-9', skillArea:'verbal', subSkill:'التناظر', difficulty:'medium', questionType:'text', questionTextAr:'الطيور : الأجنحة = الأسماك : ؟', questionImageUrl:null, options:[{text:'أرجل'},{text:'زعانف'},{text:'ذيل'},{text:'فراء'}], correctOptionIndex:1, explanationAr:'الطيور تتحرك بأجنحتها في الهواء، والأسماك تتحرك بزعانفها في الماء. هذا تناظر وظيفي.', tags:[] },
  { ageGroup:'6-9', skillArea:'verbal', subSkill:'إكمال الجملة', difficulty:'medium', questionType:'text', questionTextAr:'الطبيب يعالج المرضى كما أن المعلم يـ...', questionImageUrl:null, options:[{text:'يطبخ الطعام'},{text:'يعلم الطلاب'},{text:'يبني المنازل'},{text:'يزرع الحقول'}], correctOptionIndex:1, explanationAr:'الطبيب يعالج المرضى وهذه وظيفته، والمعلم يعلم الطلاب وهذه وظيفته.', tags:[] },
  { ageGroup:'6-9', skillArea:'verbal', subSkill:'المترادفات', difficulty:'medium', questionType:'text', questionTextAr:'ما مرادف "ذكي"؟', questionImageUrl:null, options:[{text:'غبي'},{text:'كسول'},{text:'فطين'},{text:'ضعيف'}], correctOptionIndex:2, explanationAr:'مرادف "ذكي" هو "فطين" أو "نبيه" أو "لبيب". كلها تعني سرعة الفهم والإدراك.', tags:[] },
  { ageGroup:'6-9', skillArea:'verbal', subSkill:'التناظر', difficulty:'medium', questionType:'text', questionTextAr:'النهار : الشمس = الليل : ؟', questionImageUrl:null, options:[{text:'الفجر'},{text:'النجوم'},{text:'القمر'},{text:'الغسق'}], correctOptionIndex:2, explanationAr:'الشمس تضيء النهار والقمر يضيء الليل. هذا تناظر بين النقيضين.', tags:[] },
  { ageGroup:'6-9', skillArea:'verbal', subSkill:'إكمال الجملة', difficulty:'medium', questionType:'text', questionTextAr:'العين للرؤية كما أن الأذن لـ...', questionImageUrl:null, options:[{text:'الشم'},{text:'التذوق'},{text:'السمع'},{text:'اللمس'}], correctOptionIndex:2, explanationAr:'العين تستخدم للرؤية والأذن تستخدم للسمع. حواسنا الخمس لكل منها وظيفة.', tags:[] },
  { ageGroup:'6-9', skillArea:'verbal', subSkill:'المترادفات', difficulty:'medium', questionType:'text', questionTextAr:'ما مرادف "جميل"؟', questionImageUrl:null, options:[{text:'قبيح'},{text:'حسن'},{text:'مزعج'},{text:'ثقيل'}], correctOptionIndex:1, explanationAr:'مرادف "جميل" هو "حسن" أو "بهي" أو "رائع". كلها تعبر عن الجمال.', tags:[] },
  { ageGroup:'6-9', skillArea:'verbal', subSkill:'التناظر', difficulty:'medium', questionType:'text', questionTextAr:'الملك : القصر = الأسد : ؟', questionImageUrl:null, options:[{text:'الغابة'},{text:'البحر'},{text:'الصحراء'},{text:'الجبل'}], correctOptionIndex:0, explanationAr:'الملك يسكن القصر والأسد يسكن الغابة. هذا تناظر بين الكائن ومسكنه.', tags:[] },

  // عمر 6-9 — لفظي — صعب
  { ageGroup:'6-9', skillArea:'verbal', subSkill:'التناظر اللغوي', difficulty:'hard', questionType:'text', questionTextAr:'القلم : الكاتب = المشرط : ؟', questionImageUrl:null, options:[{text:'المزارع'},{text:'الجراح'},{text:'البنّاء'},{text:'الطاهي'}], correctOptionIndex:1, explanationAr:'القلم أداة الكاتب، والمشرط أداة الجراح. كل مهنة لها أدواتها المختصة.', tags:[] },
  { ageGroup:'6-9', skillArea:'verbal', subSkill:'الفهم القرائي', difficulty:'hard', questionType:'text', questionTextAr:'قرأت: "الطالبة المجتهدة تذاكر دروسها يومياً وتحصل على درجات عالية." ما سبب حصولها على درجات عالية؟', questionImageUrl:null, options:[{text:'لأنها تنام كثيراً'},{text:'لأنها تذاكر يومياً'},{text:'لأنها تلعب'},{text:'لأن المعلمة تحبها'}], correctOptionIndex:1, explanationAr:'النص يخبرنا مباشرة أن المذاكرة اليومية هي سبب الدرجات العالية. السبب والنتيجة في النص.', tags:[] },
  { ageGroup:'6-9', skillArea:'verbal', subSkill:'التناظر اللغوي', difficulty:'hard', questionType:'text', questionTextAr:'الخريف : الأوراق = الربيع : ؟', questionImageUrl:null, options:[{text:'المطر'},{text:'الأزهار'},{text:'الثلج'},{text:'الحر'}], correctOptionIndex:1, explanationAr:'الخريف يرتبط بسقوط الأوراق والربيع يرتبط بتفتح الأزهار. هذا تناظر موسمي.', tags:[] },
  { ageGroup:'6-9', skillArea:'verbal', subSkill:'الخطأ السياقي', difficulty:'hard', questionType:'text', questionTextAr:'أي كلمة خطأ في الجملة: "ذهبت إلى المدرسة وطبخت الدرس"؟', questionImageUrl:null, options:[{text:'ذهبت'},{text:'المدرسة'},{text:'طبخت'},{text:'الدرس'}], correctOptionIndex:2, explanationAr:'"طبخت" خطأ سياقي. الصحيح "درست" أو "شرحت". الطبخ يكون في المطبخ لا للدروس.', tags:[] },
  { ageGroup:'6-9', skillArea:'verbal', subSkill:'الفهم القرائي', difficulty:'hard', questionType:'text', questionTextAr:'قرأت: "الماء يتحول إلى بخار عند تسخينه ويتحول إلى جليد عند تبريده." ما حالة الماء عند التسخين؟', questionImageUrl:null, options:[{text:'جليد'},{text:'بخار'},{text:'يبقى سائلاً'},{text:'يختفي'}], correctOptionIndex:1, explanationAr:'النص يقول صراحة أن الماء يتحول إلى بخار عند التسخين. هذه الحالة الغازية للماء.', tags:[] },
  { ageGroup:'6-9', skillArea:'verbal', subSkill:'التناظر اللغوي', difficulty:'hard', questionType:'text', questionTextAr:'الكلمات : القاموس = الكتب : ؟', questionImageUrl:null, options:[{text:'الورق'},{text:'المكتبة'},{text:'القلم'},{text:'الحبر'}], correctOptionIndex:1, explanationAr:'الكلمات تُجمع في القاموس، والكتب تُجمع في المكتبة. مكان التجميع والحفظ.', tags:[] },
  { ageGroup:'6-9', skillArea:'verbal', subSkill:'الخطأ السياقي', difficulty:'hard', questionType:'text', questionTextAr:'أي كلمة خطأ: "شرب الطالب الكتاب ببطء"؟', questionImageUrl:null, options:[{text:'شرب'},{text:'الطالب'},{text:'الكتاب'},{text:'ببطء'}], correctOptionIndex:0, explanationAr:'"شرب" خطأ سياقي. لا يُشرب الكتاب. الصحيح "قرأ" الطالب الكتاب ببطء.', tags:[] },
  { ageGroup:'6-9', skillArea:'verbal', subSkill:'الفهم القرائي', difficulty:'hard', questionType:'text', questionTextAr:'قرأت: "بنى عمر بيتاً من طوب ليصمد أمام العواصف". لماذا اختار الطوب؟', questionImageUrl:null, options:[{text:'لأنه أرخص'},{text:'لأنه يصمد أمام العواصف'},{text:'لأنه أجمل'},{text:'لأنه أسرع بناءً'}], correctOptionIndex:1, explanationAr:'النص يخبرنا صراحة أن السبب هو الصمود أمام العواصف. يجب قراءة النص بتمعن.', tags:[] },
  { ageGroup:'6-9', skillArea:'verbal', subSkill:'التناظر اللغوي', difficulty:'hard', questionType:'text', questionTextAr:'المعلم : التلميذ = الطبيب : ؟', questionImageUrl:null, options:[{text:'المستشفى'},{text:'الدواء'},{text:'المريض'},{text:'العملية'}], correctOptionIndex:2, explanationAr:'المعلم يتعامل مع التلميذ في التعليم، والطبيب يتعامل مع المريض في العلاج.', tags:[] },
  { ageGroup:'6-9', skillArea:'verbal', subSkill:'الخطأ السياقي', difficulty:'hard', questionType:'text', questionTextAr:'أي جملة صحيحة سياقياً؟', questionImageUrl:null, options:[{text:'طارت السمكة في السماء'},{text:'ركض الطفل في الحديقة'},{text:'شرب الكتاب القهوة'},{text:'نامت السيارة في الفراش'}], correctOptionIndex:1, explanationAr:'"ركض الطفل في الحديقة" صحيحة لأن الطفل يركض والحديقة مكان مناسب. باقي الجمل غير منطقية.', tags:[] },

  // ═══════════════════════════════════════════════
  // عمر 6-9 — منطقي — سهل
  // ═══════════════════════════════════════════════
  { ageGroup:'6-9', skillArea:'logical_patterns', subSkill:'السلاسل الرقمية', difficulty:'easy', questionType:'text', questionTextAr:'ما التالي: ٢، ٤، ٦، ٨، __؟', questionImageUrl:null, options:[{text:'٩'},{text:'١٠'},{text:'١١'},{text:'١٢'}], correctOptionIndex:1, explanationAr:'النمط هو إضافة ٢ في كل مرة (الأعداد الزوجية): ٢، ٤، ٦، ٨، ١٠.', tags:[] },
  { ageGroup:'6-9', skillArea:'logical_patterns', subSkill:'السلاسل الرقمية', difficulty:'easy', questionType:'text', questionTextAr:'ما التالي: ٥، ١٠، ١٥، ٢٠، __؟', questionImageUrl:null, options:[{text:'٢٢'},{text:'٢٣'},{text:'٢٥'},{text:'٢٨'}], correctOptionIndex:2, explanationAr:'النمط هو مضاعفات ٥: ٥، ١٠، ١٥، ٢٠، ٢٥.', tags:[] },
  { ageGroup:'6-9', skillArea:'logical_patterns', subSkill:'الاستنتاج', difficulty:'easy', questionType:'text', questionTextAr:'كل الطلاب في الفصل يلبسون زياً مدرسياً. خالد طالب في الفصل. هل يلبس زياً؟', questionImageUrl:null, options:[{text:'نعم'},{text:'لا'},{text:'ربما'},{text:'لا يمكن التحديد'}], correctOptionIndex:0, explanationAr:'نعم! القاعدة تقول كل طلاب الفصل يلبسون الزي، وخالد من الفصل، إذن يلبس الزي.', tags:[] },
  { ageGroup:'6-9', skillArea:'logical_patterns', subSkill:'السلاسل الرقمية', difficulty:'easy', questionType:'text', questionTextAr:'ما التالي: ١، ٣، ٥، ٧، __؟', questionImageUrl:null, options:[{text:'٨'},{text:'٩'},{text:'١٠'},{text:'١١'}], correctOptionIndex:1, explanationAr:'النمط هو الأعداد الفردية: ١، ٣، ٥، ٧، ٩.', tags:[] },
  { ageGroup:'6-9', skillArea:'logical_patterns', subSkill:'الأنماط', difficulty:'easy', questionType:'text', questionTextAr:'ما الرقم المفقود: ٢، ٤، __, ٨، ١٠؟', questionImageUrl:null, options:[{text:'٥'},{text:'٦'},{text:'٧'},{text:'٣'}], correctOptionIndex:1, explanationAr:'النمط هو إضافة ٢: ٢، ٤، ٦، ٨، ١٠. الرقم المفقود هو ٦.', tags:[] },
  { ageGroup:'6-9', skillArea:'logical_patterns', subSkill:'الاستنتاج', difficulty:'easy', questionType:'text', questionTextAr:'إذا كان اليوم السبت، ما اليوم غداً؟', questionImageUrl:null, options:[{text:'الجمعة'},{text:'الأحد'},{text:'الاثنين'},{text:'الثلاثاء'}], correctOptionIndex:1, explanationAr:'ترتيب الأسبوع: ...الجمعة، السبت، الأحد، الاثنين... غداً الأحد.', tags:[] },
  { ageGroup:'6-9', skillArea:'logical_patterns', subSkill:'السلاسل الرقمية', difficulty:'easy', questionType:'text', questionTextAr:'ما التالي: ١٠، ٢٠، ٣٠، __؟', questionImageUrl:null, options:[{text:'٣٥'},{text:'٣٨'},{text:'٤٠'},{text:'٤٥'}], correctOptionIndex:2, explanationAr:'النمط هو إضافة ١٠: ١٠، ٢٠، ٣٠، ٤٠.', tags:[] },
  { ageGroup:'6-9', skillArea:'logical_patterns', subSkill:'الاستنتاج', difficulty:'easy', questionType:'text', questionTextAr:'سارة أعلى نتيجة من نورة، ونورة أعلى من ريم. من الأول؟', questionImageUrl:null, options:[{text:'ريم'},{text:'نورة'},{text:'سارة'},{text:'كلهن متساويات'}], correctOptionIndex:2, explanationAr:'سارة > نورة > ريم. إذن سارة هي الأولى بأعلى نتيجة.', tags:[] },
  { ageGroup:'6-9', skillArea:'logical_patterns', subSkill:'الأنماط', difficulty:'easy', questionType:'text', questionTextAr:'ما الرقم المفقود: ١٠٠، ٩٠، __, ٧٠، ٦٠؟', questionImageUrl:null, options:[{text:'٧٥'},{text:'٨٠'},{text:'٨٥'},{text:'٩٥'}], correctOptionIndex:1, explanationAr:'النمط هو طرح ١٠: ١٠٠، ٩٠، ٨٠، ٧٠، ٦٠. الرقم المفقود هو ٨٠.', tags:[] },
  { ageGroup:'6-9', skillArea:'logical_patterns', subSkill:'الاستنتاج', difficulty:'easy', questionType:'text', questionTextAr:'كل المربعات لها ٤ زوايا. هذا الشكل مربع. كم زاوية له؟', questionImageUrl:null, options:[{text:'٢'},{text:'٣'},{text:'٤'},{text:'٥'}], correctOptionIndex:2, explanationAr:'لأن كل المربعات لها ٤ زوايا وهذا مربع، إذن له ٤ زوايا.', tags:[] },

  // عمر 6-9 — منطقي — متوسط
  { ageGroup:'6-9', skillArea:'logical_patterns', subSkill:'السلاسل المتقدمة', difficulty:'medium', questionType:'text', questionTextAr:'ما التالي: ٣، ٦، ١٢، ٢٤، __؟', questionImageUrl:null, options:[{text:'٣٦'},{text:'٤٨'},{text:'٤٢'},{text:'٣٠'}], correctOptionIndex:1, explanationAr:'كل رقم يُضرب في ٢: ٣×٢=٦، ٦×٢=١٢، ١٢×٢=٢٤، ٢٤×٢=٤٨.', tags:[] },
  { ageGroup:'6-9', skillArea:'logical_patterns', subSkill:'الاستدلال', difficulty:'medium', questionType:'text', questionTextAr:'إذا كان A أكبر من B وB أكبر من C وC أكبر من D، من الأصغر؟', questionImageUrl:null, options:[{text:'A'},{text:'B'},{text:'C'},{text:'D'}], correctOptionIndex:3, explanationAr:'A>B>C>D. إذن D هو الأصغر في هذه السلسلة.', tags:[] },
  { ageGroup:'6-9', skillArea:'logical_patterns', subSkill:'الأنماط المتقدمة', difficulty:'medium', questionType:'text', questionTextAr:'ما الرقم المفقود: ١، ٤، ٩، ١٦، __؟', questionImageUrl:null, options:[{text:'٢٠'},{text:'٢٣'},{text:'٢٥'},{text:'٢٨'}], correctOptionIndex:2, explanationAr:'هذه مربعات الأعداد: ١²=١، ٢²=٤، ٣²=٩، ٤²=١٦، ٥²=٢٥.', tags:[] },
  { ageGroup:'6-9', skillArea:'logical_patterns', subSkill:'الاستدلال', difficulty:'medium', questionType:'text', questionTextAr:'كل الحلويات تحتوي على سكر. الكيك حلوى. هل الكيك يحتوي على سكر؟', questionImageUrl:null, options:[{text:'نعم'},{text:'لا'},{text:'أحياناً'},{text:'لا يمكن التحديد'}], correctOptionIndex:0, explanationAr:'نعم، بالاستنتاج: كل الحلويات = سكر، الكيك = حلوى، إذن الكيك = سكر.', tags:[] },
  { ageGroup:'6-9', skillArea:'logical_patterns', subSkill:'السلاسل المتقدمة', difficulty:'medium', questionType:'text', questionTextAr:'ما التالي: ١، ٢، ٤، ٧، ١١، __؟', questionImageUrl:null, options:[{text:'١٤'},{text:'١٥'},{text:'١٦'},{text:'١٧'}], correctOptionIndex:2, explanationAr:'الفرق بين الأعداد يزداد: +١، +٢، +٣، +٤، +٥. بعد ١١ يأتي ١١+٥=١٦.', tags:[] },
  { ageGroup:'6-9', skillArea:'logical_patterns', subSkill:'الاستدلال', difficulty:'medium', questionType:'text', questionTextAr:'في مسابقة، أحمد يسبق محمداً وعلي يسبق أحمد. من الأول؟', questionImageUrl:null, options:[{text:'أحمد'},{text:'محمد'},{text:'علي'},{text:'لا يمكن التحديد'}], correctOptionIndex:2, explanationAr:'علي يسبق أحمد، وأحمد يسبق محمد. إذن الترتيب: علي، أحمد، محمد. علي الأول.', tags:[] },
  { ageGroup:'6-9', skillArea:'logical_patterns', subSkill:'الأنماط المتقدمة', difficulty:'medium', questionType:'text', questionTextAr:'ما الرقم المفقود: ٢، __, ٨، ١١، ١٤؟', questionImageUrl:null, options:[{text:'٤'},{text:'٥'},{text:'٦'},{text:'٧'}], correctOptionIndex:1, explanationAr:'النمط هو إضافة ٣: ٢+٣=٥، ٥+٣=٨، ٨+٣=١١. الرقم المفقود هو ٥.', tags:[] },
  { ageGroup:'6-9', skillArea:'logical_patterns', subSkill:'الاستدلال', difficulty:'medium', questionType:'text', questionTextAr:'لا يوجد طائر بدون جناح. البطريق طائر. هل للبطريق جناح؟', questionImageUrl:null, options:[{text:'نعم'},{text:'لا'},{text:'أحياناً'},{text:'لا أعرف'}], correctOptionIndex:0, explanationAr:'نعم، البطريق له جناح حتى لو لم يستطع الطيران. القاعدة تقول لا طائر بلا جناح.', tags:[] },
  { ageGroup:'6-9', skillArea:'logical_patterns', subSkill:'السلاسل المتقدمة', difficulty:'medium', questionType:'text', questionTextAr:'ما التالي: ٦٤، ٣٢، ١٦، ٨، __؟', questionImageUrl:null, options:[{text:'٢'},{text:'٤'},{text:'٦'},{text:'٨'}], correctOptionIndex:1, explanationAr:'كل رقم يُقسم على ٢: ٦٤÷٢=٣٢، ٣٢÷٢=١٦، ١٦÷٢=٨، ٨÷٢=٤.', tags:[] },
  { ageGroup:'6-9', skillArea:'logical_patterns', subSkill:'الأنماط المتقدمة', difficulty:'medium', questionType:'text', questionTextAr:'ما الرقم المفقود: ٣، ٦، ٩، __, ١٥؟', questionImageUrl:null, options:[{text:'١٠'},{text:'١١'},{text:'١٢'},{text:'١٣'}], correctOptionIndex:2, explanationAr:'مضاعفات ٣: ٣، ٦، ٩، ١٢، ١٥. الرقم المفقود هو ١٢.', tags:[] },

  // عمر 6-9 — منطقي — صعب
  { ageGroup:'6-9', skillArea:'logical_patterns', subSkill:'الاستدلال المعقد', difficulty:'hard', questionType:'text', questionTextAr:'ما التالي: ١، ١، ٢، ٣، ٥، ٨، ١٣، __؟', questionImageUrl:null, options:[{text:'١٨'},{text:'٢٠'},{text:'٢١'},{text:'٢٣'}], correctOptionIndex:2, explanationAr:'هذه متتالية فيبوناتشي الشهيرة: كل عدد = مجموع العددين قبله. ٨+١٣=٢١.', tags:[] },
  { ageGroup:'6-9', skillArea:'logical_patterns', subSkill:'القياس المنطقي', difficulty:'hard', questionType:'text', questionTextAr:'بعض الفواكه حلوة. التفاح فاكهة. هل التفاح حلو بالضرورة؟', questionImageUrl:null, options:[{text:'نعم دائماً'},{text:'لا أبداً'},{text:'ليس بالضرورة'},{text:'لا يمكن التحديد'}], correctOptionIndex:2, explanationAr:'القاعدة تقول "بعض" الفواكه حلوة، لا "كل" الفواكه. إذن التفاح قد يكون حلواً أو غير حلو.', tags:[] },
  { ageGroup:'6-9', skillArea:'logical_patterns', subSkill:'السلاسل المعقدة', difficulty:'hard', questionType:'text', questionTextAr:'ما التالي: ٢، ٦، ١٢، ٢٠، ٣٠، __؟', questionImageUrl:null, options:[{text:'٣٦'},{text:'٤٠'},{text:'٤٢'},{text:'٤٦'}], correctOptionIndex:2, explanationAr:'الفروق: +٤، +٦، +٨، +١٠، +١٢. بعد ٣٠ نضيف ١٢: ٣٠+١٢=٤٢.', tags:[] },
  { ageGroup:'6-9', skillArea:'logical_patterns', subSkill:'الاستدلال المعقد', difficulty:'hard', questionType:'text', questionTextAr:'إذا كان كل A هو B، وبعض B هو C، هل كل A هو C بالضرورة؟', questionImageUrl:null, options:[{text:'نعم'},{text:'لا'},{text:'أحياناً'},{text:'ليس بالضرورة'}], correctOptionIndex:3, explanationAr:'ليس بالضرورة. كل A هو B، لكن B ليست كلها C (بعضها فقط). إذن بعض A قد يكون C وبعضها لا.', tags:[] },
  { ageGroup:'6-9', skillArea:'logical_patterns', subSkill:'السلاسل المعقدة', difficulty:'hard', questionType:'text', questionTextAr:'ما الرقم المفقود: ١، ٢، ٦، ٢٤، __؟', questionImageUrl:null, options:[{text:'٤٨'},{text:'٩٦'},{text:'١٢٠'},{text:'١٤٤'}], correctOptionIndex:2, explanationAr:'كل رقم مضروب في: ×٢، ×٣، ×٤، ×٥. بعد ٢٤: ٢٤×٥=١٢٠. (المضروب هو المضاعفات).', tags:[] },
  { ageGroup:'6-9', skillArea:'logical_patterns', subSkill:'الاستدلال المعقد', difficulty:'hard', questionType:'text', questionTextAr:'في مباراة، الأحمر يكسب الأزرق، والأزرق يكسب الأخضر، والأخضر يكسب الأصفر. من الأخسر؟', questionImageUrl:null, options:[{text:'الأحمر'},{text:'الأزرق'},{text:'الأخضر'},{text:'الأصفر'}], correctOptionIndex:3, explanationAr:'السلسلة: أحمر > أزرق > أخضر > أصفر. الأصفر يخسر من الأخضر وهو في النهاية.', tags:[] },
  { ageGroup:'6-9', skillArea:'logical_patterns', subSkill:'السلاسل المعقدة', difficulty:'hard', questionType:'text', questionTextAr:'ما التالي: ١، ٤، ٩، ١٦، ٢٥، __؟', questionImageUrl:null, options:[{text:'٣٤'},{text:'٣٦'},{text:'٣٨'},{text:'٤٠'}], correctOptionIndex:1, explanationAr:'هذه مربعات الأعداد: ١²=١، ٢²=٤، ٣²=٩، ٤²=١٦، ٥²=٢٥، ٦²=٣٦.', tags:[] },
  { ageGroup:'6-9', skillArea:'logical_patterns', subSkill:'الاستدلال المعقد', difficulty:'hard', questionType:'text', questionTextAr:'لا طالب يغش. هشام لا يغش. هل هشام طالب؟', questionImageUrl:null, options:[{text:'نعم'},{text:'لا'},{text:'ربما'},{text:'ليس بالضرورة'}], correctOptionIndex:3, explanationAr:'ليس بالضرورة. عدم الغش لا يعني أنه طالب — قد يكون أي شخص لا يغش.', tags:[] },
  { ageGroup:'6-9', skillArea:'logical_patterns', subSkill:'السلاسل المعقدة', difficulty:'hard', questionType:'text', questionTextAr:'ما الرقم المفقود: ٢، ٣، ٥، ٧، ١١، __؟', questionImageUrl:null, options:[{text:'١٢'},{text:'١٣'},{text:'١٤'},{text:'١٥'}], correctOptionIndex:1, explanationAr:'هذه الأعداد الأولية: ٢، ٣، ٥، ٧، ١١، ١٣. الأعداد التي لا تقبل القسمة إلا على ١ وعلى نفسها.', tags:[] },
  { ageGroup:'6-9', skillArea:'logical_patterns', subSkill:'الاستدلال المعقد', difficulty:'hard', questionType:'text', questionTextAr:'إذا صح أن "كل ما يلمع ذهب"، ماذا نستنتج عن هذا الحجر اللامع؟', questionImageUrl:null, options:[{text:'إنه ذهب'},{text:'ليس ذهباً'},{text:'ربما ذهب'},{text:'لا يمكن التحديد'}], correctOptionIndex:0, explanationAr:'إذا افترضنا صحة القاعدة "كل ما يلمع = ذهب"، وهذا الحجر يلمع، إذن هو ذهب وفق هذه الافتراض.', tags:[] },

  // ═══════════════════════════════════════════════
  // عمر 10-12 — كمي — سهل
  // ═══════════════════════════════════════════════
  { ageGroup:'10-12', skillArea:'quantitative', subSkill:'النسبة والتناسب', difficulty:'easy', questionType:'text', questionTextAr:'إذا كانت نسبة الطلاب إلى المعلمين ١٠:١، وعدد المعلمين ٥، فكم عدد الطلاب؟', questionImageUrl:null, options:[{text:'٤٠'},{text:'٤٥'},{text:'٥٠'},{text:'٥٥'}], correctOptionIndex:2, explanationAr:'النسبة ١٠:١ تعني لكل معلم ١٠ طلاب. ٥ معلمين × ١٠ = ٥٠ طالباً.', tags:[] },
  { ageGroup:'10-12', skillArea:'quantitative', subSkill:'النسبة والتناسب', difficulty:'easy', questionType:'text', questionTextAr:'ما هو ٢٠٪ من ٨٠؟', questionImageUrl:null, options:[{text:'١٢'},{text:'١٤'},{text:'١٦'},{text:'١٨'}], correctOptionIndex:2, explanationAr:'٢٠٪ من ٨٠ = (٢٠ ÷ ١٠٠) × ٨٠ = ٠.٢ × ٨٠ = ١٦.', tags:[] },
  { ageGroup:'10-12', skillArea:'quantitative', subSkill:'الجبر', difficulty:'easy', questionType:'text', questionTextAr:'إذا كانت س + ٥ = ١٢، فما قيمة س؟', questionImageUrl:null, options:[{text:'٥'},{text:'٦'},{text:'٧'},{text:'٨'}], correctOptionIndex:2, explanationAr:'س + ٥ = ١٢ → س = ١٢ - ٥ = ٧. نطرح ٥ من الطرفين.', tags:[] },
  { ageGroup:'10-12', skillArea:'quantitative', subSkill:'الكسور', difficulty:'easy', questionType:'text', questionTextAr:'ما نتيجة ٣/٤ + ١/٤؟', questionImageUrl:null, options:[{text:'٤/٨'},{text:'١'},{text:'٢/٤'},{text:'٤/٤'}], correctOptionIndex:1, explanationAr:'٣/٤ + ١/٤ = ٤/٤ = ١. عند جمع كسور متشابهة المقام نجمع البسط.', tags:[] },
  { ageGroup:'10-12', skillArea:'quantitative', subSkill:'النسبة والتناسب', difficulty:'easy', questionType:'text', questionTextAr:'إذا كان سعر ٣ كيلو برتقال ١٥ ريال، فكم يكلف ٥ كيلو؟', questionImageUrl:null, options:[{text:'٢٠'},{text:'٢٥'},{text:'٣٠'},{text:'٣٥'}], correctOptionIndex:1, explanationAr:'سعر الكيلو = ١٥ ÷ ٣ = ٥ ريال. ٥ كيلو = ٥ × ٥ = ٢٥ ريال.', tags:[] },
  { ageGroup:'10-12', skillArea:'quantitative', subSkill:'الجبر', difficulty:'easy', questionType:'text', questionTextAr:'إذا كانت ٢ص = ١٦، فما قيمة ص؟', questionImageUrl:null, options:[{text:'٦'},{text:'٧'},{text:'٨'},{text:'٩'}], correctOptionIndex:2, explanationAr:'٢ص = ١٦ → ص = ١٦ ÷ ٢ = ٨. نقسم الطرفين على ٢.', tags:[] },
  { ageGroup:'10-12', skillArea:'quantitative', subSkill:'النسبة والتناسب', difficulty:'easy', questionType:'text', questionTextAr:'ما هو ٥٠٪ من ١٤٠؟', questionImageUrl:null, options:[{text:'٦٠'},{text:'٦٥'},{text:'٧٠'},{text:'٧٥'}], correctOptionIndex:2, explanationAr:'٥٠٪ = النصف. نصف ١٤٠ = ٧٠.', tags:[] },
  { ageGroup:'10-12', skillArea:'quantitative', subSkill:'الكسور', difficulty:'easy', questionType:'text', questionTextAr:'ما نتيجة ١/٢ × ٤؟', questionImageUrl:null, options:[{text:'١'},{text:'٢'},{text:'٣'},{text:'٤'}], correctOptionIndex:1, explanationAr:'١/٢ × ٤ = ٤/٢ = ٢. نضرب البسط في العدد ونقسم على المقام.', tags:[] },
  { ageGroup:'10-12', skillArea:'quantitative', subSkill:'الجبر', difficulty:'easy', questionType:'text', questionTextAr:'إذا كانت س - ٩ = ١٥، فما قيمة س؟', questionImageUrl:null, options:[{text:'٢١'},{text:'٢٣'},{text:'٢٤'},{text:'٢٦'}], correctOptionIndex:2, explanationAr:'س - ٩ = ١٥ → س = ١٥ + ٩ = ٢٤.', tags:[] },
  { ageGroup:'10-12', skillArea:'quantitative', subSkill:'النسبة والتناسب', difficulty:'easy', questionType:'text', questionTextAr:'إذا كانت نسبة الرجال إلى النساء ٢:٣ في مجموعة من ٢٥ شخصاً، كم عدد الرجال؟', questionImageUrl:null, options:[{text:'٨'},{text:'١٠'},{text:'١٢'},{text:'١٥'}], correctOptionIndex:1, explanationAr:'المجموع = ٢+٣ = ٥ أجزاء. الرجال = (٢/٥) × ٢٥ = ١٠.', tags:[] },

  // عمر 10-12 — كمي — متوسط
  { ageGroup:'10-12', skillArea:'quantitative', subSkill:'الجبر', difficulty:'medium', questionType:'text', questionTextAr:'حل المعادلة: ٢س + ٣ = ١١', questionImageUrl:null, options:[{text:'س = ٣'},{text:'س = ٤'},{text:'س = ٥'},{text:'س = ٦'}], correctOptionIndex:1, explanationAr:'٢س + ٣ = ١١ → ٢س = ٨ → س = ٤. نطرح ٣ ثم نقسم على ٢.', tags:[] },
  { ageGroup:'10-12', skillArea:'quantitative', subSkill:'الهندسة', difficulty:'medium', questionType:'text', questionTextAr:'مثلث قائم الزاوية أطوال ضلعيه القائمين ٣ و٤. ما طول الوتر؟', questionImageUrl:null, options:[{text:'٤'},{text:'٥'},{text:'٦'},{text:'٧'}], correctOptionIndex:1, explanationAr:'بمبرهنة فيثاغورس: الوتر² = ٣² + ٤² = ٩ + ١٦ = ٢٥. الوتر = √٢٥ = ٥.', tags:[] },
  { ageGroup:'10-12', skillArea:'quantitative', subSkill:'النسبة والتناسب', difficulty:'medium', questionType:'text', questionTextAr:'ارتفع سعر سلعة من ٨٠ إلى ١٠٠ ريال. ما نسبة الارتفاع؟', questionImageUrl:null, options:[{text:'١٥٪'},{text:'٢٠٪'},{text:'٢٥٪'},{text:'٣٠٪'}], correctOptionIndex:2, explanationAr:'نسبة الزيادة = (الزيادة ÷ السعر الأصلي) × ١٠٠ = (٢٠ ÷ ٨٠) × ١٠٠ = ٢٥٪.', tags:[] },
  { ageGroup:'10-12', skillArea:'quantitative', subSkill:'الجبر', difficulty:'medium', questionType:'text', questionTextAr:'إذا كان ٣(س + ٢) = ١٨، فما قيمة س؟', questionImageUrl:null, options:[{text:'٢'},{text:'٤'},{text:'٦'},{text:'٨'}], correctOptionIndex:1, explanationAr:'٣(س+٢)=١٨ → س+٢=٦ → س=٤.', tags:[] },
  { ageGroup:'10-12', skillArea:'quantitative', subSkill:'الهندسة', difficulty:'medium', questionType:'text', questionTextAr:'مربع محيطه ٣٢ سم. ما مساحته؟', questionImageUrl:null, options:[{text:'٤٨ سم²'},{text:'٦٠ سم²'},{text:'٦٤ سم²'},{text:'٨٠ سم²'}], correctOptionIndex:2, explanationAr:'المحيط = ٤×الضلع → الضلع = ٣٢÷٤ = ٨. المساحة = ٨² = ٦٤ سم².', tags:[] },
  { ageGroup:'10-12', skillArea:'quantitative', subSkill:'النسبة والتناسب', difficulty:'medium', questionType:'text', questionTextAr:'أنجز عامل ٤٠٪ من المشروع في ٤ أيام. كم يوماً لإنجاز الباقي؟', questionImageUrl:null, options:[{text:'٤'},{text:'٥'},{text:'٦'},{text:'٧'}], correctOptionIndex:2, explanationAr:'٤ أيام = ٤٠٪. الباقي = ٦٠٪. بالتناسب: ٦٠٪ تحتاج ٦ أيام.', tags:[] },
  { ageGroup:'10-12', skillArea:'quantitative', subSkill:'الجبر', difficulty:'medium', questionType:'text', questionTextAr:'ما قيمة س إذا كان س² = ٤٩؟', questionImageUrl:null, options:[{text:'٦'},{text:'٧'},{text:'٨'},{text:'٩'}], correctOptionIndex:1, explanationAr:'س² = ٤٩ → س = √٤٩ = ٧. (لأن ٧×٧=٤٩)', tags:[] },
  { ageGroup:'10-12', skillArea:'quantitative', subSkill:'الهندسة', difficulty:'medium', questionType:'text', questionTextAr:'دائرة نصف قطرها ٧ سم. ما محيطها؟ (استخدم π ≈ ٢٢/٧)', questionImageUrl:null, options:[{text:'٣٨ سم'},{text:'٤٢ سم'},{text:'٤٤ سم'},{text:'٤٨ سم'}], correctOptionIndex:2, explanationAr:'المحيط = ٢πر = ٢ × (٢٢/٧) × ٧ = ٢ × ٢٢ = ٤٤ سم.', tags:[] },
  { ageGroup:'10-12', skillArea:'quantitative', subSkill:'النسبة والتناسب', difficulty:'medium', questionType:'text', questionTextAr:'إذا كانت خصومة على سلعة ٣٠٪ وسعرها الأصلي ٢٠٠ ريال، فكم سعرها بعد الخصم؟', questionImageUrl:null, options:[{text:'١٢٠'},{text:'١٣٠'},{text:'١٤٠'},{text:'١٥٠'}], correctOptionIndex:2, explanationAr:'الخصم = ٣٠٪ × ٢٠٠ = ٦٠. السعر بعد الخصم = ٢٠٠ - ٦٠ = ١٤٠ ريال.', tags:[] },
  { ageGroup:'10-12', skillArea:'quantitative', subSkill:'الجبر', difficulty:'medium', questionType:'text', questionTextAr:'إذا كان الطول × (الطول - ٢) = ٢٤ وأحد الأبعاد ٦، ما البعد الآخر؟', questionImageUrl:null, options:[{text:'٣'},{text:'٤'},{text:'٥'},{text:'٦'}], correctOptionIndex:1, explanationAr:'٦ × (٦-٢) = ٦ × ٤ = ٢٤. البعد الآخر = ٦-٢ = ٤.', tags:[] },

  // عمر 10-12 — كمي — صعب
  { ageGroup:'10-12', skillArea:'quantitative', subSkill:'الاحتمالات', difficulty:'hard', questionType:'text', questionTextAr:'كيس فيه ٣ كرات حمراء و٢ زرقاء. ما احتمال سحب كرة حمراء؟', questionImageUrl:null, options:[{text:'٢/٥'},{text:'٣/٥'},{text:'١/٢'},{text:'٣/٢'}], correctOptionIndex:1, explanationAr:'إجمالي الكرات = ٥. الكرات الحمراء = ٣. الاحتمال = ٣/٥.', tags:[] },
  { ageGroup:'10-12', skillArea:'quantitative', subSkill:'الجبر المتقدم', difficulty:'hard', questionType:'text', questionTextAr:'حل: ٢س + ٣ص = ١٢ عندما ص = ٢', questionImageUrl:null, options:[{text:'س = ٢'},{text:'س = ٣'},{text:'س = ٤'},{text:'س = ٥'}], correctOptionIndex:1, explanationAr:'نعوض ص=٢: ٢س+٦=١٢ → ٢س=٦ → س=٣.', tags:[] },
  { ageGroup:'10-12', skillArea:'quantitative', subSkill:'الهندسة المتقدمة', difficulty:'hard', questionType:'text', questionTextAr:'مكعب طول ضلعه ٤ سم. ما حجمه؟', questionImageUrl:null, options:[{text:'٤٨ سم³'},{text:'٦٠ سم³'},{text:'٦٤ سم³'},{text:'٨٠ سم³'}], correctOptionIndex:2, explanationAr:'حجم المكعب = الضلع³ = ٤×٤×٤ = ٦٤ سم³.', tags:[] },
  { ageGroup:'10-12', skillArea:'quantitative', subSkill:'الاحتمالات', difficulty:'hard', questionType:'text', questionTextAr:'رُمي حجر نرد مرة واحدة. ما احتمال ظهور عدد زوجي؟', questionImageUrl:null, options:[{text:'١/٦'},{text:'١/٣'},{text:'١/٢'},{text:'٢/٣'}], correctOptionIndex:2, explanationAr:'الأعداد الزوجية على النرد: ٢، ٤، ٦ أي ٣ من ٦. الاحتمال = ٣/٦ = ١/٢.', tags:[] },
  { ageGroup:'10-12', skillArea:'quantitative', subSkill:'الأنماط المتقدمة', difficulty:'hard', questionType:'text', questionTextAr:'ما مجموع الأعداد من ١ إلى ١٠٠؟', questionImageUrl:null, options:[{text:'٤٥٠٠'},{text:'٥٠٠٠'},{text:'٥٠٥٠'},{text:'٥٥٠٠'}], correctOptionIndex:2, explanationAr:'المجموع = (٥٠ × ١٠١) = ٥٠٥٠. أو بالقاعدة: ن(ن+١)/٢ = ١٠٠×١٠١/٢ = ٥٠٥٠.', tags:[] },
  { ageGroup:'10-12', skillArea:'quantitative', subSkill:'الاحتمالات', difficulty:'hard', questionType:'text', questionTextAr:'رُميت عملة نقود مرتين. ما احتمال ظهور صورة مرتين؟', questionImageUrl:null, options:[{text:'١/٤'},{text:'١/٢'},{text:'٣/٤'},{text:'١'}], correctOptionIndex:0, explanationAr:'احتمال صورة في الأولى = ١/٢، وفي الثانية = ١/٢. الاحتمالان مستقلان: ١/٢ × ١/٢ = ١/٤.', tags:[] },
  { ageGroup:'10-12', skillArea:'quantitative', subSkill:'الجبر المتقدم', difficulty:'hard', questionType:'text', questionTextAr:'إذا كان س² - ٥س + ٦ = ٠، ما قيمتا س؟', questionImageUrl:null, options:[{text:'١ و٦'},{text:'٢ و٣'},{text:'٣ و٤'},{text:'-٢ و-٣'}], correctOptionIndex:1, explanationAr:'نحلل: (س-٢)(س-٣)=٠ → س=٢ أو س=٣.', tags:[] },
  { ageGroup:'10-12', skillArea:'quantitative', subSkill:'الهندسة المتقدمة', difficulty:'hard', questionType:'text', questionTextAr:'مثلث قاعدته ١٠ سم وارتفاعه ٦ سم. ما مساحته؟', questionImageUrl:null, options:[{text:'٢٥ سم²'},{text:'٣٠ سم²'},{text:'٤٠ سم²'},{text:'٦٠ سم²'}], correctOptionIndex:1, explanationAr:'مساحة المثلث = (القاعدة × الارتفاع) / ٢ = (١٠ × ٦) / ٢ = ٣٠ سم².', tags:[] },
  { ageGroup:'10-12', skillArea:'quantitative', subSkill:'التحليل', difficulty:'hard', questionType:'text', questionTextAr:'إذا كانت ن = ن-١ + ن-٢ للسلسلة ١، ١، ٢، ٣، ٥، ما الحد العاشر؟', questionImageUrl:null, options:[{text:'٣٤'},{text:'٥٥'},{text:'٨٩'},{text:'١٤٤'}], correctOptionIndex:1, explanationAr:'متتالية فيبوناتشي: ١،١،٢،٣،٥،٨،١٣،٢١،٣٤،٥٥. الحد العاشر هو ٥٥.', tags:[] },
  { ageGroup:'10-12', skillArea:'quantitative', subSkill:'المسائل المتقدمة', difficulty:'hard', questionType:'text', questionTextAr:'قطار يسير بسرعة ٩٠ كم/ساعة. كم يقطع في ٤٠ دقيقة؟', questionImageUrl:null, options:[{text:'٥٠ كم'},{text:'٥٥ كم'},{text:'٦٠ كم'},{text:'٦٥ كم'}], correctOptionIndex:2, explanationAr:'٤٠ دقيقة = ٢/٣ ساعة. المسافة = السرعة × الزمن = ٩٠ × ٢/٣ = ٦٠ كم.', tags:[] },

  // ═══════════════════════════════════════════════
  // عمر 10-12 — لفظي — سهل
  // ═══════════════════════════════════════════════
  { ageGroup:'10-12', skillArea:'verbal', subSkill:'المفردات المتقدمة', difficulty:'easy', questionType:'text', questionTextAr:'ما معنى كلمة "مُبهم"؟', questionImageUrl:null, options:[{text:'واضح وصريح'},{text:'غير واضح وملتبس'},{text:'مفرح وسار'},{text:'صعب ومعقد'}], correctOptionIndex:1, explanationAr:'"مبهم" تعني غير واضح أو ملتبس. نقول "كلام مبهم" أي كلام غير مفهوم بوضوح.', tags:[] },
  { ageGroup:'10-12', skillArea:'verbal', subSkill:'المفردات المتقدمة', difficulty:'easy', questionType:'text', questionTextAr:'ما مرادف "النزاهة"؟', questionImageUrl:null, options:[{text:'الكذب'},{text:'الأمانة والصدق'},{text:'الغرور'},{text:'البخل'}], correctOptionIndex:1, explanationAr:'"النزاهة" تعني الأمانة والصدق والبُعد عن الفساد. شخص نزيه لا يقبل الرشوة.', tags:[] },
  { ageGroup:'10-12', skillArea:'verbal', subSkill:'المفردات المتقدمة', difficulty:'easy', questionType:'text', questionTextAr:'ما معنى "يتهاون"؟', questionImageUrl:null, options:[{text:'يجتهد بجدية'},{text:'يتساهل ولا يُعطي الأهمية'},{text:'يعمل بنشاط'},{text:'يتفوق دائماً'}], correctOptionIndex:1, explanationAr:'"يتهاون" تعني يتساهل ولا يُعطي الأمر حقه من الاهتمام والجدية.', tags:[] },
  { ageGroup:'10-12', skillArea:'verbal', subSkill:'المتضادات المتقدمة', difficulty:'easy', questionType:'text', questionTextAr:'ما عكس كلمة "الإجمال"؟', questionImageUrl:null, options:[{text:'الإيجاز'},{text:'التفصيل'},{text:'الاختصار'},{text:'التقليل'}], correctOptionIndex:1, explanationAr:'عكس "الإجمال" (الإيجاز والاختصار) هو "التفصيل" (الشرح المطول).', tags:[] },
  { ageGroup:'10-12', skillArea:'verbal', subSkill:'المفردات المتقدمة', difficulty:'easy', questionType:'text', questionTextAr:'ما معنى "يستشف"؟', questionImageUrl:null, options:[{text:'يشفى من مرض'},{text:'يستنتج ويستخلص'},{text:'يضع في مستشفى'},{text:'يصنع دواء'}], correctOptionIndex:1, explanationAr:'"يستشف" تعني يستنتج ويستخلص معنى خفياً من كلام أو موقف.', tags:[] },
  { ageGroup:'10-12', skillArea:'verbal', subSkill:'المتضادات المتقدمة', difficulty:'easy', questionType:'text', questionTextAr:'ما عكس "الطاعة"؟', questionImageUrl:null, options:[{text:'الحكمة'},{text:'الشجاعة'},{text:'العصيان'},{text:'الكرم'}], correctOptionIndex:2, explanationAr:'عكس "الطاعة" هو "العصيان" أو "المعصية". الطاعة الالتزام بالأوامر والعصيان مخالفتها.', tags:[] },
  { ageGroup:'10-12', skillArea:'verbal', subSkill:'المفردات المتقدمة', difficulty:'easy', questionType:'text', questionTextAr:'ما معنى "التراكم"؟', questionImageUrl:null, options:[{text:'التناقص التدريجي'},{text:'التجمع والتكدس'},{text:'الانتشار السريع'},{text:'الاختفاء التام'}], correctOptionIndex:1, explanationAr:'"التراكم" يعني تجمع الأشياء فوق بعضها تدريجياً. مثل تراكم الغبار أو الديون.', tags:[] },
  { ageGroup:'10-12', skillArea:'verbal', subSkill:'المتضادات المتقدمة', difficulty:'easy', questionType:'text', questionTextAr:'ما عكس "الإسراف"؟', questionImageUrl:null, options:[{text:'الكرم'},{text:'الجود'},{text:'القصد والاعتدال'},{text:'البخل'}], correctOptionIndex:2, explanationAr:'عكس "الإسراف" (المبالغة في الإنفاق) هو "القصد" أو "الاعتدال". البخل طرف آخر.', tags:[] },
  { ageGroup:'10-12', skillArea:'verbal', subSkill:'المفردات المتقدمة', difficulty:'easy', questionType:'text', questionTextAr:'ما معنى "المثابرة"؟', questionImageUrl:null, options:[{text:'الاستسلام السريع'},{text:'الكسل والتقاعس'},{text:'الاستمرار والمواظبة'},{text:'العجلة والتسرع'}], correctOptionIndex:2, explanationAr:'"المثابرة" هي الاستمرار في العمل والمواظبة دون تراجع. صفة ضرورية للنجاح.', tags:[] },
  { ageGroup:'10-12', skillArea:'verbal', subSkill:'المتضادات المتقدمة', difficulty:'easy', questionType:'text', questionTextAr:'ما عكس "الغموض"؟', questionImageUrl:null, options:[{text:'التعقيد'},{text:'الوضوح'},{text:'التشابك'},{text:'الإبهام'}], correctOptionIndex:1, explanationAr:'عكس "الغموض" هو "الوضوح". الغامض غير مفهوم، والواضح مفهوم بسهولة.', tags:[] },

  // عمر 10-12 — لفظي — متوسط
  { ageGroup:'10-12', skillArea:'verbal', subSkill:'التناظر اللغوي', difficulty:'medium', questionType:'text', questionTextAr:'الرسام : الفرشاة = النجار : ؟', questionImageUrl:null, options:[{text:'الخشب'},{text:'المنشار'},{text:'المسمار'},{text:'الطلاء'}], correctOptionIndex:1, explanationAr:'الرسام يستخدم الفرشاة كأداة رئيسية، والنجار يستخدم المنشار كأداته الرئيسية.', tags:[] },
  { ageGroup:'10-12', skillArea:'verbal', subSkill:'الفهم القرائي', difficulty:'medium', questionType:'text', questionTextAr:'قرأت: "المثابرة مفتاح النجاح، فمن يصبر ويداوم على العمل يصل إلى هدفه مهما كانت العقبات." ما الفكرة الرئيسية؟', questionImageUrl:null, options:[{text:'النجاح سهل دائماً'},{text:'المثابرة تقود للنجاح رغم العقبات'},{text:'يجب تجنب العقبات'},{text:'الصبر وحده يكفي'}], correctOptionIndex:1, explanationAr:'النص يؤكد أن المثابرة مع الصبر يقودان للنجاح حتى في وجود العقبات.', tags:[] },
  { ageGroup:'10-12', skillArea:'verbal', subSkill:'التناظر اللغوي', difficulty:'medium', questionType:'text', questionTextAr:'الطيار : الطائرة = البحار : ؟', questionImageUrl:null, options:[{text:'البحر'},{text:'السفينة'},{text:'المرساة'},{text:'الميناء'}], correctOptionIndex:1, explanationAr:'الطيار يقود الطائرة، والبحار يقود السفينة. هذا تناظر بين الشخص وما يقوده.', tags:[] },
  { ageGroup:'10-12', skillArea:'verbal', subSkill:'الخطأ السياقي', difficulty:'medium', questionType:'text', questionTextAr:'أي جملة فيها خطأ سياقي: "الشمس تشرق في الشرق"، "الجليد يذوب في الحر"، "النار تُجمّد الماء"؟', questionImageUrl:null, options:[{text:'الأولى'},{text:'الثانية'},{text:'الثالثة'},{text:'لا يوجد خطأ'}], correctOptionIndex:2, explanationAr:'"النار تجمد الماء" خطأ سياقي. النار تسخن وتذيب وليس تجمد. الجملتان الأوليان صحيحتان.', tags:[] },
  { ageGroup:'10-12', skillArea:'verbal', subSkill:'التناظر اللغوي', difficulty:'medium', questionType:'text', questionTextAr:'الربيع : الازدهار = الشتاء : ؟', questionImageUrl:null, options:[{text:'المطر'},{text:'البرودة'},{text:'الخمول'},{text:'الثلج'}], correctOptionIndex:1, explanationAr:'الربيع يرمز للازدهار والنمو، والشتاء يرمز للبرودة والركود.', tags:[] },
  { ageGroup:'10-12', skillArea:'verbal', subSkill:'الفهم القرائي', difficulty:'medium', questionType:'text', questionTextAr:'قرأت: "إن العلم نور يضيء العقول ويرفع الأمم، وبه تتحقق التنمية والتقدم." ما الذي يرفع الأمم وفق النص؟', questionImageUrl:null, options:[{text:'المال'},{text:'القوة العسكرية'},{text:'العلم'},{text:'الموارد الطبيعية'}], correctOptionIndex:2, explanationAr:'النص يقول صراحة أن العلم هو ما يرفع الأمم ويحقق التنمية والتقدم.', tags:[] },
  { ageGroup:'10-12', skillArea:'verbal', subSkill:'التناظر اللغوي', difficulty:'medium', questionType:'text', questionTextAr:'القضاء : العدالة = التعليم : ؟', questionImageUrl:null, options:[{text:'الكتب'},{text:'المعرفة'},{text:'المدارس'},{text:'المعلمون'}], correctOptionIndex:1, explanationAr:'القضاء غايته تحقيق العدالة، والتعليم غايته نشر المعرفة.', tags:[] },
  { ageGroup:'10-12', skillArea:'verbal', subSkill:'الخطأ السياقي', difficulty:'medium', questionType:'text', questionTextAr:'أي كلمة خطأ سياقي: "الشاعر كتب قصيدة رائعة وقرأها بصوت عالٍ على المُستمعين"؟', questionImageUrl:null, options:[{text:'الشاعر'},{text:'قصيدة'},{text:'لا يوجد خطأ'},{text:'المستمعين'}], correctOptionIndex:2, explanationAr:'الجملة صحيحة تماماً سياقياً. الشاعر يكتب القصائد ويقرأها على المستمعين.', tags:[] },
  { ageGroup:'10-12', skillArea:'verbal', subSkill:'التناظر اللغوي', difficulty:'medium', questionType:'text', questionTextAr:'الكلمة : الجملة = الجملة : ؟', questionImageUrl:null, options:[{text:'الحرف'},{text:'المقطع'},{text:'الفقرة'},{text:'الكلمة'}], correctOptionIndex:2, explanationAr:'الكلمات تتكون منها الجملة، والجمل تتكون منها الفقرة. تناظر تركيبي متسلسل.', tags:[] },
  { ageGroup:'10-12', skillArea:'verbal', subSkill:'الفهم القرائي', difficulty:'medium', questionType:'text', questionTextAr:'قرأت: "الوقت كالسيف إن لم تقطعه قطعك." ماذا يقصد الكاتب؟', questionImageUrl:null, options:[{text:'الوقت أداة حادة'},{text:'من لا يستثمر وقته يخسره'},{text:'السيف أهم من الوقت'},{text:'الوقت خطر جداً'}], correctOptionIndex:1, explanationAr:'المقصود: من لا يستثمر وقته ويستغله بالعمل المفيد، ضاع عمره وخسر. هو كناية عن أهمية الوقت.', tags:[] },

  // عمر 10-12 — لفظي — صعب
  { ageGroup:'10-12', skillArea:'verbal', subSkill:'الاستنتاج من النص', difficulty:'hard', questionType:'text', questionTextAr:'قرأت: "لم تكن الرحلة سهلة، لكن الفريق لم يتراجع. واجهوا العواصف والإرهاق، وفي النهاية وصلوا." ما الصفة الغالبة على الفريق؟', questionImageUrl:null, options:[{text:'الخوف'},{text:'الكسل'},{text:'الإصرار'},{text:'التهور'}], correctOptionIndex:2, explanationAr:'النص يصف مواجهتهم للصعاب دون تراجع — هذا يدل على الإصرار والعزيمة.', tags:[] },
  { ageGroup:'10-12', skillArea:'verbal', subSkill:'التناظر المعقد', difficulty:'hard', questionType:'text', questionTextAr:'الإهمال : الفشل = الاجتهاد : ؟', questionImageUrl:null, options:[{text:'الكسل'},{text:'التعب'},{text:'النجاح'},{text:'المحاولة'}], correctOptionIndex:2, explanationAr:'الإهمال سبب الفشل، والاجتهاد سبب النجاح. تناظر سبب ونتيجة.', tags:[] },
  { ageGroup:'10-12', skillArea:'verbal', subSkill:'الخطأ السياقي المتقدم', difficulty:'hard', questionType:'text', questionTextAr:'أي جملة صحيحة منطقياً وسياقياً؟', questionImageUrl:null, options:[{text:'ابتلع الجبل البحيرة كاملة'},{text:'قرأ العالم الكتاب بعناية ليفهم النظرية'},{text:'شرب القلم الحبر وكتب بالماء'},{text:'نامت الأفكار في الدرج الأيمن'}], correctOptionIndex:1, explanationAr:'"قرأ العالم الكتاب بعناية" منطقية وصحيحة. باقي الجمل تنسب أفعالاً لغير مالكيها.', tags:[] },
  { ageGroup:'10-12', skillArea:'verbal', subSkill:'الاستنتاج من النص', difficulty:'hard', questionType:'text', questionTextAr:'قرأت: "ازداد تلوث الهواء في المدن مع نمو الصناعة." ما الاستنتاج المنطقي؟', questionImageUrl:null, options:[{text:'الصناعة مفيدة فقط'},{text:'التلوث لا علاقة له بالصناعة'},{text:'الصناعة تساهم في تلوث الهواء'},{text:'المدن أنظف من الريف'}], correctOptionIndex:2, explanationAr:'النص يقول "ازداد التلوث مع نمو الصناعة" — هذا دليل على علاقة سببية بين الصناعة والتلوث.', tags:[] },
  { ageGroup:'10-12', skillArea:'verbal', subSkill:'التناظر المعقد', difficulty:'hard', questionType:'text', questionTextAr:'الديمقراطية : الانتخاب = الملكية : ؟', questionImageUrl:null, options:[{text:'البرلمان'},{text:'الوراثة'},{text:'الانقلاب'},{text:'التصويت'}], correctOptionIndex:1, explanationAr:'في الديمقراطية يُختار الحاكم بالانتخاب، وفي الملكية ينتقل الحكم بالوراثة.', tags:[] },
  { ageGroup:'10-12', skillArea:'verbal', subSkill:'الاستنتاج من النص', difficulty:'hard', questionType:'text', questionTextAr:'قرأت: "لكل إنسان طاقة محدودة. النجاح الحقيقي في توزيع هذه الطاقة بذكاء." ما النتيجة؟', questionImageUrl:null, options:[{text:'يجب العمل بلا توقف'},{text:'إدارة الطاقة أهم من كميتها'},{text:'الكسل مقبول أحياناً'},{text:'الطاقة لا تنفد'}], correctOptionIndex:1, explanationAr:'النص يقول إن التوزيع الذكي للطاقة هو مفتاح النجاح — أي الإدارة أهم من الكمية.', tags:[] },
  { ageGroup:'10-12', skillArea:'verbal', subSkill:'التناظر المعقد', difficulty:'hard', questionType:'text', questionTextAr:'البذرة : الشجرة = الفكرة : ؟', questionImageUrl:null, options:[{text:'الكتاب'},{text:'العقل'},{text:'المشروع'},{text:'العلم'}], correctOptionIndex:2, explanationAr:'البذرة تنمو لتصبح شجرة، والفكرة تتطور لتصبح مشروعاً. تناظر نمو وتطور.', tags:[] },
  { ageGroup:'10-12', skillArea:'verbal', subSkill:'الخطأ السياقي المتقدم', difficulty:'hard', questionType:'text', questionTextAr:'أي جملة فيها خطأ دلالي: "شعر الطالب بالفرح عند سماع النتيجة الجيدة"، "تألم المريض من الألم"، "تألم المريض من الدواء"؟', questionImageUrl:null, options:[{text:'الأولى'},{text:'الثانية'},{text:'الثالثة'},{text:'لا يوجد خطأ'}], correctOptionIndex:1, explanationAr:'"تألم المريض من الألم" تحصيل حاصل — ليست جملة ذات معنى إضافي. هي خطأ دلالي بالتكرار.', tags:[] },
  { ageGroup:'10-12', skillArea:'verbal', subSkill:'الاستنتاج من النص', difficulty:'hard', questionType:'text', questionTextAr:'قرأت: "من لا يُجرّب لا يكتسب خبرة، ومن لا تكون له خبرة لا يُحكم في الأمور." ما الخلاصة؟', questionImageUrl:null, options:[{text:'التجربة تضيع الوقت'},{text:'الخبرة تأتي من التجربة وتُنتج حكمة'},{text:'يجب تجنب التجارب الصعبة'},{text:'الحكمة فطرية لا مكتسبة'}], correctOptionIndex:1, explanationAr:'السلسلة: تجربة → خبرة → حكم سليم. التجربة هي أصل الخبرة التي تُنتج الحكمة.', tags:[] },
  { ageGroup:'10-12', skillArea:'verbal', subSkill:'التناظر المعقد', difficulty:'hard', questionType:'text', questionTextAr:'الفوضى : النظام = الجهل : ؟', questionImageUrl:null, options:[{text:'التعلم'},{text:'الكتاب'},{text:'العلم'},{text:'المدرسة'}], correctOptionIndex:2, explanationAr:'الفوضى عكس النظام، والجهل عكس العلم. تناظر بين المتضادات.', tags:[] },

  // ═══════════════════════════════════════════════
  // عمر 10-12 — منطقي — سهل
  // ═══════════════════════════════════════════════
  { ageGroup:'10-12', skillArea:'logical_patterns', subSkill:'السلاسل الرقمية', difficulty:'easy', questionType:'text', questionTextAr:'ما التالي: ٣، ٦، ١٢، ٢٤، __؟', questionImageUrl:null, options:[{text:'٣٦'},{text:'٤٢'},{text:'٤٨'},{text:'٥٠'}], correctOptionIndex:2, explanationAr:'كل رقم يُضرب في ٢: ٣×٢=٦، ٦×٢=١٢، ١٢×٢=٢٤، ٢٤×٢=٤٨.', tags:[] },
  { ageGroup:'10-12', skillArea:'logical_patterns', subSkill:'الاستنتاج', difficulty:'easy', questionType:'text', questionTextAr:'كل الثدييات تتنفس هواء. الحوت ثديي. هل الحوت يتنفس هواء؟', questionImageUrl:null, options:[{text:'لا لأنه يعيش في الماء'},{text:'نعم'},{text:'أحياناً'},{text:'لا أعرف'}], correctOptionIndex:1, explanationAr:'نعم. بالرغم من عيشه في الماء، الحوت ثديي يتنفس هواء من خلال خياشيمه على سطح الماء.', tags:[] },
  { ageGroup:'10-12', skillArea:'logical_patterns', subSkill:'السلاسل الرقمية', difficulty:'easy', questionType:'text', questionTextAr:'ما الرقم المفقود: ٢، ٥، ٨، ١١، __؟', questionImageUrl:null, options:[{text:'١٢'},{text:'١٣'},{text:'١٤'},{text:'١٥'}], correctOptionIndex:2, explanationAr:'النمط هو إضافة ٣: ٢+٣=٥، ٥+٣=٨، ٨+٣=١١، ١١+٣=١٤.', tags:[] },
  { ageGroup:'10-12', skillArea:'logical_patterns', subSkill:'القياس', difficulty:'easy', questionType:'text', questionTextAr:'إذا كان كل المدراء موظفون، وسالم مدير، فهل سالم موظف؟', questionImageUrl:null, options:[{text:'لا'},{text:'نعم'},{text:'ربما'},{text:'لا يمكن التحديد'}], correctOptionIndex:1, explanationAr:'نعم. كل مدير = موظف، وسالم مدير، إذن سالم موظف. هذا قياس منطقي صحيح.', tags:[] },
  { ageGroup:'10-12', skillArea:'logical_patterns', subSkill:'السلاسل الرقمية', difficulty:'easy', questionType:'text', questionTextAr:'ما التالي: ١، ٨، ٢٧، ٦٤، __؟', questionImageUrl:null, options:[{text:'١٠٠'},{text:'١١٩'},{text:'١٢٥'},{text:'١٣٦'}], correctOptionIndex:2, explanationAr:'هذه مكعبات الأعداد: ١³=١، ٢³=٨، ٣³=٢٧، ٤³=٦٤، ٥³=١٢٥.', tags:[] },
  { ageGroup:'10-12', skillArea:'logical_patterns', subSkill:'الاستنتاج', difficulty:'easy', questionType:'text', questionTextAr:'إذا كان ٣س = ١٥، هل س أكبر من ٤؟', questionImageUrl:null, options:[{text:'نعم'},{text:'لا'},{text:'لا يمكن التحديد'},{text:'متساوٍ مع ٤'}], correctOptionIndex:0, explanationAr:'س = ١٥÷٣ = ٥. وبما أن ٥ > ٤، فنعم س أكبر من ٤.', tags:[] },
  { ageGroup:'10-12', skillArea:'logical_patterns', subSkill:'السلاسل الرقمية', difficulty:'easy', questionType:'text', questionTextAr:'ما الرقم المفقود: ٧، ١٤، ٢١، ٢٨، __؟', questionImageUrl:null, options:[{text:'٣٣'},{text:'٣٤'},{text:'٣٥'},{text:'٣٦'}], correctOptionIndex:2, explanationAr:'مضاعفات ٧: ٧، ١٤، ٢١، ٢٨، ٣٥.', tags:[] },
  { ageGroup:'10-12', skillArea:'logical_patterns', subSkill:'القياس', difficulty:'easy', questionType:'text', questionTextAr:'لا يوجد مربع له ٣ زوايا. هذا الشكل له ٣ زوايا. هل هو مربع؟', questionImageUrl:null, options:[{text:'نعم'},{text:'لا'},{text:'ربما'},{text:'يحتاج معلومات أكثر'}], correctOptionIndex:1, explanationAr:'لا. المربع له ٤ زوايا. الشكل ذو ٣ زوايا هو مثلث وليس مربعاً.', tags:[] },
  { ageGroup:'10-12', skillArea:'logical_patterns', subSkill:'السلاسل الرقمية', difficulty:'easy', questionType:'text', questionTextAr:'ما التالي: ٥٠، ٤٥، ٤٠، ٣٥، __؟', questionImageUrl:null, options:[{text:'٢٨'},{text:'٣٠'},{text:'٣٢'},{text:'٣٤'}], correctOptionIndex:1, explanationAr:'النمط هو طرح ٥: ٥٠-٥=٤٥، ٤٥-٥=٤٠، ٤٠-٥=٣٥، ٣٥-٥=٣٠.', tags:[] },
  { ageGroup:'10-12', skillArea:'logical_patterns', subSkill:'الاستنتاج', difficulty:'easy', questionType:'text', questionTextAr:'إذا كانت ٣ كتب تكلف ٣٦ ريال، كم تكلف ٧ كتب؟', questionImageUrl:null, options:[{text:'٧٠'},{text:'٧٤'},{text:'٨٢'},{text:'٨٤'}], correctOptionIndex:3, explanationAr:'سعر الكتاب الواحد = ٣٦÷٣ = ١٢. ٧ كتب = ٧×١٢ = ٨٤ ريال.', tags:[] },

  // عمر 10-12 — منطقي — متوسط
  { ageGroup:'10-12', skillArea:'logical_patterns', subSkill:'الاستدلال المنطقي', difficulty:'medium', questionType:'text', questionTextAr:'إذا كانت كل X تكون Y وبعض Y تكون Z، فما الذي يمكن استنتاجه؟', questionImageUrl:null, options:[{text:'كل X تكون Z'},{text:'بعض X قد تكون Z'},{text:'لا علاقة بين X وZ'},{text:'X = Z دائماً'}], correctOptionIndex:1, explanationAr:'كل X هي Y، وبعض Y هي Z. يمكن أن بعض X تقع ضمن الـ Y التي هي Z. إذن بعض X قد تكون Z.', tags:[] },
  { ageGroup:'10-12', skillArea:'logical_patterns', subSkill:'السلاسل المتقدمة', difficulty:'medium', questionType:'text', questionTextAr:'ما التالي: ٢، ٣، ٥، ٧، ١١، ١٣، __؟', questionImageUrl:null, options:[{text:'١٥'},{text:'١٦'},{text:'١٧'},{text:'١٩'}], correctOptionIndex:2, explanationAr:'هذه الأعداد الأولية بالترتيب: ٢، ٣، ٥، ٧، ١١، ١٣، ١٧.', tags:[] },
  { ageGroup:'10-12', skillArea:'logical_patterns', subSkill:'الاستدلال المنطقي', difficulty:'medium', questionType:'text', questionTextAr:'كل الشعراء حساسون. بعض الفنانين شعراء. ما الذي يلزم؟', questionImageUrl:null, options:[{text:'كل الفنانين حساسون'},{text:'لا أحد من الفنانين حساس'},{text:'بعض الفنانين حساسون'},{text:'الفنانون ليسوا حساسين'}], correctOptionIndex:2, explanationAr:'بعض الفنانين = شعراء. وكل الشعراء = حساسون. إذن بعض الفنانين (الذين هم شعراء) حساسون.', tags:[] },
  { ageGroup:'10-12', skillArea:'logical_patterns', subSkill:'الأنماط المتقدمة', difficulty:'medium', questionType:'text', questionTextAr:'ما الرقم المفقود: ٢، ٦، ١٢، ٢٠، ٣٠، __؟', questionImageUrl:null, options:[{text:'٣٨'},{text:'٤٠'},{text:'٤٢'},{text:'٤٤'}], correctOptionIndex:2, explanationAr:'الفروق: +٤، +٦، +٨، +١٠، +١٢. بعد ٣٠: ٣٠+١٢=٤٢.', tags:[] },
  { ageGroup:'10-12', skillArea:'logical_patterns', subSkill:'الاستدلال المنطقي', difficulty:'medium', questionType:'text', questionTextAr:'إذا "ليس كل الطلاب مجتهدون" فأي جملة صحيحة بالضرورة؟', questionImageUrl:null, options:[{text:'لا أحد مجتهد'},{text:'كلهم كسالى'},{text:'بعض الطلاب ليسوا مجتهدين'},{text:'كلهم مجتهدون'}], correctOptionIndex:2, explanationAr:'"ليس كل" = بعضهم ليسوا. إذن بعض الطلاب ليسوا مجتهدين.', tags:[] },
  { ageGroup:'10-12', skillArea:'logical_patterns', subSkill:'السلاسل المتقدمة', difficulty:'medium', questionType:'text', questionTextAr:'ما التالي: ١، ٤، ١٠، ٢٠، ٣٥، __؟', questionImageUrl:null, options:[{text:'٥٠'},{text:'٥٣'},{text:'٥٦'},{text:'٥٨'}], correctOptionIndex:1, explanationAr:'الفروق: +٣، +٦، +١٠، +١٥، +٢١. (الفروق نفسها هي أعداد مثلثية). بعد ٣٥: ٣٥+٢١=٥٦. تصحيح: +٣،+٦،+١٠،+١٥ → الفرق +٥،+٤،+٥ → ٣٥+٢١=٥٦.', tags:[] },
  { ageGroup:'10-12', skillArea:'logical_patterns', subSkill:'الاستدلال المنطقي', difficulty:'medium', questionType:'text', questionTextAr:'خالد أذكى من سامي وسامي أذكى من فهد. من الأقل ذكاءً من سامي؟', questionImageUrl:null, options:[{text:'خالد'},{text:'سامي'},{text:'فهد'},{text:'لا يمكن التحديد'}], correctOptionIndex:2, explanationAr:'خالد > سامي > فهد. فهد هو أقل الثلاثة ذكاءً.', tags:[] },
  { ageGroup:'10-12', skillArea:'logical_patterns', subSkill:'الأنماط المتقدمة', difficulty:'medium', questionType:'text', questionTextAr:'ما التالي: أ، ج، هـ، ز، __؟', questionImageUrl:null, options:[{text:'ح'},{text:'ط'},{text:'ي'},{text:'ك'}], correctOptionIndex:1, explanationAr:'حروف الهجاء: أ(١)، ب(٢)، ج(٣)، د(٤)، هـ(٥)، و(٦)، ز(٧)، ح(٨)، ط(٩)... النمط الأحرف الفردية: ١،٣،٥،٧،٩. بعد ز(٧) يأتي ط(٩).', tags:[] },
  { ageGroup:'10-12', skillArea:'logical_patterns', subSkill:'الاستدلال المنطقي', difficulty:'medium', questionType:'text', questionTextAr:'جميع أ هي ب. لا شيء من ب هو ج. ما العلاقة بين أ وج؟', questionImageUrl:null, options:[{text:'أ = ج'},{text:'أ وج مختلفتان تماماً'},{text:'أحياناً أ = ج'},{text:'لا يمكن التحديد'}], correctOptionIndex:1, explanationAr:'كل أ = ب، ولا شيء من ب = ج. إذن لا شيء من أ = ج. أ وج مختلفتان تماماً.', tags:[] },
  { ageGroup:'10-12', skillArea:'logical_patterns', subSkill:'السلاسل المتقدمة', difficulty:'medium', questionType:'text', questionTextAr:'ما الرقم المفقود: ١، ٣، ٦، ١٠، ١٥، __؟', questionImageUrl:null, options:[{text:'٢٠'},{text:'٢١'},{text:'٢٢'},{text:'٢٥'}], correctOptionIndex:1, explanationAr:'هذه الأعداد المثلثية: الفروق +٢،+٣،+٤،+٥،+٦. بعد ١٥: ١٥+٦=٢١.', tags:[] },

  // عمر 10-12 — منطقي — صعب
  { ageGroup:'10-12', skillArea:'logical_patterns', subSkill:'القياس المنطقي المعقد', difficulty:'hard', questionType:'text', questionTextAr:'كل أ هي ب. كل ب هي ج. بعض ج هي د. ما الذي يلزم؟', questionImageUrl:null, options:[{text:'كل أ هي د'},{text:'بعض أ قد تكون د'},{text:'لا علاقة بين أ ود'},{text:'أ لا تكون د أبداً'}], correctOptionIndex:1, explanationAr:'كل أ هي ب، وكل ب هي ج، وبعض ج هي د. أ ⊂ ب ⊂ ج وبعض ج ⊂ د. إذن بعض أ قد تكون د.', tags:[] },
  { ageGroup:'10-12', skillArea:'logical_patterns', subSkill:'السلاسل المعقدة', difficulty:'hard', questionType:'text', questionTextAr:'ما التالي: ١، ٢، ٤، ٨، ١٦، ٣٢، __؟', questionImageUrl:null, options:[{text:'٤٨'},{text:'٦٠'},{text:'٦٤'},{text:'٧٢'}], correctOptionIndex:2, explanationAr:'كل رقم يُضرب في ٢: ٣٢×٢=٦٤. هذه قوى العدد ٢.', tags:[] },
  { ageGroup:'10-12', skillArea:'logical_patterns', subSkill:'القياس المنطقي المعقد', difficulty:'hard', questionType:'text', questionTextAr:'إذا كان "إذا مطر ← فرطوبة" و"رطوبة الآن موجودة". هل مطرت بالضرورة؟', questionImageUrl:null, options:[{text:'نعم'},{text:'لا'},{text:'ليس بالضرورة'},{text:'مستحيل'}], correctOptionIndex:2, explanationAr:'ليس بالضرورة. الرطوبة قد تأتي من مصدر آخر غير المطر. هذا خطأ منطقي يسمى "تأكيد التالي".', tags:[] },
  { ageGroup:'10-12', skillArea:'logical_patterns', subSkill:'السلاسل المعقدة', difficulty:'hard', questionType:'text', questionTextAr:'ما التالي: ٢، ٦، ١٨، ٥٤، __؟', questionImageUrl:null, options:[{text:'١٠٨'},{text:'١٦٢'},{text:'١٢٦'},{text:'١٤٤'}], correctOptionIndex:1, explanationAr:'كل رقم يُضرب في ٣: ٢×٣=٦، ٦×٣=١٨، ١٨×٣=٥٤، ٥٤×٣=١٦٢.', tags:[] },
  { ageGroup:'10-12', skillArea:'logical_patterns', subSkill:'القياس المنطقي المعقد', difficulty:'hard', questionType:'text', questionTextAr:'إذا كان "إذا اجتهدت ← نجحت" ولم تنجح. ماذا نستنتج؟', questionImageUrl:null, options:[{text:'اجتهدت'},{text:'لم تجتهد'},{text:'ربما اجتهدت'},{text:'لا يمكن الاستنتاج'}], correctOptionIndex:1, explanationAr:'بالنفي المنطقي: "إذا أ ← ب" فنفي ب يعني نفي أ. لم ينجح → لم يجتهد. (مبدأ نقيض الشرطية)', tags:[] },
  { ageGroup:'10-12', skillArea:'logical_patterns', subSkill:'الاستدلال الرياضي', difficulty:'hard', questionType:'text', questionTextAr:'إذا كان مجموع ٣ أعداد متتالية ٥١، ما الأعداد؟', questionImageUrl:null, options:[{text:'١٥، ١٦، ١٧'},{text:'١٦، ١٧، ١٨'},{text:'١٧، ١٨، ١٩'},{text:'١٨، ١٩، ٢٠'}], correctOptionIndex:1, explanationAr:'الأعداد: ن، ن+١، ن+٢. مجموعها = ٣ن+٣ = ٥١ → ٣ن = ٤٨ → ن = ١٦. الأعداد: ١٦، ١٧، ١٨.', tags:[] },
  { ageGroup:'10-12', skillArea:'logical_patterns', subSkill:'السلاسل المعقدة', difficulty:'hard', questionType:'text', questionTextAr:'ما الرقم المفقود: ١، ٣، ٧، ١٣، ٢١، __؟', questionImageUrl:null, options:[{text:'٢٩'},{text:'٣١'},{text:'٣٣'},{text:'٣٥'}], correctOptionIndex:1, explanationAr:'الفروق: +٢، +٤، +٦، +٨، +١٠. بعد ٢١: ٢١+١٠=٣١.', tags:[] },
  { ageGroup:'10-12', skillArea:'logical_patterns', subSkill:'القياس المنطقي المعقد', difficulty:'hard', questionType:'text', questionTextAr:'إذا كان "الحرارة تمدد المعادن"، ماذا يحدث للجسر المعدني في الصيف الحار؟', questionImageUrl:null, options:[{text:'يتقلص'},{text:'يبقى كما هو'},{text:'يتمدد'},{text:'يذوب'}], correctOptionIndex:2, explanationAr:'الحرارة تمدد المعادن، والصيف حار، إذن الجسر المعدني يتمدد. لهذا تُترك فجوات في الجسور.', tags:[] },
  { ageGroup:'10-12', skillArea:'logical_patterns', subSkill:'الاستدلال الرياضي', difficulty:'hard', questionType:'text', questionTextAr:'في مجموعة من ٣٠ شخصاً، ٢٠ يحبون القهوة و١٥ يحبون الشاي و١٠ يحبون كليهما. كم لا يحب شيئاً؟', questionImageUrl:null, options:[{text:'٣'},{text:'٥'},{text:'٧'},{text:'٨'}], correctOptionIndex:1, explanationAr:'بمبدأ الإدراج والإقصاء: يحبون الأقل واحد = ٢٠+١٥-١٠ = ٢٥. لا يحب شيئاً = ٣٠-٢٥ = ٥.', tags:[] },
  { ageGroup:'10-12', skillArea:'logical_patterns', subSkill:'السلاسل المعقدة', difficulty:'hard', questionType:'text', questionTextAr:'ما التالي: ١، ٢، ٦، ٢٤، ١٢٠، __؟', questionImageUrl:null, options:[{text:'٣٦٠'},{text:'٦٠٠'},{text:'٧٢٠'},{text:'٨٤٠'}], correctOptionIndex:2, explanationAr:'هذه المضروبات (Factorials): ١!=١، ٢!=٢، ٣!=٦، ٤!=٢٤، ٥!=١٢٠، ٦!=٧٢٠.', tags:[] },
];

async function seed2() {
  const client = createClient({ url: process.env.TURSO_DATABASE_URL || 'file:./local.db' });
  const db = drizzle(client);
  console.log('Seeding part 2...');
  let count = 0;
  for (const q of questionData2) {
    await db.insert(questions).values({
      id: crypto.randomUUID(),
      skillArea: q.skillArea,
      subSkill: q.subSkill,
      ageGroup: q.ageGroup,
      difficulty: q.difficulty,
      questionType: q.questionType as 'text' | 'image',
      questionTextAr: q.questionTextAr,
      questionImageUrl: q.questionImageUrl,
      options: q.options as Array<{text: string}>,
      correctOptionIndex: q.correctOptionIndex,
      explanationAr: q.explanationAr,
      tags: q.tags,
      isActive: true,
    }).onConflictDoNothing();
    count++;
  }
  console.log(`Seeded ${count} additional questions`);
  return count;
}

if (require.main === module) {
  seed2().then(n => { console.log(`Done: ${n}`); process.exit(0); }).catch(e => { console.error(e); process.exit(1); });
}
