import { getDb } from './index';
import { questions } from './schema';

const newQuestions = [
  // ==========================================
  // 6-9 سنوات — كمي (18 سؤال)
  // ==========================================
  {
    id: crypto.randomUUID(), ageGroup: '6-9', skillArea: 'quantitative', subSkill: 'number_sequences',
    difficulty: 'easy', questionType: 'text',
    questionTextAr: 'أكمل المتسلسلة: 10 ، 20 ، 30 ، __',
    questionImageUrl: null,
    options: [{ text: '35' }, { text: '38' }, { text: '40' }, { text: '45' }],
    correctOptionIndex: 2, explanationAr: 'كل رقم يزيد بمقدار 10، لذا 30 + 10 = 40',
    tags: ['sequences'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '6-9', skillArea: 'quantitative', subSkill: 'basic_operations',
    difficulty: 'easy', questionType: 'text',
    questionTextAr: '6 + 8 = ؟',
    questionImageUrl: null,
    options: [{ text: '12' }, { text: '13' }, { text: '14' }, { text: '15' }],
    correctOptionIndex: 2, explanationAr: '6 + 8 = 14',
    tags: ['addition'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '6-9', skillArea: 'quantitative', subSkill: 'basic_operations',
    difficulty: 'easy', questionType: 'text',
    questionTextAr: '20 - 9 = ؟',
    questionImageUrl: null,
    options: [{ text: '9' }, { text: '10' }, { text: '11' }, { text: '12' }],
    correctOptionIndex: 2, explanationAr: '20 - 9 = 11',
    tags: ['subtraction'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '6-9', skillArea: 'quantitative', subSkill: 'number_sequences',
    difficulty: 'easy', questionType: 'text',
    questionTextAr: 'أكمل المتسلسلة: 3 ، 6 ، 9 ، 12 ، __',
    questionImageUrl: null,
    options: [{ text: '13' }, { text: '14' }, { text: '15' }, { text: '16' }],
    correctOptionIndex: 2, explanationAr: 'كل رقم يزيد بمقدار 3، لذا 12 + 3 = 15',
    tags: ['sequences', 'counting_by_3'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '6-9', skillArea: 'quantitative', subSkill: 'multiplication',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: '5 × 6 = ؟',
    questionImageUrl: null,
    options: [{ text: '25' }, { text: '28' }, { text: '30' }, { text: '35' }],
    correctOptionIndex: 2, explanationAr: '5 × 6 = 30',
    tags: ['multiplication', 'times_tables'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '6-9', skillArea: 'quantitative', subSkill: 'word_problems',
    difficulty: 'easy', questionType: 'text',
    questionTextAr: 'في الصف 15 بنتاً و12 ولداً. كم عدد الطلاب جميعاً؟',
    questionImageUrl: null,
    options: [{ text: '25' }, { text: '26' }, { text: '27' }, { text: '28' }],
    correctOptionIndex: 2, explanationAr: '15 + 12 = 27 طالباً',
    tags: ['addition', 'word_problem'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '6-9', skillArea: 'quantitative', subSkill: 'division',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: '24 ÷ 4 = ؟',
    questionImageUrl: null,
    options: [{ text: '4' }, { text: '5' }, { text: '6' }, { text: '7' }],
    correctOptionIndex: 2, explanationAr: '24 ÷ 4 = 6',
    tags: ['division'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '6-9', skillArea: 'quantitative', subSkill: 'money',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'اشترى علي كتاباً بـ 12 ريالاً ودفع 20 ريالاً. كم يستلم باقي؟',
    questionImageUrl: null,
    options: [{ text: '6' }, { text: '7' }, { text: '8' }, { text: '9' }],
    correctOptionIndex: 2, explanationAr: '20 - 12 = 8 ريالات',
    tags: ['money', 'subtraction', 'word_problem'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '6-9', skillArea: 'quantitative', subSkill: 'time',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'كم دقيقة في ساعة ونصف؟',
    questionImageUrl: null,
    options: [{ text: '60' }, { text: '75' }, { text: '90' }, { text: '120' }],
    correctOptionIndex: 2, explanationAr: '60 دقيقة في الساعة + 30 دقيقة = 90 دقيقة',
    tags: ['time', 'units'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '6-9', skillArea: 'quantitative', subSkill: 'number_comparison',
    difficulty: 'easy', questionType: 'text',
    questionTextAr: 'أي العبارات صحيحة؟',
    questionImageUrl: null,
    options: [{ text: '5 > 8' }, { text: '3 = 4' }, { text: '9 > 7' }, { text: '6 < 2' }],
    correctOptionIndex: 2, explanationAr: '9 أكبر من 7، لذا 9 > 7 صحيحة',
    tags: ['comparison', 'inequality'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '6-9', skillArea: 'quantitative', subSkill: 'basic_operations',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: '35 + 28 = ؟',
    questionImageUrl: null,
    options: [{ text: '59' }, { text: '62' }, { text: '63' }, { text: '64' }],
    correctOptionIndex: 2, explanationAr: '35 + 28 = 63',
    tags: ['addition', 'two_digit'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '6-9', skillArea: 'quantitative', subSkill: 'multiplication',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: '7 × 8 = ؟',
    questionImageUrl: null,
    options: [{ text: '49' }, { text: '54' }, { text: '56' }, { text: '64' }],
    correctOptionIndex: 2, explanationAr: '7 × 8 = 56',
    tags: ['multiplication', 'times_tables'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '6-9', skillArea: 'quantitative', subSkill: 'geometry',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'كم عدد أضلاع المثلث؟',
    questionImageUrl: null,
    options: [{ text: '2' }, { text: '3' }, { text: '4' }, { text: '5' }],
    correctOptionIndex: 1, explanationAr: 'المثلث له 3 أضلاع و3 زوايا',
    tags: ['geometry', 'shapes'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '6-9', skillArea: 'quantitative', subSkill: 'fractions',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'كسرت سارة تفاحة إلى نصفين وأكلت قطعة واحدة. كم تبقى؟',
    questionImageUrl: null,
    options: [{ text: 'ربع' }, { text: 'نصف' }, { text: 'ثلث' }, { text: 'التفاحة كاملة' }],
    correctOptionIndex: 1, explanationAr: 'النصف الآخر تبقى معها',
    tags: ['fractions', 'halves'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '6-9', skillArea: 'quantitative', subSkill: 'word_problems',
    difficulty: 'hard', questionType: 'text',
    questionTextAr: 'يعمل أب 6 ساعات يومياً. كم ساعة يعمل في 5 أيام؟',
    questionImageUrl: null,
    options: [{ text: '24' }, { text: '28' }, { text: '30' }, { text: '36' }],
    correctOptionIndex: 2, explanationAr: '6 × 5 = 30 ساعة',
    tags: ['multiplication', 'word_problem'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '6-9', skillArea: 'quantitative', subSkill: 'number_sequences',
    difficulty: 'hard', questionType: 'text',
    questionTextAr: 'أكمل النمط: 1 ، 4 ، 9 ، 16 ، __',
    questionImageUrl: null,
    options: [{ text: '20' }, { text: '23' }, { text: '24' }, { text: '25' }],
    correctOptionIndex: 3, explanationAr: 'هذه مربعات الأعداد: 1²=1، 2²=4، 3²=9، 4²=16، 5²=25',
    tags: ['squares', 'sequences'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '6-9', skillArea: 'quantitative', subSkill: 'measurement',
    difficulty: 'easy', questionType: 'text',
    questionTextAr: 'كم سنتيمتراً في متر واحد؟',
    questionImageUrl: null,
    options: [{ text: '10' }, { text: '50' }, { text: '100' }, { text: '1000' }],
    correctOptionIndex: 2, explanationAr: 'يوجد 100 سنتيمتر في المتر الواحد',
    tags: ['measurement', 'units'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '6-9', skillArea: 'quantitative', subSkill: 'basic_operations',
    difficulty: 'hard', questionType: 'text',
    questionTextAr: 'ما ناتج: (4 × 5) + (3 × 2)؟',
    questionImageUrl: null,
    options: [{ text: '24' }, { text: '26' }, { text: '28' }, { text: '30' }],
    correctOptionIndex: 1, explanationAr: '(4×5) = 20 و(3×2) = 6، إذن 20 + 6 = 26',
    tags: ['order_of_operations'], isActive: true,
  },

  // ==========================================
  // 6-9 سنوات — لفظي (17 سؤال)
  // ==========================================
  {
    id: crypto.randomUUID(), ageGroup: '6-9', skillArea: 'verbal', subSkill: 'antonyms',
    difficulty: 'easy', questionType: 'text',
    questionTextAr: 'ما مضاد كلمة "سريع"؟',
    questionImageUrl: null,
    options: [{ text: 'قوي' }, { text: 'بطيء' }, { text: 'ثقيل' }, { text: 'بعيد' }],
    correctOptionIndex: 1, explanationAr: 'مضاد سريع هو بطيء',
    tags: ['antonyms'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '6-9', skillArea: 'verbal', subSkill: 'antonyms',
    difficulty: 'easy', questionType: 'text',
    questionTextAr: 'ما مضاد كلمة "قريب"؟',
    questionImageUrl: null,
    options: [{ text: 'طويل' }, { text: 'واسع' }, { text: 'بعيد' }, { text: 'ضيق' }],
    correctOptionIndex: 2, explanationAr: 'مضاد قريب هو بعيد',
    tags: ['antonyms'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '6-9', skillArea: 'verbal', subSkill: 'odd_one_out',
    difficulty: 'easy', questionType: 'text',
    questionTextAr: 'أي الكلمات لا تنتمي للمجموعة: تفاحة — موزة — عنب — جزر؟',
    questionImageUrl: null,
    options: [{ text: 'تفاحة' }, { text: 'موزة' }, { text: 'عنب' }, { text: 'جزر' }],
    correctOptionIndex: 3, explanationAr: 'التفاحة والموزة والعنب فواكه، أما الجزر فهو خضروات',
    tags: ['classification', 'odd_one_out'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '6-9', skillArea: 'verbal', subSkill: 'categories',
    difficulty: 'easy', questionType: 'text',
    questionTextAr: 'أي من الآتي وسيلة مواصلات؟',
    questionImageUrl: null,
    options: [{ text: 'طاولة' }, { text: 'قلم' }, { text: 'سيارة' }, { text: 'كتاب' }],
    correctOptionIndex: 2, explanationAr: 'السيارة وسيلة مواصلات تُستخدم للتنقل',
    tags: ['categories', 'vocabulary'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '6-9', skillArea: 'verbal', subSkill: 'analogies',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'الطائر يطير بالأجنحة، كما يسبح السمك بـ...',
    questionImageUrl: null,
    options: [{ text: 'الأرجل' }, { text: 'الزعانف' }, { text: 'الذيل' }, { text: 'الرأس' }],
    correctOptionIndex: 1, explanationAr: 'الطائر يستخدم أجنحته للطيران، والسمكة تستخدم زعانفها للسباحة',
    tags: ['analogies', 'animals'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '6-9', skillArea: 'verbal', subSkill: 'synonyms',
    difficulty: 'easy', questionType: 'text',
    questionTextAr: 'ما مرادف كلمة "جميل"؟',
    questionImageUrl: null,
    options: [{ text: 'قبيح' }, { text: 'حزين' }, { text: 'حسن' }, { text: 'بطيء' }],
    correctOptionIndex: 2, explanationAr: 'مرادف جميل هو حسن، وكلاهما يصفان الجمال',
    tags: ['synonyms'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '6-9', skillArea: 'verbal', subSkill: 'grammar',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'أي الجمل صحيحة نحوياً؟',
    questionImageUrl: null,
    options: [{ text: 'ذهبت البنات إلى المدرسة' }, { text: 'ذهب البنات إلى المدرسة' }, { text: 'يذهب البنات إلى المدرسة' }, { text: 'ذهبن البنات إلى المدرسة' }],
    correctOptionIndex: 0, explanationAr: '"البنات" جمع مؤنث، ويناسبه "ذهبت"',
    tags: ['grammar', 'agreement'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '6-9', skillArea: 'verbal', subSkill: 'sentence_completion',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'اخترت الكتاب ___ أعجبني موضوعه.',
    questionImageUrl: null,
    options: [{ text: 'التي' }, { text: 'الذي' }, { text: 'اللذان' }, { text: 'اللتان' }],
    correctOptionIndex: 1, explanationAr: '"الكتاب" مذكر، لذا يأتي بعده "الذي"',
    tags: ['grammar', 'relative_pronoun'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '6-9', skillArea: 'verbal', subSkill: 'antonyms',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'ما مضاد كلمة "حاضر"؟',
    questionImageUrl: null,
    options: [{ text: 'جاهز' }, { text: 'غائب' }, { text: 'موجود' }, { text: 'قادم' }],
    correctOptionIndex: 1, explanationAr: 'مضاد حاضر هو غائب',
    tags: ['antonyms'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '6-9', skillArea: 'verbal', subSkill: 'plurals',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'ما جمع كلمة "قلم"؟',
    questionImageUrl: null,
    options: [{ text: 'أقلام' }, { text: 'قلمات' }, { text: 'قليمة' }, { text: 'قلمان' }],
    correctOptionIndex: 0, explanationAr: 'جمع قلم هو أقلام',
    tags: ['plurals'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '6-9', skillArea: 'verbal', subSkill: 'categories',
    difficulty: 'easy', questionType: 'text',
    questionTextAr: 'أي من الآتي حيوان بري وليس أليفاً؟',
    questionImageUrl: null,
    options: [{ text: 'قطة' }, { text: 'كلب' }, { text: 'أسد' }, { text: 'بقرة' }],
    correctOptionIndex: 2, explanationAr: 'الأسد حيوان بري يعيش في الغابات والسافانا، وليس أليفاً',
    tags: ['animals', 'categories'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '6-9', skillArea: 'verbal', subSkill: 'analogies',
    difficulty: 'easy', questionType: 'text',
    questionTextAr: 'الطبيب يعالج المرضى، كما يُعلِّم المعلم ...',
    questionImageUrl: null,
    options: [{ text: 'المرضى' }, { text: 'الطلاب' }, { text: 'اللاعبين' }, { text: 'الأطفال فقط' }],
    correctOptionIndex: 1, explanationAr: 'الطبيب يعالج المرضى، والمعلم يُعلِّم الطلاب',
    tags: ['analogies', 'occupations'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '6-9', skillArea: 'verbal', subSkill: 'sentence_completion',
    difficulty: 'hard', questionType: 'text',
    questionTextAr: 'المفرد يكتب، والجمع يكتبون. ما مفرد "يلعبون"؟',
    questionImageUrl: null,
    options: [{ text: 'تلعب' }, { text: 'يلعبان' }, { text: 'يلعب' }, { text: 'لعب' }],
    correctOptionIndex: 2, explanationAr: 'مفرد "يلعبون" هو "يلعب" لأنها المضارع للمفرد الغائب',
    tags: ['grammar', 'conjugation'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '6-9', skillArea: 'verbal', subSkill: 'odd_one_out',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'أي الكلمات لا تنتمي للمجموعة: عين — أنف — أذن — قميص؟',
    questionImageUrl: null,
    options: [{ text: 'عين' }, { text: 'أنف' }, { text: 'أذن' }, { text: 'قميص' }],
    correctOptionIndex: 3, explanationAr: 'العين والأنف والأذن أعضاء في الجسم، والقميص ملابس',
    tags: ['classification'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '6-9', skillArea: 'verbal', subSkill: 'synonyms',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'ما مرادف كلمة "أجاب"؟',
    questionImageUrl: null,
    options: [{ text: 'سأل' }, { text: 'رد' }, { text: 'صمت' }, { text: 'أكمل' }],
    correctOptionIndex: 1, explanationAr: 'مرادف "أجاب" هو "رد"، وكلاهما يعني الإجابة على سؤال',
    tags: ['synonyms'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '6-9', skillArea: 'verbal', subSkill: 'grammar',
    difficulty: 'hard', questionType: 'text',
    questionTextAr: 'أي الجمل تحتوي على فعل ماضٍ؟',
    questionImageUrl: null,
    options: [{ text: 'يذهب أحمد إلى المدرسة' }, { text: 'ذهب أحمد إلى المدرسة' }, { text: 'سيذهب أحمد إلى المدرسة' }, { text: 'أحمد في المدرسة' }],
    correctOptionIndex: 1, explanationAr: '"ذهب" فعل ماضٍ يدل على حدث وقع في الماضي',
    tags: ['grammar', 'verb_tenses'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '6-9', skillArea: 'verbal', subSkill: 'comprehension',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: '"القراءة غذاء العقل" — ماذا تعني هذه العبارة؟',
    questionImageUrl: null,
    options: [{ text: 'القراءة تُسبب الجوع' }, { text: 'القراءة تُقوّي العقل وتُنمّيه' }, { text: 'العقل يأكل الكتب' }, { text: 'الغذاء مفيد للقراءة' }],
    correctOptionIndex: 1, explanationAr: 'تشبّه العبارة القراءة بالطعام لأن كليهما يُقوّي ويُنمّي: الطعام للجسم، والقراءة للعقل',
    tags: ['comprehension', 'figurative_language'], isActive: true,
  },

  // ==========================================
  // 6-9 سنوات — منطقي (15 سؤال)
  // ==========================================
  {
    id: crypto.randomUUID(), ageGroup: '6-9', skillArea: 'logical_patterns', subSkill: 'number_sequences',
    difficulty: 'easy', questionType: 'text',
    questionTextAr: 'أكمل المتسلسلة: 50 ، 40 ، 30 ، __',
    questionImageUrl: null,
    options: [{ text: '15' }, { text: '20' }, { text: '25' }, { text: '28' }],
    correctOptionIndex: 1, explanationAr: 'كل رقم يتناقص بمقدار 10: 30 - 10 = 20',
    tags: ['sequences', 'decreasing'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '6-9', skillArea: 'logical_patterns', subSkill: 'pattern_completion',
    difficulty: 'easy', questionType: 'text',
    questionTextAr: 'أي الشكل يكمل النمط: ⭐ ⭐ ❤️ ⭐ ⭐ ❤️ ⭐ ⭐ __؟',
    questionImageUrl: null,
    options: [{ text: '⭐' }, { text: '❤️' }, { text: '🔵' }, { text: '🔶' }],
    correctOptionIndex: 1, explanationAr: 'النمط هو نجمتان ثم قلب. بعد النجمتين الأخيرتين يأتي القلب ❤️',
    tags: ['patterns', 'repeating'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '6-9', skillArea: 'logical_patterns', subSkill: 'deductive_reasoning',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'نور تسكن في بيت أكبر من بيت ريم. بيت ريم أكبر من بيت هند. من تسكن في أصغر بيت؟',
    questionImageUrl: null,
    options: [{ text: 'نور' }, { text: 'ريم' }, { text: 'هند' }, { text: 'نفس الحجم' }],
    correctOptionIndex: 2, explanationAr: 'الترتيب: نور > ريم > هند، إذن هند في أصغر بيت',
    tags: ['ordering', 'deduction'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '6-9', skillArea: 'logical_patterns', subSkill: 'rules',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'إذا كانت: 6 → 3 و 10 → 5 و 8 → 4. فماذا يصبح 12 →؟',
    questionImageUrl: null,
    options: [{ text: '4' }, { text: '5' }, { text: '6' }, { text: '7' }],
    correctOptionIndex: 2, explanationAr: 'القاعدة هي القسمة على 2: 12 ÷ 2 = 6',
    tags: ['rules', 'function'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '6-9', skillArea: 'logical_patterns', subSkill: 'number_sequences',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'أكمل المتسلسلة: 1 ، 3 ، 7 ، 15 ، __',
    questionImageUrl: null,
    options: [{ text: '23' }, { text: '27' }, { text: '31' }, { text: '33' }],
    correctOptionIndex: 2, explanationAr: 'كل رقم = الرقم السابق × 2 + 1: 15×2+1=31',
    tags: ['sequences', 'complex'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '6-9', skillArea: 'logical_patterns', subSkill: 'if_then',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'إذا كانت جميع الفواكه تحتوي على بذور، والتفاحة فاكهة. هل التفاحة تحتوي على بذور؟',
    questionImageUrl: null,
    options: [{ text: 'نعم' }, { text: 'لا' }, { text: 'أحياناً' }, { text: 'لا نعلم' }],
    correctOptionIndex: 0, explanationAr: 'بما أن جميع الفواكه تحتوي بذور، والتفاحة فاكهة، فهي تحتوي بذور بالضرورة',
    tags: ['deduction', 'if_then'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '6-9', skillArea: 'logical_patterns', subSkill: 'spatial',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'المكتب شمال الكرسي، والكرسي شمال النافذة. أين المكتب بالنسبة للنافذة؟',
    questionImageUrl: null,
    options: [{ text: 'جنوبها' }, { text: 'شرقها' }, { text: 'شمالها' }, { text: 'غربها' }],
    correctOptionIndex: 2, explanationAr: 'المكتب → شمال → الكرسي → شمال → النافذة، إذن المكتب شمال النافذة',
    tags: ['spatial', 'directions'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '6-9', skillArea: 'logical_patterns', subSkill: 'pattern_completion',
    difficulty: 'hard', questionType: 'text',
    questionTextAr: 'إذا كان اليوم الثلاثاء، ما اليوم بعد 5 أيام؟',
    questionImageUrl: null,
    options: [{ text: 'السبت' }, { text: 'الأحد' }, { text: 'الاثنين' }, { text: 'الثلاثاء' }],
    correctOptionIndex: 1, explanationAr: 'الثلاثاء +5 أيام: الأربعاء، الخميس، الجمعة، السبت، الأحد',
    tags: ['days', 'counting'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '6-9', skillArea: 'logical_patterns', subSkill: 'deductive_reasoning',
    difficulty: 'easy', questionType: 'text',
    questionTextAr: 'لدى كل طالب في الفصل كتاب. فاطمة طالبة في الفصل. هل لدى فاطمة كتاب؟',
    questionImageUrl: null,
    options: [{ text: 'نعم' }, { text: 'لا' }, { text: 'ربما' }, { text: 'لا يمكن المعرفة' }],
    correctOptionIndex: 0, explanationAr: 'كل طالب لديه كتاب، وفاطمة طالبة، إذن لديها كتاب بالضرورة',
    tags: ['deduction'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '6-9', skillArea: 'logical_patterns', subSkill: 'number_sequences',
    difficulty: 'easy', questionType: 'text',
    questionTextAr: 'أكمل المتسلسلة: 2 ، 5 ، 8 ، 11 ، __',
    questionImageUrl: null,
    options: [{ text: '12' }, { text: '13' }, { text: '14' }, { text: '15' }],
    correctOptionIndex: 2, explanationAr: 'كل رقم يزيد بمقدار 3: 11 + 3 = 14',
    tags: ['sequences', 'add_3'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '6-9', skillArea: 'logical_patterns', subSkill: 'pattern_completion',
    difficulty: 'easy', questionType: 'text',
    questionTextAr: 'ما الرقم المفقود: 2 ، 4 ، __ ، 8 ، 10؟',
    questionImageUrl: null,
    options: [{ text: '5' }, { text: '6' }, { text: '7' }, { text: '9' }],
    correctOptionIndex: 1, explanationAr: 'النمط هو الأعداد الزوجية بالترتيب: 2، 4، 6، 8، 10',
    tags: ['even_numbers', 'sequences'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '6-9', skillArea: 'logical_patterns', subSkill: 'comparison',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'فهد أصغر من سعد بسنتين. سعد عمره 8 سنوات. كم عمر فهد؟',
    questionImageUrl: null,
    options: [{ text: '5' }, { text: '6' }, { text: '7' }, { text: '8' }],
    correctOptionIndex: 1, explanationAr: 'فهد = سعد - 2 = 8 - 2 = 6 سنوات',
    tags: ['age_problems', 'subtraction'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '6-9', skillArea: 'logical_patterns', subSkill: 'if_then',
    difficulty: 'hard', questionType: 'text',
    questionTextAr: 'إذا كانت A = 2 وB = 3، ما قيمة A × B + A؟',
    questionImageUrl: null,
    options: [{ text: '6' }, { text: '7' }, { text: '8' }, { text: '10' }],
    correctOptionIndex: 2, explanationAr: 'A×B = 2×3 = 6، ثم +A = 6+2 = 8',
    tags: ['algebra', 'substitution'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '6-9', skillArea: 'logical_patterns', subSkill: 'rules',
    difficulty: 'hard', questionType: 'text',
    questionTextAr: 'في كل صف، الرقم الثالث = مجموع الرقمين الأولين. ما الرقم المفقود: 3 ، 4 ، __؟',
    questionImageUrl: null,
    options: [{ text: '5' }, { text: '6' }, { text: '7' }, { text: '8' }],
    correctOptionIndex: 2, explanationAr: '3 + 4 = 7',
    tags: ['rules', 'addition'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '6-9', skillArea: 'logical_patterns', subSkill: 'pattern_completion',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'ما الشكل الناقص: 🔴🔵🔴🔵🔴__؟',
    questionImageUrl: null,
    options: [{ text: '🔴' }, { text: '🔵' }, { text: '🟡' }, { text: '🟢' }],
    correctOptionIndex: 1, explanationAr: 'النمط يتناوب بين 🔴 و🔵، بعد 🔴 الأخيرة تأتي 🔵',
    tags: ['patterns', 'alternating'], isActive: true,
  },

  // ==========================================
  // 10-12 سنة — كمي (17 سؤال)
  // ==========================================
  {
    id: crypto.randomUUID(), ageGroup: '10-12', skillArea: 'quantitative', subSkill: 'algebra',
    difficulty: 'easy', questionType: 'text',
    questionTextAr: 'إذا كان 2س = 16، فما قيمة س؟',
    questionImageUrl: null,
    options: [{ text: '6' }, { text: '7' }, { text: '8' }, { text: '9' }],
    correctOptionIndex: 2, explanationAr: 'س = 16 ÷ 2 = 8',
    tags: ['algebra'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '10-12', skillArea: 'quantitative', subSkill: 'geometry',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'ما محيط مستطيل طوله 12 م وعرضه 7 م؟',
    questionImageUrl: null,
    options: [{ text: '34' }, { text: '36' }, { text: '38' }, { text: '42' }],
    correctOptionIndex: 2, explanationAr: 'المحيط = 2 × (الطول + العرض) = 2 × (12+7) = 2 × 19 = 38 م',
    tags: ['geometry', 'perimeter'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '10-12', skillArea: 'quantitative', subSkill: 'percentages',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'ارتفع سعر سلعة من 200 إلى 250 ريالاً. ما نسبة الارتفاع؟',
    questionImageUrl: null,
    options: [{ text: '20٪' }, { text: '25٪' }, { text: '30٪' }, { text: '50٪' }],
    correctOptionIndex: 1, explanationAr: 'نسبة الارتفاع = (250-200)/200 × 100 = 50/200 × 100 = 25٪',
    tags: ['percentages', 'change'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '10-12', skillArea: 'quantitative', subSkill: 'number_theory',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'أي من الأعداد التالية عدد أولي؟',
    questionImageUrl: null,
    options: [{ text: '9' }, { text: '15' }, { text: '17' }, { text: '21' }],
    correctOptionIndex: 2, explanationAr: '17 عدد أولي لأنه لا يقبل القسمة إلا على 1 وعلى نفسه',
    tags: ['prime_numbers'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '10-12', skillArea: 'quantitative', subSkill: 'algebra',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'ما قيمة: 5² - 3²؟',
    questionImageUrl: null,
    options: [{ text: '4' }, { text: '8' }, { text: '16' }, { text: '22' }],
    correctOptionIndex: 2, explanationAr: '5² = 25 و3² = 9، إذن 25 - 9 = 16',
    tags: ['powers', 'subtraction'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '10-12', skillArea: 'quantitative', subSkill: 'statistics',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'ما الوسيط (المتوسط الحسابي) للأعداد: 2 ، 4 ، 6 ، 8 ، 10؟',
    questionImageUrl: null,
    options: [{ text: '4' }, { text: '5' }, { text: '6' }, { text: '7' }],
    correctOptionIndex: 2, explanationAr: 'المتوسط = (2+4+6+8+10) ÷ 5 = 30 ÷ 5 = 6',
    tags: ['statistics', 'average'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '10-12', skillArea: 'quantitative', subSkill: 'fractions',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: '3/4 + 1/2 = ؟',
    questionImageUrl: null,
    options: [{ text: '4/6' }, { text: '4/8' }, { text: '5/4' }, { text: '7/4' }],
    correctOptionIndex: 2, explanationAr: '3/4 + 2/4 = 5/4',
    tags: ['fractions', 'addition'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '10-12', skillArea: 'quantitative', subSkill: 'algebra',
    difficulty: 'hard', questionType: 'text',
    questionTextAr: 'إذا كان 2س + 3ص = 17 وس = 4، فما قيمة ص؟',
    questionImageUrl: null,
    options: [{ text: '2' }, { text: '3' }, { text: '4' }, { text: '5' }],
    correctOptionIndex: 1, explanationAr: '2×4 + 3ص = 17 → 8 + 3ص = 17 → 3ص = 9 → ص = 3',
    tags: ['algebra', 'simultaneous'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '10-12', skillArea: 'quantitative', subSkill: 'geometry',
    difficulty: 'hard', questionType: 'text',
    questionTextAr: 'ما مساحة المثلث الذي قاعدته 10 وارتفاعه 6؟',
    questionImageUrl: null,
    options: [{ text: '20' }, { text: '30' }, { text: '40' }, { text: '60' }],
    correctOptionIndex: 1, explanationAr: 'مساحة المثلث = ½ × القاعدة × الارتفاع = ½ × 10 × 6 = 30',
    tags: ['geometry', 'triangle', 'area'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '10-12', skillArea: 'quantitative', subSkill: 'ratios',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'قُسِّم مبلغ 120 ريال بين شخصين بنسبة 3:5. ما نصيب كل شخص؟',
    questionImageUrl: null,
    options: [{ text: '30 و90' }, { text: '40 و80' }, { text: '45 و75' }, { text: '50 و70' }],
    correctOptionIndex: 2, explanationAr: 'الحصص 3+5=8، لكل جزء 120÷8=15. الأول 3×15=45، الثاني 5×15=75',
    tags: ['ratios', 'division'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '10-12', skillArea: 'quantitative', subSkill: 'number_theory',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'ما أكبر عامل مشترك للعددين 24 و36؟',
    questionImageUrl: null,
    options: [{ text: '4' }, { text: '6' }, { text: '8' }, { text: '12' }],
    correctOptionIndex: 3, explanationAr: 'عوامل 24: 1،2،3،4،6،8،12،24. عوامل 36: 1،2،3،4،6،9،12،18،36. الأكبر المشترك: 12',
    tags: ['GCF', 'number_theory'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '10-12', skillArea: 'quantitative', subSkill: 'word_problems',
    difficulty: 'hard', questionType: 'text',
    questionTextAr: 'اشترى تاجر بضاعة بـ 400 ريال وباعها بـ 520 ريالاً. ما نسبة ربحه؟',
    questionImageUrl: null,
    options: [{ text: '20٪' }, { text: '25٪' }, { text: '30٪' }, { text: '35٪' }],
    correctOptionIndex: 2, explanationAr: 'الربح = 120، نسبة الربح = 120/400 × 100 = 30٪',
    tags: ['profit', 'percentages'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '10-12', skillArea: 'quantitative', subSkill: 'sequences',
    difficulty: 'hard', questionType: 'text',
    questionTextAr: 'ما مجموع أول 10 أعداد طبيعية (1 إلى 10)؟',
    questionImageUrl: null,
    options: [{ text: '45' }, { text: '50' }, { text: '55' }, { text: '60' }],
    correctOptionIndex: 2, explanationAr: 'المجموع = ن × (ن+1) ÷ 2 = 10 × 11 ÷ 2 = 55',
    tags: ['sum', 'sequences'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '10-12', skillArea: 'quantitative', subSkill: 'geometry',
    difficulty: 'easy', questionType: 'text',
    questionTextAr: 'كم درجة في الزوايا الداخلية لأي مثلث؟',
    questionImageUrl: null,
    options: [{ text: '90°' }, { text: '120°' }, { text: '180°' }, { text: '360°' }],
    correctOptionIndex: 2, explanationAr: 'مجموع زوايا أي مثلث = 180 درجة',
    tags: ['geometry', 'angles'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '10-12', skillArea: 'quantitative', subSkill: 'algebra',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'إذا كان ف(س) = س² + 3، فما قيمة ف(4)؟',
    questionImageUrl: null,
    options: [{ text: '13' }, { text: '16' }, { text: '19' }, { text: '23' }],
    correctOptionIndex: 2, explanationAr: 'ف(4) = 4² + 3 = 16 + 3 = 19',
    tags: ['functions', 'algebra'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '10-12', skillArea: 'quantitative', subSkill: 'fractions',
    difficulty: 'hard', questionType: 'text',
    questionTextAr: '3/5 من عدد ما يساوي 24. ما العدد؟',
    questionImageUrl: null,
    options: [{ text: '32' }, { text: '36' }, { text: '40' }, { text: '45' }],
    correctOptionIndex: 2, explanationAr: '3/5 × العدد = 24، إذن العدد = 24 × 5/3 = 40',
    tags: ['fractions', 'algebra'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '10-12', skillArea: 'quantitative', subSkill: 'word_problems',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'إذا كانت الساعة 9 صباحاً، فأي وقت سيكون بعد 3 ساعات و40 دقيقة؟',
    questionImageUrl: null,
    options: [{ text: '12:20' }, { text: '12:30' }, { text: '12:40' }, { text: '1:00' }],
    correctOptionIndex: 2, explanationAr: '9:00 + 3:40 = 12:40',
    tags: ['time', 'addition'], isActive: true,
  },

  // ==========================================
  // 10-12 سنة — لفظي (15 سؤال)
  // ==========================================
  {
    id: crypto.randomUUID(), ageGroup: '10-12', skillArea: 'verbal', subSkill: 'antonyms',
    difficulty: 'easy', questionType: 'text',
    questionTextAr: 'ما مضاد كلمة "كريم"؟',
    questionImageUrl: null,
    options: [{ text: 'جميل' }, { text: 'بخيل' }, { text: 'شجاع' }, { text: 'ذكي' }],
    correctOptionIndex: 1, explanationAr: 'مضاد كريم هو بخيل',
    tags: ['antonyms'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '10-12', skillArea: 'verbal', subSkill: 'word_roots',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'ما جذر كلمة "مُتَعَلِّم"؟',
    questionImageUrl: null,
    options: [{ text: 'علم' }, { text: 'لمم' }, { text: 'تعل' }, { text: 'معل' }],
    correctOptionIndex: 0, explanationAr: 'جذر "متعلّم" هو "ع ل م" — وهو نفس جذر عَلَّمَ وتَعَلَّمَ والعِلم',
    tags: ['word_roots', 'morphology'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '10-12', skillArea: 'verbal', subSkill: 'analogies',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'الطبيب للمستشفى كالمعلم لـ...',
    questionImageUrl: null,
    options: [{ text: 'الكتاب' }, { text: 'المدرسة' }, { text: 'الطالب' }, { text: 'العلم' }],
    correctOptionIndex: 1, explanationAr: 'الطبيب يعمل في المستشفى، والمعلم يعمل في المدرسة',
    tags: ['analogies', 'occupations'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '10-12', skillArea: 'verbal', subSkill: 'grammar',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'في جملة "أكرمَ المعلمُ الطالبَ"، ما إعراب "الطالب"؟',
    questionImageUrl: null,
    options: [{ text: 'فاعل' }, { text: 'مفعول به' }, { text: 'مبتدأ' }, { text: 'نعت' }],
    correctOptionIndex: 1, explanationAr: '"الطالب" مفعول به منصوب وعلامة نصبه الفتحة الظاهرة',
    tags: ['grammar', 'syntax'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '10-12', skillArea: 'verbal', subSkill: 'synonyms',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'ما مرادف كلمة "الفصاحة"؟',
    questionImageUrl: null,
    options: [{ text: 'الجمال' }, { text: 'البلاغة' }, { text: 'الشجاعة' }, { text: 'الحكمة' }],
    correctOptionIndex: 1, explanationAr: 'الفصاحة والبلاغة كلتاهما تعنيان حسن التعبير والإيصال',
    tags: ['synonyms', 'rhetoric'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '10-12', skillArea: 'verbal', subSkill: 'antonyms',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'ما مضاد كلمة "الغموض"؟',
    questionImageUrl: null,
    options: [{ text: 'الجمال' }, { text: 'الوضوح' }, { text: 'الصعوبة' }, { text: 'العمق' }],
    correctOptionIndex: 1, explanationAr: 'مضاد الغموض هو الوضوح والجلاء',
    tags: ['antonyms'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '10-12', skillArea: 'verbal', subSkill: 'plurals',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'ما جمع كلمة "إنسان"؟',
    questionImageUrl: null,
    options: [{ text: 'إنسانات' }, { text: 'أناسي' }, { text: 'ناس' }, { text: 'إنسانون' }],
    correctOptionIndex: 1, explanationAr: 'جمع إنسان هو "أُناس" أو "ناس" وأيضاً "أناسيّ" — الجواب الأكمل هو أناسي',
    tags: ['plurals', 'irregular'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '10-12', skillArea: 'verbal', subSkill: 'sentence_completion',
    difficulty: 'hard', questionType: 'text',
    questionTextAr: 'اخترت الكلمة الصحيحة: "يسعى الإنسان ___ تحقيق أهدافه."',
    questionImageUrl: null,
    options: [{ text: 'لـ' }, { text: 'إلى' }, { text: 'على' }, { text: 'في' }],
    correctOptionIndex: 1, explanationAr: '"سعى" يتعدى بـ"إلى": يسعى إلى تحقيق أهدافه',
    tags: ['grammar', 'prepositions'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '10-12', skillArea: 'verbal', subSkill: 'comprehension',
    difficulty: 'hard', questionType: 'text',
    questionTextAr: '"الكلمة الطيبة صدقة" — ما المراد بهذه العبارة؟',
    questionImageUrl: null,
    options: [{ text: 'الكلام يُكلّف مالاً' }, { text: 'الكلام اللطيف له أجر وثواب' }, { text: 'الصدقة أفضل من الكلام' }, { text: 'يجب التحدث كثيراً' }],
    correctOptionIndex: 1, explanationAr: 'تُشبّه العبارة الكلام الطيب بالصدقة من حيث الأجر والأثر الحسن',
    tags: ['comprehension', 'religion'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '10-12', skillArea: 'verbal', subSkill: 'grammar',
    difficulty: 'hard', questionType: 'text',
    questionTextAr: 'أي الجمل خالية من الخطأ الإملائي؟',
    questionImageUrl: null,
    options: [{ text: 'إن الله مع الصابرين' }, { text: 'إن الله مع الصابرون' }, { text: 'إن الله مع الصابرين إن' }, { text: 'أن الله مع الصابرين' }],
    correctOptionIndex: 0, explanationAr: '"إن" حرف ناسخ ينصب الاسم، فـ"الصابرين" منصوب بالياء لأنه جمع مذكر سالم',
    tags: ['grammar', 'spelling'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '10-12', skillArea: 'verbal', subSkill: 'odd_one_out',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'أي الكلمات لا تنتمي للمجموعة: صادق — أمين — وفي — غادر؟',
    questionImageUrl: null,
    options: [{ text: 'صادق' }, { text: 'أمين' }, { text: 'وفي' }, { text: 'غادر' }],
    correctOptionIndex: 3, explanationAr: 'صادق وأمين ووفي صفات إيجابية، أما غادر (الخائن) فهي سلبية',
    tags: ['antonyms', 'odd_one_out'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '10-12', skillArea: 'verbal', subSkill: 'proverbs',
    difficulty: 'hard', questionType: 'text',
    questionTextAr: 'ما معنى المثل: "كل إناء ينضح بما فيه"؟',
    questionImageUrl: null,
    options: [{ text: 'الأواني تحتوي السوائل' }, { text: 'يظهر على الإنسان ما يبطنه' }, { text: 'يجب ملء الإناء قبل استخدامه' }, { text: 'الاستعداد المبكر مهم' }],
    correctOptionIndex: 1, explanationAr: 'المثل يعني أن طبيعة الإنسان الحقيقية تظهر في أقواله وأفعاله، كالإناء الذي يسيل بما يحويه',
    tags: ['proverbs', 'culture'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '10-12', skillArea: 'verbal', subSkill: 'word_roots',
    difficulty: 'hard', questionType: 'text',
    questionTextAr: 'أي الكلمات التالية مشتقة من جذر "كتب"؟',
    questionImageUrl: null,
    options: [{ text: 'مكتبي' }, { text: 'قراءة' }, { text: 'حروف' }, { text: 'أقلام' }],
    correctOptionIndex: 0, explanationAr: '"مكتبي" مشتقة من "كتب"، بخلاف قراءة (قرأ) وحروف (حرف) وأقلام (قلم)',
    tags: ['word_roots', 'derivation'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '10-12', skillArea: 'verbal', subSkill: 'analogies',
    difficulty: 'hard', questionType: 'text',
    questionTextAr: 'الجهل للعقل كالمرض لـ...',
    questionImageUrl: null,
    options: [{ text: 'الدواء' }, { text: 'الجسم' }, { text: 'الطبيب' }, { text: 'الصحة' }],
    correctOptionIndex: 1, explanationAr: 'الجهل يُضعف العقل كما يُضعف المرض الجسم',
    tags: ['analogies', 'figurative'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '10-12', skillArea: 'verbal', subSkill: 'synonyms',
    difficulty: 'hard', questionType: 'text',
    questionTextAr: 'ما مرادف كلمة "الإيجاز"؟',
    questionImageUrl: null,
    options: [{ text: 'الإطالة' }, { text: 'الاختصار' }, { text: 'التفسير' }, { text: 'الإبداع' }],
    correctOptionIndex: 1, explanationAr: 'الإيجاز هو الاختصار في الكلام مع وضوح المعنى',
    tags: ['synonyms', 'rhetoric'], isActive: true,
  },

  // ==========================================
  // 10-12 سنة — منطقي (13 سؤال)
  // ==========================================
  {
    id: crypto.randomUUID(), ageGroup: '10-12', skillArea: 'logical_patterns', subSkill: 'number_sequences',
    difficulty: 'easy', questionType: 'text',
    questionTextAr: 'أكمل المتسلسلة: 2 ، 6 ، 18 ، 54 ، __',
    questionImageUrl: null,
    options: [{ text: '102' }, { text: '108' }, { text: '162' }, { text: '216' }],
    correctOptionIndex: 2, explanationAr: 'كل رقم يُضرب في 3: 54 × 3 = 162',
    tags: ['sequences', 'geometric'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '10-12', skillArea: 'logical_patterns', subSkill: 'deductive_reasoning',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'لا يوجد طالب كسول في الفصل. محمد طالب في الفصل. هل محمد كسول؟',
    questionImageUrl: null,
    options: [{ text: 'نعم' }, { text: 'لا' }, { text: 'ربما' }, { text: 'لا يمكن التحديد' }],
    correctOptionIndex: 1, explanationAr: 'بما أنه لا يوجد طالب كسول في الفصل، ومحمد طالب، فهو ليس كسولاً',
    tags: ['deduction', 'negation'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '10-12', skillArea: 'logical_patterns', subSkill: 'if_then',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'إذا كان "كل A هو B" و"كل B هو C"، فأي العبارات صحيحة؟',
    questionImageUrl: null,
    options: [{ text: 'كل C هو A' }, { text: 'كل A هو C' }, { text: 'كل B هو A' }, { text: 'لا شيء مما سبق' }],
    correctOptionIndex: 1, explanationAr: 'إذا كل A→B وكل B→C، فبالضرورة كل A→C (قياس منطقي متسلسل)',
    tags: ['logic', 'syllogism'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '10-12', skillArea: 'logical_patterns', subSkill: 'word_problems',
    difficulty: 'hard', questionType: 'text',
    questionTextAr: 'في مسابقة، حصل خالد على ضعف نقاط سعيد، وسعيد على 15 نقطة أكثر من فيصل الذي حصل على 25 نقطة. كم نقطة لدى خالد؟',
    questionImageUrl: null,
    options: [{ text: '60' }, { text: '70' }, { text: '80' }, { text: '90' }],
    correctOptionIndex: 2, explanationAr: 'فيصل=25، سعيد=25+15=40، خالد=40×2=80',
    tags: ['word_problems', 'algebra'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '10-12', skillArea: 'logical_patterns', subSkill: 'number_sequences',
    difficulty: 'hard', questionType: 'text',
    questionTextAr: 'أكمل المتسلسلة: 1 ، 2 ، 6 ، 24 ، __',
    questionImageUrl: null,
    options: [{ text: '80' }, { text: '100' }, { text: '120' }, { text: '144' }],
    correctOptionIndex: 2, explanationAr: 'هذه مضروبات الأعداد (Factorials): 1! ، 2! ، 3! ، 4! ، 5!=120',
    tags: ['factorials', 'sequences'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '10-12', skillArea: 'logical_patterns', subSkill: 'spatial',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'إذا أدرت الحرف "b" 180 درجة، أي حرف ستحصل عليه؟',
    questionImageUrl: null,
    options: [{ text: 'd' }, { text: 'p' }, { text: 'q' }, { text: 'g' }],
    correctOptionIndex: 1, explanationAr: 'عند إدارة "b" بمقدار 180 درجة تحصل على "p"',
    tags: ['spatial', 'rotation'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '10-12', skillArea: 'logical_patterns', subSkill: 'deductive_reasoning',
    difficulty: 'hard', questionType: 'text',
    questionTextAr: 'كل طيور هذه المنطقة مهاجرة. البطة مقيمة في هذه المنطقة طوال العام. هل البطة طائر من هذه المنطقة؟',
    questionImageUrl: null,
    options: [{ text: 'نعم' }, { text: 'لا' }, { text: 'ربما' }, { text: 'لا يمكن تحديده' }],
    correctOptionIndex: 1, explanationAr: 'كل طيور المنطقة مهاجرة، والبطة مقيمة (غير مهاجرة)، إذن هي ليست من طيور هذه المنطقة',
    tags: ['deduction', 'contrapositive'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '10-12', skillArea: 'logical_patterns', subSkill: 'coding',
    difficulty: 'hard', questionType: 'text',
    questionTextAr: 'في نظام ترميز معين: 1=A، 2=B ... إذا كانت رسالة "3-1-2"، فهي تعني:',
    questionImageUrl: null,
    options: [{ text: 'ABC' }, { text: 'CAB' }, { text: 'BAC' }, { text: 'BCA' }],
    correctOptionIndex: 1, explanationAr: '3=C، 1=A، 2=B، إذن الرسالة هي CAB',
    tags: ['coding', 'decoding'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '10-12', skillArea: 'logical_patterns', subSkill: 'rules',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'إذا كانت: 5 ← 26 و 3 ← 10 و 2 ← 5. فماذا تصبح 4 ← ؟',
    questionImageUrl: null,
    options: [{ text: '15' }, { text: '17' }, { text: '19' }, { text: '21' }],
    correctOptionIndex: 1, explanationAr: 'القاعدة هي س² + 1: 4² + 1 = 16 + 1 = 17',
    tags: ['rules', 'quadratic'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '10-12', skillArea: 'logical_patterns', subSkill: 'comparison',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'سرعة A أكبر من B، وسرعة B أقل من C، وسرعة C مساوية لـ A. من الأبطأ؟',
    questionImageUrl: null,
    options: [{ text: 'A' }, { text: 'B' }, { text: 'C' }, { text: 'A وC' }],
    correctOptionIndex: 1, explanationAr: 'A > B وC = A، إذن A = C > B. B هو الأبطأ',
    tags: ['ordering', 'comparison'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '10-12', skillArea: 'logical_patterns', subSkill: 'if_then',
    difficulty: 'hard', questionType: 'text',
    questionTextAr: '"إذا لم يذاكر الطالب، فلن ينجح." أي من التالي يعني نفس الشيء؟',
    questionImageUrl: null,
    options: [{ text: 'إذا نجح الطالب فقد ذاكر' }, { text: 'إذا ذاكر الطالب فسينجح' }, { text: 'إذا رسب الطالب فلم يذاكر' }, { text: 'إذا لم ينجح الطالب فلم يذاكر' }],
    correctOptionIndex: 0, explanationAr: 'الجملة الأصلية: لا مذاكرة → لا نجاح. عكسها المناقض: نجاح → مذاكرة',
    tags: ['logic', 'contrapositive'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '10-12', skillArea: 'logical_patterns', subSkill: 'spatial',
    difficulty: 'hard', questionType: 'text',
    questionTextAr: 'مكعب أبعاده 3×3×3 طُلي من الخارج. كم مكعباً صغيراً ليس له أي وجه مطلي؟',
    questionImageUrl: null,
    options: [{ text: '1' }, { text: '3' }, { text: '6' }, { text: '9' }],
    correctOptionIndex: 0, explanationAr: 'فقط المكعب الذي في المنتصف تماماً (1×1×1) ليس له أي وجه يُلمس من الخارج',
    tags: ['spatial', '3D', 'cube'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '10-12', skillArea: 'logical_patterns', subSkill: 'pattern_completion',
    difficulty: 'medium', questionType: 'text',
    questionTextAr: 'ما الرقم المفقود: 36 ، 30 ، __ ، 21 ، 18؟',
    questionImageUrl: null,
    options: [{ text: '22' }, { text: '24' }, { text: '25' }, { text: '27' }],
    correctOptionIndex: 2, explanationAr: 'الفرق بين الأرقام: -6، -6، -6... إذن 30 - ... الفرق يتغير: 36-30=6، 30-?=5، ?-21=4، 21-18=3. إذن ?=25',
    tags: ['sequences', 'decreasing_difference'], isActive: true,
  },

  // ==========================================
  // 4-5 سنوات — صوتي (30 سؤال)
  // ==========================================
  {
    id: crypto.randomUUID(), ageGroup: '4-5', skillArea: 'quantitative', subSkill: 'counting',
    difficulty: 'easy', questionType: 'audio',
    questionTextAr: 'كم إصبعاً لديك في يد واحدة؟',
    questionImageUrl: null,
    options: [{ text: '3' }, { text: '4' }, { text: '5' }, { text: '6' }],
    correctOptionIndex: 2, explanationAr: 'في كل يد 5 أصابع',
    tags: ['counting', 'body'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '4-5', skillArea: 'quantitative', subSkill: 'counting',
    difficulty: 'easy', questionType: 'audio',
    questionTextAr: 'كم بيضة في العش: واحدة واثنتان وثلاث؟',
    questionImageUrl: null,
    options: [{ text: '2' }, { text: '3' }, { text: '4' }, { text: '5' }],
    correctOptionIndex: 1, explanationAr: '1 + 2 + 3 = 3 بيضات... لا، في العش ثلاث بيضات',
    tags: ['counting'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '4-5', skillArea: 'quantitative', subSkill: 'number_order',
    difficulty: 'easy', questionType: 'audio',
    questionTextAr: 'ما الرقم الذي يأتي قبل الرقم ثلاثة؟',
    questionImageUrl: null,
    options: [{ text: '1' }, { text: '2' }, { text: '4' }, { text: '5' }],
    correctOptionIndex: 1, explanationAr: 'قبل الرقم 3 يأتي الرقم 2',
    tags: ['number_order'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '4-5', skillArea: 'quantitative', subSkill: 'comparison',
    difficulty: 'easy', questionType: 'audio',
    questionTextAr: 'عند سالم ثلاث لعب وعند ريم لعبة واحدة. من لديه أكثر؟',
    questionImageUrl: null,
    options: [{ text: '👦 سالم' }, { text: '👧 ريم' }, { text: '🤝 نفس' }, { text: '❓' }],
    correctOptionIndex: 0, explanationAr: 'سالم لديه 3 لعب وريم لديها 1، لذا سالم لديه أكثر',
    tags: ['comparison', 'more_less'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '4-5', skillArea: 'quantitative', subSkill: 'counting',
    difficulty: 'easy', questionType: 'audio',
    questionTextAr: 'كم قطعة: تفاحة وتفاحتان معاً؟',
    questionImageUrl: null,
    options: [{ text: '2' }, { text: '3' }, { text: '4' }, { text: '5' }],
    correctOptionIndex: 1, explanationAr: '1 + 2 = 3 تفاحات',
    tags: ['addition', 'counting'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '4-5', skillArea: 'quantitative', subSkill: 'number_order',
    difficulty: 'easy', questionType: 'audio',
    questionTextAr: 'ما الرقم بعد السبعة؟',
    questionImageUrl: null,
    options: [{ text: '6' }, { text: '7' }, { text: '8' }, { text: '9' }],
    correctOptionIndex: 2, explanationAr: 'بعد 7 يأتي 8',
    tags: ['number_order'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '4-5', skillArea: 'quantitative', subSkill: 'comparison',
    difficulty: 'easy', questionType: 'audio',
    questionTextAr: 'أيهما أثقل: كيلو تفاح أم كيلو قطن؟',
    questionImageUrl: null,
    options: [{ text: '🍎 التفاح' }, { text: '☁️ القطن' }, { text: '🤝 نفس' }, { text: '❓' }],
    correctOptionIndex: 2, explanationAr: 'الكيلوغرام يساوي نفس الوزن دائماً، سواء كان تفاحاً أو قطناً',
    tags: ['weight', 'comparison'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '4-5', skillArea: 'verbal', subSkill: 'colors',
    difficulty: 'easy', questionType: 'audio',
    questionTextAr: 'ما لون الشمس؟',
    questionImageUrl: null,
    options: [{ text: '🔵' }, { text: '🟡' }, { text: '🔴' }, { text: '🟢' }],
    correctOptionIndex: 1, explanationAr: 'الشمس لونها أصفر',
    tags: ['colors'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '4-5', skillArea: 'verbal', subSkill: 'colors',
    difficulty: 'easy', questionType: 'audio',
    questionTextAr: 'ما لون الحشيش والأشجار؟',
    questionImageUrl: null,
    options: [{ text: '🟤' }, { text: '🔵' }, { text: '🟢' }, { text: '🟡' }],
    correctOptionIndex: 2, explanationAr: 'الحشيش والأشجار لونها أخضر',
    tags: ['colors', 'nature'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '4-5', skillArea: 'verbal', subSkill: 'animals',
    difficulty: 'easy', questionType: 'audio',
    questionTextAr: 'أي الحيوانات يطير؟',
    questionImageUrl: null,
    options: [{ text: '🐟' }, { text: '🐕' }, { text: '🐦' }, { text: '🐘' }],
    correctOptionIndex: 2, explanationAr: 'الطائر يطير باستخدام أجنحته',
    tags: ['animals', 'classification'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '4-5', skillArea: 'verbal', subSkill: 'animals',
    difficulty: 'easy', questionType: 'audio',
    questionTextAr: 'أي الحيوانات يسبح في الماء؟',
    questionImageUrl: null,
    options: [{ text: '🐈' }, { text: '🐟' }, { text: '🐮' }, { text: '🐎' }],
    correctOptionIndex: 1, explanationAr: 'السمكة تسبح في الماء',
    tags: ['animals', 'habitat'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '4-5', skillArea: 'verbal', subSkill: 'body_parts',
    difficulty: 'easy', questionType: 'audio',
    questionTextAr: 'ماذا نستخدم للاستماع إلى الأصوات؟',
    questionImageUrl: null,
    options: [{ text: '👁️' }, { text: '👃' }, { text: '👂' }, { text: '👄' }],
    correctOptionIndex: 2, explanationAr: 'نستخدم الأذن للسماع',
    tags: ['body_parts', 'senses'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '4-5', skillArea: 'verbal', subSkill: 'body_parts',
    difficulty: 'easy', questionType: 'audio',
    questionTextAr: 'ماذا نستخدم للمشي والركض؟',
    questionImageUrl: null,
    options: [{ text: '🤲' }, { text: '🦶' }, { text: '👁️' }, { text: '👄' }],
    correctOptionIndex: 1, explanationAr: 'نستخدم الأرجل والقدمين للمشي والركض',
    tags: ['body_parts'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '4-5', skillArea: 'verbal', subSkill: 'seasons',
    difficulty: 'easy', questionType: 'audio',
    questionTextAr: 'في أي فصل تتساقط الأمطار الكثيرة وتنمو الأزهار؟',
    questionImageUrl: null,
    options: [{ text: '☀️ الصيف' }, { text: '🍂 الخريف' }, { text: '❄️ الشتاء' }, { text: '🌸 الربيع' }],
    correctOptionIndex: 3, explanationAr: 'في فصل الربيع تتساقط الأمطار وتتفتح الأزهار',
    tags: ['seasons', 'nature'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '4-5', skillArea: 'verbal', subSkill: 'seasons',
    difficulty: 'easy', questionType: 'audio',
    questionTextAr: 'في أي فصل يكون الجو حاراً جداً ونذهب للبحر؟',
    questionImageUrl: null,
    options: [{ text: '☀️ الصيف' }, { text: '🍂 الخريف' }, { text: '❄️ الشتاء' }, { text: '🌸 الربيع' }],
    correctOptionIndex: 0, explanationAr: 'الصيف هو الفصل الحار الذي يذهب فيه الناس للشاطئ',
    tags: ['seasons'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '4-5', skillArea: 'verbal', subSkill: 'family',
    difficulty: 'easy', questionType: 'audio',
    questionTextAr: 'من هو والد أبيك؟',
    questionImageUrl: null,
    options: [{ text: '👨 عمك' }, { text: '👴 جدك' }, { text: '👦 أخوك' }, { text: '👨‍👧 أبوك' }],
    correctOptionIndex: 1, explanationAr: 'والد الأب هو الجد',
    tags: ['family', 'relationships'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '4-5', skillArea: 'verbal', subSkill: 'food',
    difficulty: 'easy', questionType: 'audio',
    questionTextAr: 'أي من هذه الأشياء نشربها وليس نأكلها؟',
    questionImageUrl: null,
    options: [{ text: '🍞' }, { text: '🍌' }, { text: '🥛' }, { text: '🍎' }],
    correctOptionIndex: 2, explanationAr: 'الحليب مشروب نشربه',
    tags: ['food', 'classification'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '4-5', skillArea: 'logical_patterns', subSkill: 'shapes',
    difficulty: 'easy', questionType: 'audio',
    questionTextAr: 'أي الأشكال مستدير وليس له زوايا؟',
    questionImageUrl: null,
    options: [{ text: '⬛' }, { text: '⭕' }, { text: '🔺' }, { text: '🔷' }],
    correctOptionIndex: 1, explanationAr: 'الدائرة شكل مستدير وليس لها زوايا',
    tags: ['shapes'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '4-5', skillArea: 'logical_patterns', subSkill: 'patterns',
    difficulty: 'easy', questionType: 'audio',
    questionTextAr: 'قبل الليل يكون النهار، وبعد النهار يكون؟',
    questionImageUrl: null,
    options: [{ text: '☀️ الصبح' }, { text: '🌙 الليل' }, { text: '🌅 الغروب' }, { text: '🌄 الشروق' }],
    correctOptionIndex: 1, explanationAr: 'الليل يأتي بعد النهار',
    tags: ['patterns', 'time_of_day'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '4-5', skillArea: 'logical_patterns', subSkill: 'comparison',
    difficulty: 'easy', questionType: 'audio',
    questionTextAr: 'الأسد حيوان كبير والقط حيوان صغير. ما الذي يشتركان فيه؟',
    questionImageUrl: null,
    options: [{ text: 'كلاهما طائر' }, { text: 'كلاهما يسبح' }, { text: 'كلاهما لديه فراء' }, { text: 'كلاهما أليف' }],
    correctOptionIndex: 2, explanationAr: 'الأسد والقط كلاهما لديه فراء (شعر كثيف يغطي الجسم)',
    tags: ['comparison', 'animals'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '4-5', skillArea: 'logical_patterns', subSkill: 'sequences',
    difficulty: 'easy', questionType: 'audio',
    questionTextAr: 'في الصباح نفطر، وفي الظهيرة نتغدى، وفي المساء نـ...',
    questionImageUrl: null,
    options: [{ text: '😴 ننام' }, { text: '🍽️ نتعشى' }, { text: '🏃 نركض' }, { text: '📚 ندرس' }],
    correctOptionIndex: 1, explanationAr: 'وجبات اليوم: إفطار، غداء، عشاء',
    tags: ['sequences', 'daily_routine'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '4-5', skillArea: 'quantitative', subSkill: 'counting',
    difficulty: 'easy', questionType: 'audio',
    questionTextAr: 'عد معي: واحد، اثنان، ثلاثة، أربعة، __؟',
    questionImageUrl: null,
    options: [{ text: '3' }, { text: '4' }, { text: '5' }, { text: '6' }],
    correctOptionIndex: 2, explanationAr: 'بعد أربعة يأتي خمسة',
    tags: ['counting', 'number_order'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '4-5', skillArea: 'quantitative', subSkill: 'counting',
    difficulty: 'easy', questionType: 'audio',
    questionTextAr: 'في الأسبوع كم يوماً؟',
    questionImageUrl: null,
    options: [{ text: '5' }, { text: '6' }, { text: '7' }, { text: '8' }],
    correctOptionIndex: 2, explanationAr: 'في الأسبوع 7 أيام: الأحد والاثنين والثلاثاء والأربعاء والخميس والجمعة والسبت',
    tags: ['counting', 'days'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '4-5', skillArea: 'verbal', subSkill: 'weather',
    difficulty: 'easy', questionType: 'audio',
    questionTextAr: 'عندما تمطر السماء ماذا نحمل لنحمي أنفسنا؟',
    questionImageUrl: null,
    options: [{ text: '🕶️' }, { text: '☂️' }, { text: '🧤' }, { text: '🧣' }],
    correctOptionIndex: 1, explanationAr: 'نحمل المظلة لنحمي أنفسنا من المطر',
    tags: ['weather', 'tools'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '4-5', skillArea: 'verbal', subSkill: 'occupations',
    difficulty: 'easy', questionType: 'audio',
    questionTextAr: 'من يطفئ الحرائق ويساعد الناس عند الخطر؟',
    questionImageUrl: null,
    options: [{ text: '👨‍⚕️ الطبيب' }, { text: '👨‍🚒 رجل الإطفاء' }, { text: '👨‍🏫 المعلم' }, { text: '👨‍🍳 الطباخ' }],
    correctOptionIndex: 1, explanationAr: 'رجل الإطفاء يطفئ الحرائق ويحمي الناس',
    tags: ['occupations', 'community'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '4-5', skillArea: 'verbal', subSkill: 'occupations',
    difficulty: 'easy', questionType: 'audio',
    questionTextAr: 'من يعالج المرضى في المستشفى؟',
    questionImageUrl: null,
    options: [{ text: '👨‍🏫 المعلم' }, { text: '👨‍⚕️ الطبيب' }, { text: '👨‍🚒 رجل الإطفاء' }, { text: '👮 الشرطي' }],
    correctOptionIndex: 1, explanationAr: 'الطبيب يعالج المرضى في المستشفى',
    tags: ['occupations'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '4-5', skillArea: 'logical_patterns', subSkill: 'opposites',
    difficulty: 'easy', questionType: 'audio',
    questionTextAr: 'عكس كلمة "فوق" هو...',
    questionImageUrl: null,
    options: [{ text: '⬆️ أعلى' }, { text: '⬇️ تحت' }, { text: '➡️ يمين' }, { text: '⬅️ يسار' }],
    correctOptionIndex: 1, explanationAr: 'عكس فوق هو تحت',
    tags: ['opposites', 'directions'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '4-5', skillArea: 'logical_patterns', subSkill: 'opposites',
    difficulty: 'easy', questionType: 'audio',
    questionTextAr: 'عكس كلمة "داخل" هو...',
    questionImageUrl: null,
    options: [{ text: 'خارج' }, { text: 'فوق' }, { text: 'تحت' }, { text: 'بجانب' }],
    correctOptionIndex: 0, explanationAr: 'عكس داخل هو خارج',
    tags: ['opposites', 'prepositions'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '4-5', skillArea: 'verbal', subSkill: 'nature',
    difficulty: 'easy', questionType: 'audio',
    questionTextAr: 'ماذا تحتاج النبتة لتنمو؟',
    questionImageUrl: null,
    options: [{ text: '🚗 سيارة' }, { text: '💧 ماء وشمس' }, { text: '📱 هاتف' }, { text: '🧸 لعبة' }],
    correctOptionIndex: 1, explanationAr: 'النبتة تحتاج الماء والشمس لتنمو',
    tags: ['nature', 'plants'], isActive: true,
  },
  {
    id: crypto.randomUUID(), ageGroup: '4-5', skillArea: 'verbal', subSkill: 'actions',
    difficulty: 'easy', questionType: 'audio',
    questionTextAr: 'ماذا نفعل بالكتاب؟',
    questionImageUrl: null,
    options: [{ text: 'نأكله' }, { text: 'نشربه' }, { text: 'نقرأه' }, { text: 'نلبسه' }],
    correctOptionIndex: 2, explanationAr: 'نقرأ الكتاب',
    tags: ['actions', 'objects'], isActive: true,
  },
];

async function main() {
  const db = getDb();
  console.log(`⏳ إضافة ${newQuestions.length} سؤال جديد...`);
  let added = 0;
  for (const q of newQuestions) {
    await db.insert(questions).values(q);
    added++;
    process.stdout.write(`\r✅ ${added}/${newQuestions.length}`);
  }
  console.log(`\n🎉 تم بنجاح إضافة ${added} سؤال.`);
  process.exit(0);
}
main();
